### ISSUE TITLE
Add concept of provider to mock

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1008]
Now that we have a repository, it is clear that we need the concept of instance provider for the mock environment.  This would be to help with:

1. Methods - tied to a provider rather than the repository
2. Provider where the requests are routed to the provider rather than directly to the repo fake_... methods. This provider could then manipulate the response.  This is probably not as difficult as it sounds.  It could be subclassed from a new class (ex. MockProvider) that would implement the basic methods (get_instance, enumerate_instances, create_instance, modify_instance and optionally get_instance, the ..Names extensions and associations/references.  The optional methods are because any of these could be implemented by the mock_provider class itself as simply extensions to enumerate_instances.

The first clear case of this is CIM_Namespace where, instead of adding the responses to the repository, the provider would inspect the repo to handle getting namespaces and creating namespaces.

**Comment by andy-maier** [comment]
The case of a user-provided callback method for method invocations has been implemented in the mock support of pywbem in version 0.12.0.

**Comment by andy-maier** [comment]
This issue has been addressed by the set of PRs that fix issue #2062.
