### ISSUE TITLE
Lots of warnings in our tests after the recent changes

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1009]
Examples:
  /home/kschopmeyer/pywbem/githubpywbem/pywbem/testsuite/test_client.py:140: UserWarning: Initializing a pywbem.NocaseDict object from <class 'dict'> will not preserve order of items
    obj_ = ctor_call(**ctor_args)
  /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/tupleparse.py:995: UserWarning: Initializing a pywbem.NocaseDict object from <class 'dict'> will not preserve order of items
    array_size, scopes, **flavors)
  /home/kschopmeyer/pywbem/githubpywbem/pywbem/testsuite/test_client.py:782: UserWarning: Initializing a pywbem.NocaseDict object from <class 'dict'> will not preserve order of items
    NocaseDict(exp_result_obj[1])

testsuite/test_wbemconnection_mock.py::TestRepoMethods::()::test_get_superclassnames[CIM_Foo_sub-exp_cln1-True-root/blah]
  /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/mof_compiler.py:1416: UserWarning: Initializing a pywbem.NocaseDict object from <class 'dict'> will not preserve order of items
    scopes=scopes, **flavors)

testsuite/test_wbemconnection_mock.py::TestRepoMethods::()::test_get_superclassnames[CIM_Foo_sub_sub-exp_cln2-True-root/cimv2]
  /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/mof_compiler.py:1416: UserWarning: Initializing a pywbem.NocaseDict object from <class 'dict'> will not preserve order of items
    scopes=scopes, **flavors)

**Comment by andy-maier** [comment]
There is one warning for each source code location of the caller outside of the pywbem module. Because there are multiple such locations, we get multiple such warnings.

It should be looked at to see whether we can reduce that (capturing a warning in a testcase causes it not to show up).

**Comment by andy-maier** [comment]
Reason was mainly that the hash support caused the warnings; it was written without the order preservation in mind and was merged with it later.

**Comment by andy-maier** [comment]
Addressed in PR #1013.
