### ISSUE TITLE
Requirement for provider concept for mock_wbemconnection

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1010]
Now that we have a repository, it is clear that we need the concept of instance provider for the mock environment.  This would be to help with:

1. Methods - tied to a provider rather than the repository
2. Provider where the requests are routed to the provider rather than directly to the repo fake_... methods. This provider could then manipulate the response.  This is probably not as difficult as it sounds.  It could be subclassed from a new class (ex. MockProvider) that would implement the basic methods (get_instance, enumerate_instances, create_instance, modify_instance and optionally get_instance, the ..Names extensions and associations/references.  The optional methods are because any of these could be implemented by the mock_provider class itself as simply extensions to enumerate_instances.

**Comment by andy-maier** [comment]
Possibly a dup of issue #1008?
