### ISSUE TITLE
I accidently created branch fixmorepylint.  It is worthless and should be deleted

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#102]
Have not figured out how yet.

**Comment by andy-maier** [comment]
* To delete a local branch:  `git branch -d fixmorepylint`
* To delete a local branch if it is not fully merged (you better know what you do): `git branch -d fixmorepylint`
* To delete the local copy of a remote branch:  `git branch -d -r origin/fixmorepylint`
* To delete a branch in the remote repo:  `git push origin :fixmorepylint`
The last one basically pushes the empty content into the remote branch, which is understood to be a delete request. Pretty nasty...
An alternative for removing a remote branch is to delete it via the Github web interface. Then, the command: `git remote prune origin` can be used to delete your local copies of those remote branches that are gone meanwhile.

I removed the fixmorepylint branch on the remote repo.
