### ISSUE TITLE
Problems with processing embedded Instances on input.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#103]
Started by will but I can duplicate. The embedded instance attribute is found, used, but for some reason the property is still a string when things like tomof is called.

Luckly I can create easily from openpegasus so this is easily solvable but I have gone blind at this point for the day.

Will upload some samples in the morning.

**Comment by KSchopmeyer** [comment]
There is a clear problem generating tomof with instances containing embedded instances.  Here is an example that I incorporated into test_cim_obj.py as a demo.  Generates cimxml ok but
fails on tomof()

class CIMInstanceWithEmbeddedInst(unittest.TestCase):
    def test_all(self):

        embed = CIMInstance('CIM_Embedded',
                        {'MyString': 'string',
                         'MyUint8': Uint8(0),
                         'MyUint8array': [Uint8(1), Uint8(2)],
                         'MyRef': CIMInstanceName('CIM_Bar')})

        i = CIMInstance('CIM_Foo',
                        {'MyString': 'string',
                         'MyUint8': Uint8(0),
                         'MyUint8array': [Uint8(1), Uint8(2)],
                         'MyRef': CIMInstanceName('CIM_Bar'),
                         'MyEmbed' : embed})
        icimxml = i.tocimxml()

        #kept for debugging
        print('%s' % (icimxml.toxml()))

        ## very general match. Just confirm part of first element
        n = re.match(
                     r"^\S*INSTANCE CLASSNAME\S*",
                     icimxml.toxml())

        if n is None:
            self.fail("Invalid CIM/XML generated.\n"\
                      "Instance: %r\n"\
                      "Generated XML: %r" % (i, icimxml.toxml()))

        imof = i.tomof()

Generates:
======================================================================
ERROR: test_all (__main__.CIMInstanceWithEmbeddedInst)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_cim_obj.py", line 1172, in test_all
    imof = i.tomof()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_obj.py", line 1899, in tomof
    prop.value))
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_obj.py", line 1889, in _prop2mof
    val = mofstr(value)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_obj.py", line 607, in mofstr
    escaped_str = strvalue.replace("\n", "\\n").replace("\r", "\\r").\
AttributeError: 'CIMInstance' object has no attribute 'replace'

**Comment by andy-maier** [comment]
It seems to believe it is a string, and does not treat it / convert it to as a CIMInstance object.
