### ISSUE TITLE
DSP0201 issue: ARRAYSIZE not clear about representation and range of the integer value

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1044]
In DSP0201, the %ArraySize entity defines the ARRAYSIZE attribute that is used on array declarations, i.e. on the elements PROPERTY.ARRAY, PARAMETER.ARRAY, PARAMETER.REFARRAY, and QUALIFIER.DECLARATION.

In DSP0201 2.4.0, the %ArraySize entity defines the possible values for the array size in its DTD as CDATA, and in its description as: "The value of this attribute (if it is present) shall be a positive integer."

That leaves two important things unclear:

* Which representations of the integer are allowed?
  Decimal representations are probably supported by everyone, but the interesting question is on hex representations. After all, section 5.3.3.1.5 "Integer Values" defines decimal and hex, but it is targeted at VALUE elements.

* What is the maximum value for the integers?
  This is important to understand for implementations that represent integers in data types that have a fixed value range.

A corresponding DMTF issue should be opened against DSP0201 with the goal to add the respective clarifications.

**Comment by KSchopmeyer** [comment]
Created Mantis issue #2845 on 8 Oct. 2019
