### ISSUE TITLE
DSP0201 issue: Purpose of xml:lang attribute on INSTANCE element is not clear

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1046]
DSP0201 2.4.0 defines that the INSTANCE element may have an `xml:lang` attribute. However, the purpose of that attribute is not clear on an instance, because an instance does not have a value that could be subject of the attribute.

It can be assumed that the `xml:lang` attribute on an INSTANCE element has no meaning. If that is the case, an according statement ahouls be added and it should be deprecated on that element.

A corresponding DMTF issue against DSP0201 should be opened .

**Comment by KSchopmeyer** [comment]
Filed as DMTF Mantis issue # 2844 on 8 Oct 2019
