### ISSUE TITLE
DSP0201 issue: Support of void methods creates confusion

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1050]
DSP0201 2.4.0 describes support for representing void methods (i.e. methods without a return value) in a class declaration, in section 5.3.5.7 "METHOD":

"The TYPE attribute (defined by the CIMType entity) defines the method return type, if the method returns a value. If this attribute is absent, the method shall return no value (that is, it has the special return type void)."

DSP0004 does not support methods that return no value (i.e. void).

It is confusing that DSP0201 describes void methods, because as an implementor, one is not sure whether this is an extension to DSP0004 or an inconsistency that should be ignored.

Proposal is to deprecate the support for void methods in DSP0201, with no replacement, recommending that CIM-XML receivers reject such void methods.

A corresponding DMTF issue against DSP0201 should be created.

**Comment by KSchopmeyer** [comment]
Created DMTF Mantis issue # 2731
