### ISSUE TITLE
pip install pywbem==0.11.0 -> Cannot open include file 'openssl/err.h'

### ISSUE THREAD

**Issue by remdragon** [pywbem/pywbem#1061]
See log below. I did some Googling first and I found there's scripts to install os-level headers for Linux, but I didn't see anything for Windows.

I could hunt down the openssl headers and find the right place to stick them, but I thought I'd reach out here first to see if I just missed something in the documentation about the recommended way to go about this ( and what specific version of headers etc ):

C:\>pip install pywbem==0.11.0
Collecting pywbem==0.11.0
  Using cached pywbem-0.11.0-py2.py3-none-any.whl
Requirement already satisfied: ply in c:\python27\lib\site-packages (from pywbem==0.11.0)
Collecting M2Crypto>=0.24 (from pywbem==0.11.0)
  Using cached M2Crypto-0.27.0.tar.gz
Collecting PyYAML (from pywbem==0.11.0)
  Using cached PyYAML-3.12-cp27-cp27m-win32.whl
Requirement already satisfied: six in c:\python27\lib\site-packages (from pywbem==0.11.0)
Requirement already satisfied: typing in c:\python27\lib\site-packages (from M2Crypto>=0.24->pywbem==0.11.0)
Installing collected packages: M2Crypto, PyYAML, pywbem
  Running setup.py install for M2Crypto ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\royce3\\appdata\\local\\temp\\pip-build-xnkxjq\\M2Crypto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\royce3\appdata\local\temp\pip-wauhdc-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    copying M2Crypto\ASN1.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\AuthCookie.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\BIO.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\BN.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\callback.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\DH.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\DSA.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\EC.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\Engine.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\Err.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\EVP.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\ftpslib.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\httpslib.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\m2.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\m2crypto.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\m2urllib.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\m2urllib2.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\m2xmlrpclib.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\Rand.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\RC4.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\RSA.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\six.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\SMIME.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\threading.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\util.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\X509.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\__init__.py -> build\lib.win32-2.7\M2Crypto
    creating build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\constants.py -> build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\packet.py -> build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\PublicKey.py -> build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\PublicKeyRing.py -> build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\RSA.py -> build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\__init__.py -> build\lib.win32-2.7\M2Crypto\PGP
    creating build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\cb.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Checker.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Cipher.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Connection.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Context.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Session.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\SSLServer.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\ssl_dispatcher.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\timeout.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\TwistedProtocolWrapper.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\__init__.py -> build\lib.win32-2.7\M2Crypto\SSL
    running build_ext
    building 'M2Crypto._m2crypto' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\SWIG
    C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -Ic:\python27\PC -Ic:\users\royce3\appdata\local\temp\pip-build-xnkxjq\M2Crypto\SWIG /TcSWIG/_m2crypto_wrap.c /Fobuild\temp.win32-2.7\Release\SWIG/_m2crypto_wrap.obj -DTHREADING -D_CRT_SECURE_NO_WARNINGS
    _m2crypto_wrap.c
    SWIG/_m2crypto_wrap.c(3550) : warning C4068: unknown pragma
    SWIG/_m2crypto_wrap.c(3551) : warning C4068: unknown pragma
    SWIG/_m2crypto_wrap.c(3554) : fatal error C1083: Cannot open include file: 'openssl/err.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\royce3\\appdata\\local\\temp\\pip-build-xnkxjq\\M2Crypto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\royce3\appdata\local\temp\pip-wauhdc-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\royce3\appdata\local\temp\pip-build-xnkxjq\M2Crypto\

C:\>

**Comment by andy-maier** [comment]
Hello Royce,
sorry for the confusion.

The description for installing to Windows is pretty incomplete for pywbem 0.11.0. That description will be improved in the upcoming pywbem 0.12 (see this draft: https://pywbem.readthedocs.io/en/latest/intro.html#installing-to-windows).

To install pywbem on Windows, use the M2CryptoWin32 or M2CryptoWin64 Python packages instead of M2Crypto, depending on the bit size of your Python environment (not the bit size of Windows itself). The OpenSSL header files, swig, etc are not needed if you do it that way. I also ran into compile issues when I tried with the M2Crypto package on Windows and gave up on it.

Please let us know ehther it worked.

**Comment by remdragon** [comment]
Thank you for the quick feedback!

I am running into a new error that makes me think I need to update setuptools, but I'm afraid to update setuptools to the latest version because I tried to do so a month ago and pyinstaller broke ( I opened a ticket with them but haven't heard back ). Is there a minimum required version of setuptools that's required or is this error indicative of something else?

C:\>pip install M2CryptoWin32
Collecting M2CryptoWin32
  Using cached M2CryptoWin32-0.21.1-3.tar.gz
Installing collected packages: M2CryptoWin32
  Running setup.py install for M2CryptoWin32 ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\royce3\\appdata\\local\\temp\\pip-build-xwnite\\M2CryptoWin32\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\royce3\appdata\local\temp\pip-b7wchl-record\install-record.txt --single-version-externally-managed --compile:
    c:\python27\lib\site-packages\setuptools\dist.py:331: UserWarning: Normalizing '0.21.1-3' to '0.21.1.post3'
      normalized_version,
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\royce3\\appdata\\local\\temp\\pip-build-xwnite\\M2CryptoWin32\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\royce3\appdata\local\temp\pip-b7wchl-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\royce3\appdata\local\temp\pip-build-xwnite\M2CryptoWin32\

C:\>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.version.__version__
'28.8.0'
>>> exit()

C:\>pip freeze
altgraph==0.15
asn1crypto==0.24.0
astroid==1.6.1
backports.functools-lru-cache==1.4
bcrypt==3.1.4
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
colorama==0.3.9
configparser==3.5.0
coverage==4.4.2
cryptography==2.1.4
dis3==0.1.2
enum34==1.1.6
funcsigs==1.0.2
future==0.16.0
glfw==1.4.0
idna==2.6
ipaddress==1.0.19
isort==4.2.15
jsoncomment==0.3.0
lazy-object-proxy==1.3.1
macholib==1.9
mccabe==0.6.1
MiniMock==1.2.8
mock==2.0.0
olefile==0.44
paramiko==2.4.0
pathlib==1.0.1
pbr==3.1.1
pdfkit==0.6.1
pefile==2017.11.5
pem==17.1.0
Pillow==4.3.0
ply==3.10
pyasn1==0.4.2
pycparser==2.18
pyenchant==2.0.0
PyInstaller==3.3.1
pylint==1.8.2
pymssql==2.1.3
PyMySQL==0.8.0
PyNaCl==1.2.1
pyodbc==4.0.21
pyparsing==2.2.0
pypiwin32==219
python-dateutil==2.6.1
python-engineio==2.0.2
pytz==2017.3
pyvmomi==6.5.0.2017.5.post1
requests==2.18.4
requests-mock==1.4.0
singledispatch==3.4.0.3
six==1.11.0
termcolor==1.1.0
typing==3.6.4
tzlocal==1.5.1
unicodecsv==0.14.1
urllib3==1.22
vulkan==1.0.61.3
wrapt==1.10.11
wsman==0.9.27

**Comment by remdragon** [comment]
I went ahead and upgraded setuptools, but it appears I'm getting the same error.

C:>pip install --upgrade setuptools
Collecting setuptools
  Downloading setuptools-38.5.0-py2.py3-none-any.whl (489kB)
    100% |################################| 491kB 2.0MB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
Successfully installed setuptools-38.5.0

C:>pip install M2CryptoWin32
Collecting M2CryptoWin32
  Using cached M2CryptoWin32-0.21.1-3.tar.gz
Installing collected packages: M2CryptoWin32
  Running setup.py install for M2CryptoWin32 ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\royce3\\appdata\\local\\temp\\pip-build-9x3ged\\M2CryptoWin32\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\royce3\appdata\local\temp\pip-uup25z-record\install-record.txt --single-version-externally-managed --compile:
    c:\python27\lib\site-packages\setuptools\dist.py:355: UserWarning: Normalizing '0.21.1-3' to '0.21.1.post3'
      normalized_version,
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\royce3\\appdata\\local\\temp\\pip-build-9x3ged\\M2CryptoWin32\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\royce3\appdata\local\temp\pip-uup25z-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\royce3\appdata\local\temp\pip-build-9x3ged\M2CryptoWin32\

C:>

**Comment by andy-maier** [comment]
I'm afraid I don't have a 32-bit Python on my Windows, so I can only try with the 64-bit version and there installing M2CryptoWin64 works.

Also, just to make sure you know: `pip install pywbem==0.11.0` does not work on Windows, because the information pip uses causes it to try to install M2Crypto. You can circumvent this by either cloning the pywbem repo or by downloading and unpacking the pywbem source tar file, and issuing `python setup.py install`.

Here are the package versions on 64-bit Windows 7 with 64-bit Python 2.7.11, when I clone the pywbem repo, checkout the `stable_0.11` branch and run `python setup.py install` in a fresh Python virtual environment:

m2cryptowin64 (0.21.1.post3)
pip (7.1.0)
ply (3.10)
pywbem (0.11.0)
pyyaml (3.12)
setuptools (18.0.1)
six (1.11.0)
wheel (0.24.0)

Did you try with a Python virtual environment? I can only highly recommend that, because it allows you to put in only the packages that are needed, and thereby reduces the risk of package incompatibilities.

**Comment by andy-maier** [comment]
Here is a StackOverflow article on the sympton you are seeing: https://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind

**Comment by remdragon** [comment]
"pip install wheel" fixed it so that "pip install M2CryptoWin32" now works.

Sorry I didn't think to Google this error, too.

Too many packages don't yet have binary wheels for 64-bit, which is why I still use 32-bit. Also, I have to support clients who are still running 32-bit versions of Windows.

You're right, this still doesn't allow pip install pywbem to work.

I have no experience using virtual envs. I will have to research and learn how to do this, thanks.

**Comment by andy-maier** [comment]
Thanks for letting me know what fixed it.
It should work in the system Python as well (i.e. without a virtual env). It is just more convenient in a development environment to use virtualenvs.

I still use virtualenvwrapper for that:

`pip install virtualenvwrapper` - to install the required packages
`mkvirtualenv myenv` - to create a new venv "myenv" with Python 2.7 and to activate it

Other commands:
`deactivate` - to deactivate the venv (i.e. to use the system Python again)
`workon` - to list available venvs
`workon myenv` - to switch to "myenv"

**Comment by andy-maier** [comment]
I think we should update the documentation and trouble shooting info for pywbem 0.11.

Otherwise, I assume this issue can be closed. Feel free to reopen it, or to create a new one if needed.
