### ISSUE TITLE
MOF compiler: Remove req that instances with alias must have any key props initialized

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1079]
In the MOF processed by the pywbem MOF compiler, the key properties of instances with aliases must be initialized in the instance specification, or their default values must be non-NULL.

We want instances in MOF to be able to have an alias without a requirement for having one or more keys specified or defaulted. Specifically, there is no requirement that multiple instances have different key values in MOF, as long as they have different aliases. This means the implementation of the MOF compiler must use the alias name to identify instances, and must not try to create instance paths at that stage. Only when the MOF compiler has issued the CreateInstance for an instance specification, does it get a valid instance path.

The pywbem MOF compiler should be improved to lift this limitation.

See issue #1078 for a related limitation. For more background, see issue #853.

**Comment by andy-maier** [comment]
This issue is mentioned as a limitation in the introduction of chapter 7 "MOF compiler API" of the pywbem documentation. The limitation needs to be removed from the documentation when this issue is fixed.

**Comment by KSchopmeyer** [comment]
Karl beleives this is fixed and will confirm.  Marked investigation needed.

**Comment by KSchopmeyer** [comment]
PR #1911 modified the code to get the instance path from the cim repository when the alias was defined on an instance.  This resolved two issues. 1) Building the path in the compiler and 2)always putting putting a path element on the instance.  It puts the burden on the implementation of CreateInstance to set the path which has been the case for the mock environment for some time.

I am marking this issues as resolved.
