### ISSUE TITLE
Getting DeprecationWarning from our assert

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1086]
testsuite/test_statistics.py:350: DeprecationWarning: Please use assertRegex instead.
  self.assertRegexpMatches(stat_repr, r'Statistics\(')

Not sure why since this is part of our RegexpMixin.

**Comment by andy-maier** [comment]
Apparently our call to our `assertRegexpMatches()` ends up going to unittest2's. Needs investigation. Could possibly be fixed by renaming our test methods. If we do that, we should do it consistently, also for the other method.

**Comment by andy-maier** [comment]
PR #1089 renames the assertion methods and should fix this issue (I could not reproduce the issue on RHEL with Python 2.7 in a virtual env with a fresh `make clobber install develop`).
