### ISSUE TITLE
Pywbem Listener stop and context

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1090]
The stop() operation is critical to the pywbem listener if a listener is to be stopped or possibly failed and restarted within a single execution of an application.  

Once the start() method is executed the ports defined for the listener will remain open until the stop() is executed.  Note that since there is no timeout parameter defined for the listener this is absolutely true.

Some possible changes are logical:

1. Note in the documentation that a listener must be stopped to free the ports it is using.
2. Add code to capture the OSError98 exception that comes from the listener.start() if any of the ports are in use and create a more helpful message.  Remember that this could be either, that the previous listener did not stop.

3. Implement the context manager pattern for the listener to make it at least somewhat more apparent that issuing the stop is important.

I propose that this supercede issue # 452.

**Comment by andy-maier** [comment]
I think we should implement all three of them.

**Comment by andy-maier** [comment]
Addressed all three items in PR #1097.
