### ISSUE TITLE
mof output of properties with arrays does not deal with 80 column width limit.  

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#110]
Need to expand code so that we fold array outputs gt than 80 col in length.  This means two folds,

a. total of all items is gt 80 col
b. Any single item is gt 80 col.

**Comment by andy-maier** [comment]
Is this completely addressed by PR #148?

**Comment by KSchopmeyer** [comment]
Not sure since we do not have all test cases.   There is at least one more test case to add, the case of an array where at least one single entry is gt than 80 characters so that the entry must be folded before the array is folded.  Since there is not a single case of this in the cim model, I put it off.

There is another issue in general in that the compiler has never folded arrays of qualifier data.  I have left the fix for this out of the previous code (one problem at a time) since it is a different part of the code. Also, this occurs very frequently and in class output whereas the instance folding is less frequently seen so for this one we want to fold the array when output hits 80 col for compactness rather than the approach of one array entry per line we took with instance array output.

**Comment by KSchopmeyer** [comment]
The last part of the fix for this is in pr #263 and #260

**Comment by andy-maier** [comment]
Karl: Please verify whether these PRs fix the issue completely.

**Comment by KSchopmeyer** [comment]
We apparently still have one problem that does not show up normally in schema mof output but does in instance mof output.  We are not folding property text values on instances.  See example:

The only problem is that the first line is too long before the fold.

instance of PG_ComputerSystem {
    Status = "OK";
    ElementName = "Computer System";
    PowerState = 1;
    Description = "Linux version 3.13.0-86-generic (buildd@lgw01-51) (gcc versio
n 4.8.2 "
    "(Ubuntu 4.8.2-19ubuntu1) ) #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016";
    PowerManagementSupported = False;

I am closing this one and creating new issue with this single problem

Marking this one closed since the originally defined issues are closed by pr #263 and #260

**Comment by KSchopmeyer** [comment]
mark closed
