### ISSUE TITLE
cimxml_parse.py does not seem to be used anywhere except its own test program

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#111]
It appears everything is done through tuple_parse and I do not understand the purpose for cimxml_parse.py

The question is:  is there a reason for it either now or in the future or should we eliminate it.

If it is significantly faster or more complete that tupleparse that would make sense.  Otherwise it might be best to kill it and its test.

**Comment by KSchopmeyer** [comment]
Obviously the first issue is that the code is significantly more complex (32k for cimxml_parse vs. about 3k for tupleparse.

**Comment by andy-maier** [comment]
I suggest to move cimxml_parse into a kind of "attic" directory (along with cim_provider* and twisted_client).

**Comment by KSchopmeyer** [comment]
I agree and will do this ASAP.
