### ISSUE TITLE
Can we improve info in some connection error exceptions

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1118]
We are getting the following error from a server in the SMI center but that is the only info the user is getting back and they are using an older version of pywbem without logging.

    raise ConnectionError("The server closed the connection "
pywbem.exceptions.ConnectionError: The server closed the connection without 
returning any data, or the client timed out

I was wondering if there is more detailed info that we could get back.

**Comment by andy-maier** [comment]
I looked into the code, and there is no more information to get. What happened is what the message said, i.e. the server closed the connection. The reason for it closing the connection may be because it went down or because it timed out the keep-alive connection.

**Comment by andy-maier** [comment]
PR #1119 has some improvements in error handling. Please review it and test it in the scenario that caused this exception.

**Comment by andy-maier** [comment]
Discussion point: Once the connection ID will have been added as part of the logging PR, should we show it in the exception messages  raised in cim_http.py?

**Comment by KSchopmeyer** [comment]
KARL will look at this one

**Comment by andy-maier** [comment]
We agreed that the exception messages should contain both the connection id and the server url. That would be in the message and accessible as additional fields on the exception. The exceptions in question are those in cim_http.py, because they have to do with connections.
