### ISSUE TITLE
Python 2.7.6 Fails in make develop. ImportError from tornado

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1121]
Reopened by Karl when the problem happened again and I captured the issue.

**NOTE:** When I first filed this I did not record the error assuming I could reproduce it.  After the python 2.7.14 fiasco I went back to 2.7.6 and this pops up again.

My build process (make develop), the default on Ubuntu 14.04 fails because of a new dependency failure.   Tornado says it depends on an up-to-date ssl module and references python 2.7.9 as minimum.

Here is the issue I was getting but did not record earlier::

    Requirement already up-to-date: nbformat>=4.4 in 
    /home/kschopmeyer/.virtualenvs/pywbem27/lib/python2.7/site-packages (from nbconvert-
    >jupyter>=1.0.0->-r dev-requirements.txt (line 46))
    Requirement already up-to-date: ipython>=4.0.0 in 
    /home/kschopmeyer/.virtualenvs/pywbem27/lib/python2.7/site-packages (from ipykernel-
    >jupyter>=1.0.0->-r dev-requirements.txt (line 46))
    Collecting tornado>=4.0 (from ipykernel->jupyter>=1.0.0->-r dev-requirements.txt (line 46))
      Using cached tornado-5.0.1.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-0jS1DS/tornado/setup.py", line 146, in <module>
            raise ImportError("Tornado requires an up-to-date SSL module. This means "
        ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ 
    (although some distributions have backported the necessary changes to older versions).

The tornado github already has this listed as issue https://github.com/floydhub/dl-docker/issues/84

The issue is from the Tornado setup.py with the following code which specifically tests for selected attributes in the ssl module:

    import ssl
    . . .
    # Verify that the SSL module has all the modern upgrades. Check for several
    # names individually since they were introduced at different versions,
    # although they should all be present by Python 3.4 or 2.7.9.
    if (not hasattr(ssl, 'SSLContext') or
            not hasattr(ssl, 'create_default_context') or
            not hasattr(ssl, 'match_hostname')):
        raise ImportError("Tornado requires an up-to-date SSL module. This means "
                          "Python 2.7.9+ or 3.4+ (although some distributions have "
                          "backported the necessary changes to older versions).")

This was apparently added to the lastest tornado release (5.0.0 or 5.0.1). Thus the problem is that tornado setup is not finding required attributes in any Python prior to 2.7.9 (unless some specific
backporting was done)

**TEMPORARY RESOLUTION:** add the following to dev_requirements.txt::

    tornado ==4.4.2; python_version == '2.7'

That works.
 
My current pip list::

alabaster (0.7.10)
astroid (1.6.1)
attrs (17.4.0)
Babel (2.5.3)
backports-abc (0.5)
backports.functools-lru-cache (1.5)
backports.shutil-get-terminal-size (1.0.0)
bleach (2.1.3)
certifi (2018.1.18)
chardet (3.0.4)
configparser (3.5.0)
coverage (4.5.1)
decorator (4.2.1)
distro (1.2.0)
docutils (0.14)
entrypoints (0.2.3)
enum34 (1.1.6)
flake8 (3.5.0)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.2.0)
gitdb2 (2.0.3)
GitPython (2.1.8)
html5lib (1.0.1)
httpretty (0.8.14)
idna (2.6)
imagesize (1.0.0)
ipykernel (4.8.2)
ipython (5.5.0)
ipython-genutils (0.2.0)
ipywidgets (7.1.2)
isort (4.3.4)
Jinja2 (2.10)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.2.3)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
lazy-object-proxy (1.3.1)
linecache2 (1.0.0)
logging-tree (1.7)
lxml (4.2.0)
M2Crypto (0.29.0)
MarkupSafe (1.0)
mccabe (0.6.1)
mistune (0.8.3)
mock (2.0.0)
nbconvert (5.3.1)
nbformat (4.4.0)
notebook (5.4.0)
packaging (17.1)
pandocfilters (1.4.2)
pathlib2 (2.3.0)
pbr (3.1.1)
pexpect (4.4.0)
pickleshare (0.7.4)
pip (9.0.2)
pkginfo (1.4.1)
pluggy (0.6.0)
ply (3.11)
prompt-toolkit (1.0.15)
ptyprocess (0.5.2)
py (1.5.2)
pycodestyle (2.3.1)
pyflakes (1.6.0)
Pygments (2.2.0)
pylint (1.8.2)
pyparsing (2.2.0)
pytest (3.4.2)
pytest-cov (2.5.1)
python-coveralls (2.9.1)
python-dateutil (2.7.0)
pytz (2018.3)
pywbem (0.11.1.dev425, /home/kschopmeyer/pywbem/githubpywbem/pywbem)
PyYAML (3.12)
pyzmq (17.0.0)
qtconsole (4.3.1)
requests (2.18.4)
requests-toolbelt (0.8.0)
scandir (1.7)
Send2Trash (1.5.0)
setuptools (39.0.1)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.11.0)
smmap2 (2.0.3)
snowballstemmer (1.2.1)
Sphinx (1.7.1)
sphinx-git (10.1.1)
sphinxcontrib-websupport (1.0.1)
terminado (0.8.1)
testfixtures (5.4.0)
testpath (0.3.1)
tornado (5.0)
tqdm (4.19.7)
traceback2 (1.4.0)
traitlets (4.3.2)
twine (1.10.0)
typing (3.6.4)
unittest2 (1.1.0)
urllib3 (1.22)
wcwidth (0.1.7)
webencodings (0.5.1)
wheel (0.30.0)
widgetsnbextension (3.1.4)
wrapt (1.10.11)
yamlordereddictloader (0.4.0)

**Comment by andy-maier** [comment]
Karl, I have created and already merged PR #1122 which fixes an issue in freshly set up virtual Python environments that happens when the LEX/YACC MOF table files need to be re-generated during 'make install'.

Not sure this solves the issue you are reporting here, but I still wanted to mention it.

**Comment by KSchopmeyer** [comment]
Close as invalid.  Fingers problem

**Comment by KSchopmeyer** [comment]
Andy. this is not the issue you noted above.  It is clearly an issue with an update to an imported library that executes a setup test that fails when we are using python 2.7.6.

**Comment by andy-maier** [comment]
I suggest that we exclude tornado 5.0 from dev-reqs. I'll file a PR for that.

**Comment by andy-maier** [comment]
I tried to verify this on RHEL 7.4, with Python 2.7.5 and was unable to:

```
$ python --version
Python 2.7.5
$ grep ssl tornado-5.0.1/setup.py 
import ssl
if (not hasattr(ssl, 'SSLContext') or
        not hasattr(ssl, 'create_default_context') or
        not hasattr(ssl, 'match_hostname')):
$ python -c "import ssl; ssl.SSLContext; ssl.create_default_context; ssl.match_hostname"
```
