### ISSUE TITLE
InvokeMethod Failed for CreateOrModifyElementFromStoragePool

### ISSUE THREAD

**Issue by hemendra9636** [pywbem/pywbem#1123]
Hi all,`
i am calling InvokeMethod  function for which : 
MethodName :- 'CreateOrModifyElementFromStoragePool'
ObjectName  :- CIMInstanceName o f class 'CIM_StorageConfigurationService'
Params:-
Params.append(('ElementName',pywbem.cimvalue(newName,'string')))
Params.append(('ElementType',pywbem.cimvalue(eleType,'uint16')))
Params.append(pywbem.CIMParameter('Goal','reference',value=None))
Params.append(('Goal',pywbem.cimvalue(None,'reference')))
Params.append(('Size',pywbem.cimvalue(inSize,'uint64')))
Params.append(('InPool',pywbem.cimvalue(targetPool,'reference')))
Params.append(('TheElement',pywbem.cimvalue(None,'reference')))
Params.append(('isSpaceEfficient',pywbem.cimvalue(isSpaceEfficient,'boolean')))
Params.append(('Autoexpand',pywbem.cimvalue(isSpaceEfficient,'boolean')))
Params.append(('RealSizePercent',pywbem.cimvalue(rsp,'uint64')))
Params.append(('IOGroup',pywbem.cimvalue(params[6],'string')))

declaration of CreateOrModifyElementFromStoragePool from MS site :- https://msdn.microsoft.com/en-us/library/mt432331(v=vs.85).aspx

i need to create storageVolume so parameter 'Goal' and 'TheElement' should be NULL according to declaration from MS site. But None is not a CIM data type and it is giving me error.
Please help me on how to pass 'Goal' and 'TheElement' parameter so that function is invoked successfully.
Thanks in advance, any help is very much appreciated.

**Comment by andy-maier** [comment]
Python `None` is in fact a valid CIM data type value, and your way of passing it looks correct to me. 

You could also pass `None` directly without using the `pywbem.cimvalue()` function, i.e.:
```
Params.append(('Goal',None))
```

Please let us know exactly what error you are getting.

**Comment by hemendra9636** [comment]
Hi,
1. i need 'goal' and 'TheElement' both params as null, so i added like this for both of them
inParams.append(('Goal',None))
inParams.append(('TheElement',None))
error :- 
![image](https://user-images.githubusercontent.com/14199370/37713442-fdb42462-2d3c-11e8-9afa-8c649411738d.png)

2. if i add like this :- 
inParams.append(('Goal',pywbem.cimvalue(None,'reference')))
inParams.append(('TheElement',pywbem.cimvalue(None,'reference')))

error :- same error as i am getting in 1st.

**Comment by andy-maier** [comment]
Thanks for the information. That's a bug. We'll fix that quickly.

Since you are using the new `cimvalue()` function already, I assume you could use a fixed version of pywbem as soon as we get the fix merged into the master branch?

The 0.12.0 release of pywbem will probably take a couple more weeks before it is ready for releasing.

**Comment by andy-maier** [comment]
PR #1133 addresses the issue and extends the testclient testcases accordingly.
Can you please test with that PR?

**Comment by hemendra9636** [comment]
Hi andy,
i tested using PR #1133 and the error is gone.
But when i pass like :- 
 inParams.append(('Goal',None))
inParams.append(('TheElement',None))
i am getting HTTPError :- 
![image](https://user-images.githubusercontent.com/14199370/37749870-077fcd52-2db0-11e8-81a3-40ae74a971ee.png)

Actually i have code in c++ and i am writing script in python  of that code. In c++ i am using pegasus-2.8.1 and pegasus provides below function to make any CIMType as NULL :- 
'void setNullValue(CIMType type, Boolean isArray, Uint32 arraySize = 0);'

i think when i am passing 'Goal' and 'TheElement' as None in python, server is not recognizing  parameters as NULL and it is giving 'request-not-valid' error. Could you please help me on how to overcome this.
'Goal' and 'TheElement' both are 'reference' type and server should recognize them as NULL. So how and what to pass in value for both parameters. Also please correct me if error is because of any other reason.

Thanks & Regards
Hemendra

**Comment by andy-maier** [comment]
I'd like to see the CIM-XML request for the method invocation, if possible. Within the CIM-XML protocol, a CIM type is optional on the method parameter (the PARAMTYPE attribute on the PARAMVALUE element), so the representation of NULL as a parameter value in CIM-XML does not need to have a type (but it may).

The preversion of pywbem 0.12 you are using added support for specifying a method parameter value as a CIMParameter object, in which case you can specify a type and it can have a value of None:
```
inParams.append(CIMParameter('Goal', type='reference', value=None))
```
I don't believe this will help, but you could still try it.

Otherwise, please provide the CIM-XML request. You can get that through the `last_request` attribute on your WBEMConnection object after attempting the method invocation.

**Comment by hemendra9636** [comment]
Hi andy,
i tried with this :- 
inParams.append(CIMParameter('Goal', type='reference', value=None))
inParams.append(CIMParameter('TheElement', type='reference', value=None))
but i am getting same error :- 
![image](https://user-images.githubusercontent.com/14199370/37764620-2a3837b6-2de8-11e8-907f-12ab6a455cb0.png)

Attaching CIM-XML. the VALUE field for both parameters in xml is not there.Please let me know if anything you need.
Thank you very much for help. 
[xml.txt](https://github.com/pywbem/pywbem/files/1837008/xml.txt)

**Comment by hemendra9636** [comment]
Please get this xml :- 
[xml.txt](https://github.com/pywbem/pywbem/files/1837044/xml.txt)

**Comment by andy-maier** [comment]
I verified the CIM-XML and at a first glance, it seems correct. I also verified the embedded instance, also correct.

**Comment by hemendra9636** [comment]
For the 'Goal' and 'TheElement' parameter we are not having '<VALUE></VALUE>' field. is it giving problem because both of them are not optional parameter for the function which we are invoking. Their values should be null. Pegasus has 'setNullValue' function to set null for any CIMType. Don't we have anything similar to that.
![image](https://user-images.githubusercontent.com/14199370/37766655-9811a2c2-2ded-11e8-89d3-5e60c51b5c3e.png)

**Comment by hemendra9636** [comment]
For the 'Goal' and 'TheElement' parameter we are not having value field in xml.

**Comment by andy-maier** [comment]
In CIM-XML, the NULL value is represented by not having the VALUE element. So the PARAMVALUE element for Goal you are showing above is exactly right if it is supposed to represent NULL.

The error you are seeing is created by OpenPegasus when processing the request. I asked for the CIM-XML of the request because I wanted to figure out whether Pegasus would have a reason to complain about the request, and from what I can see, the CIM-XML request is good. So there must be another reason Pegasus complains.

Can you try to invoke the method using the Pegasus cimcli command?
See https://www.mankier.com/1/cimcli#Operations-im_invokeMethod_Operation
I believe this requires a cimcli from a newer version of Pegasus than the 2.8.1 you are using. You can use such a newer version of cimcli against the old Pegasus server version you have.

I'd like to get Karl involved in his capacity as OpenPegasus owner and will discuss the matter with him. We have a phone call tomorrow.

**Comment by andy-maier** [comment]
Thinking about the error message: Pegasus complains about an invalid request, and points to the INSTANCE element. The only place in the request with an INSTANCE element is the embedded instance in the IOGroup parameter. That's why I decoded its value and verified it as well, but I found it to be correct. Let me discuss with Karl as to whether he recalls issues in OpenPegasus related to embedded instance processing (I seem to recall there were some).

**Comment by andy-maier** [comment]
Hi Hemendra, we have merged PR #1133 which fixes the rejection of `None`, so you can now again use the master branch.

**Comment by hemendra9636** [comment]
Hi Andy,
I am using IBM SVC and your concern is right, instance of 'IOGroup' was compared with 'reference'. When I passed reference of 'IOGroup' then method invocation happened successfully. Your help is very much appreciated.

Thank you
Hemendra Teli

**Comment by andy-maier** [comment]
Hi Hemendra, this is good to hear. I am closing this issue now. If other issues come up, feel free to reopen it, or open a new one.

**Comment by andy-maier** [comment]
For further investigation, here is the decoded (unescaped) embedded instance in the 'IOGroup' parameter value:

```
<VALUE.NAMEDINSTANCE>
  <LOCALINSTANCEPATH>
    <LOCALNAMESPACEPATH>
      <NAMESPACE NAME="root"/>
      <NAMESPACE NAME="ibm"/>
    </LOCALNAMESPACEPATH>
    <INSTANCENAME CLASSNAME="IBMTSSVC_IOGroup">
      <KEYBINDING NAME="CreationClassName">
        <KEYVALUE VALUETYPE="string">IBMTSSVC_IOGroup</KEYVALUE>
      </KEYBINDING>
      <KEYBINDING NAME="Name">
        <KEYVALUE VALUETYPE="string">0000020063A0CE56:0</KEYVALUE>
      </KEYBINDING>
    </INSTANCENAME>
  </LOCALINSTANCEPATH>
  <INSTANCE CLASSNAME="IBMTSSVC_IOGroup">
    <PROPERTY NAME="InstanceID" PROPAGATED="true" TYPE="string"/>
    <PROPERTY NAME="InstallDate" PROPAGATED="true" TYPE="datetime"/>
    <PROPERTY NAME="Status" PROPAGATED="true" TYPE="string"/>
    <PROPERTY NAME="HealthState" PROPAGATED="true" TYPE="uint16"/>
    <PROPERTY NAME="CommunicationStatus" PROPAGATED="true" TYPE="uint16"/>
    <PROPERTY NAME="DetailedStatus" PROPAGATED="true" TYPE="uint16"/>
    <PROPERTY NAME="OperatingStatus" PROPAGATED="true" TYPE="uint16"/>
    <PROPERTY NAME="PrimaryStatus" PROPAGATED="true" TYPE="uint16"/>
    <PROPERTY NAME="TimeOfLastStateChange" PROPAGATED="true" TYPE="datetime"/>
    <PROPERTY.ARRAY NAME="AvailableRequestedStates" PROPAGATED="true" TYPE="uint16"/>
    <PROPERTY NAME="TransitioningToState" PROPAGATED="true" TYPE="uint16">
      <VALUE>12</VALUE>
    </PROPERTY>
    <PROPERTY NAME="PrimaryOwnerName" PROPAGATED="true" TYPE="string"/>
    <PROPERTY NAME="PrimaryOwnerContact" PROPAGATED="true" TYPE="string"/>
    <PROPERTY.ARRAY NAME="Roles" PROPAGATED="true" TYPE="string"/>
    <PROPERTY.ARRAY NAME="PowerManagementCapabilities" PROPAGATED="true" TYPE="uint16"/>
    <PROPERTY NAME="Caption" PROPAGATED="false" TYPE="string">
      <VALUE>io_grp0</VALUE>
    </PROPERTY>
    <PROPERTY NAME="CreationClassName" PROPAGATED="false" TYPE="string">
      <VALUE>IBMTSSVC_IOGroup</VALUE>
    </PROPERTY>
    <PROPERTY.ARRAY ARRAYSIZE="1" NAME="Dedicated" PROPAGATED="false" TYPE="uint16">
      <VALUE.ARRAY>
        <VALUE>0</VALUE>
      </VALUE.ARRAY>
    </PROPERTY.ARRAY>
    <PROPERTY NAME="Description" PROPAGATED="false" TYPE="string">
      <VALUE>A group containing two Nodes. An IOGroup defines an interface for a set of Volumes. All Nodes and Volumes are associated with exactly one IOGroup. The read and write cache provided by a node is duplicated for redundancy. When IO is performed to a Volume, the node that processes the IO will duplicate the data on the Partner node in the IOGroup. This class represents the system aspect of an IO group wheras IOGroupSet represents the set aspect.</VALUE>
    </PROPERTY>
    <PROPERTY NAME="ElementName" PROPAGATED="false" TYPE="string">
      <VALUE>io_grp0</VALUE>
    </PROPERTY>
    <PROPERTY NAME="EnabledDefault" PROPAGATED="false" TYPE="uint16">
      <VALUE>2</VALUE>
    </PROPERTY>
    <PROPERTY NAME="EnabledState" PROPAGATED="false" TYPE="uint16">
      <VALUE>5</VALUE>
    </PROPERTY>
    <PROPERTY.ARRAY ARRAYSIZE="2" NAME="IdentifyingDescriptions" PROPAGATED="false" TYPE="string">
      <VALUE.ARRAY>
        <VALUE>Node WWN</VALUE>
        <VALUE>Node WWN</VALUE>
      </VALUE.ARRAY>
    </PROPERTY.ARRAY>
    <PROPERTY NAME="Name" PROPAGATED="false" TYPE="string">
      <VALUE>0000020063A0CE56:0</VALUE>
    </PROPERTY>
    <PROPERTY NAME="FlashCopyFreeMemory" PROPAGATED="false" TYPE="uint32">
      <VALUE>19685376</VALUE>
    </PROPERTY>
    <PROPERTY NAME="FlashCopyTotalMemory" PROPAGATED="false" TYPE="uint32">
      <VALUE>20971520</VALUE>
    </PROPERTY>
    <PROPERTY NAME="MirrorFreeMemory" PROPAGATED="false" TYPE="uint32">
      <VALUE>172032</VALUE>
    </PROPERTY>
    <PROPERTY NAME="MirrorTotalMemory" PROPAGATED="false" TYPE="uint32">
      <VALUE>192512</VALUE>
    </PROPERTY>
    <PROPERTY NAME="RAIDFreeMemory" PROPAGATED="false" TYPE="uint32">
      <VALUE>41943040</VALUE>
    </PROPERTY>
    <PROPERTY NAME="RAIDTotalMemory" PROPAGATED="false" TYPE="uint32">
      <VALUE>41943040</VALUE>
    </PROPERTY>
    <PROPERTY NAME="NameFormat" PROPAGATED="false" TYPE="string">
      <VALUE>Other</VALUE>
    </PROPERTY>
    <PROPERTY NAME="NumberOfHosts" PROPAGATED="false" TYPE="uint32">
      <VALUE>156</VALUE>
    </PROPERTY>
    <PROPERTY NAME="NumberOfNodes" PROPAGATED="false" TYPE="uint32">
      <VALUE>2</VALUE>
    </PROPERTY>
    <PROPERTY NAME="NumberOfVolumes" PROPAGATED="false" TYPE="uint32">
      <VALUE>342</VALUE>
    </PROPERTY>
    <PROPERTY.ARRAY ARRAYSIZE="1" NAME="OperationalStatus" PROPAGATED="false" TYPE="uint16">
      <VALUE.ARRAY>
        <VALUE>0</VALUE>
      </VALUE.ARRAY>
    </PROPERTY.ARRAY>
    <PROPERTY.ARRAY NAME="OtherDedicatedDescriptions" PROPAGATED="false" TYPE="string"/>
    <PROPERTY NAME="OtherEnabledState" PROPAGATED="false" TYPE="string"/>
    <PROPERTY.ARRAY ARRAYSIZE="2" NAME="OtherIdentifyingInfo" PROPAGATED="false" TYPE="string">
      <VALUE.ARRAY>
        <VALUE>500507680100672B</VALUE>
        <VALUE>5005076801006719</VALUE>
      </VALUE.ARRAY>
    </PROPERTY.ARRAY>
    <PROPERTY NAME="RemoteCopyFreeMemory" PROPAGATED="false" TYPE="uint32">
      <VALUE>20914176</VALUE>
    </PROPERTY>
    <PROPERTY NAME="RemoteCopyTotalMemory" PROPAGATED="false" TYPE="uint32">
      <VALUE>20971520</VALUE>
    </PROPERTY><PROPERTY NAME="RequestedState" PROPAGATED="false" TYPE="uint16">
      <VALUE>5</VALUE>
    </PROPERTY>
    <PROPERTY NAME="ResetCapability" PROPAGATED="false" TYPE="uint16">
      <VALUE>5</VALUE>
    </PROPERTY>
    <PROPERTY.ARRAY NAME="StatusDescriptions" PROPAGATED="false" TYPE="string"/>
    <PROPERTY NAME="CompressionSupported" PROPAGATED="false" TYPE="boolean">
      <VALUE>FALSE</VALUE>
    </PROPERTY>
  </INSTANCE>
</VALUE.NAMEDINSTANCE>
```

**Comment by andy-maier** [comment]
Further analysis shows that the CIM-XML of the embedded instance in the `IOGroup` parameter is incorrect. According to DSP0201, it should be an INSTANCE element, when actually it is VALUE.NAMEDINSTANCE (even with an incorrect LOCALINSTANCEPATH child element).

What is left to do for pywbem is to double check that pywbem does not create this invalud CIM-XML for embedded instances.

**Comment by andy-maier** [comment]
We are following up on the remaining pywbem issue in issue #1136, so we can close this one (that was about a different issue)
