### ISSUE TITLE
pywbem 0.8.1 breaking Openstack Ansible builds

### ISSUE THREAD

**Issue by logan2211** [pywbem/pywbem#113]
I'm seeing local failures trying to build 0.8.1 wheels: http://cdn.pasteraw.com/f3su2r6wanlc9feocqaf95btf370c33

The Openstack Ansible gate checks also seem to be affected:
http://logs.openstack.org/99/277199/16/check/gate-openstack-ansible-dsvm-commit/51de785/console.html#_2016-03-18_21_09_37_014
http://logs.openstack.org/65/294765/1/check/gate-openstack-ansible-dsvm-commit/03b96b6/console.html#_2016-03-18_19_50_33_660

Bug filed with OSA at:
https://bugs.launchpad.net/openstack-ansible/+bug/1559380

**Comment by andy-maier** [comment]
I can see two issues:

1. The break of the OpenStack Ansible gate checks is caused by the dependency of pywbem on the "six" package, already during pywbem installation.

   Proposed solution: pywbem project eliminates the pre-dependency on "six". Is already under way.

2. The local build failures may be caused by the M2Crypto dependency being established in the build script after pywbem (see first line of the log you quoted). 

   Proposed solution: Please move M2Crypto before pywbem and let us know whether that solves it.

**Comment by andy-maier** [comment]
I released 0.8.2 to PyPI. That version eliminates the dependency on the "six" package it had during its own installation.

Please try it out to see whether it resolves the issue in the OpenStack Ansible gate checks.

Please also let me know whether you can move the M2Crypto installation before the pywbem installation in your local build, and if so, whether that helps. Note that pywbem does state its dependency on M2Crypto in the 'install_requires' argument of its setup script.

**Comment by Logan2211** [comment]
Hi Andy,

pip controls the ordering. OSA is building wheels using pip requirements files:
https://github.com/openstack/openstack-ansible/blob/liberty/playbooks/roles/repo_build/tasks/repo_build.yml#L33-L48
and an example requirements file: http://rpc-repo.rackspace.com/os-releases/12.0.5/requirements_local_filtered.txt

So OSA itself does not pull in m2crypto, but pywbem does.
From my build log:
Collecting M2Crypto (from pywbem->-r /var/www/repo/os-releases/12.0.9/requirements_local_filtered.txt (line 34))
  Downloading M2Crypto-0.23.0.tar.gz (183kB)

I'm not sure why pip is building m2crypto after pywbem, but it seems like some issue with the pywbem packaging implementation as it relates to pip. At this point it looks like OSA will be removing pywbem from the build requirements as it is not a globally required item in openstack. https://review.openstack.org/#/q/topic:broken_gate so I think for me it is now a non-issue. But thank you for looking into it and if you look into it further and need more debugging just let me know.

**Comment by andy-maier** [comment]
I compared the way pywbem specifies its requirements in the setup script with paramiko (as one example that is also referenced in the pip requirements files of OSA linked in your response, and I did not find a notable difference. Both calculate the content of the `install_requires` argument to `setup()` at runtime, and both use the `setup()` function from `setuptools`. Paramiko does have a simple 'setup.cfg` file, while pywbem does not have one, but I did not see anything in it that caught my eye.

Given that pywbem was removed, I consider this resolved, and if the EMC VMAX Cinder driver has a new issue, we'll work it once it gets raised.

**Comment by andy-maier** [comment]
Hmmm. When I look at the PyPI entry for paramiko 0.16.0, it *does* show a section "Requires Distributions" listing `ecdsa` and `pycrypto`, which is exactly what it sets as the `install_requires` argument. Pywbem 0.8.2 also sets that argument, but its PyPI page does not have a section "Requires Distributions".
So there must be a difference that is not yet understood.
Does anyone know why this happens?

**Comment by andy-maier** [comment]
I have posted an according question to the python-dev mailing list, and at some point, it will hopefully show up in the archives:
https://mail.python.org/pipermail/python-dev/2016-April/date.html

**Comment by ionelmc** [comment]
You have to use [twine](https://pypi.python.org/pypi/twine) for uploading the distributions. Using `setup.py upload` doesn't send the right metadata for some reasons.

**Comment by andy-maier** [comment]
Ionel,
thanks much for this hint!!

**Comment by andy-maier** [comment]
I have created issue #242 to follow up on the use of `twine`.

I think this issue here can be closed, as the OpenStack Ansible team has removed the dependency to pywbem.
