### ISSUE TITLE
MOF Compiler fails string compile with the dir search options

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1138]
The mof_compiler compile_file search option lets the compiler search directories in an iterable of directories for dependent classes.  Thus, classes where the superclasses reference properties, etc.are not in the repo these directories are searched for these classes.

However, despite the fact that compile_string has access to the same search path iterable it does not work if the mof to be compiled is a string rather than a file

If fails at the first include because that is not considered a dependent class so the find_class algorithm is not implemented.

Thus, if I can do:

``

        mofcomp = MOFCompiler(MOFWBEMConnection(),
                              search_paths=search_paths,
                              verbose=verbose)
        mofcomp.compile_file(mof_file, namespace)

where mof_file is:

``

     #pragma locale ("en_US")
     #pragma include ("Interop/CIM_RegisteredProfile.mof")

I should also be able to do:

``

       mof_str = """
            #pragma locale ("en_US")
            #pragma include ("Interop/CIM_RegisteredProfile.mof")
            """
        mofcomp = MOFCompiler(MOFWBEMConnection(),
                              search_paths=search_paths,
                              verbose=verbose)
        mofcomp.compile_str(mof_str, namespace)

**Comment by andy-maier** [comment]
Fixed by PR #1154.
