### ISSUE TITLE
Left side menu in docs missing table of contents

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1141]
In some cases , ex. 4.7 and 4.8 for me, the left side menu only has next topic and previous top but not link to section 4 or table of contents.

I marked this priority because it makes it hard to get out of some sections of the document.

**Comment by andy-maier** [comment]
The Sphinx concept for the left side menu seems to be that it shows the sections on the current page.

It does *not* show a user-definable heading level that is the same regardless of which heading level is shown on the current page.

If e.g. heading 4.2 is shown on the current page, showing a left side menu of the entire chapter 4 would require showing a heading level in the left menu that is *above* the heading level shown on the current page.

I already tried to get there, but did not find a way (that at the same time splits the lengthy chapter 4 across multiple pages).

The way to get out of a subchapter of chapter 4 is for example to click on the link to the (parent) chapter 4 which is shown at the very top of the page layout.

This is no different how you get to the top level of the chapter hierarchy when you are on e.g. the chapter 3 page (i.e. by clicking on the link "pywbem {version}" at the top of the page layout.

**Comment by andy-maier** [comment]
We agreed to close this one for now.
