### ISSUE TITLE
WBEMServer get_central_instances error from server

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1145]
When get_central instances makes a request on the server it looks for CIMError exceptions of ::

            if exc.status_code in (CIM_ERR_METHOD_NOT_AVAILABLE,
                                   CIM_ERR_NOT_SUPPORTED):

and passes on to the next method to test.  I think it should also look for CIM_ERR_METHOD_NOT_FOUND.

The ones it passes on to go to the next technique are CIM_ERR_INVALID_NAMESPACE,  INVALID_PARAMETER, NOT_FOUND(The class is not found and FAILED.   This seems like a logical choice.

**Comment by andy-maier** [comment]
I agree with adding CIM_ERR_METHOD_NOT_FOUND.

**Comment by andy-maier** [comment]
Fixed in PR #1146.
