### ISSUE TITLE
New valuemapping class method

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1153]
While the toValues is the core capability of the ValueMapping class (i.e. the ability to get from mapvalue to value for display, etc.  I had to do the opposite for creating instances to intsert into the mock repository for the wbemserver test. I definined what I wanted in terms of the Value and wanted to create convert that to the map.

I note that there is no method for that.

I propose that we need a tovaluemap that takes a string parameter and returns either the corresponding ValueMap or an error if that string is not in the valuelist.

**Comment by andy-maier** [comment]
We agreed this is useful e.g. when creating instances, and we will schedule it for a future release.

**Comment by andy-maier** [comment]
Fixed in PR #1215.
