### ISSUE TITLE
Testsuite readme and compiling test.mof

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1159]
This README currerntly defines the building of a repo using pegasus cimmof to install the test.mof

cimmof < test.mof

In particular since it is not really required that pegasus be on the same system as pywbem. I also think that this line of code is actually incorrect for pegasus today.

I think that should reflect using mof_compiler.

mof_compiler -s <target_url> test.mof

**Comment by andy-maier** [comment]
Fixed in PR #1161.
