### ISSUE TITLE
Change name of compile mof method in mocker

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1174]
Currently the name for the compile string method is mocker is 

compile_mof_str

Would like to change it to compile_mof_string just to keep the full word string to be more consistent with what is in the mof compiler

compile_string

and 

compile_file

Would like to get this into 0.12.0 since this is the initial release.   

I am doing this only because I keep making the error when typing in the method name.

Note that we could even change to

compile_string

compile_file

To be completely consistent with the mof compiler.

**Comment by andy-maier** [comment]
Fixed by PR #1178.

**Comment by andy-maier** [comment]
I like the variant with "_mof_" in the names, because in the faked connection, there is no implicit MOF context. However, one could also argue that the only kind of compile tehre is, is theone for MOF.
I'm open either way. Please comment on that via the PR that is up.
