### ISSUE TITLE
Default log_dest on pywbem log config functions

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1180]
In the code of the current master branch, the log_dest default is "file" because that seemed to be convenient if one wants to enable logging and uses the pywbem log config functions for both python logger configuration and pywbem activation.

However, it is inconvenient for users that want to use the python logging config functions and use the pywbem log config functions only for detail level and activation. It seems a bit weird that one needs to disable the default "file" to `None`, in that case.

**Discussion point:** Should we change the default for log_dest in the pywbem log config functions to `None`?

**Comment by KSchopmeyer** [comment]
I need to think this one through this afternoon

**Comment by andy-maier** [comment]
Karl, let's make the decision whether to change to a default of `None` independently of what it takes to get there. The worst case is that we have to adjusttest cases, which is always doable.

**Comment by KSchopmeyer** [comment]
I agree.   I just want to see what the impact is and a test case is a good way to do that.

**Comment by KSchopmeyer** [comment]
I think it is logical. Lets do it.,  None is the default. 

I added a couple of new tests around None that we can put in.

**Comment by KSchopmeyer** [comment]
There is still a bunch of behavior in logging that and log_capture that I do not understand. In any case if it makes sense to you, lets set the log_dest default to None and proceed from there.

**Comment by andy-maier** [comment]
It does make sense to me, and I'll put up a PR for it.

**Comment by andy-maier** [comment]
FIxed in PR #1189.
