### ISSUE TITLE
Add method to simplify getting dmtf schema for pywbem_mock

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1187]
After working with the mocker it would appear that:

1. It is much easier to use if you can compile classes into it directly.

2. In most cases this is based on the DMTF classes and DMTF schema.  This is the core for most users

3. The user probably only needs a small subset of classes to build the repository necessary for even a group of tests.

4. The user only knows the leaf classes that they want to install but the repository needs the class hierarchy and class dependences above the leaf classes to be a consistent repository and complete for creating instances and executing tests.

A simple solution would be a single method that acquires the DMTF mof for a specified schema releasefrom the DMTF web site, downloads and expands it and compiles the classes necessary from the list of leaf classes provided by the user.  I believe that most of the code for this works except for the problems documented in issue #1160. The current test code to install the schema is a major part of this.

Thus a method that depended on the following input parameters and resulted in the classes and qualifiers compiled into the repository seems logical

1. DMTF Schema version - Note that since SMI uses the experimental schema we may want option to include experimental schema also.

2. List of leaf classes that the user wants in the repository.

3. Local directory location for the schema to be stored. This allows the schema to be downloaded just once rather than for each test.

With this the new method would:

1. Use a slight expansion of the current install_dmtf_schema (destination directory and schema version variables)

2. Create the include mof from the class list as a string

3. Call the pywbem_mock compile_mof_string with the include mof from (b) which would compile the
classes on the list and any classes upon which these classes depend (superclasses, etc.)

As we did in pywbem, the user could chose to commit the directory containing the DMTF schema to
a repository eliminating the need to download frequently but that is beyond the scope of this work.

```

   #  possible method in FakedWBEMConnection
    def build_dmtf_schema_mof(class_list, schema_version, schema_dir):
        """
        Install the classes defined by class_list and classes/qualifier declaration upon which they
        depend from the DMTF  release schema defined by schema_version into the fake repository.   
       The directory schema_dir is used to acquire, and expand the  downloaded DMTF zip file so that
       it does not need to be downloaded a second time unless the schema version changes.
       This methods does not include any classes in the repository that are not on the class_list or
       are a)superclasses of the classes on the list, classes references in the embeddedInstance
       qualifier, or classes referenced in reference properties.
      The user should be able to correctly build instances of these classes subsequent to calling this
      method.
      """

```

**Comment by andy-maier** [comment]
Fixed with PR #1220.
