### ISSUE TITLE
mof_compiler issue with search_paths ctor parameter

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1227]
This parameter requires an iterable but accepts a string and tries to use it.  In this case, since typically the string is an absolute file path, it tries to search the whole disk

We either accept a string and cvt it to a list or issue a TypeError message to correct this.

**Comment by KSchopmeyer** [comment]
DISCUSSION: 

1. the description for the searche path parameter in mof_compiler ctor  is that this requires an iterable. However, a string is an iterable.  Should we reduce that from iterable to list or tuple???  Do we have other places where this same issues comes up???

2. We can either allow string and put it in a list or disallow it. Since this is not a heavily used api I am happy with either noting that the biggest single use is probably the DMTF schema where the search path is a single string representing a path to the schema_mof_dir, not a list of paths.

**Comment by KSchopmeyer** [comment]
The first conclusion documented as issue # 1292. The second is being fixed in the compiler.

**Comment by KSchopmeyer** [comment]
I thought we had fixed this.  Karl will review this one

**Comment by andy-maier** [comment]
PR #1391 fixes this.
