### ISSUE TITLE
Create issues from TODOs in test_wbemconnection_mock.py

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1240]

**Comment by KSchopmeyer** [comment]
Yes I agree.  Removing discussion needed.

**Comment by andy-maier** [comment]
**Discussion point:** Is this about the 12 TODOs marked "future" or about the 3 TODOs not marked "future"?

**Comment by andy-maier** [comment]
Karl will take a pass through these TODOs and will create issues as needed. If an issue is created, the corresponding TODO should be marked with an issue number.

**Comment by andy-maier** [comment]
This issue should be re-evaluated once the mocker refactoring is complete.

**Comment by andy-maier** [comment]
I think this issue can now be re-assessed.

**Comment by andy-maier** [comment]
A part of the TODOs have been addressed in #2328, for 1.0.0b3.
Another part is covered in issue #2327 .
This issue can be considered fixed.
