### ISSUE TITLE
`python setup.py` failed when ran from taged release tarball

### ISSUE THREAD

**Issue by cathay4t** [pywbem/pywbem#1245]
* Errors:
  Got error when run `python setup.py` from release tarball from (https://github.com/pywbem/pywbem/releases/tag/0.12.2)
```
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/fge/Downloads/pywbem-0.12.2/.eggs/pbr-4.0.2-py3.6.egg/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/fge/Downloads/pywbem-0.12.2/.eggs/pbr-4.0.2-py3.6.egg/pbr/util.py", line 258, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/fge/Downloads/pywbem-0.12.2/.eggs/pbr-4.0.2-py3.6.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/fge/Downloads/pywbem-0.12.2/.eggs/pbr-4.0.2-py3.6.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/fge/Downloads/pywbem-0.12.2/.eggs/pbr-4.0.2-py3.6.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/fge/Downloads/pywbem-0.12.2/.eggs/pbr-4.0.2-py3.6.egg/pbr/packaging.py", line 816, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or
access to an upstream git repository. It's also possible that there is a
mismatch between the package name in setup.cfg and the argument given to
pbr.version.VersionInfo. Project name pywbem was given, but was not able to be
found.
error in setup command: Error parsing
/home/fge/Downloads/pywbem-0.12.2/setup.cfg: Exception: Versioning for this
project requires either an sdist tarball, or access to an upstream git
repository. It's also possible that there is a mismatch between the package
name in setup.cfg and the argument given to pbr.version.VersionInfo. Project
name pywbem was given, but was not able to be found.
```

* Root casue
  `pbr.version.VersionInfo` failed to find out the version of current project. The `pbr` get version from
   any of below. (https://git.openstack.org/cgit/openstack-dev/pbr/tree/pbr/packaging.py)
  * Get version from git repo: `_get_version_from_git()`.
  * Get from `_get_version_from_pkg_metadata` which are `['PKG-INFO', 'METADATA']`.
  * Environment variable `PBR_VERSION` or `OSLO_PACKAGE_VERSION`.

* How to fix:
  Add `PKG-INFO` or `METADATA` file.

* Workaround:
  `env PBR_VERSION=0.12.2 python setup.py`

**Comment by andy-maier** [comment]
Hello, thanks for reporting this and for doing the analysis on how it could be solved.

I have to say though that you are the first one I know of that tries to install pywbem from the source archive provided by Github!

Github seems to simply pack the directory content, and the result is not a valid Python sdist archive. When building the Python sdist archive using setuptools (e.g. via `make build`), the resulting tarball does include a PKG-INFO file, and is installable using `python setup.py install` (or `pip install .`, fwiw).

So the question for us is whether we want to add support for installing from the Github-created source archive. I don't know of a way to influence how Github creates that archive, so the only way I currently see to support this, is to have a PKG-INFO file checked in the Git repo, presumably with an automated process that copies it from `pywbem.egg-info/PKG-INFO`.

We'll have to discuss this in the team.

Another alternative for you would be to follow the install recommendations in the pywbem docs (http://pywbem.readthedocs.io/en/latest/intro.html#installation). Is there a reason you cannot use `pip`?

**Comment by cathay4t** [comment]
I am packing pywbem in rpm for Fedora where `pip` might not be appropriate (will find that out).

**Comment by andy-maier** [comment]
Fixed by PR #1247.

**Comment by cathay4t** [comment]
Thank you.

**Comment by andy-maier** [comment]
Do you have a target date when you need this change to be released?

**Comment by cathay4t** [comment]
@andy-maier No. I already used the workaround `env PBR_VERSION` for the Fedora pywbem 0.12.2 release: https://src.fedoraproject.org/rpms/pywbem/c/f21e42209695b7fcdff096e983a13fc89096b80a?branch=master

**Comment by andy-maier** [comment]
OK, great. Then we will schedule that for the pywbem 0.13.0 release, which should not be too far away (but does not have a firm date).

**Comment by andy-maier** [comment]
@cathay4t One more question on the rpm source: I was always wondering whether or not the LICENSE.txt file should be installed to the `pywbem` package directory.

Do you have a recommendation for us regarding this?

**Comment by andy-maier** [comment]
@cathay4t One more on the rpm source: The files installed to the bin directory (mof_compiler, wbemcli, wbemcli.py) and the README file are part of the `%files` list for Python 3, but not for Python 2. So if someone installs only `python2-pywbem`, they will not get these files. Please double check whether my understanding is correct.

If so, this part of the rpm spec file is incorrect. These files apply to both Python 3 and Python 2.

**Comment by andy-maier** [comment]
@cathay4t One more on the rpm spec file: The Python "mock" package is needed for running pywbem since its version 0.12.0, because the new `pywbem_mock` sub-module needs it. So the corresponding RPM package needs to be specified, for both Python 2 and 3.

**Comment by andy-maier** [comment]
@cathay4t One more: Since quite a while, pywbem no longer contains a provider interface.

Please change the summary definitions in the spec file to remove "and Provider Interface".

**Comment by andy-maier** [comment]
@cathay4t I'm in the process of creating a fork of the pywbem repo on fedoraprojects, so I can make these proposals in the form of PRs. Let me know in case you disagree with this approach. I'm just trying to make things easier for you, since this is really a number of changes.

**Comment by cathay4t** [comment]
@andy-maier 
> @cathay4t One more comment on the rpm spec file: The files installed to the bin directory (mof_compiler, wbemcli, wbemcli.py) and the README file are part of the %files list for Python 3, but not for Python 2. So if someone installs only python2-pywbem, they will not get these files. Please double check whether my understanding is correct.

> If so, this part of the rpm spec file is incorrect. These files apply to both Python 3 and Python 2.

The [Fedora packaging guidelines of python][1] said `If the executables provide the same functionality independent of whether they are run on top of Python 2 or Python 3, then only the Python 3 version of the executable should be packaged.`

So the bin files are python3 only. I will try to move them to new sub package `pywbem-utils` once I
find a way to install it when user upgrade.

[1]: https://fedoraproject.org/wiki/Packaging:Python

**Comment by cathay4t** [comment]
> @cathay4t One more question on the rpm spec file: I was always wondering whether or not the LICENSE.txt file should be installed to the pywbem package directory.

> Do you have a recommendation for us regarding this?
No, I don't know. For rpm, I should use `%license` macro.

**Comment by cathay4t** [comment]
> @cathay4t  I'm in the process of creating a fork of the pywbem repo on  fedoraprojects, so I can make these proposals in the form of PRs. Let me  know in case you disagree with this approach. I'm just trying to make  things easier for you, since this is really a number of changes.

@andy-maier It would be great to have a developer supervise rpm packaging. 

No sure it's related or not. From upstream's prospective, I provide `make rpm` and `make deb` in my project libstoragemgmt. That helps package maintainers on taking reference for their distribution.

BTW: debian pywbem package are still 0.8.0 for years. Maybe a `make deb` command could helps
debian maintainer to adopt it without understanding the layout/attic/etc.

**Comment by cathay4t** [comment]
For `attic/twisted_client`, since we have it in F28, we should keep doing the same for API stability seek.
For F29 or later, since python2 is removed, we will not have that at all.

**Comment by cathay4t** [comment]
I also made a new update on the Fedora rpm SPEC, if you are working on a PR, please take a look first:
https://src.fedoraproject.org/rpms/pywbem/commits/master

Thank you.

**Comment by andy-maier** [comment]
Updated PR #1266.

**Comment by andy-maier** [comment]
PR #1266 has been moved to the next release, and so has this issue.

**Comment by andy-maier** [comment]
We have removed the use of pbr, and that should solve this issue.

PR #1882 applies that to the upcoming 0.15.0 release, and PR #1876 to master.
If you want to try it out before 0.15.0 is released, create a source tarball with `make build` on the `stable_0.15` branch.

I am closing this issue; please feel free to reopen if needed.
