### ISSUE TITLE
pywbem_mock  _wbemconnection.py outputs bytes

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1276]
In python 3 the uprint method outputs bytes and not unicode.   The method str.encode produces a byte output not unitocde so that the result is bytes when the terminal output is used.

Python 3 output to terminal

    b'# Namespace root/blah: contains 9 Qualifier Declarations \n'
    b'Qualifier Abstract : boolean = false,\n    Scope(class, association, indication),\n       Flavor(EnableOverride, Restricted);\n'
    b'Qualifier Aggregate : boolean = false,\n    Scope(reference),\n    Flavor(DisableOverride, ToSubclass);\n'

Python 2 output to terminal::

    # Namespace root/blah: contains 9 Qualifier Declarations 

    Qualifier Abstract : boolean = false,
        Scope(class, association, indication),
        Flavor(EnableOverride, Restricted);

    Qualifier Aggregate : boolean = false,
        Scope(reference),
       Flavor(DisableOverride, ToSubclass);

Output to file in python 3 has same issue.

**Comment by andy-maier** [comment]
Fixed in PR #1277.
