### ISSUE TITLE
Problem compiling unicode

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1278]
I tried to compile the following unicode and the compiler failed.

NOTE: Sure this is really an issue but wanted to document immediatly

    E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u212b' in position 0: ordinal not in range(128)  pywbem/mof_compiler.py:1798: UnicodeEncodeError

        str = u'instance of CIM_Foo_sub2 as $foosub22 {' \
              u'InstanceID = "CIM_Foo_unicode";\n' \
              u'cimfoo_sub2 = \u212b \u0420 \u043e \u0441 \u0441' \
              u' \u0438 \u044f \u00e0;};'

generally same in python 3:

      raise MOFParseError(parser_token=p, msg=msg)

    E pywbem.mof_compiler.MOFParseError: MOFParseError:
    E None:2:14 msg=Illegal character 'Å'
    E ['instance of CIM_Foo_sub2 as $foosub22 {InstanceID = "CIM_Foo_unicode";', 'cimfoo_sub2 = Å   Р о с с и я à;};', ' ^^^^^^^^^^^^^^^^^^']

pywbem/mof_compiler.py:460: MOFParseError

**Comment by andy-maier** [comment]
I believe that PR #1277 is very likely to resolve this issue.

Can you please try to reproduce the issue with PR #1277 applied?

**Comment by andy-maier** [comment]
Fixed in PR #1280.

**Comment by andy-maier** [comment]
A note on the example originally reported: The double quotes around the string value were missing in that example. Nevertheless, there were bugs. See the commit message in PR #1280.
