### ISSUE TITLE
Subscription manager fails with python 2.6

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1279]
The subscription manager fails with python 2.6 in the statement

        listener_url = '{}://{}:{}'.format(schema, host, port)

with the error:

    ValueError: zero length field name in format

**Comment by andy-maier** [comment]
Python 2.6 requires a field number:;

    listener_url = '{0}://{1}:{2}'.format(schema, host, port)

However, I don't find this code in the master branch...
