### ISSUE TITLE
Review code for iterables as method, etc. input but accept strings and misuse them

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1292]
From discusssion in issue #1227. We agreed to set this up as a separate issue.

Check code for any case where we have only iterable as type input for method, ctor, etc. but allow string since string is a form of iterable.

**Comment by andy-maier** [comment]
Here is the complete list of locations where we have input parameters that are iterables but not string, and are not type-checked:
* `MOFCompiler.__init__(search_paths)` - TODO

The following functions take iterables but are fine:
* `FakedWBEMConnection.compile_mof_file(search_paths)` - DONE: Parameter is passed on to `MOFCompiler.__init__(search_paths)` and should be checked there.
* `pl` in several operation functions in wbemcli.py - DONE: Parameter is passed on to `WBEMConnection` operation methods and should be checked there.
* `PropertyList` in several operation functions in `WBEMConnection` - DONE: The Iter... functions pass it on to the Tradtional or Pull operations. All other operation functions pass it through a common function `_iparam_propertylist()`
* `WBEMConnection._iparam_propertylist()` - DONE: Type was already checked

**Comment by andy-maier** [comment]
Fixed in PR #1300.
