### ISSUE TITLE
Lots of Resource Warning messages during tests with python 3

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1299]
We are getting lots  of the following Resource warning messages now with python 3, for each test run, Looks like one for each test.

testsuite/testclient/setqualifierdecl.yaml::SetQualifierF1
  /home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/httpretty/core.py:485: ResourceWarning: unclosed file <_io.BufferedRandom name=5>
    self.fd = FakeSockFile()
  /home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/httpretty/core.py:485: ResourceWarning: unclosed file <_io.BufferedRandom name=6>
    self.fd = FakeSockFile()

testsuite/testclient/setqualifierdecl.yaml::SetQualifierNS1
  /home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/httpretty/core.py:485: ResourceWarning: unclosed file <_io.BufferedRandom name=5>
    self.fd = FakeSockFile()
  /home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/httpretty/core.py:485: ResourceWarning: unclosed file <_io.BufferedRandom name=6>
    self.fd = FakeSockFile()

**Comment by KSchopmeyer** [comment]
per discussion, Karl agreed to close this one.

**Comment by ZebtinRis** [comment]
Hey! I'm running into a similar issue when we run out tests and using httpretty.

I would love to know how you guys cleaned up the Warnings :)
