### ISSUE TITLE
Add more testcases for the client test (test_client.py)

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#13]
The new test_client.py provides a real life end to end test for the client. It mocks up the HTTP connection and is able to check expected request, hand back a response, and check for the expected result at the client API.

There is an initial set of testcases right now, but that set should be extended to cover more operations, and more success and particularly error scenarios.

**Comment by andy-maier** [comment]
There are several other issues open to add such test cases.
Suggest to close this one.

**Comment by KSchopmeyer** [comment]
We will start by karl generating the output of some specific tests and we can determine how hard it is to convert those to mock.

**Comment by andy-maier** [comment]
Can we close this one?

**Comment by KSchopmeyer** [comment]
Karl agreed in another issue to grab the test output from run_cimoperations.py and start the move to mock and this is such a general issue we will close it.
