### ISSUE TITLE
get one  performance

### ISSUE THREAD

**Issue by allen0817** [pywbem/pywbem#1304]
"Usage: svc_perf_wbem.py --cluster <cluster1> [--cluster <cluster2>...] --user <username> --password <pwd> --cachefile <path>|none"

I want a specific disk performance value for IBM v7000. What should I write in this path?

**Comment by andy-maier** [comment]
@allen0817: I suggest that you ask this question over in https://github.com/ma-tty/svc-perf.
@ma-tty: In case you see this, can you please answer this?

**Comment by andy-maier** [comment]
@allen0817: Any progress on this one?

**Comment by andy-maier** [comment]
Closing the issue due to inactivity.
