### ISSUE TITLE
DSP0200 issue: Namespace creation via CIM_Namespace in "root" namespace

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1311]
Another issue that should be created in Mantis:

DSP0200 1.4 says in 5.4.3.1 "Namespace Creation":

"It is recommended that instances of CIM_Namespace be created in root unless there is a specific reason to define them in another namespace. The inclusion of a CIM_Namespace instance within a namespace other than root is allowed."

Issues with this:

1. Editorial: It uses the word root without making it clear that this is meant to be the name of a namespace, i.e. "root".

2. The recommendation to target "root" for creating CIM_Namespace instances is a bit unexpected here, because it mixes the old and new world. The old world uses hierarchical namespace names with the `__Namespace` pseudo class, and the "root" namespace plays a central role there. The new world uses flat namespace names with the `CIM_Namespace` class, and a flat namespace named "root" should not play any special role in that new world (for example, consider the namespace named "/interop" defined in DSP1033). If we call out any special namespace for the new world at all, it should be the interop namespace (with its different possible names as defined in DSP1033). While this information is marked as deprecated, it is still important because the only other place that defines how to create namespaces is the WBEM Server Profile DSP1092, which is not widely implemented, and which only defines namespace creation via an extrinsic method. It does not even cover namespace creation via CreateInstance.

Here is my suggestion regarding issue 2: Keep it as deprecated, but update it so that it describes a working approach for namespace creation in the new world via CreateInstance on CIM_Namespace class targeting the interop namespace, referencing DSP1033 for a definition of the interop namespace.

**Comment by KSchopmeyer** [comment]
Filed as DMTF Mantis issue #2842 on 8 Oct. 2019
