### ISSUE TITLE
string index exception in tomof of CIMInstance

### ISSUE THREAD

**Issue by dugganj** [pywbem/pywbem#1312]
I ran across this problem running pywbem against providers in SNIA's SMI-Lab.  When running tomof on the instance named 
//10.1.134.184/interop:ECOM_RegisteredProfile.InstanceID="EMC Corporation:DMTF Indications profile:1.0.0"

I got a string index out of range exception.  The stack traceback is:
Traceback (most recent call last):
  File "C:/Users/dugganj/PycharmProjects/untitled/test1.py", line 41, in basicTest
    mof = singleInst.tomof()
  File "C:\Miniconda3\lib\site-packages\pywbem\cim_obj.py", line 3374, in tomof
    mof.append(p.tomof(True, MOF_INDENT, maxline))
  File "C:\Miniconda3\lib\site-packages\pywbem\cim_obj.py", line 5147, in tomof
    if val_str[0] != '\n':
IndexError: string index out of range

Interestingly, I was able to run the same instance through to cimxmlstr.  The result of doing so is:
<VALUE.INSTANCEWITHPATH>
 <INSTANCEPATH>
  <NAMESPACEPATH>
   <HOST>10.1.134.184</HOST>
   <LOCALNAMESPACEPATH>
    <NAMESPACE NAME="interop"/>
   </LOCALNAMESPACEPATH>
  </NAMESPACEPATH>
  <INSTANCENAME CLASSNAME="ECOM_RegisteredProfile">
   <KEYBINDING NAME="InstanceID">
    <KEYVALUE VALUETYPE="string">EMC Corporation:DMTF Indications profile:1.0.0</KEYVALUE>
   </KEYBINDING>
  </INSTANCENAME>
 </INSTANCEPATH>
 <INSTANCE CLASSNAME="ECOM_RegisteredProfile">
  <PROPERTY.ARRAY NAME="ImplementedFeatures" PROPAGATED="false" TYPE="string"/>
  <PROPERTY NAME="SpecificationType" PROPAGATED="false" TYPE="uint16">
   <VALUE>2</VALUE>
  </PROPERTY>
  <PROPERTY NAME="OtherSpecificationType" PROPAGATED="false" TYPE="string">
   <VALUE></VALUE>
  </PROPERTY>
  <PROPERTY NAME="RegisteredOrganization" PROPAGATED="false" TYPE="uint16">
   <VALUE>2</VALUE>
  </PROPERTY>
  <PROPERTY NAME="OtherRegisteredOrganization" PROPAGATED="false" TYPE="string">
   <VALUE></VALUE>
  </PROPERTY>
  <PROPERTY NAME="RegisteredName" PROPAGATED="false" TYPE="string">
   <VALUE>Indications</VALUE>
  </PROPERTY>
  <PROPERTY NAME="RegisteredVersion" PROPAGATED="false" TYPE="string">
   <VALUE>1.0.0</VALUE>
  </PROPERTY>
  <PROPERTY.ARRAY NAME="AdvertiseTypes" PROPAGATED="false" TYPE="uint16">
   <VALUE.ARRAY/>
  </PROPERTY.ARRAY>
  <PROPERTY.ARRAY NAME="AdvertiseTypeDescriptions" PROPAGATED="false" TYPE="string">
   <VALUE.ARRAY/>
  </PROPERTY.ARRAY>
  <PROPERTY NAME="InstanceID" PROPAGATED="false" TYPE="string">
   <VALUE>EMC Corporation:DMTF Indications profile:1.0.0</VALUE>
  </PROPERTY>
  <PROPERTY NAME="Caption" PROPAGATED="false" TYPE="string">
   <VALUE>DMTF Indications profile</VALUE>
  </PROPERTY>
  <PROPERTY NAME="Description" PROPAGATED="false" TYPE="string">
   <VALUE>DMTF Indications profile</VALUE>
  </PROPERTY>
  <PROPERTY NAME="ElementName" PROPAGATED="false" TYPE="string">
   <VALUE>DMTF Indications profile</VALUE>
  </PROPERTY>
 </INSTANCE>
</VALUE.INSTANCEWITHPATH>

**Comment by andy-maier** [comment]
I had a look into this, and from analyzing the code, I suspect the exception is raised when processing the `AdvertiseTypes` property, which is an empty array. The code in `CIMProperty.tomof()` accesses the first character of the returned MOF fragment for the empty array value to check it for `\n`, but because the value of the empty array is represented as an empty string, this causes the `IndexError` being raised.
It works in `CIMProperty.tocimxml()` because the logic for creating CIM-XML is quite different.

**Comment by andy-maier** [comment]
Also, the issue was not found in our tests because the testcase for empty array was missing. I will add one. (Shame on us, but this part of the tests was still in front of us to be made complete, so we would have gotten to it at some point).

**Comment by andy-maier** [comment]
This issue is fixed in PR #1313 targeting pywbem 0.13.0 and has been rolled back into the pywbem 0.12 fix stream in PR #1314.

**Comment by andy-maier** [comment]
@dugganj Please let me know which version of pywbem you are using.

If you want to test the fixes, you can install any of the two pywbem branches that have the fix as described in the installation section of the pywbem docs.

**Comment by andy-maier** [comment]
I have checked for further occurrences of this error, and it also occurs for `CIMQualifier` and `CIMQualifierDeclaration` with empty array values. I updated the PRs to fix that as well, and to also add testcases for those.

**Comment by dugganj** [comment]
0.12.3

jpd

**Comment by andy-maier** [comment]
@dugganj Jerry, I have merged the two PRs, so if you want to use the 0.12 based version now, use it from branch `stable_0.12`. We'll release a 0.12.4 version containing the fix, shortly.

**Comment by andy-maier** [comment]
@dugganj Jerry, I just talked with Karl. If you have further issues to bring up, please do so. We can then also put that into the 0.12.4 version. Otherwise, we would release it with just this one fix in.

**Comment by dugganj** [comment]
I’ll hang loose until you do an official release of 0.12.4.

jpd

**Comment by dugganj** [comment]
I have no further issues to add.

jpd

**Comment by andy-maier** [comment]
@dugganj Jerry, I have just released pywbem 0.12.4 to Pypi.

Installation via e.g.:

`pip install pywbem --upgrade`

**Comment by dugganj** [comment]
Excellent.  I’ll check it out later today.

jpd

**Comment by andy-maier** [comment]
CLosing this issue. Please open a new issue in case of any trouble.
