### ISSUE TITLE
Automate PyWBEM release process

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#132]
Currently, there is a lot to be done manually for a release to PyPI, or for starting development of a new releasse. See the new DEVELOP.md that is part of PR #133 for a detailed description of the current process.

This ought to be more automated, in order to save time and to avoid problems.

Here is an example of a Python script that automates the release process for a PyPI package:
https://github.com/python-babel/babel/blob/master/scripts/make-release.py

**Comment by andy-maier** [comment]
We agreed in the call today that we would want to automate it as much as possible.

**Comment by andy-maier** [comment]
PR #229 addresses some of this.

**Comment by andy-maier** [comment]
**Discussion:** Reading through the DEVELOP.md in PR #238 for v0.8.x, and imagining how it would look like for v0.9.0 onwards, it seems to me that there is not much potential for further automating the release process.

My proposal is to update the DEVELOP.md of the `master` branch to be consistent with the v0.8 version in PR #238, and to go with that.

**Comment by andy-maier** [comment]
PR #246 updated DEVELOP.md to be consistent with the v0.8 version.

**Discussion:** Can we close this issue, or do we think there is more to be automated.

**Comment by KSchopmeyer** [comment]
Karl agrees.  Time to close this one.  When we figure out if we do want to automate more, we can open another issue
