### ISSUE TITLE
How to properly add a CIMInstance into a dictionary?

### ISSUE THREAD

**Issue by dugganj** [pywbem/pywbem#1323]
I would like to have a dictionary (aka hashtable) to map instances to various things -- basically summaries of things like hardware / software versions, capacity summaries, etc.  In order to do this, I need to make more than one call to the provider and traverse associations.

The question is -- what do I put into the dictionary as the key?

I cannot use the CIMInstance directly, as the contents may change from call to call.  For instance, some storage providers put performance counters into their instances.  This totally negates the ability to use them as keys.

I cannot use the path (CIMInstanceName), as the complete path includes IP address information.  It is certainly possible to have a single WBEM server running on a host with multiple NIC cards.  Each NIC would have a different IP address, and thus multiple different CIMInstanceNames could access the same CIMInstance.

My best thought is to use the keybindings property of the CIMInstanceName.  This will only work, though, if the keybindings property were guaranteed to always have the same hash value for each unique CIMInstanceName.  I have run across providers that, for example, return the key properties in different orders.  The values are the same, just the order is different.  Will the pywbem hash function for keybindings return the same value in this case?

And what about the namespace component of the CIMInstanceName?

**Comment by andy-maier** [comment]
@dugganj Hi Jerry. A good key would be the WBEM URI string created from the instance path with host being set to None.

```
path = inst.path.copy()
path.host = None
key = path.to_wbem_uri()
```

**Comment by andy-maier** [comment]
I read the description of to_wbem_uri() again and there are some issues with using it for this purpose, most notably that the order of keybindings in the resulting string is the order in which they were set on the CIMInstanceName object. If the CIMInstanceName object is the result of a CIM operation, this is the order in which the keybindings appear in the CIM-XML response. Which may or may not be reliable.

The to_wbem_uri() methods have a "format" parameter, which we could extend to support a new value e.g. "canonical" that would guarantee a reliable lexical case of the class name and key names and a reliable order of the keybindings. Please let us know whether this would address your needs.

**Comment by KSchopmeyer** [comment]
Actually, we did that in OpenPegasus I believe, sorted the keys into alphabetical order so that they were always displayed, sent, etc. in the same order.

**Comment by dugganj** [comment]
I just read the documentation for to_wbem_uri.  I think adding a new format might work.  I assume such a beast would:

  1.  Strip out the authority component of the host attribute
  2.  Order the keys in a canonical way (alphabetical order would be fine)
  3.  Convert all characters to either upper or lower case.  I suggest the latter so it doesn’t feel that these names are shouting at me.

And the documentation should specifically explain how and why to use this format.  The existing documentation talks about not using the WBEM URI strings, and instead use the == operator, but it is pretty obtuse – it references DSP004, which is an incredibly obtuse document in its own right.  At the very least, add a caveat to the documentation that although == works, coming up with a hashable identifier is more tricky.

jpd

**Comment by andy-maier** [comment]
Fixed in PR #1324.

**Comment by andy-maier** [comment]
@dugganj Jerry, I have implemented support for a canonical format, as discussed, in PR #1324. Its branch is `andy/#1323-add-canonical-wbem-uri`.

Could you please verify whether this suits your needs?

Usage would be as follows, assuming you want to eliminate host from your dict key:

```
path = instance.path.copy()
path.host = None
dict_key = path.to_wbem_uri('canonical')
```

**Comment by andy-maier** [comment]
The PR #1324 will be part of the upcoming 0.13.0 release. Closing this issue.
