### ISSUE TITLE
Is there a way to specify the cimxml header?

### ISSUE THREAD

**Issue by yq8925** [pywbem/pywbem#1326]
Hi, 
In case when I invoke CIM method 'UpdateExpiredPassword', I need to add ('Pragma', 'UpdateExpiredPassword') to the cimxml header. But I cannot find a way to specify the cimxml header from class WBEMConnection. 
Is there a way to specify the cimxml header? How?

Thanks a lot.

**Comment by andy-maier** [comment]
Pywbem does not currently provide a means to set the HTTP headers of a CIM-XML request.

After googling around, I found that the SFCB CIMOM requires such a non-standard HTTP header to be set in order to update the CIMOM password, as described here: http://sblim.sourceforge.net/wiki/index.php/SfcbExpiredPasswordUpdate

We'll discuss how we can address this and get back to you.

**Comment by andy-maier** [comment]
On CIM/WBEM standards conformance: It turns out that the `Pragma` HTTP header field is defined in HTTP 1.1 for implementation-specific directives: https://tools.ietf.org/html/rfc2616#section-14.32

DSP0200 allows the use of any HTTP header field in CIM-XML request or response messages, so besides putting a new requirement on clients, this header field does not violate CIM-XML standards.

**Comment by andy-maier** [comment]
A basic assumption is that any control of this that we provide in pywbem needs to be on a per operation call basis (WBEMConnection operation methods). A setting in the WBEMConnection object or a pywbem-global config value does not suffice.

I see the following options to address this. They differ in how generic the mechanism would be:

* Provide a means in operations to set arbitrary HTTP header fields on CIM-XML request messages. If we do that, the next question is should we provide access to arbitrary HTTP header fields in CIM-XML responses.
* Provide a means in operations to set just a defined set of HTTP header fields. Initially that set would consist only of the `Pragma` header field.
* Provide a means in operations to set just the `Pragma` header to a user-defined value.
* Provide a boolean flag (e.g. "sfcb_update_expired_password") in operations that causes just `Pragma: UpdateExpiredPassword` to be set.

**Discussion point:** Which option to use.

**Comment by yq8925** [comment]
hi @andy-maier , will we address it in 0.13.0 release? is there an outlook date on 0.13.0? thanks.

**Comment by andy-maier** [comment]
@yq8925 Karl and I will discuss this in our weekly pywbem call today. I will post the outcome.

**Comment by andy-maier** [comment]
We agreed to implement option 5, as follows:
- the method is detected by just its name
- the automatic mechanism is enabled by default, and there is a pywbem config variable that can disable the mechanism (in case there ia s CIM server that is not SFCB, implemented also a method with this name, and does not tolerate the HTTP Pragma header).

**Comment by andy-maier** [comment]
Regarding timeframe: It will be in 0.13.0, which would be probably around end of august. If you need it earlier, you can use the master branch once we have merged the work, which will probably be in the next few days.

**Comment by andy-maier** [comment]
@yq8925 This capability has been added in PR #1329.
If you want, you can test whether this does what you need, by installing from the branch of that PR (in your pywbem repo clone: checkout that branch, pip install . --upgrade`)

**Comment by yq8925** [comment]
@andy-maier , I will wait for 0.13.0,  thanks a lot for quick support!

**Comment by andy-maier** [comment]
I made one more change, which is to also check for the class name "SFCB_Account". This lowers the chances of generating this header field by accident to practically zero. The PR has been updated accordingly.

**Comment by andy-maier** [comment]
PR #1329 has been merged and will be released in the upcoming 0.13.0 of pywbem. Closing this issue.
