### ISSUE TITLE
monitored HDS

### ISSUE THREAD

**Issue by allen0817** [pywbem/pywbem#1330]
Hello, have you ever monitored HDS? The port of 5989 is open. Do you still need to install official agent software? Now I don't know where to start

**Comment by andy-maier** [comment]
I did not. If the port is open, you could try to run the example in the section about the WBEM Server API to see whether there is functionality behind the port.

**Comment by andy-maier** [comment]
@allen0817 Please let us know whether you made progress in this matter. Otherwise, we'll close this issue in a few days.

**Comment by allen0817** [comment]
Thank you very much for your help. Now you can connect to the storage normally, but ExecQuery cannot be used. Neither CQL nor WQL is correct

use CQL  error content
>>> res = conn.ExecQuery('CQL', 'select * from HITACHI_FCPort')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pywbem/cim_operations.py", line 1348, in ExecQuery
    Query=Query)
  File "/usr/lib/python2.6/site-packages/pywbem/cim_operations.py", line 686, in imethodcall
    raise CIMError(code, tup_tree[1]['DESCRIPTION'])
pywbem.cim_operations.CIMError: (7, u'')

**Comment by andy-maier** [comment]
The CIMError exception that is raised indicates that the WBEM server on the HDS system returned an error. CIM status code 7 is "CIM_ERR_NOT_SUPPORTED", which may mean that CQL is not supported by the HDS system, or the entire ExecQuery operation is not supported by the HDS system. Despite the returned error, it is great to see that the WBEM server on the HDS system is active and responds!

I don't know much about the CIM / SMI-S support on the HDS system, so I'm afraid I cannot help you much there. Your best bet would be to use the documentation provided by HDS.

If such documentation is not available, the way I would start investigating the CIM / SMI-S support there is to find out the brand and version of the WBEM server (CIMOM), the set of CIM namespaces it provides, and set of management profiles that are implemented. This is what you get displayed when you run the example Python code that is shown here: https://pywbem.readthedocs.io/en/latest/server.html#example

With the set of namespaces known, you could pick the right one, and enumerate the HITACHI_FCPort instances using the EnumerateInstances operation:

```
ns = 'root/cimv2'  # or whatever the right namespace would be
instances = conn.EnumerateInstances('HITACHI_FCPort', ns)
print(instances)
```

**Comment by allen0817** [comment]
His command space refers to the root/ Hitachi /smis of the official manual, and I use the same one. If ExecQuery doesn't support it, I want to get his various attributes, which method should I use? For example, I want to get the capacity of luns, the basic information on the hard drive, and the lun-dynamic data.

**Comment by allen0817** [comment]
His command space refers to the 'root/hitachi/smis'  of the official manual, which I use as well, and if ExecQuery doesn't support it, I want to get his various properties what method should I use? For example, I want to get the capacity of luns, the basic information on the hard drive, and the lun-dynamic data.

**Comment by andy-maier** [comment]
'root/hitachi/smis' looks as if that is the CIM namespace to be used, i.e. what you would specify in the `ns` variable in my short example above.

Which CIM classes you would need to use for these resources, I don't know. I would expect that to be described in the official manual.

If you don't know the CIM classes, you can list the classes in a namespace with this code:

```
ns = 'root/hitachi/smis'  # CIM namespace
classnames = conn.EnumerateClassNames(ns, DeepInheritance=True)
classnames = [cn for cn in classnames if cn.startswith('HITACHI_')]. # only implementation classes
print(classnames)
```

Then, for class names that look interesting, list their instances and look at their properties:

```
classname = 'HITACHI_.....'
instances = conn.EnumerateInstances(classname, ns)
for inst in instances:
    print(inst.tomof())  # tomof() does a more readable formatting compared to %r
```

**Comment by andy-maier** [comment]
Closing this issue. Question seems to be answered and there is no defect in pywbem.
