### ISSUE TITLE
CIMVERSION 2.8 

### ISSUE THREAD

**Issue by allen0817** [pywbem/pywbem#1331]
pywbem  version 0.7.0
The debug code version CIMVERSION  is 2.8, but pywbem only supports 2.0 ，May I have that version, please

tupleparse.py  code 
    if attrs(tt)['CIMVERSION'] <> '2.0':
        raise ParseError('CIMVERSION is %s, expected 2.0' %
                         attrs(tt)[CIMVERSION])

    child = one_child(tt, ['MESSAGE', 'DECLARATION'])

    return name(tt), attrs(tt), child

**Comment by andy-maier** [comment]
Pywbem supports any 2.x value for CIMVERSION since pywbem 0.8.

**Comment by andy-maier** [comment]
I suggest to use the latest pywbem version available on pypi.

**Comment by andy-maier** [comment]
@allen0817 Please let us know in case using the latest pywbem version creates a problem for you. Otherwise, we'll close this issue in a few days.

**Comment by allen0817** [comment]
Thank you very much for your help. I can connect normally with 0.8.1
