### ISSUE TITLE
Code issue in IterQueryInstances

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1334]
The input parameters are reversed for the ExecQuery in the IterQueryInstances method.  The call
puts the Query as the first parameter and the QueryLanguage as the second parameter.

I have no idea why I did not catch this before since it is tested in run_cimoperations.py.

Passed the mock tests because we don't really do anything in the mocker for the query.

**Comment by andy-maier** [comment]
PR #1335 addresses this in the master branch (targeting 0.13.0).
PR #1345 rolls back ths fix into the 0.12 fix stream (targeting 0.12.5).
