### ISSUE TITLE
Incompatible Python package versions

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1342]
The following incompatible versions are currently reported during "make clobber install develop" in a freshly created virtual environment:

On Python 3.6, with PACKAGE_LEVEL=minimum (with PR #1340):

* google-api-core 1.2.1 has requirement requests<3.0.0dev,>=2.18.0, but you'll have requests 2.12.4 which is incompatible.
* google-api-core 1.2.1 has requirement setuptools>=34.0.0, but you'll have setuptools 33.1.1 which is incompatible.

Not clear who needs google-api-core. Could not be reproduced.

On Python 3.7, with PACKAGE_LEVEL=minimum (with PR #1340):

* pipenv 2018.7.1 has requirement setuptools>=36.2.1, but you'll have setuptools 33.1.1 which is incompatible. (see https://travis-ci.org/pywbem/pywbem/jobs/417908077)

pipenv seems to be used temporarily during installation of some packages, but it is not a package that is shown after the installs with pip list.

**Comment by andy-maier** [comment]
**Discussion point:** Do we know about more of those? Would we bother to resolve the conflicts reported for packages that are not in our pip list?

**Comment by KSchopmeyer** [comment]
We agree to review the travis runs and add any new incompatibilities to this list. We will make the change later.

**Comment by andy-maier** [comment]
Checking the manual-ci-run branch as of 2018-09-14:

* pipenv 2018.7.1 has requirement setuptools>=36.2.1, but you'll have setuptools 33.1.1 which is incompatible. (py35, minimum / py37, minimum)

**Comment by andy-maier** [comment]
Suggest to close this issue.

**Comment by andy-maier** [comment]
We agreed in the call today to close this one.
