### ISSUE TITLE
Tupleparser: VALUE.OBJECTWITHLOCALPATH not allowed under IRETURNVALUE

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1347]
DSP0201 2.4 allows a VALUE.OBJECTWITHLOCALPATH element as a child of the IRETURNVALUE element.

In `parse_ireturnvalue()`, the tupleparse implementation documents that child element in the docstring, but does not allow it in the code.

**Comment by andy-maier** [comment]
Checking DSP0200 1.4 and DSP0201 2.4 reveals that VALUE.OBJECTWITHLOCALPATH is used as one possibility for the `<object>` pseudo-type in DSP0200, which is used only as a return type for the ExecQuery operation. Apparently, this method is free to include or omit host and namespace in the returned classes and instances.

**Comment by andy-maier** [comment]
PR #1349 Fixes this issue.

**Discussion point:** Any disagreements to fixing this?

**Comment by KSchopmeyer** [comment]
No.  I agree with fixing
