### ISSUE TITLE
Exception during WBEMServer.get_central_instances

### ISSUE THREAD

**Issue by dugganj** [pywbem/pywbem#1365]
When I run the following code in the SMI Lab:

import pywbem as pw

URL='https://10.1.134.96'
PRINCIPAL='smilab'
PASSWORD='F00sb4ll'

conn = pw.WBEMConnection(URL, (PRINCIPAL, PASSWORD))
arrayProfile = server.get_selected_profiles(registered_org="SNIA", registered_name="Array", registered_version="1.6.1")[0]
arrayTLCS = server.get_central_instances(arrayProfile.path)

I get the following exception:

---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
<ipython-input-5-e5a990ba79b1> in <module>()
      7 conn = pw.WBEMConnection(URL, (PRINCIPAL, PASSWORD))
      8 arrayProfile = server.get_selected_profiles(registered_org="SNIA", registered_name="Array", registered_version="1.6.1")[0]
----> 9 arrayTLCS = server.get_central_instances(arrayProfile.path)

C:\Miniconda3\lib\site-packages\pywbem\_server.py in get_central_instances(self, profile_path, central_class, scoping_class, scoping_path)
    468         try:
    469             (ret_val, out_params) = self._conn.InvokeMethod(
--> 470                 MethodName="GetCentralInstances",
    471                 ObjectName=profile_path)
    472         except CIMError as exc:

C:\Miniconda3\lib\site-packages\pywbem\cim_operations.py in InvokeMethod(self, MethodName, ObjectName, Params, **params)
   3683 
   3684             # Make the method call
-> 3685             result = self._methodcall(MethodName, ObjectName, Params, **params)
   3686 
   3687             return result

C:\Miniconda3\lib\site-packages\pywbem\cim_operations.py in _methodcall(self, methodname, objectname, Params, **params)
   1864         # Parse the XML into a tuple tree (may raise ParseError):
   1865         tt_ = xml_to_tupletree_sax(reply_xml, "CIM-XML response")
-> 1866         tup_tree = parse_cim(tt_)
   1867 
   1868         # Set the pretty response after parsing (it could fail otherwise)

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in parse_cim(tup_tree)
    334                          attrs(tup_tree)['CIMVERSION'])
    335 
--> 336     child = one_child(tup_tree, ['MESSAGE', 'DECLARATION'])
    337 
    338     return name(tup_tree), attrs(tup_tree), child

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in one_child(tup_tree, acceptable)
    227                          (name(tup_tree), name(child), acceptable))
    228 
--> 229     return parse_any(child)
    230 
    231 

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in parse_any(tup_tree)
   1917         raise ParseError("Invalid element %r" % name(tup_tree))
   1918     else:
-> 1919         return funct_name(tup_tree)
   1920 
   1921 

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in parse_message(tup_tree)
   1520                       ['SIMPLEREQ', 'MULTIREQ', 'SIMPLERSP', 'MULTIRSP',
   1521                        'SIMPLEEXPREQ', 'MULTIEXPREQ', 'SIMPLEEXPRSP',
-> 1522                        'MULTIEXPRSP'])
   1523 
   1524     return name(tup_tree), attrs(tup_tree), child

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in one_child(tup_tree, acceptable)
    227                          (name(tup_tree), name(child), acceptable))
    228 
--> 229     return parse_any(child)
    230 
    231 

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in parse_any(tup_tree)
   1917         raise ParseError("Invalid element %r" % name(tup_tree))
   1918     else:
-> 1919         return funct_name(tup_tree)
   1920 
   1921 

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in parse_simplersp(tup_tree)
   1756     check_node(tup_tree, 'SIMPLERSP')
   1757 
-> 1758     child = one_child(tup_tree, ['METHODRESPONSE', 'IMETHODRESPONSE'])
   1759 
   1760     return name(tup_tree), attrs(tup_tree), child

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in one_child(tup_tree, acceptable)
    227                          (name(tup_tree), name(child), acceptable))
    228 
--> 229     return parse_any(child)
    230 
    231 

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in parse_any(tup_tree)
   1917         raise ParseError("Invalid element %r" % name(tup_tree))
   1918     else:
-> 1919         return funct_name(tup_tree)
   1920 
   1921 

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in parse_methodresponse(tup_tree)
   1785                                                             ['ERROR',
   1786                                                              'RETURNVALUE',
-> 1787                                                              'PARAMVALUE'])
   1788 
   1789 

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in list_of_various(tup_tree, acceptable)
    259                              "(allowed are child elements %r)" %
    260                              (name(tup_tree), name(child), acceptable))
--> 261         result.append(parse_any(child))
    262 
    263     return result

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in parse_any(tup_tree)
   1917         raise ParseError("Invalid element %r" % name(tup_tree))
   1918     else:
-> 1919         return funct_name(tup_tree)
   1920 
   1921 

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in parse_error(tup_tree)
   1823     """
   1824 
-> 1825     check_node(tup_tree, 'ERROR', ['CODE'], ['DESCRIPTION'], [])
   1826 
   1827     return (name(tup_tree), attrs(tup_tree), None)

C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py in check_node(tup_tree, nodename, required_attrs, optional_attrs, allowed_children, allow_pcdata)
    193                                  "(allowed are child elements %r)" %
    194                                  (name(tup_tree), name(child),
--> 195                                   allowed_children))
    196 
    197     if not allow_pcdata:

ParseError: Element 'ERROR' has invalid child element 'INSTANCE' (allowed are child elements [])

**Comment by dugganj** [comment]
I was playing around with it a bit, and if I comment out the code in get_central_instances that invokes the GetCentralInstances method (lines 468 - 488), the call to_get_central_instances succeeds.

**Comment by andy-maier** [comment]
Assuming this ended up to be no issue, since it was closed by the originator.

**Comment by dugganj** [comment]
This issue morphed into the namespace bug, which was better written up.

Ignoring this one (1365) is legit.

jpd
