### ISSUE TITLE
cim_obj.py tomof output generate TOINSTANCE flavor on qualifiers but compiler does not accept

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#138]
We cannot read our own mof because we generate a a tomof flavor on qualifier output but the pywbem compiler does not accept that flavor.  The toinstance flavor is a concept that existed because of early microsoft requirements and that was documented in the CIM/XML specifications.  However, it never made it into the DSP0004 specification so specifically should not be output as part of a mof generation.

Proposal for now is to remove it from the tomof output now and worry about removing it elsewhere later.

**Comment by KSchopmeyer** [comment]
Actually it is even messier since we set the default true so that it is output on every class output from pywbem tomof.   An alternative would be to force it false for qualifiers. The mof compiler forces toinstance true for any case where tosubclass flavor  is true and it is actually not allowed as a separate flavor string upon input to the compiler.

**Comment by andy-maier** [comment]
Addressed by PR #139, which is merged. Closing this issue.
