### ISSUE TITLE
DSP0200 issue: Unclear how empty result list of operation is represented

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1392]
When DSP0200 describes the return type of an intrinsic operation that returns a list of items, it simply places a "*" after the type of the item in the list, but it does not describe how that is to be mapped to CIM-XML elements.

From DSP0201, it is clear that the return value of an intrinsic operation is represented using an IRETURNVALUE element. In case of a return value that is a list of items, the elements representing the items in the list are the child elements of the IRETURNVALUE element.

The lack of description in DSP0200 leaves two options for how to represent a return value that is an empty list of items:

* IRETURNVALUE element without children
* Omitted IRETURNVALUE element

For example, pywbem has always had code to tolerate a missing IRETURNVALUE element and to treat that as an empty list.

Clarification is needed in DSP0200 for how to represent return values that are lists of items, and specifically how to represent the case of an empty list.

**Comment by KSchopmeyer** [comment]
Filed as DMTF Mantis bug # 2840 on 8 Oct 2019
