### ISSUE TITLE
cim_obj CIMQualifier undefined variable

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#141]
def __str__(self):
        """Return a short string representation of the
        `CIMQualifierDeclaration` object for human consumption."""

        return '%s(name=%r, value=%r, type=%r, ' \
               'is_array=%r, ...)' % \
               (self.__class__.__name__, self.name, elf.value, self.type,

elf.value should be self.value

**Comment by andy-maier** [comment]
Solved by PR #142, which is merged. Closing this issue.
