### ISSUE TITLE
Antecedent/Dependent issue for CIM_RegisteredProfile issue with SMI profiles

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1411]
SMI registered profiles provide a unique error in that they do not comply with DMTF in the use of the CIM_ReferencedProfile because a number of the current implementation available actually implement the class  xxx a aubclass of CIM_ReferencedProfile which which confuxed the use of Antecedent and Dependent roles.  Thus, any particular smi provider can have the roles of these properties reveresed making the definitions of things like getting autonomous profiles in the DMTF Profile usage guide impossible to use directly.

Today we do not directly include the ability to view autonomous/component profiles or other algoritims that use ReferencedProfile in pywbem. It is not a direct part of getCentralClass or get registeredprofiles.

Should we include algorithms for this and if so, should it include the code to figure out this know issue with the confused dependent and antecedent roles in pywbem or leave to higher level code.

**Comment by andy-maier** [comment]
IMO, we should support that in pywbem.
What we need is test against a real implementation of this.

**Comment by andy-maier** [comment]
**Discussion point:** Decide whether we want to address that for 0.13.

**Comment by andy-maier** [comment]
We decided to address that in 0.13.
Karl is running tests in the SMi lab.

**Comment by andy-maier** [comment]
Here is my investigation of what the standards have to say. Unfortunately, there is no consistent definition, taking all of them together.

There are three "dimensions" to consider for this issue:
1. The roles Antecedent and Dependent of the CIM_ReferencedProfile class (SNIA: CIM_SubProfileRequiresProfile)
2. The "referencing profile" and "referenced profile"
3. The "autonomous profile" (SNIA: profile) and "component profile" (SNIA: subprofile)

**Comment by andy-maier** [comment]
DMTF view
-----------

* DSP1033 (PRP) defines how Antecedent/Dependent belong to the referencing direction, but it does not define whether the referenced profile is the autonomous or component profile. Both PRP 1.0 and 1.1 state that Antecedent goes to the referenced profile.

  Quotes: 
    - DSP1033 1.0.0 in section 7.11 "CIM_ReferencedProfile":
      "Note that the use of the Dependent and Antecedent properties in the CIM_ReferencedProfile association is defined in a somewhat non-intuitive way, such that the profile being referenced is the antecedent and the profile doing the referencing is the dependent."
    - DSP1033 1.1.0 in section 7.2.6.2 "Property: Antecedent":
       "Referenced instances shall be of class adaptation ReferencedRegisteredProfile.",
       and it defines that adaptation in section 7.2.7 "Adaptation: ReferencedRegisteredProfile: CIM_RegisteredProfile" as follows:
      "This adaptation models referenced profiles; that is, profiles that are referenced by the registered profile ...".
      The adaptation diagram is consistent with that.

* DSP1001 (PUG) defines the referencing direction between autonomous and component profiles.
  PUG 1.0 can be interpreted such that autonomous profiles reference component profiles, but the statement is not very strong, IMO.
  PUG 1.1 is explicit in stating that autonomous profiles reference component profiles, and it also needs that referencing direction so that the autonomous profile's central class adaptation can be based upon the referenced profile's scoping class adaptation. I recall we had lengthy discussions about that.
  I think both PUG versions may be incorrect, there.

  Quotes:
    - DSP1001 1.0.0 in section 5.1 "Profile terminology":
      "A component profile describes a subset of a management domain. A component profile includes CIM elements that are scoped within an autonomous profile (or in rare cases, another component profile). Multiple autonomous profiles may reference the same component profile.".
      The referencing direction is not the main topic of this statement, but there is no other definition of the referencing direction.
    - DSP1001 1.1.0 in section 7.8.3 "Component profiles":
      "A component profile defines a management interface of a subset or special aspect of a management domain. In most cases it is possible and desirable to specify a component profile independent of its use in the context of a particular referencing profile, enabling reuse of the component profile in the context of many possible referencing profiles.
      For example, an autonomous profile addressing the management domain of systems might reference a component profile for the purpose of addressing the management domain of network ports in systems. The same component profile might be referenced by another autonomous profile that addresses the management domain of network switches, in this case for the purpose of addressing the management domain of switch ports."
    - DSP1001 1.1.0 in section 7.9.3 "Definition of scoping relationships":
      "Four elements contribute to defining a scoping relationship:
      • The central class adaptation (see 7.9.3.2) defined by the used profile
      • The scoping class adaptation (see 7.9.3.3) defined by the used profile
      • The scoping path (see 7.9.3.4) defined by the used profile
      • The central class adaptation (see 7.9.3.2) defined by the referencing profile".
      Because it is not disputed that the scoping path is defined in the component profile, and because "used profile" is defined as a special case of "referenced profile", this quote uses "referencing profile" to mean the autonomous profile and "used=referenced profile" to mean the component profile.

**Comment by andy-maier** [comment]
SNIA view
-----------

Summary:

Mostly:
* Antecedent = referenced profile = autonomous profile
* Dependent = referencing profile = component (= sub) profile

One exception: figure 56 in the SMI-S PRP:
* Antecedent = component (= sub) profile
* Dependent = autonomous profile

Details:

* SMI-S PRP (1.5) does not define how Antecedent/Dependent belong to the referencing direction, and instead defers to DSP1033. In the element table for CIM_SubProfileRequiresProfile, it defines that Dependent goes to the component (=sub) profile, which is the opposite of the DMTF view. In figure 56 however, the example shows the opposite attribution of Antecedent/Dependent to autonomous/component profiles, compared to the element table.

  Quotes:
    - SMI-S PRP (1.5) in section 41.3 of the common profiles book:
      "The DMTF Profile Registration Profile describes how the Antecedent and Dependent references should be used when one profile includes another in its supported/referenced profile list. Implementations are inconsistent in the use of these references and clients should be prepared for either approach; one technique to achieve this would be to specify NULL for Role and RemoteRole in Associator or AssociatorName operations."
    - SMI-S PRP (1.5) in table 414 "CIM_SubProfileRequiresProfile":
      Dependent / Mandatory / Reference to a RegisteredSubProfile.
      Antecedent / Mandatory / Reference to a RegisteredProfile.
    - SMI-S PRP (1.5) in diagram "Figure 56 - Model for SMI-S Registered Profile" shows the Antecedent role on the component (= sub) profile and the Dependent role on the autonomous profile, which is opposite to the other quotes. **This is likely an error and should be reported to SNIA.**

* CIM Schema: The MOF of class CIM_SubProfileRequiresProfile defines how Antecedent/Dependent belong to the referencing direction, and it defines whether the referenced profile is the autonomous or component (=sub) profile:

  ```
     [Association, Deprecated { "CIM_ReferencedProfile" }, 
      Version ( "2.37.0" ), 
      UMLPackagePath ( "CIM::Interop" ), 
      Description ( 
         "A subprofile requires another RegisteredProfile for context. "
         "This association mandates the scoping relationship between a "
         "subprofile and its scoping profile." )]
  class CIM_SubProfileRequiresProfile : CIM_ReferencedProfile {

        [Deprecated { "CIM_ReferencedProfile.Antecedent" }, 
         Override ( "Antecedent" ), 
         Min ( 1 ), 
         Description ( 
            "The RegisteredProfile that is referenced/required by the "
            "subprofile." )]
     CIM_RegisteredProfile REF Antecedent;

        [Deprecated { "CIM_ReferencedProfile.Dependent" }, 
         Override ( "Dependent" ), 
         Description ( 
            "A RegisteredSubProfile that requires a scoping profile, "
            "for context." )]
     CIM_RegisteredSubProfile REF Dependent;

  };
  ```

**Comment by KSchopmeyer** [comment]
We propose that we need to provide for pywbem to get central instances for either the case of the original dmtf definition for CIM_ReferencedProfile or the snia modification. 

One solution is to:

1. Provide an additional parameter to get_central_instances that defines which definition to use for get_central_instances.

2. Provide a method for the user to define which approach to defining the dependent/antecedent definiition was taken by a particular implementation.

Generally we should be able to determine the direction by:

1. Knowledge of a set of profiles that may be autonomous

2. Find for an implementation the profiles that have associations with in only a single direction. 

3. The source instance for these associations is either autonomous or a component profile that is the bottom of a tree of CIM_ReferencedProfiles.

4. A profile that has associations in one direction and is also a known autonomous profile should allow the direction of dependent/antecedent to be determined.

**Comment by KSchopmeyer** [comment]
This is a side issue but I am documenting it here. In some of the test servers we are finding that there some servers that have multiple CIM_ReferenedProfile with only a single difference, the name of the class that for the instance.  Thus, there will be one instance with CIM_ReferencedProfile and another with CIM_SubProfileRequiresProfile. 

Thus here is an example:

inst=
CIMInstance(classname='ECOM_ReferencedProfile',         path=CIMInstanceName(classname='ECOM_ReferencedProfile        ', keybindings=NocaseDict({'Antecedent': CIMInstanceName(classname='ECOM_RegisteredProfile', keybindings=NocaseDict({'InstanceID': 'Array+1.2.0'}), namespace='interop', host='10.1.134.185'), 'Dependent': CIMInstanceName(classname='ECOM_RegisteredSubProfile', keybindings=NocaseDict({'InstanceID': 'iSCSI Target Ports+1.2.0'}), namespace='interop', host='10.1.134.185')}), namespace='interop', host=None), properties=NocaseDict({'Antecedent': CIMProperty(name='Antecedent', value=CIMInstanceName(classname='ECOM_RegisteredProfile', keybindings=NocaseDict({'InstanceID': 'Array+1.2.0'}), namespace='interop', host='10.1.134.185'), type='reference', reference_class=None, embedded_object=None, is_array=False, array_size=None, class_origin=None, propagated=False, qualifiers=NocaseDict({})), 'Dependent': CIMProperty(name='Dependent', value=CIMInstanceName(classname='ECOM_RegisteredSubProfile', keybindings=NocaseDict({'InstanceID': 'iSCSI Target Ports+1.2.0'}), namespace='interop', host='10.1.134.185'), type='reference', reference_class=None, embedded_object=None, is_array=False, array_size=None, class_origin=None, propagated=False, qualifiers=NocaseDict({}))}), property_list=None, qualifiers=NocaseDict({}))
CIMInstance(classname='ECOM_SubProfileRequiresProfile', path=CIMInstanceName(classname='ECOM_SubProfileRequiresProfile', keybindings=NocaseDict({'Antecedent': CIMInstanceName(classname='ECOM_RegisteredProfile', keybindings=NocaseDict({'InstanceID': 'Array+1.2.0'}), namespace='interop', host='10.1.134.185'), 'Dependent': CIMInstanceName(classname='ECOM_RegisteredSubProfile', keybindings=NocaseDict({'InstanceID': 'iSCSI Target Ports+1.2.0'}), namespace='interop', host='10.1.134.185')}), namespace='interop', host=None), properties=NocaseDict({'Antecedent': CIMProperty(name='Antecedent', value=CIMInstanceName(classname='ECOM_RegisteredProfile', keybindings=NocaseDict({'InstanceID': 'Array+1.2.0'}), namespace='interop', host='10.1.134.185'), type='reference', reference_class=None, embedded_object=None, is_array=False, array_size=None, class_origin=None, propagated=False, qualifiers=NocaseDict({})), 'Dependent': CIMProperty(name='Dependent', value=CIMInstanceName(classname='ECOM_RegisteredSubProfile', keybindings=NocaseDict({'InstanceID': 'iSCSI Target Ports+1.2.0'}), namespace='interop', host='10.1.134.185'), type='reference', reference_class=None, embedded_object=None, is_array=False, array_size=None, class_origin=None, propagated=False, qualifiers=NocaseDict({}))}), property_list=None, qualifiers=NocaseDict({}))

This could mean that the associators request could end up returning multiple instances where they are
actually the same instance.  Note that so far, all of the server implementations of Associators weed this out and only return a single instance.

**Comment by KSchopmeyer** [comment]
More test comments.  On one particular server. EMC3 we consistently get the following error back when attempting to execute the get_central_instances method::

EMC3: PROFILE get_central_class: SNIA:Masking and Mapping inst.path=interop:ECOM_RegisteredSubProfile.InstanceID="Masking and Mapping+1.3.0"
   central_class=CIM_ControllerConfigurationService,scoping_class=CIM_ComputerSystem, scoping_path=['CIM_HostedService']
pywbem.Error: EMC3: SNIA:Masking and Mapping:1.3.0
  inst_path=interop:ECOM_RegisteredSubProfile.InstanceID="Masking and Mapping+1.3.0"
   server=WBEMServer(conn.url='https://10.1.134.185', brand='EMC CIM Server', version='2.7.3.10.0.15', ... )
   Exception=SAXParseException raised when parsing CIM-XML response: <unknown>:3:78: not well-formed (invalid token), Connection id: None
LAST_REQUEST
<CIM CIMVERSION="2.0" DTDVERSION="2.0">
  <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
    <SIMPLEREQ>
      <METHODCALL NAME="GetCentralInstances">
        <LOCALINSTANCEPATH>
          <LOCALNAMESPACEPATH>
            <NAMESPACE NAME="interop"/>
          </LOCALNAMESPACEPATH>
          <INSTANCENAME CLASSNAME="ECOM_RegisteredSubProfile">
            <KEYBINDING NAME="InstanceID">
              <KEYVALUE VALUETYPE="string">Masking and Mapping+1.3.0</KEYVALUE>
            </KEYBINDING>
          </INSTANCENAME>
        </LOCALINSTANCEPATH>
      </METHODCALL>
    </SIMPLEREQ>
  </MESSAGE>
</CIM>

LAST_REPLY
None
EMC3: PROFILE get_central_class: SNIA:Job Control inst.path=interop:ECOM_RegisteredSubProfile.InstanceID="Job Control+1.5.0"
   central_class=CIM_ConcreteJob,scoping_class=CIM_Service, scoping_path=['CIM_OwningJobElement']
pywbem.Error: EMC3: SNIA:Job Control:1.5.0
  inst_path=interop:ECOM_RegisteredSubProfile.InstanceID="Job Control+1.5.0"
   server=WBEMServer(conn.url='https://10.1.134.185', brand='EMC CIM Server', version='2.7.3.10.0.15', ... )
   Exception=SAXParseException raised when parsing CIM-XML response: <unknown>:3:78: not well-formed (invalid token), Connection id: None
LAST_REQUEST
<CIM CIMVERSION="2.0" DTDVERSION="2.0">
  <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
    <SIMPLEREQ>
      <METHODCALL NAME="GetCentralInstances">
        <LOCALINSTANCEPATH>
          <LOCALNAMESPACEPATH>
            <NAMESPACE NAME="interop"/>
          </LOCALNAMESPACEPATH>
          <INSTANCENAME CLASSNAME="ECOM_RegisteredSubProfile">
            <KEYBINDING NAME="InstanceID">
              <KEYVALUE VALUETYPE="string">Job Control+1.5.0</KEYVALUE>
            </KEYBINDING>
          </INSTANCENAME>
        </LOCALINSTANCEPATH>
      </METHODCALL>
    </SIMPLEREQ>
  </MESSAGE>
</CIM>

LAST_REPLY
None
EMC3: PROFILE get_central_class: SNIA:iSCSI Target Ports inst.path=interop:ECOM_RegisteredSubProfile.InstanceID="iSCSI Target Ports+1.2.0"
   central_class=CIM_iSCSICapabilities,scoping_class=CIM_ComputerSystem, scoping_path=['CIM_ElementCapabilities']
pywbem.Error: EMC3: SNIA:iSCSI Target Ports:1.2.0
  inst_path=interop:ECOM_RegisteredSubProfile.InstanceID="iSCSI Target Ports+1.2.0"
   server=WBEMServer(conn.url='https://10.1.134.185', brand='EMC CIM Server', version='2.7.3.10.0.15', ... )
   Exception=SAXParseException raised when parsing CIM-XML response: <unknown>:3:78: not well-formed (invalid token), Connection id: None
LAST_REQUEST
<CIM CIMVERSION="2.0" DTDVERSION="2.0">
  <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
    <SIMPLEREQ>
      <METHODCALL NAME="GetCentralInstances">
        <LOCALINSTANCEPATH>
          <LOCALNAMESPACEPATH>
            <NAMESPACE NAME="interop"/>
          </LOCALNAMESPACEPATH>
          <INSTANCENAME CLASSNAME="ECOM_RegisteredSubProfile">
            <KEYBINDING NAME="InstanceID">
              <KEYVALUE VALUETYPE="string">iSCSI Target Ports+1.2.0</KEYVALUE>
            </KEYBINDING>
          </INSTANCENAME>
        </LOCALINSTANCEPATH>
      </METHODCALL>
    </SIMPLEREQ>
  </MESSAGE>
</CIM>

LAST_REPLY
None

**Comment by andy-maier** [comment]
The "not well-formed" issue is followed up in issue #1438.
This issue here should be scoped to the Antecedent/Dependent direction issue.

**Comment by andy-maier** [comment]
I have set this issue to fixed, because all related PRs are underway and related issues are fixed.

**Comment by andy-maier** [comment]
Since PR #1533 was withdrawn, there is nothing more to do for this issue. Closing it.
