### ISSUE TITLE
Testing with smi servers, issue with server namespaces

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1430]
One server returns an interop namespace for interop_ns but does not include the interop namespace in the return for general namespaces.  I am not sure exactly what is returned from the server but  this is what shows up in the result use of the properties.

server.interop_ns      server.namespaces
interop                     /root/eternus

i.e the  interop does not show up in the list displayed for server.namespaces.

TODO: KS, Display exactly what the server returns.

Tests with a number of other servers show correct results.

**Comment by andy-maier** [comment]
Did not check the impl but I think that is either not possible or a pywbem bug. Not a server bug

**Comment by andy-maier** [comment]
@KSchopmeyer Karl, I looked into the code and the determination of the interop namespace uses its own algorithm, the resulting interop namespace is then used in the determination of the namespaces, so if the server handles a particular interop namespace but does not have a namespace instance for it, then this results in the behavior you saw.

Could you please also output the `WBEMServer.namespace_classname` attribute and the `WBEMServer.namespace_paths` attribute?

**Comment by andy-maier** [comment]
We could handle that in pywbem by adding the determined interop namespace to the list of determined namespaces, if missing there. But first we should make sure the server really behaves like that.

**Comment by andy-maier** [comment]
**Discussion point:** Should pywbem add the determined interop namespace to the list of determined namespaces, if missing there?

**Comment by andy-maier** [comment]
We decided it should.

**Comment by andy-maier** [comment]
Addressed in PR #1542.
