### ISSUE TITLE
get_central_instances returns SAXParseexception

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1438]
We receive the following response from at least one SMI server indicating that it has a problem processing a request for a method that does not exist in the server.

EMC3: PROFILE get_central_class: SNIA:Masking and Mapping   inst.path=interop:ECOM_RegisteredSubProfile.InstanceID="Masking and Mapping+1.3.0"

central_class=CIM_ControllerConfigurationService,scoping_class=CIM_ComputerSystem, scoping_path=['CIM_HostedService']
pywbem.Error: EMC3: SNIA:Masking and Mapping:1.3.0
inst_path=interop:ECOM_RegisteredSubProfile.InstanceID="Masking and Mapping+1.3.0"
server=WBEMServer(conn.url='https://10.1.134.185', brand='EMC CIM Server', version='2.7.3.10.0.15', ... )
Exception=SAXParseException raised when parsing CIM-XML response: :3:78: not well-formed (invalid token), Connection id: None

::

    LAST_REQUEST
    <CIM CIMVERSION="2.0" DTDVERSION="2.0">
      <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
        <SIMPLEREQ>
         <METHODCALL NAME="GetCentralInstances">
            <LOCALINSTANCEPATH>
              <LOCALNAMESPACEPATH>
                <NAMESPACE NAME="interop"/>
              </LOCALNAMESPACEPATH>
             <INSTANCENAME CLASSNAME="ECOM_RegisteredSubProfile">
               <KEYBINDING NAME="InstanceID">
                 <KEYVALUE VALUETYPE="string">Masking and Mapping+1.3.0</KEYVALUE>
               </KEYBINDING>
             </INSTANCENAME>
            </LOCALINSTANCEPATH>
         </METHODCALL>
       </SIMPLEREQ>
     </MESSAGE>
    </CIM>

    LAST_REPLY
    None

**Comment by andy-maier** [comment]
PR #1439 improves the exception message, so that the faulty XML string is included.

Please run again with that PR.

**Comment by andy-maier** [comment]
SAXParseError "not well formed" is raised when the start element misses its trailing angle bracket, as in:

```
<ELEM</ELEM>
```

This case is now part of the new testcases added by PR #1439. However, I'm not sure this is exhaustive yet, so there may be other cases that also produce the same symptom.

**Comment by KSchopmeyer** [comment]
Using the pr defined by Andy (With one small additional hack to show the whole xml response string we recreated this problem with the following result:

The server is EMC3 in our tests.  The result is:

EMC3: PROFILE get_central_class: SNIA:Job Control inst.path=interop:ECOM_RegisteredSubProfile.InstanceID="Job Control+1.5.0"
   central_class=CIM_ConcreteJob,scoping_class=CIM_Service, scoping_path=['CIM_OwningJobElement']
GET_CENTRAL_INSTANCES Exception ParseError:XML parsing error encountered in CIM-XML response: <unknown>:3:78: not well-formed (invalid token), XML string (line 3, column 78): b'<?xml version="1.0" encoding="utf-8" ?>\n<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0">\n<SIMPLERSP><METHODRESPONSE NAME="GetCentralInstances"><RETURNVALUE PARAMTYPE="<ERROR CODE="1" DESCRIPTION="A general error occurred that is not covered by a more specific error code. (Unhandled Exception)" />\n</METHODRESPONSE></SIMPLERSP></MESSAGE></CIM>\n\n', Connection id: None
LAST_REQUEST
<CIM CIMVERSION="2.0" DTDVERSION="2.0">
  <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
    <SIMPLEREQ>
      <METHODCALL NAME="GetCentralInstances">
        <LOCALINSTANCEPATH>
          <LOCALNAMESPACEPATH>
            <NAMESPACE NAME="interop"/>
          </LOCALNAMESPACEPATH>
          <INSTANCENAME CLASSNAME="ECOM_RegisteredSubProfile">
            <KEYBINDING NAME="InstanceID">
              <KEYVALUE VALUETYPE="string">Job Control+1.5.0</KEYVALUE>
            </KEYBINDING>
          </INSTANCENAME>
        </LOCALINSTANCEPATH>
      </METHODCALL>
    </SIMPLEREQ>
  </MESSAGE>
</CIM>

LAST_REPLY
None
EMC3: PROFILE get_central_class: SNIA:iSCSI Target Ports inst.path=interop:ECOM_RegisteredSubProfile.InstanceID="iSCSI Target Ports+1.2.0"
   central_class=CIM_iSCSICapabilities,scoping_class=CIM_ComputerSystem, scoping_path=['CIM_ElementCapabilities']
GET_CENTRAL_INSTANCES Exception ParseError:XML parsing error encountered in CIM-XML response: <unknown>:3:78: not well-formed (invalid token), XML string (line 3, column 78):
b'<?xml version="1.0" encoding="utf-8" ?>\n
<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0">\n
<SIMPLERSP><METHODRESPONSE NAME="GetCentralInstances"><RETURNVALUE PARAMTYPE="<ERROR CODE="1" DESCRIPTION="A general error occurred that is not covered by a more specific error code. (Unhandled Exception)" />\n
</METHODRESPONSE></SIMPLERSP></MESSAGE></CIM>\n\n', Connection id: None

This is clearly malformed in that it is attempting to return an error as a RETURNVALUE element of an ERROR element, irrespective of whether this should be handled as a CIMERROR return with one of the status codes indicating that the method  could not be found.

NOTE: Most other servers tested handle this correctly.

**Comment by andy-maier** [comment]
To summarize:
* The reason for this is faulty XML returned by the server.
* PR #1439 improves the exception message, so that the faulty XML string is included.
* PR #1537 improves the description of the `last_reply` property to hint at using `last_raw_reply` which is in fact set in this case.

**Discussion point:**
* What remains to be done is to tolerate a ParseError in get_central_instances() when trying to invoke the GetCentralInstances method, and to raise a warning instead.

**Comment by andy-maier** [comment]
We decided to have a separate PR for tolerating the ParseError in get_central_instances() when trying to invoke the GetCentralInstances method, and to raise a warning instead.

**Comment by andy-maier** [comment]
PR #1538 adds support for tolerating the ParseError in get_central_instances() when trying to invoke the GetCentralInstances method. It does not yet raise a warning, though.
