### ISSUE TITLE
tomof for instances does not handle mof output of embedded instances

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#147]
This actually causes an exception.

I thought I had documented this one but could not find it in the list.

**Comment by andy-maier** [comment]
Is this completely addressed by PR #148?

**Comment by KSchopmeyer** [comment]
Since we do not have a complete round trip test (mof back to mof) I cannot be sure.  See issue #146 where mofstr cannot handle all strings provided.  Leave this one open until we get the round trip test done.

I cannot believe that I wrote and incomplete bug description likt that one above.

**Comment by andy-maier** [comment]
**Discussion point:**
* What is left for this one?

**Comment by KSchopmeyer** [comment]
Found bug in tomof for property values on instances.   The spec calls for output in mof format but as a string.  The code outputs xml. At the same time, if we output as mof the formatting is horrible

instance of Test_CLITestEmbeddedClass {
    embeddedInst = "instance of Test_CLITestEmbedded1 {\n    comment = \"Instance created by "
    "provider.\";\n    Id = \"100\";\n    name = \"Ronald\";\n};\n";
};

I want to make the single change to output as mof and then move any further work to 0.10.0 since whe also have issues with the mof compiler and compiling embedded mof.  See the testmofs where the properties for embedded instance and object are commented out.
