### ISSUE TITLE
API consistency

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#152]
The Operation apis are inconsistent in that most generalize to \* and *\* but a couple (see CIMQualifierDeclaration are detailed.

This is more a question for discussion that a firm issue

**Comment by andy-maier** [comment]
Karl, the problem with fixing that is compatibility, I believe. However, it needs to be tested out, and Py3 may allow more here than Py2

**Comment by andy-maier** [comment]
testcase variations:
- passing defined args by position and by name,
- passing keyword args by name and by dict.
This assumes we don't have external functions with *args (need to check)

**Comment by andy-maier** [comment]
I think I need some clarification what we talk about:

- The WBEMConnection operation methods still have `**params` for optional parameters, and I had them in mind when I responded, above.
- The wbemcli convenience functions for operations had `*args` and `**kwargs`, and I fixed that throughout in PR #155, so that is now addressed. Because this is meant to be used interactively, I assumed compatibility does not count here.
- The mof_compiler repository methods still have `*args` and `**kwargs`, but I think we can change them to be specific (with defaults `None`??) because they are on a class that is used by the module itself, and we may assume that it is not used by users.
- You mentioned a CIM object class (CIMQualifierDeclaration), but they do not have any `*args` or `**kwargs`, except where they must (in NocaseDict ctor, and in the `update()` or `update_existing()` methods).

**Comment by KSchopmeyer** [comment]
On 03/29/2016 04:19 AM, Andreas Maier wrote:
>
> I think I need some clarification what we talk about:
>
>   * The WBEMConnection operation methods still have |**params| for
>     optional parameters, and I had them in mind when I responded, above.
>
See comment at end of email.  It was fatigue talking.
>
>   * The wbemcli convenience functions for operations had |*args| and
>     |**kwargs|, and I fixed that throughout in PR #155
>     <https://github.com/pywbem/pywbem/pull/155>, so that is now
>     addressed. Because this is meant to be used interactively, I
>     assumed compatibility does not count here.
>
True and we will probably eventually pretty much ignore that tool some day
>
>   * The mof_compiler repository methods still have |*args| and
>     |**kwargs|, but I think we can change them to be specific (with
>     defaults |None|??) because they are on a class that is used by the
>     module itself, and we may assume that it is not used by users.
>
OK, seems logical to do this
>
>   * You mentioned a CIM object class (CIMQualifierDeclaration), but
>     they do not have any |*args| or |**kwargs|, except where they must
>     (in NocaseDict ctor, and in the |update()| or |update_existing()|
>     methods).
>
Forget that one,  I was getting mixed up between operations and objects 
(never work late at night).

  The
operations methods consistently use the *args ** kwargs and the objects 
pretty much consistently use the actual
optional args as far as I can tell.  Actually I always just wondered 
what the advantage was of not forcing the
actual input parameters (postional and keyword) on each cimoperation 
method, thus having them enforced
early and documented. Probably because that was more effort than 
enforcing them only once during the
xml build process.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/152#issuecomment-202795532>
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
OK, that leaves two potential changes, that we need to discuss and decide about:

* For the WBEMConnection operation methods, change their `**params` into a set of specific args. Compatibility need to be investigated and issues judged.
* For the mof_compiler repository methods, change their `*args` and `**kwargs` into a set of specific args. We are not concerned about compatibility here.

**Comment by andy-maier** [comment]
I pushed a test script `testsuite/compat_args.py` to the master branch, which confirms that a change from `*args` and `**kwargs` to named args is compatible. I ran it on py27 and py34 so far.

**Comment by KSchopmeyer** [comment]
Let me look at it.

**Comment by andy-maier** [comment]
We discussed in the call to actually pursue the change described 3 comments up.

Everyone should think about additional ways to call the functions, besides those implemented in `testsuite/compat_args.py`, before we actually do that.

**Comment by andy-maier** [comment]
With the updated MOF compiler API documentation as of PR #168, I think we can leave the operation methods of `MFWBEMConnection` and the new abstract base class `BaseRepositoryConnection` defined with `*args` and `**kwargs`. Their descriptions contain links to the corresponding `WBEMConnection` methods, so the description is just one click away.

On changing the `**params` of the `WBEMConnection` methods, that is still left to be done.

**Comment by andy-maier** [comment]
PR #180 changes the `**params` of the `WBEMConnection` methods.
