### ISSUE TITLE
mock test for enumerate instances incomplete.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#153]
A lot of these test groups (ex. getInstance) are incomplete but thought I would document this one for now.  We can never get to 100% but we do need to add many more tests to each group.  I will try to create the working list for enumerate instances in this issue.

TODO indicate which of these already done.
The test for EnumerateInstance should include:

1. Standard good delivery with no, single, multiple objects
2. Return instances that have
      no properties
      all properties
3. Test with property list
4. test with all request parameters set both ways.
5. Test of the following errors
    TODO

**Comment by andy-maier** [comment]
I think it is useful to write down the different dimensions and to figure out which of them are not independent.
For example, each input parameter is a dimension, plus whatever the server can vary. The independent dimensions just need to be "added", the dependent ones need to be multiplied out (maybe not always completely). This tends to result in large numbers, but it seems to me we have to drill this complexity through at some point.

Some server side variations (for EI):

* Successful:
  - Top level class / derived class
  - Props declared in superclasses: None, One, More
  - Props declared in class: None, One, More
  - Props actually returned: None, Subset of inherited, Subset of leaf class, All
  - Key props: One, More, different data types
  - Data types of props, incl arrays and embedded inst, emb. obj. with inst, emb. obj. with class
  - Do other qualifiers (besides key, emb*) influence the behavior?
  - Number inst: Zero, one, more
  - Variations that are relevant for input parameter variations, e.g deepinheritance
  - .. more
* Errors:
  - A wide field. It seems to me that we can separate into errors that can happen independent of a specific operation, and op-specific ones.
* Op-independent Errors:
  - Illegal input parms to WBEMConnection ctor
  - Server not found and many other conn. related errors
  - Exceptions in client before sending request
  - .. after receiving response
  - All kinds of invalid responses: headers, xml validity at XML and CIM-XML level, logical validity (we have redundancies in CIM-XML that can become inconsistent)
  - .. more
* op-specific errors
  - all cim status codes allowed for the op
  - cim status codes not allowed for the op
  - ... more

**Comment by KSchopmeyer** [comment]
Lets continue the discussion of this list to next week.

**Comment by KSchopmeyer** [comment]
Karl write first cut a list for next week.

**Comment by andy-maier** [comment]
Grabbed this one.

**Comment by andy-maier** [comment]
Addressed for EnumerateInstances and EnumerateInstanceNames in PR #441.

The tests cover all successful cases, including special handling of input parameters (namespace and classname) and output parameters (namespace set in returned path), and the documented server-originated error cases.

Any other error cases are not covered; they should be covered in separate test cases, because they are not so much specific to an operation.

**Discussion point:**
* Do we agree that the test cases are reasonably complete for these two operations.
