### ISSUE TITLE
fix issue in mocker createclass

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1540]
My TODO in mocker createclass bit me.  Code is incomplete and does not propagate key from association superclass to subclass.

**Comment by andy-maier** [comment]
This diagram shows the ideal structure for repository interfaces, mock support, etc:
[RepositoryStructure.pptx](https://github.com/pywbem/pywbem/files/2680717/RepositoryStructure.pptx)

**Comment by KSchopmeyer** [comment]
updated Repository Structure, 2018-1-17
[RepositoryStructure.pptx](https://github.com/pywbem/pywbem/files/2770298/RepositoryStructure.pptx)

**Comment by andy-maier** [comment]
Fixed by PR #1543.

**Comment by andy-maier** [comment]
PR #2066 adds the last version of RepositoryStructure.pptx to the design directory, in order not to loose it.
