### ISSUE TITLE
Resource not available

### ISSUE THREAD

**Issue by allen0817** [pywbem/pywbem#1546]
product hds
pywbem version pywbem-master
error 

>>> conn = pywbem.WBEMConnection('https://192.168.149.55', ('maintenance', 'raid-mainte'), 'root/hitachi/smis',None,None,None,True)
>>> data = conn.EnumerateInstances('HITACHI_DiskDrive')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pywbem/cim_operations.py", line 2412, in EnumerateInstances
    **extra)
  File "pywbem/cim_operations.py", line 1783, in _imethodcall
    code, desc, instances=err_insts, conn_id=self.conn_id)
pywbem.exceptions.CIMError: 2 (CIM_ERR_ACCESS_DENIED): Resource not available, Connection id: 1-55399

At present, there is no condition to view the remote device, may I ask what is wrong with this

**Comment by andy-maier** [comment]
Hi Allen, You get back access denied, which means either that your userid and/or password is invalid, or that that userid is not authorized sufficiently.

**Comment by andy-maier** [comment]
The parameters for your `pywbem.WBEMConnection()` initialization look good, otherwise.

**Comment by allen0817** [comment]
about Associators   Can you give me an example?
lunclass ,lungroupclass,relationclass ,I don't know how to relate them

**Comment by allen0817** [comment]
Do you have pywbem video tutorial？

**Comment by andy-maier** [comment]
Hi Allen.
There is no video tutorial I know of. However, the pywbem documentation contains a tutorial section: https://pywbem.readthedocs.io/en/latest/tutorial.html
It provides examples for a number of operations, but not for the association operations, unfortunately.

If you tell me what you which instances you have at the point where you want to make the association operation,. and what you want to achieve, I can help you with a specific example.

As a starter, the two most important things to understand when using association operations are:
* You need to know which classes are association classes and which are ordinary (= non-association) classes. You find that information in the SMI-S profiles, or by looking up the class names in the CIM Schema and looking out for the `Association` qualifier.
* The basic abilities of the `Associator...` and `Reference...` operations: They both traverse an association class from a single instance on a starting end, and `Associator...` returns the associated (ordinary) instances on the far end, while `Reference...` returns the association instances.

**Comment by allen0817** [comment]
hi Andreas Maier .
I really don't know what to do.
I know there are two classes, HuaSy_StorageVolume and HuaSy_OrderedMemberOfCollection HuaSy_DeviceMaskingGroup and their associated class, and their associated field is HuaSy_StorageVolume: DeviceID, HuaSy_DeviceMaskingGroup: InstanceID, and these two fields is also exist in HuaSy_OrderedMemberOfCollection class, I now is to find out HuaSy_StorageVolume associated HuaSy_DeviceMaskingGroup properties. Can you help me? The following is part of the official smi-s document relationship

HuaSy_StorageVolume   <----[DeviceID]---HuaSy_OrderedMemberOfCollection---[InstanceID]--->HuaSy_DeviceMaskingGroup

I hope to get your help, thank you

**Comment by andy-maier** [comment]
Allen, from your description it is not entirely clear to me which instances you have and which instances you want to navigate to, so I must speculate:

If you have an instance of class HuaSy_StorageVolume  and you want to navigate to the instances of class HuaSy_DeviceMaskingGroup via the association HuaSy_OrderedMemberOfCollection, then you can issue the following call to the Associators operation:

```
    sv_inst = ...    # You have an instance of HuaSy_StorageVolume
    dmg_insts = conn.Associators(
        sv_inst,
        AssocClass='HuaSy_OrderedMemberOfCollection',
        ResultClass='HuaSy_DeviceMaskingGroup') 
    # dmg_insts is the list of associated HuaSy_DeviceMaskingGroup instances
```

Let me know if that is what you want to do.

**Comment by allen0817** [comment]
I really don't know how to thank you enough.

With your help, I successfully obtained the associated property of pywbem 0.9.

But there was an anomaly at 0.81：TypeError: Associators() takes exactly 2 arguments (4 given)

Neither do I

**Comment by andy-maier** [comment]
Allen, that is good to hear:

On your anomaly in pywbem 0.8.1: We are at pywbem 0.12.x currently. pywbem 0.11.x is in fix-only mode. pywbem 0.10.x and earlier are not supported anymore. Please upgrade your pywbem version.

I looked at the source code of Associators in pywbem 0.8.1, but could not find why that TypeError would show up, particularly without knowing where it was raised. In the future, please provide the entire traceback information if you report exceptions. But again, pywbem 0.8.x is not maintained anymore.

**Comment by andy-maier** [comment]
Closing this issue. Please use the upcoming pywbem 0.13.0. If the problem shows up again, please open a new issue.
