### ISSUE TITLE
Invalid Value Map exception in valuemapping

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1547]
The following value map/value qualifier definition generated an error when ValueMapping.for_property was applied to it.

The valueMap is 

      [ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
          "11", "..", "0x8000.." },
       Values { "Unknown", "Other", "Not Applicable", "Linux RPM",
          "HP-UX Depot", "Windows MSI", "Solaris Package",
          "Macintosh Disk Image", "Debian linux Package",
          "VMware vSphere Installation Bundle", "VMware Software Bulletin",
          "HP Smart Component", "DMTF Reserved", "Vendor Reserved" },
       ModelCorrespondence { "CIM_SoftwareIdentity.OtherExtendedResource",
          "CIM_SoftwareIdentity.MinExtendedResourceTypeMajorVersion",
          "CIM_SoftwareIdentity.MinExtendedResourceTypeMinorVersion",
          "CIM_SoftwareIdentity.MinExtendedResourceTypeRevisionNumber",
          "CIM_SoftwareIdentity.MinExtendedResourceTypeBuildNumber",
          "CIM_SoftwareInstallationServiceCapabilities.SupportedExtendedResourc"
          "eTypes[]" }]

from the dmtf class
namespaces /root/eternus
   [UMLPackagePath ( "CIM::Core::Software" ),
    Version ( "2.28.0" ),
    ClassConstraint {
       "inv:self.IsLargeBuildNumber=true implies self.BuildNumber = null and "
       "self.LargeBuildNumber <> null",
       "inv:self.IsLargeBuildNumber=false implies "
       "self.LargeBuildNumber=null" }]
class CIM_SoftwareIdentity : CIM_LogicalElement {

The error was \
ValueError: The value-mapped property 'Classifications' in class 'CIM_SoftwareIdentity' (in 'root/eternus') has an invalid ValueMap entry: '0x8000..0xFFFF'

**Comment by KSchopmeyer** [comment]
This is a fairly common ValueMap in the DMTF schema with about 115+ occurrences for example:

ValueMap { "2", "3", "..", "0x8000..0xFFFF" }

**Comment by andy-maier** [comment]
A first analysis shows that the code in _valuemapping.py supports only decimal integers as values of the ValueMap qualifier. That needs to be extended to support all number formats allowed as per DSP0004.

**Comment by andy-maier** [comment]
Looking up DSP0004 2.8 reveals that the string values of ValueMap on an integer-typed element can be any of binaryValue / octalValue / decimalValue / hexValue. pywbem today only supports decimalValue.

**Comment by andy-maier** [comment]
Fixed in PR #1549.
