### ISSUE TITLE
WBEMServer.get_selected_profiles() treats profile names case sensitively

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1551]
The `WBEMServer.get_selected_profiles()` method treats profile names and the profile organisation strings case sensitively.

However, for some profiles defined in the SMI-S standard, the registered profile name has changed its lexical case over time:
* 'Pools From Volumes':
  - In SMI-S 1.4 to 1.6: 'Pools from Volumes'
  - In SMI-S 1.7 to 1.8: 'Pools From Volumes'
* 'Filesystem Quotas':
  - In SMI-S 1.2 to 1.7: 'FileSystem Quotas'
  - In SMI-S 1.8: 'Filesystem Quotas'

Neither the SMI-S profile overview in the Common Profiles book, nor the DMTF PUG 1.1, nor the DMTF PRP (DSP1033) 1.1, nor the description of the RegisteredName property in the CIM Schema 2.51 make any statement about whether profile names are supposed to be treated case sensitively or case insensitively.

To address this issue, we first need to agree on whether profile names are supposed to be treated case sensitively or case insensivitely.

If we agree on the latter, pywbem needs to be adjusted accordingly:
- Description and implementation of `WBEMServer.get_selected_profiles()`
- Description of `WBEMServer.profiles` property
- TBD: maybe more.

**Comment by KSchopmeyer** [comment]
ACTION: Discuss with Mike.

**Comment by KSchopmeyer** [comment]
Mike:

I prefer case sensitive. However, I don't have a problem with case insensitive interpretation. I just think it is kinder to clients if we insist on case sensitive.

However, we generally agree that there enough issue of case differences that pywbem probably needs to treat this as case insensitive.

**Comment by andy-maier** [comment]
Ok, then I suggest we implement any profile name matching in pywbem to be case insensitive, and any storage/retrieval of profile names to be case-preserving.

**Comment by andy-maier** [comment]
Fixed in PR #1579.
