### ISSUE TITLE
Clarify whether we expect DMTF profiles on SMI-S servers to use DMTF or SNIA reference direction

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1557]
What is not yet clear (to me, at least), is whether we would expect DMTF profiles that are implemented on a WBEM server that otherwise implements SMI-S profiles, to use the DMTF or the SNIA reference direction for CIM_ReferencedProfile.

This needs to be understood if we want to be able to write end2end test cases for any profiles.

**Comment by KSchopmeyer** [comment]
ACTION: 1. Discuss this with Mike Walker

ACTION 2: Define test to determine which of the approaches discusses is correct (reference direction universal for a server or reference direction determined by profile org). Note that this gets messier if we add another org.

**Comment by KSchopmeyer** [comment]
Comment from Mike. For some reason it loses his  comments after he inserts  them:

This is the result of an unfortunate screw up in the CIM Schema where SubprofileRequiresProfile reversed the references of ReferencedProfile. As I see it, the situation is hopeless if you don't have "knowledge" of the spec. If you have knowledge of the spec, you know what are autonomous profiles and you know what their "Related Profiles" are (for both autonomous and component profiles). With this knowledge you can following CIM_ReferencedProfile (without asking for Role) to determine which related profiles have been implemented.

**Comment by andy-maier** [comment]
I agree with that, but that does not answer the question whether a DMTF profile implemented on a WBEM server that also implements SMI-S profiles implements the DMTF or SNIA direction. Note that there can be two reasons a DMTF profile is implemented:
- Because an SMI-S profile references a DMTF profile.
- Because someone wanted to add DMTF profiles regardless of SMI-S profiles.

**Comment by andy-maier** [comment]
There is actually a third case:
* SMI-S profile specializes DMTF profile.

**Comment by andy-maier** [comment]
In our discussion between Mike, Karl and myself we concluded that cases (1) and (3) would fall under SNIA rules, and for case (2) we don't have an answer.
