### ISSUE TITLE
Review scoping class methodology as implemented in WBEMServer.get_central_instances()

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1563]
PR #1561 has made some fixes to `WBEMServer.get_central_instances()`, that I think were necessary.

This issue is to review the scoping algorithm in general. The algorithm implemented in that PR is (only the part when having decided to perform the scoping methodology):

* From the RP instance representing the input profile (for which the central instances are desired), traverse CIM_ReferencedProfile in the reference direction as per SNIA or DMTF. The far end must be exactly one RP instance and represents the scoping profile (of the original profile).
* For the RP instance of the scoping profile, invoke `get_central_instances()` with the `central_class` parameter set to the scoping class, and without scoping class or scoping path. The result is the central instances of the scoping profile, which are at the same time the scoping instances of the original profile. That invocation requires that the scoping profile is implemented using the central class methodology. Support for implementation of the scoping class methdology would be possible but requires that the input parameters of `get_central_instances()` could specify a series of scoping paths (with one scoping path for each level of scoping profile), up to the top.
* For each of the scoping instances of the original profile, traverse down to the central instances of the original profile by traversing the reversed scoping path of the original profile. Which could be a multi-hop traversal. Accumulating all the instances this results in results in the desired list of central instances of the original profile.

**Comment by KSchopmeyer** [comment]
ACTION: Karl. Discusss this with Mike.

**Comment by KSchopmeyer** [comment]
Mikes comment:

First, let me point out that the whole scoping class/central class notion was a well intended, but poorly thought out design, which was also poorly specified.

Second, it was defined long after most SMI-S (and DMTF) profiles were specified. The retrofit of the Scoping class/central class concepts was (in most cases) superficial.

On the first point the idea of identifying a Central Class for every profile makes sense if there is a non-association class in the profile to which everything is connected (either directly or indirectly) and that central class is connected to a class in a referencing (either direct or indirect) profile. Unfortunately, the design sort of fell apart on a couple of items:
1. Multiple uses of a CIM Class - The central class should have been a central class adaptation
2. How to handle Ephemeral classes & profiles (Job control, Indications, etc)
3. How to handle glue profiles (Health, File Storage, Virtual Fabrics, etc)
4. There was no specification of how to express the scoping path
5. Other unexpected anomalies

On the second point, adding scoping class and central class to existing profiles was a superficial exercise. The was no attempt to re-design to profiles to enable use of either the scoping class or central class methodologies. In some cases (e.g., DMTF Software Inventory) the Central Class is mandatory, but the association to the system is optional. It is not clear that an optional scoping path is particularly useful.

In the area of "other unexpected anomalies" include:
1. How to handle an autonomous profile that is used as a component profile (e.g., Switch, PRP)? 
2. How to handle profile specializations (e.g., can they change the Central Class and if so, under what conditions)? (e.g., DMTF Launch In Context and Group Masking and Mapping).
3. How to specify multiple scoping paths (e.g., SystemDevice to either a top level or component system)
4. How to specify multiple hop scoping paths

The net effect of all this is that both the scoping methodology and the central class methodology are unreliable (at least for SMI-S, if not DMTF profiles). Fixing this would require fixing the PUG and fixing a number of profiles. I don't see that happening.

**Comment by andy-maier** [comment]
Given the difficulties Mike describes, I cannot imagine that any SMI-S profile can reasonably have been implemented using the scoping class methodology. And if they are all implemented using the central class methodology, everything is fine, even for profiles with ephemeral central instances.
