### ISSUE TITLE
Jupyter notebook linux requires prompt-toolkit 2.0 or greater

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1625]
The jupyter server fails when the user starts working with the notebook with an error stating that
there is a prompt-toolkit method it cannot find.

We have as minimum requirement 1.0.... but we do not test loading jupyter

I fixed this locally by pip install -U prompt-toolkit

I am not sure if a running jupyter is actually a requirement for us in general but it is logical for the development code since it means you can develop and test notebooks right in the development environment.
DISCUSSION: Is this a requirement for us.  Is this the only use of the prompt-toolkit in pywbem development?

**Comment by andy-maier** [comment]
First, it is definitely a requirement that jupyter runs properly.

The `prompt-toolkit` package is directly used by `pywbemtools`. It is not directly used by `pywbem`, but indirectly via jupyter. Executing `make develop` in a freshly created Python virtualenv shows the dependency path for it:
```
Collecting prompt-toolkit<2.0.0,>=1.0.0 (from jupyter-console->jupyter>=1.0.0->-r dev-requirements.txt (line 63))
```

So:
* jupyter-console requires prompt-toolkit to be <2.0.0 and >=1.0.0
* pywbemtools requires prompt-toolkit to be >=1.0.15

So far, that is compatible. However, there still seems to be an issue, as you found.

Note that upgrading prompt-toolkit to the latest version as you did is in conflict with the jupyter-console requirement for it to be <2.0.0.

Can you please find out which version of the following packages you have installed when the method failure is reported:
* jupyter
* jupyter-console
* prompt-toolkit

**Comment by KSchopmeyer** [comment]
We left pywbemtools at 1.0.15 because it appeared that there was no real reason for updating it.  Also, the first 2, 0.0 of prompt-toolkit broke click so we temporarily (w had an issue on that problem to document it for pywbem toolkit) set it to less than 2.0. I though we later removed that limit.

It was definitely prompt-toolkit 1.0.... and it was clear that it was a method that did not exist in the 1.0 toolkit.  The minute I updated to toolkit 2, it worked.

Jupyter 1.0.0
jupyter-core 4.4.0
prompt-tookit 2.0.7 - after update

**Comment by andy-maier** [comment]
I was not able to reproduce the error on MacOS with:

jupyter                            1.0.0         
jupyter-client                     4.4.0         
jupyter-console                    5.0.0         
jupyter-core                       4.2.1    
prompt-toolkit                     1.0.15

I started Jupyter as documented in the pywbem docs:
```
jupyter notebook --notebook-dir=docs/notebooks/
```

**Comment by andy-maier** [comment]
If you install the minimum versions of all packages, does it work?
```
deactivate
mkvirtualenv new27
make clobber
make develop
jupyter notebook --notebook-dir=docs/notebooks/
```

**Comment by KSchopmeyer** [comment]
We retested and could not reproduce the problem. Therefore we are closing this issue
