### ISSUE TITLE
Directions and priorities for version 0.9.0

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#163]
Initial plan for 0.9.0 content, resulting from call on 3/23:

Internal things (not by priority)
1. argparse - DONE
2. more unit tests and end-end unit tests(i.e. increase coverage)
3. more run tests
4. Increased code coverage - Probably not set goal but informally would like to see 75% this next release
5. move doc to sphinx - DONE

External.  We should have an external enhancement for each new version to encourage usage.
1. **pull operations**
2. **irecv** - complete and test Karl will put up as issue
3. WBEMCLI (documentation and help DONE, what is left?)
4. mofcompiler -remove is not implemented DONE (it was in fact impemented)
5. mof compiler rollback not complete (qualifiers), and invoked on wrong object (that part DONE, it was in fact invoked on right object). Also not tested.
6. Guarantees on TLS selected level support.
7. What should we do about SLP. This generated a discussion of several items including:
   a. Should we incorporate the slp functions into our code or push for a separate Pypi openslp package? No conclusion this morning.
   b. What should we use as the basis for slp, the sourceforge or github? No conclusion other than that the github is only minor changes to the sourceforge version
   c. What is our purpose for python openslp.  Karl feels that it is to add methods so that within a python client implementation the user can use a pypi import to get basic functionality of openslp (note that this requires openslp installation) and then have a shim on top to request specific smi or dmtf templates and attributes that can be used to make connections.

**Comment by andy-maier** [comment]
I have updated the milestones of the existing issues to match what we said, above.
Whatever is not targeted for 0.9.0, got the milestone removed.
There are still quite a number of issues that would go into 0.9.0. (28 of them, not counting this one).

**Comment by KSchopmeyer** [comment]
Lets assume that this list is our directions and priorities list, not list of all things that end up in 0.9.0

**Comment by andy-maier** [comment]
Agree.

**Comment by andy-maier** [comment]
**Discussion point:**

Let's review this list and make sure we have issues open and targeted for 0.10.0 for the remaining items of the 0.9.0 list above:

Internal:

1. more unit tests and end-end unit tests (i.e. increase coverage)
2. more run tests
3. Increased code coverage - Probably not set goal but informally would like to see 75% this next release

External:
1. What should we do about SLP. This generated a discussion of several items including:
a. Should we incorporate the slp functions into our code or push for a separate Pypi openslp package? No conclusion this morning.
b. What should we use as the basis for slp, the sourceforge or github? No conclusion other than that the github is only minor changes to the sourceforge version
c. What is our purpose for python openslp. Karl feels that it is to add methods so that within a python client implementation the user can use a pypi import to get basic functionality of openslp (note that this requires openslp installation) and then have a shim on top to request specific smi or dmtf templates and attributes that can be used to make connections.

**Comment by andy-maier** [comment]
The only open item was SLP support. Created issue #490 for that. Closing this issue.
