### ISSUE TITLE
Set up makefile to run pylint with python 3

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1640]
1. We are now moving to make python3 the preferred platform. It also should be the preferred platform for development also.

2. I am not sure that pylint with python 3 and pylint with python 2 generate the same list of discrepencies.

The choices are:

1. Allow running with both python 2 and python 3

2. Switch so it only runs with python 3

3. Leave as it is.

I prefer 1 above unless there is a real reason we cannot run it with python 3.  Note that it apparently uses the defined python and its AST as the  basis for its linter so there may be differences

**Comment by andy-maier** [comment]
I agree we should establish option 1.

**Comment by andy-maier** [comment]
Fixed in PR #1641.
