### ISSUE TITLE
Simplify creating mock end-end tests

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#167]
Right now the end-end tests are difficult to create and require a lot of detail.  At the same time, we are processing exactly the same data through live tests with a server with run_cim_operations.py tests against a running server.  The proposal is to create a logging mechanism for the live tester (be it the current run... or something else that will log the core information in the yaml format, thus creating the test data for more yaml based mock data sets.

**Comment by andy-maier** [comment]
We have the proposed logging mechanism by means of the yaml recorder.
I suggest that we handle the creation of missing tests in different issues, in order to be more specific.

If that is the case, what is left from this issue?

**Comment by KSchopmeyer** [comment]
Close this one as resolved by the recorder.
