### ISSUE TITLE
Should we give a int type parameter if the invoked method need

### ISSUE THREAD

**Issue by tanshaolong** [pywbem/pywbem#1733]
Hi everybody,

I am creating a volume by pywbem for IBM SVC V7000. In term of IBM document(IBM_English_CIM_Agt_Dev_Ref.pdf), I pass a int type parameter but I meet some errors when call InvokeMethod. I don't know how to pull the parameters to IBM SVC WBEM server. Would you give some samples for IBM SVC provider? Thank you very much.

Below is my code.

import pywbem
server = 'https://192.168.**.**'
username = 'superuser'
password = '******'
namespace = 'root/ibm'

conn = pywbem.WBEMConnection(server, (username, password),
                             default_namespace=namespace,
                             no_verification=True)

classname = "IBMTSSVC_StorageConfigurationService"
sp_classname = "CIM_StoragePool"
sp_paths = conn.EnumerateInstanceNames(sp_classname)
os_inst_paths = conn.EnumerateInstanceNames(classname)

Params = [('ElementType', 2),
          ('InPool', sp_paths[0]),
          ('Size', 1024000),
          ('TheElement', None)]
result, outparams = conn.InvokeMethod('CreateOrModifyElementFromStoragePool', os_inst_paths[0], Params)

I got below error messages:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pywbem/cim_operations.py", line 4081, in InvokeMethod
    result = self._methodcall(MethodName, ObjectName, Params, **params)
  File "pywbem/cim_operations.py", line 1995, in _methodcall
    ptuple = (p[0], p[1], infer_type(p[1]),
  File "pywbem/cim_operations.py", line 1948, in infer_type
    _format("Unsupported parameter type {0}", type(obj)))
TypeError: Unsupported parameter type <type 'int'>

I changed the “int” type to “string” type in Params variable and run again. Although I didn’t get exception, the volume was created failure. The result code is 5. The reason of the failure is “5: At least one of the parameters was invalid.” reference IBM document. Please see my code.

Params = [('ElementType', '2'),
          ('InPool', sp_paths[0]),
          ('Size', '1024000'),
          ('TheElement', None)]
result, outparams = conn.InvokeMethod('CreateOrModifyElementFromStoragePool', os_inst_paths[0], Params)

The value of the result is
print(result)
5

How should I pass the parameters for IBM SVC?

Best regards
Ray

**Comment by tanshaolong** [comment]
You can get IBM_English_CIM_Agt_Dev_Ref.pdf document from ftp://ftp.software.ibm.com/storage/san/sanvc/V1.2.0/pubs/English/IBM_English_CIM_Agt_Dev_Ref.pdf

**Comment by andy-maier** [comment]
Hi Ray.
The reason for the failure is that you are passing Python int typed objects (2 for 'ElementType' and 1024000 for 'Size'). In CIM, integers can only be the CIM-typed integers such as uint32 etc. pywbem offers specific types for that, e.g. `pywbem.Uint32`.

So please look up what the cim integer tapes are for these parameters, and (assuming they would be uint32), pass the parameters as follows:

`('ElementType', pywbem.Uint32(2))`

Having said that, I admit that the TypeError raised by pywbem does not really lend itself to make that clear to the user... We'll fix that.

**Comment by tanshaolong** [comment]
Thank for your help.
I didn't see the above exception after I used your suggestion. Although I created the storage volume failure yet(The error code is ox8006 that return from SVC CIM agent),  I think the error was related with my incorrectly parameters. I will check IBM document to resolve it.  Thank you again.

Best regards
Ray

**Comment by andy-maier** [comment]
Ok. Good to hear :-)

I am closing this issue. If you have further problems, please open a new one.
