### ISSUE TITLE
How to get support about AttachDevice function in IBM svc WBEM server?

### ISSUE THREAD

**Issue by tanshaolong** [pywbem/pywbem#1746]
Hi Everybody:

I create a storage volume in IBM svc by pywbem. I want to map the volume to a hardware/VM host by AttachDevice in IBMTSSVC_ControllerConfigurationService, but I get result code is 1. I check the IBM CIM developer guide. The result code 1 mean that the WBEM server don’t support AttachDevice function.

I get instance of IBMTSSVC_ProtocolControllerMaskingCapabilities. Same as the above, the “AttachDeviceSupported” value is false.

I know the issue is not at pywbem, but I am blocked by the issue. I really can’t find a solution for it. If everybody know it or have some suggestions how to get effective help, would you please tell me? Thank you very much.

BTW, my IBM WBEM server version is 7.1.2

Best regards
Ray

**Comment by andy-maier** [comment]
Hi Ray. We cannot help you on this one. You can always open a PMR against IBM.

**Comment by andy-maier** [comment]
I assume you know the SMI-S / CIM documentation of the SVC?
https://www.ibm.com/support/knowledgecenter/STPVGU_8.2.1/com.ibm.storage.svc.console.821.doc/svc_sdkintro_215ebp.html

**Comment by andy-maier** [comment]
I looked through the SMI_s 1.4 books and the only mentioning of AttachDevice was in the Block book:

18.5 Methods of the Profile
18.5.1 ExposePaths
ExposePaths is used in place of the AssignAccess and AttachDevice methods used in 1.0. The problem with these methods was that they required the clients to perform multiple transactions to achieve a valid view. This forced providers to maintain invalid view states while waiting for the client to complete a sequence of transactions. This also created non-interoperability when the providers only supported transactions in a certain order, and when a second client looked at the model before a sequence of transactions was completed.

Maybe you should be looking at ExposePaths() instead (also on the ControllerConfigService class).

**Comment by andy-maier** [comment]
I assume you do have the SMI-S specs at hand, in the right version, that is implemented by the SVC?

**Comment by tanshaolong** [comment]
Thanks you very much. I don't try your information, but I believe the information is very useful for me. :)
