### ISSUE TITLE
Make all on any local branch updates the dist file

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#176]
Not sure if this is what you wanted or not but any general make on any branch does a update to the file 

dist/pywbem-0.9/pywbem-0.9.0.dev0.tar.gz

Which means that we are continually committing or removing this file.

More of an annoyance than big issue

**Comment by andy-maier** [comment]
It is definitely not intended. Need to investigate.

**Comment by andy-maier** [comment]
I found the problem: the "all" target does a "clean", which removes the moftab files, and they are on the dependency list of the dist archive, so the moftab files get re-created in "build" and consequently the dist archive as well.

By accident, I pushed the fix to the "master" branch; sorry for that.
