### ISSUE TITLE
New documentation issues related to WBEMListener

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1768]
This is an accumulation of some documentation issues based on 0.14.3 as the base.

1.  WBEMListener example.  Listener should probably not use 5988 and 5989 as ports. I believe that they are reserved for server.  If this implementation also had a server, the ports would conflict.
   AM> DONE - Changed to 5990 and 5991. Checked that these are not used in the tcp/udp port list (e.g on wikipedia).

2. Mispelling in Listener and Subscription manager examples.
   AM> DONE - Fixed some errors in these examples, but they were no mispellings. The examples now pass flake8.

3. WBEMListener examples shows but does not use getfqdn.
   AM> DONE - Removed import of getfqdn in `_subscription_manager.py`. In `_listener.py`, it is used.

**Comment by andy-maier** [comment]
The above changes are addressed in PR #1863.
