### ISSUE TITLE
python3: AttributeError: 'SSLContext' object has no attribute 'load_cert'

### ISSUE THREAD

**Issue by markpeek** [pywbem/pywbem#1769]
When using python3 I am seeing an AttributeError for load_cert(). I do not see this defined in the python3 documentation for the [SSLContext](https://docs.python.org/3/library/ssl.html#ssl-contexts) object.

```
# cat t.py
#!/usr/bin/env python

import platform
import pywbem

print("python version: ", platform.python_version())
print("pywbem version: ", pywbem.__version__)

cred = { 'cert_file': 'client.pem', 'key_file': 'file.pem', }
conn = pywbem.WBEMConnection('https://localhost', None, 'root/cimv2', cred)
print(conn.EnumerateClassNames(namespace='root/interop'))

# python t.py
python version:  3.7.0
pywbem version:  0.14.3
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    print(conn.EnumerateClassNames(namespace='root/interop'))
  File "/root/t/lib/python3.7/site-packages/pywbem/cim_operations.py", line 8932, in EnumerateClassNames
    **extra)
  File "/root/t/lib/python3.7/site-packages/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/root/t/lib/python3.7/site-packages/pywbem/cim_http.py", line 813, in wbem_request
    client.endheaders()
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/root/t/lib/python3.7/site-packages/pywbem/cim_http.py", line 480, in send
    self.connect()  # pylint: disable=no-member
  File "/root/t/lib/python3.7/site-packages/pywbem/cim_http.py", line 624, in connect
    ctx.load_cert(self.cert_file, keyfile=self.key_file)
AttributeError: 'SSLContext' object has no attribute 'load_cert'
```

**Comment by andy-maier** [comment]
I am currently on vacation and cannot look at this. Give us so.e time pls.

**Comment by markpeek** [comment]
@andy-maier have you had a chance to reproduce or look into this issue? Thanks.

**Comment by andy-maier** [comment]
@KSchopmeyer wanted to take a look at this. We discussed it today and it needs some investigation.

**Comment by KSchopmeyer** [comment]
We definitly have an issue with pywbem itself.  We use two different libraries for Python 2 and Python 3 and used the name of a method from Python 2 in the Python3 SSL context processor.

The correct method name should probably be load_cert_chain(...).

This is an issue we will have to correct and probably means a new revision release of pywbem 0.14

**Comment by KSchopmeyer** [comment]
NOTE: to bypass the server cert verification, use the no-verify option in WBEMConnection

**Comment by markpeek** [comment]
Yes, my work around was to use the Python3 load_cert_chain() method.

**Comment by KSchopmeyer** [comment]
Thats it.  I need to write another test against a working server to be absolutly certain but will put a PR up on this issue now.

**Comment by KSchopmeyer** [comment]
Does that mean that you are correctly passing the verify on server certs? Also, have you tried testing with client certs?

**Comment by andy-maier** [comment]
PR #1777 fixes this in master (future 1.0.0) and PR #1779 rolls that fix back into 0.14.4 (to be released).
We consider this one fixed. If another issue comes up with it, please open a new issue.

**Comment by andy-maier** [comment]
We'll release 0.14.4 in the next couple of days.

**Comment by markpeek** [comment]
Thank you @KSchopmeyer and @andy-maier for the fix and release.

**Comment by andy-maier** [comment]
pywbem 0.14.4 has been released today, including the fix for this issue.
