### ISSUE TITLE
pywbem iter...() requests and FilterQuery

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1801]
There is an inherent issue between the DMTF pull operations and the coresponding traditional operations and the FilterQuery parameter. The feature to filter resutls was a powerfull tool but was a part of only the Pull operations and was never implemented for the traditional operations.

In our iter operations, we first try the pull and then fall back to the traditional operations. If there is a FilterQuery, the result is that we generate a ValueError because the traditional operations cannot handle the filter and we documented the pull such that it had to guarantee that either the pull worked or generate an error. We wanted the user to know that they were getting filtered results returned.

Since we have the chance of this ValueError coming back from the Iter...() we want to try to sort out a more logical solution than the fValueError out of the clear blue.

There are a number of possible solutions including:

1. Build the FilterQuery processor into the client so that if we fall back, we filter the result.

2. Accept that the results will be bad and pass the request without the filter to the server knowing that they will get back a non-filtered response.  This one hurts because it means that our Iter...() oprations would not really be observing the rules that the result must be filtered if the filter is requested.

**Comment by andy-maier** [comment]
I suggest that we go for the first solution.

**Comment by KSchopmeyer** [comment]
Lets move this to 1.1.

**Comment by KSchopmeyer** [comment]
Confirm that the documentation covers this issue and that the recommendation is that they set the pull only flag if they are going to use the FQL query.  We will not implement the FQL processor in the client.
