### ISSUE TITLE
tests/README clarifications/questions

### ISSUE THREAD

**Issue by tasleson** [pywbem/pywbem#1803]
When looking at the `tests/README` file it reads: 

> Depending on how the `pywbem` package is installed in that
Python environment, either the `pywbem` and `pywbem_mock` directories in the
main repository directory are used, or the installed `pywbem` package.

How does a user run tests against a system wide install?  When you run `make test` in the root of the source tree, pywbem directory is in the current working directory, thus it will get picked up by the interpreter.  Furthermore, if you move pywbem and pywbem_mock directories, then you run into an issue where make encounters the following:

``` bash
make: *** No rule to make target 'pywbem/mof_compiler.py', needed by 'pywbem/mofparsetab.py'.  Stop.
```
as the files: `pywbem/mofparsetab.py` and `pywbem/moflextab.py` get created during the test.

How does a user run the unit tests from the source tree against installed system wide libraries?  This is something I would like to have the ability to do, thanks!

**Comment by andy-maier** [comment]
`make test` invokes py.test, which gets the test case directories as input (i.e. `tests/unittest` and `tests/functiontest`). The `pywbem` and `pywbem_mock` modules are then imported by the test cases. This means they don't have to be in the work directory, as long as they are in the Python module search path.

So the following will test the installed pywbem:

```
mkdir -p disabled
mv pywbem disabled/
mv pywbem_mock disabled/
rm -rf pywbem.egg-info
# check where pywbem comes from now:
python -c "import pywbem; print(pywbem.__file__)"
pip list | grep pywbem
py.test --color=yes --cov pywbem --cov pywbem_mock  --cov-config coveragerc   tests/unittest tests/functiontest -s
mv disabled/* .
```

**Comment by tasleson** [comment]
@andy-maier It might be good to have something like this in the documentation.  However, I find it interesting if you take a cleanly cloned repo. and just run 

```bash
py.test --color=yes --cov pywbem --cov pywbem_mock  --cov-config coveragerc   tests/unittest tests/functiontest -s
```
All the `test_wbemcli.py` tests fail.  Running `make tests` apparently is needed to setup all the things for the unit tests to pass.

**Comment by andy-maier** [comment]
In order to run the tests, `make develop` is a prerequisite. `make test` does that automatically.

**Comment by tasleson** [comment]
> What is your use case for this?

My use case is to validate that a rpm packaged install of pywbem is functional.

**Comment by andy-maier** [comment]
I was afraid you would have a valid use case :-)

**Comment by KSchopmeyer** [comment]
Agreed, that is a valid use case.

**Comment by andy-maier** [comment]
PR #1806 implements support for testing an installed version of pywbem. For now, the PR description provides a brief usage.

Can you please check out whether this works for you?

Proper docs update will also come.

**Comment by tasleson** [comment]
@andy-maier Thanks, will test it out today.

**Comment by tasleson** [comment]
See https://github.com/pywbem/pywbem/pull/1815

**Comment by tasleson** [comment]
Output with my 2 commits

[latest_test.txt.gz](https://github.com/pywbem/pywbem/files/3527090/latest_test.txt.gz)

**Comment by andy-maier** [comment]
I have created PRs #1833 and #1835 to pick up the two changes from Tony's PR #1815, so they can be fixed independently.

In addition, we need to follow up on the errors in Tony's test runs (see above).

**Comment by andy-maier** [comment]
@tasleson Hi Tony.
PR #1842 improves the support for TEST_INSTALLED such that any Python and OS-level prerequisites are now also assumed to be installed (as well as pywbem).

So using:

`TEST_INSTALLED=1 make test`

no longer performs any installation and just runs the tests. This should get you over the dnf usage error in your logs, because pywbem_os_setup.sh is no longer called. The assumption is of course that the pywbem RPM package has ensured that any of its Python and OS-level prerequisites are installed.

Of course, we still need to fix the dnf usage error.

**Comment by andy-maier** [comment]
Issue #1844 (dnf error) is fixed, and the PRs are merged. If you try it out, you can use the stable_0.14 branch.

**Comment by andy-maier** [comment]
@tasleson Closing this issue in preparation of releasing 0.14.5 in the next week or so. Please reopen this one or a new one if you find additional issues on this.

**Comment by tasleson** [comment]
@andy-maier Thank you for your work on this.  I will re-test soon.
