### ISSUE TITLE
Whether or not could pywbem generator CIM mof files?

### ISSUE THREAD

**Issue by tanshaolong** [pywbem/pywbem#1805]
Hello,

I have a storage device, but I just can get empty mof file by below GetClass method.

```
print(hcon.GetClass("Nex_StorageConfigurationService").tomof())
class Nex_StorageConfigurationService : HuaSy_StorageConfigurationService {

};
```

If I don’t have the class mof file, I couldn’t check some methods guide in the class.
Check pywbem document, the mof_compiler tool can input or update CIM repository of a WBEM server. Whether or not could pywbem generator CIM mof files? Or could I get the mof class by other method? 
I am not familiar with SMI-S mechanism. Maybe, my mean is naive. :)

Thanks
Ray

**Comment by andy-maier** [comment]
The way you want to produce MOF in your code above is correct.

The reason you don't see any properties or methods in the MOF is that this class does not have any local properties or methods.

**Comment by KSchopmeyer** [comment]
The Nex_storageConfigurationService class is probably what we call a trivial subclass of CIM_StorageConfigurationService, a technicque many implementations use just to separate the names. Thus your class has exactly the same characteristics as the superclass except for the class name.

**Comment by tanshaolong** [comment]
I see. Thanks for your detail response. :)

**Comment by andy-maier** [comment]
You're welcome. Closing this issue now - feel free to reopen or open a new one in case of additional issues or questions!
