### ISSUE TITLE
Pywbemtools causes python-mock failure

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1816]
Running the pywbemtools enumerate instances with the pywbem file simple_mock_model_ext.mof causes a failure with the message that an instance was duplicated in the repository.

We confirmed that apparently no instance was duplicated. 

We have traces in the corresponding pywbemtools issue https://github.com/pywbem/pywbemtools/issues/260

**Comment by andy-maier** [comment]
Is this fixed by PR #1827?

**Comment by andy-maier** [comment]
Karl will investigate and fix if needed.

**Comment by andy-maier** [comment]
After discussing with Karl: This issue describes the symptom that is caused by issue #1852. Closing it as a duplicate.
