### ISSUE TITLE
wbemcli script error creates unreadable msg out

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1851]

**Comment by andy-maier** [comment]
Please provide more details.

**Comment by andy-maier** [comment]
@KSchopmeyer 
I created PR #1853 which improves all error messages and error handling in wbemcli.
Please review that and post any further issues in that PR, or here.

**Comment by andy-maier** [comment]
PR #1854 rolls this back to 0.14.5.
