### ISSUE TITLE
Pywbem_mock method compile_file allows duplicate instances

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1852]
We used the standard method in the mof_compiler class MOFWBEMConnection. This method does not test for existing instance with same name before adding new instance.

This is not really an issue with the MOFWBEMConnection CreateInstance function itself but within the MOF compiler where the p_mp_createInstance function  recovers from getting an Error back from CreateInstance with status "ALREADY_EXISTS" by falling into mModifyInstance and modifies the existing instance or, if that fails, deletes and replaces the existing instance.

I don't think that we dare modify this behavior as the default behavior for the compiler creating instances.  The only thing I can think of is a compiler flag that modifies this behavior if set.  And since the parser methods are top level functions, that would mean that we create a global to modify the behavior and that  global gets set from MOFWBEMConnection constructor, i.e. no_instance-modify.

Note that we want to change the mocker use our own CreateInstance since the one in MOFWBEMConnection does not test for all key properties set or even that the class exists.

Any other ideas are welcome

**Comment by andy-maier** [comment]
For which case do we need a different behavior than the one you described?

**Comment by andy-maier** [comment]
This one should be fixed by changing the pywbem mock support to do all these checks, including the one for duplicate instances, and the pywbem MOF compiler needs to be changed to use the mock operations instead of accessing low level functions or data variables directly.

**Comment by andy-maier** [comment]
Fixed in PR #1892 for master, and TBD for 0.15.0.
