### ISSUE TITLE
Mock instance create, property name case inequality

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1883]
When we create new instances in the mocker with CreateInstace operation, the property names are not significant except that in the created instance, if the case is different for a property name between the class and the new instance, the new instance property receives the name with the case defined by the new instance, not the case sensitive definition of the class itself.  This works but means that property names on instance vary widely in displays. 

We propose that the mocker set the correcntly case defined name from the class into each property of the new instance.

Thus, the creation of a new instance where the class property name was ScalBool but the new_instance corresponding property name was scalbool creates the instance with the property name scalbool.

Marked RollBack to be rolled back to 0.15.0 assuming that this is the next release

**Comment by andy-maier** [comment]
Fixed in PR #1884 for master, and rolled back into 0.15.0 with PR #1888.
