### ISSUE TITLE
Issues with MOF escaping in mofstr()

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#189]
The `mofstr()` function in `cim_obj.py` has two issues in the area of MOF escaping:
- It attempts to recognize MOF escape sequences and will pass them through unchanged, to the output. A comment states that the motivation for that is to handle strings returned by WBEM servers that use MOF escape sequences (instead of XML rules), so because they already are MOF escape sequences, they are passed through to the MOF output.
  
  This motivation is moot however, because the `mofstr()` function is called only from two places, both of which are in `tomof()` methods of CIM objects (`CIMInstance` and `CIMQualifierDeclaration`). Any CIM string typed values in CIM objects are supposed to contain the proper strings as a Python unicode string object, without any escaping or remainders from protocol encoding.
  
  **Proposed solution:** Remove the special casing for MOF escape sequences.
- DSP0004 at some point clarified that MOF string constants may contain the whole character repertoire for CIM string typed values, which is the whole Unicode repertoire minus U+0000. The control characters (U+0001...U+001F) are not nicely handled by most editors, and after all MOF is supposed to be editable. The `mofstr()` function does not do anything with them (except for the few special ones in that range).
  
  **Proposed solution:** Add support for escaping control characters using the generic escaping, e.g. U+001B becomes to `"\x001B"`.

**Comment by KSchopmeyer** [comment]
On 04/06/2016 11:06 AM, Andreas Maier wrote:
>
> There are two issues with the MOF escaling in the |mofstr()| function 
> in |cim_obj.py|:
>
>  *
>
>     It has code that attempts to tolerate already escaped MOF
>     sequences, by not escaling them again. A comment states that this
>     is done in support of WBEM servers that incorrectly ship escaped
>     MOF sequences back in CIM string values in the CIM-XML payload.
>
>     The issue is that the |mofstr()| function is not used at all for
>     processing returned strings. It is called only from two places and
>     in both cases are within a |tomof()| function, so it is only used
>     to convert CIM string typed values into MOF string constants.
>     These values come from CIM objects (e.g. |CIMProperty|), which are
>     supposed to contain the proper Python strings without any
>     remainders from unresolved payload parsing.
>
It is only used for returned string values and by far the largest use in 
for the string values of things like
description qualifier and only for mof output..  It is actually needed 
unless we have an issue elsewhere in particular for strings coming into 
the environment through mof. By an large it maps things like /n to //n 
on its output.  Note that the other thing it does (and that could be a 
separate function) is to fold strings for the mof output.  There is 
actually a fold function in python that we could use for the folder.
>
>  *
>
>     So if a toleration of server-provided MOF escape sequences is
>     needed, this is the wrong place anyway.
>
>     *Proposed solution:* Remove the special-casing for MOF escape
>     sequences.
>
>  *
>
>     It does not handle control characters. DSP0004 at some point
>     clarified that the character repertoire for MOF string constants
>     consists of the entire character repertoire for CIM string types,
>     which is the whole Unicode repertoire except U+0000. So the
>     control characters U+0001 to U+001F are possible, and except for
>     some special ones, they would show up as binary characters in the
>     generated MOF.
>
>     *Proposed solution:* Add support for escaping the control characters.
>
That was another bug I wanted to file.  However, the first goal was 
simply to get through the mof round trip test
and this thing kills that test by messing up sequences like "asdfasdfas 
//w asdfasd"
>
>  *
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/189>
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
Karl,
on the first issue: I'm not sure I understand your comment. Did you intend to say that the passing through of MOF escape sequences in the old code is needed for anything?
