### ISSUE TITLE
MOF Compiler issue with CreateInstance

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1890]
The pywbem mof compilermay have a logic issue with its CreateInstance processing (see p_mp_createInstnace(p) line 618. The logic is such that it can overwrite existing instances in its working repository of instances.

The compiler  calls p.parser.handle.CreateInstance()  to create the new instance.  The default for this is in MOFWBEMConnection or a user can subsitute another repository with a CreateInstance method..

If the CreateInstance fails with CIM_ERR_ALREADY_EXISTS, it falls back to first try ModifyInstance and if this fails it next tries DeleteInstance the existing instance and recreate it with the new instance with CreateInstance.

NOTE: None of this actually happens when the compiler uses MOFWBEMConnection because the CreateInstance method in that code simply appends any new instance to the existing list of instances without checking for duplicates which is what currently causes duplicates in the mocker. See Issue #1852 

However, underlying this is the question of whether the compiler should be attempting to modify or replace existing instances in a repository based on a new instance with the same path or should simply generate an error if the instance already exists.

**DISCUSSION** Should the mof compiler ever try to replace existing instances in a repository with a new instance.   What I  found was in DSP0004, section 6.3 Instance Declarations is:

6.3   Instance Declarations
Any instance declaration is treated as an instruction to create a new instance where the key values of the object do not already exist or an instruction to modify an existing instance where an object with identical key values already exists.

The implication here is that if ModifyInstance exists, the rule is to modify the existing instance. However, this does not seem to extend to the idea of delete and replace which is being done by the current compiler

**Comment by andy-maier** [comment]
I think the delete and replace approach was implemented as an additional safety net in case the modification does not work for some reason. I think we need to understand under which circumstances that would be needed.

**Comment by andy-maier** [comment]
PR #1895 fixes this for master, and PR #1897 for 0.15.0.

**Comment by KSchopmeyer** [comment]
**DISCUSSION** I think the real question here might be whether concept of retry with modify, etc. should be an issue for the client or the server.  In the case of the pywbem mof_compiler it actually works only if the server returns ALREADY_EXISTS for the create and NOT_SUPPORTED for the modify.

**Comment by andy-maier** [comment]
We agreed on the following approach for this issue:
* Drop the third step of delete/create once modify fails
* Make sure that the error code that is now returned from the mock support causes modify to be used when create fails.

**Comment by andy-maier** [comment]
This PR is fixed by PR #1909 for master and **TBD** for 0.15.0.
