### ISSUE TITLE
MOF compiler, setting path keybindings component of new instances

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1911]
The pywbem mof compiler today only sets the keybindings part of the path c**omponent of new instances if alias is set. Otherwise, it sends a path with {} keybindings, mof_compiler line 1585.  That is because it only creates the keybindings if alias is set for the instance.

In other words, it is the existence of the instance alias tag that causes keybindings to be set into the path of new instances.

**DISCUSSION**: Is this correct or should we always be creating the keybindings of a new instance created by the compiler?

Note** that there are two other issues tied to this issue of usage of instance alias.

**Comment by andy-maier** [comment]
The approach for setting the keybindings is to look at the class to identify which properties are key properties, and then to build the keybindings from exactly these properties. If the instance does not have all key properties, it fails. Correct me if that is not the case.
In this approach, the alias does not play any role whatsoever. Therefore I dont think this should be limited to only instances with alias.

**Comment by andy-maier** [comment]
If I look at this more generally, then the MOF compiler works against a repository. If the repository is that of a real WBEM server, then I think there are two cases:
* The provider constructs the key values and ignores or rejects any key properties in the input instance. Classes with InstanceID would typically have such providers.
* The provider relies on the key properties being provided in the input instance. Classes with natural keys would typically have such providers.
The mgmt profiles are supposed to clarify which case is used.

For our discussion, this means two things:
1. It should probably be the mock repository that constructs the path and not the MOF compiler.
2. The user of pywbem/pywbemtools needs to decide how they go about classes where the provider is supposed to create the keys: Either by means of Python mockers, or by means of supplying the keys in the input MOF.

**Comment by KSchopmeyer** [comment]
In general, the value that is used for the alias should not be the path created as the new instance is created in the server but should be the path received back from the connection when the CreateInstance is executed. Since the compiler does execute a createinstance, that data is available and could be inserted into the alias definition for each new instance to be used to create association instances.

The use of the alias to create a path to be used by the WBEM Server is really incorrect.

**Comment by KSchopmeyer** [comment]
NOTE: the current MOF compiler actually could not create instances for an SFCB server since it depends on knowledge of the corresponding class and SFCB does not have a class repository.

NOTE: Lets make this version 1.0 since it changes the local CreateInstance interface by not including a path with the NewInstance.

**Comment by KSchopmeyer** [comment]
Summary: There are two issues:

1. The  path that it uses as an alias should be the path received back from the server, not the the one on the instance being created.  The compiler should update/set the alias path when the mofcompiler issues the CreateInstance() is completed successfully.

2. Re: SFCB.  Karl believes that we do not even need the class information to create the path since the compiler uses that class to determine key properties and then builds the path from the just created instance.  If we use the returned instance path from the CreateInstance we do not need this class call.

**Comment by KSchopmeyer** [comment]
Karl: Action determine if this one is done.

**Comment by andy-maier** [comment]
Addressed in PR #2212 (TBD: Karl to confirm?)

**Comment by andy-maier** [comment]
Then I'm closing this issue as done.
