### ISSUE TITLE
Issue in pywbem_mock associators algorthim

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1917]
1. The algorithm for class referencenames does not account for the fact that we are really trying to process for all target classes from the name provided with the operation request and its superclasses. 

 2. Altough it is not documented clearly in the spec, at least two other implementations return error if the ResultClass or AssocClass do not exist. Note that the errors returned are BAD_Paramenter if the reference Result class or associator AssocClass does not exist and NOT_Found if the associator ResultClass does not exist.

**Comment by andy-maier** [comment]
Karl said this one is still being worked. Needs to be rolled back because it is a bug.

**Comment by andy-maier** [comment]
Fixed wth PR #1918 for master, and TBD for 0.15.0.
