### ISSUE TITLE
Removal of wbemcli in 1.0.0

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1932]
Now that pywbemcli has been released to Pypi (https://pypi.org/project/pywbemtools/), it seems to me that we should remove wbemcli from pywbem:

* Wbemcli does not have a command mode, but pywbemcli does.
* The interactive mode of wbemcli is more of a programming environment than an interactive CLI which makes it harder to use than necessary, but pywbemcli does have an interactive CLI.
* The functionality of pywbemcli is superior to wbemcli (e.g. server commands, persistent connections, class find, instance count, flexible output formats).

On at least RHEL and Fedora, pywbem's wbemcli is installed under the command name `pywbemcli` because there was already another `wbemcli` command (the one from the SBLIM project). @tasleson Tony, I think that the new pywbemcli from the pywbemtools package is not only superior to pywbem's wbemcli, but also to SBLIM's wbemcli. Could you please try it out and let us know how you think about integrating it into the next Fedora release, replacing (at least) the pywbem wbemcli ?

**Comment by tasleson** [comment]
We have been renaming wbemcli to pywbemcli in later versions of fedora to correct the name collision, but if it's dropped for 1.0 then we wouldn't have a need for that.  As for utilizing pywbemcli from pywbemtools, we would want to package that separately, which should be fine.

**Comment by andy-maier** [comment]
Ok, that sounds great to me. In the pywbem repo, there is a directory named "packaging" which contains some files for the distro packaging, but I suppose it is not very up to date there, right now. We could do something similar in pywbemtools if that makes sense for you. Just let us know, or post a PR.

**Comment by tasleson** [comment]
We store the spec file in the package repo, so it's not needed in the upstream repo.  In general it's something that just gets out of date :-)

**Comment by andy-maier** [comment]
Karl and I discussed this in our call this week, and we decided to go ahead and remove wbemcli from pywbem in its 1.0 version. The versions below 1.0.0 will continue to have it.

**Comment by andy-maier** [comment]
Addressed by PR #1936 which removes wbemci in 1.0.0, and PR #1935 which deprecates wbemcli in 0.15.0, announcing its removal in 1.0.0.
