### ISSUE TITLE
Doc repository does not make the presentations public on the web. Site.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#194]
We have a presentations directory with a number of presentations but there is no public presentation of that on the web pages.

**Comment by KSchopmeyer** [comment]
We may be forced to have PDFs versions of each of them and present those in public but it turns out that just having them in the repository buried several layers in the directories does not help readers.  Just figured that out when I tried to tell people where they could get the presentation from Feb.

**Comment by andy-maier** [comment]
I thought we had a presentations page, but that must have been on SF. I suggest to add a presentations page, and to have links there.

**Comment by andy-maier** [comment]
This issue is addressed by [pywbem.github.io PR #12](https://github.com/pywbem/pywbem.github.io/pull/12).

Please review it, over there.
