### ISSUE TITLE
pywbem MOF compiler cannot compile to remote connection

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1956]
The pywbem MOF compiler does not create classes, instances, or qualifer declarations in the defined target connection.

While it uses the defined target connection if defined to get information from the server if the target is specified (conn=...) The MOFWBEMConnection definitions for CreateClass, CreateInstance and SetQualifier only write to the local repository in MOFWBEMConnection, not to the remote repository.

This, for example, The set qualifier consists only of the code:

```
    def SetQualifier(self, *args, **kwargs):
        """Create or modify a qualifier type in the local repository of this
        class.

        For a description of the parameters, see
        :meth:`pywbem.WBEMConnection.SetQualifier`.
        """

        qual = args[0] if args else kwargs['QualifierDeclaration']
        try:
            self.qualifiers[self.default_namespace][qual.name] = qual
        except KeyError:
            self.qualifiers[self.default_namespace] = \
                NocaseDict({qual.name: qual})

That is why the remove works.  The remove recompiles the mof into the local repository the MOFWBEMConnection) and uses the results of that to try to remove the mof from the remote repository.

**Comment by andy-maier** [comment]
Fixed in PR #1957 for master and PR TBD for 0.15.0.
