### ISSUE TITLE
pywbem mocker rejects instances from compiler with no keybindings

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1958]
Currently we issue exception for these instances (no keybindings on new instance from compiler. We did this specifically because before that we were allowing them to pass and the compiler only puts the path on when the instance alias is defined.

I would like to change this so that the mocker compile_mof_string/file:

1. Runs test to be sure all key properties are in the instance. and rejects if not. Even if there already is an instance path with keybinding (i.e protects the mock repository better)
2. Builds the inst path if it does not exist complete with good keybindings.

We have some people using the mocker now and this would just make it a bit easier to use.

This would allow users to build compiled mof without having to put the instance alias on all created instances.  Note the instance alias would still be used to define reference property values, but not be used to force the inst path on to the instance.

This is backward compatible with existing since having the instance path is still OK.

NOTE: I want this one to go into 0.15.0.

**Comment by andy-maier** [comment]
We discussed this and agreed to pursue it as proposed. This is an intermediate step on the way to reorganize the path creation to be fully ii the mocker.

**Comment by andy-maier** [comment]
Addressed by PR #1962 for master and PR #1965 for 0.15.0.
