### ISSUE TITLE
Remove conn_lite mode from pywbem_mock

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1959]
While this seemed to be a good idea when we first defined it, the conn-lite mode turned out to be mostly confusion an implementation complexity with no gain.

The idea was to be able to create repositories with mostly instances without having to worry about the class characteristics.

Since it is easy to build the class components of mock repositories, there is really no reason for this mode at all.

I want to simply remove it.

**Comment by andy-maier** [comment]
Agreed. No rollback into 0.15.0.

**Comment by andy-maier** [comment]
Addressed by PR #2047 (for master, not being rolled back).
