### ISSUE TITLE
Should methodcall() and imethodcall() be made private

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#196]
In an earlier discussion, we said that they should not be part of the documented external API.
For compatibiity (in case someone has built operations on top of them), it would be appropriate to still have them public with their unchanged names, but just not part of the documented external API.

Here is why it is difficult to do both of that:
- The `__all__` approach does not work for them, because they are not module-global symbols, but members of a class.
- The `.. autoclass::` statement has the ability to specify those class members that are supposed to be shown. However, specifying the other names there causes the special members (e.g. `__str__()`) to no longer be shown. This seems to be a bug in Sphinx or its Autodoc extension.

In the current code, they show up in the documentation, and their description states that they are not part of the external API.

We could go beyond that by making them private, i.e. by adding an underscore. However, that changes the class interface incompatibly.

The discussion point is whether we are serious enough with the intention to remove them from the documented external API, that we would buy into the incompatibility of making them private. We did that for a number of other module-global functions, so it comes down to whether we think someone might have actually used them.

**Comment by andy-maier** [comment]
Agreed on the call today that we would move this out beyond 0.9.0.

**Comment by skolsuper** [comment]
Was just idly browsing issues and happened across this, but have a suggested flow:

1. Move the function bodies to underscore-prefixed method names.
1. Replace it with a [`warnings.warn`](https://docs.python.org/2/library/warnings.html) and a call to the private method.
1. Wait a few releases...
1. Remove the public function

You might also want to add a deprecation policy to the repo as a step 0.

**Comment by andy-maier** [comment]
I like the idea.

**Comment by andy-maier** [comment]
Agreed to go for this way of deprecating stuff.
