### ISSUE TITLE
mof_compiler qualifierdecl prerequisites for compile

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1978]
The mof compiler is designed to get prerequisites for any compile.  This works for other classes such as installing the superclass or the class defined for a reference property or embedded object.

However it does not consider getting qualifier declarations that do not current exist in the defined namespace.

The following is an example from OpenPegasus where one of the test namespaces does not have all of the normally expected qualifier declarations.

```
mof_compiler -s http://localhost -v -I tests/schema/mofFinal2.51.0/ -n test/cimv2 tests/unittest/pywbem/test.mof
MOF repository: Namespace test/cimv2 in WBEM server http://localhost
Generating LALR tables
Compiling file './tests/unittest/pywbem/test.mof'
Creating class 'test/cimv2':'PyWBEM_Person'
Created class 'test/cimv2':'PyWBEM_Person'
Creating class 'test/cimv2':'PyWBEM_PersonCollection'
Compiling file '/home/kschopmeyer/pywbem/githubpywbem/pywbem/tests/schema/mofFinal2.51.0/Core/CIM_ConcreteCollection.mof'
Fatal Error: /home/kschopmeyer/pywbem/githubpywbem/pywbem/tests/schema/mofFinal2.51.0/Core/CIM_ConcreteCollection.mof:3
A general error occurred:Unknown Qualifier: 'UMLPackagePath'
Fatal Error: /home/kschopmeyer/pywbem/githubpywbem/pywbem/tests/schema/mofFinal2.51.0/Core/CIM_ConcreteCollection.mof:9
A general error occurred:Unknown Qualifier: 'UMLPackagePath'
mof_compiler: CIMError: 1 (CIM_ERR_FAILED): Unknown Qualifier: 'UMLPackagePath'
(pywbem3) kschopmeyer@leonard:~/pywbem/githubpywbem/pywbem(ks/#1158-repo-remove-fails)$

```

At this point I am not sure whether this should be fixed or just a warning in the documentation

**Comment by KSchopmeyer** [comment]
We agree that we should do this in version 1.0.0.  We will add the qualifiers from the search path that are required for this compile should be added as part of the compile process.

**Comment by KSchopmeyer** [comment]
We agree that  this should be documentation change only

**Comment by KSchopmeyer** [comment]
Karl ACTION: Clarify what we should do

**Comment by KSchopmeyer** [comment]
I am very uncomfortable with automatically adding qualifier declarations to a WBEM server since we do not know anything  about the schema version, etc.   However, I do note that it is not easy to just compile specific qualifiers into a server namespace; in the mocker, for example, when compiling in MOF for the schema we just compile in all of the qualifiers.

1. Just document that we do not compile qualifier declarations in if they are missing.

2. Expand the compiler so that we could compile in qualifiers only if there is a flag set so that the user knows that they are compiling in qualifier declarations.

**Comment by andy-maier** [comment]
This question is discussed in issue #2217. Let's make sure we review it there.

**Comment by andy-maier** [comment]
We agreed to move this to 1.1.0, where issue #2217 already is.

**Comment by KSchopmeyer** [comment]
Close as invalid since we install all qualifiers with the compiler for the schema version.
