### ISSUE TITLE
Confusing error message in cim_obj.CIMInstanceName

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1985]
The message in cim_obj.py, CIMInstanceName.keybindings 

CIMInstance keybinding {0!A} key {1!A} value "
                                "value is 'None' which is not allowed unless "
                                "unless 'IGNORE_NULL_KEY_VALUE' is True.

Is confusing for users of higher level packages because it does not identify where this variable is.

Suggest change to unless pywbem config.IGNORE_NULL_KEY_VALUE is True.

**Comment by andy-maier** [comment]
Addressed by PR #1990.
