### ISSUE TITLE
MOF compile methods of FakedWBEMConnection always write errors to stdout

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1997]
The MOF compilation methods `compile_mof_string()`, `compile_mof_file()` and `compile_dmtf_schema()` of the `FakedWBEMConnection` class always write MOF compilation errors to stdout, and do not provide any means to turn this off.

Proposal:
- Do not write to stdout at all, because the errors can be obtained from the exceptions that are raised.

**Discussion point:** Go with proposal?

**Comment by andy-maier** [comment]
Fixed in PR #1995.

**Comment by KSchopmeyer** [comment]
We agree. Go ahead with this proposal
