### ISSUE TITLE
tls connect

### ISSUE THREAD

**Issue by allen0817** [pywbem/pywbem#2000]
@andy-maier 
hi andy

env 
 Python 3.5.7 (default, Nov 14 2019, 10:38:20) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
pywbem : 0.14.0
openssl version : OpenSSL 1.1.1  11 Sep 2018
system : CentOS release 6.5 (Final)

stroage: 
      New, TLSv1.0, Cipher is ECDHE-RSA-AES128-SHA
      Server public key is 2048 bit
      Secure Renegotiation IS supported
     Compression: NONE
     Expansion: NONE
     No ALPN negotiated
     SSL-Session:
       Protocol  : TLSv1
=============

my code 
   conn = pywbem.WBEMConnection('https://192.168.1.10:6989', ('customer', 'cust0mer'), 'root/ibm',None,None,None,True)
  res = conn.ExecQuery('WQL', 'select * from IBMTSSVC_StorageVolume')

error:
  AuthError:Unauthorized

my try:
   change openssl.cnf, as
tail /usr/local/openssl-1.1.1/ssl/openssl.cnf
				# (optional, default: no)
ess_cert_id_chain	= no	# Must the ESS cert id chain be included?
				# (optional, default: no)
ess_cert_id_alg		= sha1	# algorithm to compute certificate
				# identifier (optional, default: sha1)
#add by allen 
[system_default_sect]
MinProtocol = TLSv1.0
CipherString = DEFAULT@SECLEVEL=2

=========
Authentication failed. I don't know what's wrong. IBM engineers said there was no problem with the account.please

**Comment by KSchopmeyer** [comment]
Lets see what pywbem thinks its SSL config is.  Since you don't get any real information from the client itself, you can use the pywbem indication listener.  We have an example client listener in the examples library.  Note that you only get the examples directory when you clone pywbem github, not when you pip install it.

That script (examples/listen.py starts a pywbem indication listener and keeps it open until you kill the program. Since this is, in effect, a server, it can be probed for SSL information using an SSL Scaller. The cmd line to start it is 

    listen.py <host> <http port> <https port> <certfile> <keyfile> 

1. Be sure you are using the pywbem clone so this is example listener is available.
2. Get a tool that does an SSL scan.  SSLScan which should be in the CentOS available packages lib works well.  I know it is available for Ubuntu but right now I do not have a CentOS 6.5 installed so will have to play a bit to create that environment.
3. Create a simple self-signed cert and key. They are required for the https port. 
A one liner on at linux that does this is:

openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout server.key -out server.crt

4. Start the listener:

    listen.py localhost 50000 50001 server.crt server.key

If this works, the listener should be running and a python interpeter running

```
./listen.py localhost 5000 5001 server.crt server.key

WBEM listener started on host localhost (HTTP port: 5000, HTTPS port: 5001).
This Python console displays any indications received by this listener as
logger outputs (Level=INFO) to the console by default.

listener: WBEMListener instance that has been started.

help(listener): Display help for using listener instance.

status() : Display count of indications received; status(reset=True) to reset
           counters

Modify logger characteristics through listener.logger:
     (ex. listener.logger.setLevel(logging.ERROR))

Ctrl-d to exit

>>>

```

5. See what the scan tool says about SSL on the https port.  It should provide info on OpenSSL version, Protocol versions, ciphers available, etc.

**Comment by andy-maier** [comment]
@allen0817 WHat is the device you are trying to use? Still the DS8000?

**Comment by KSchopmeyer** [comment]
No. I am working against OpenPegasus in a local configuration or a number of SNIA SMI servers in the SNIA test center. We work against all of these since pywbem is the monitor tool and tests against all of them about ever 30 minutes for reporting on the SNIA test center status.  This includes HP, EMC, Fujitsu, and other mfgrs.  There is no IBM equipment in that lab however.

**Comment by KSchopmeyer** [comment]
The little proposal I made above is just to get more information on the SSL you are using with your client by making a server that uses it and asking it what its characteristics are.  That returns all the possible ciphers, protocols, etc.

OpenSSL is notably stingy with real information and the python SSL library on top of it does not really help.  Thus, there is no ability to log the interaction within the Python SSL library, or more detailed displays that we know of.

**Comment by KSchopmeyer** [comment]
Thus, the message AuthError:Unauthorized covers a lot of things without giving any real information about where it the protocol it failed.  Normally it gives some indication of there are things like certificate issues from the server (Python SSL library client code does at least some testing against the cert received from the server) and those types of issues do raise exceptions with more information but simple AuthError:Unauthorized is minimialy useful unless it is with a communication where you would know that you have connected to the server before so it then would mean that you have issues just with your authentication (name, password).

**Comment by KSchopmeyer** [comment]
Lets try something simple.  What does

openssl s_client connect https://192.168.1.10:6989

give you? 

It should return info on the protocol, cipher, the server cert, etc.

NEXT Question: Are you sure about the port address.  The standard port address for WBEM servers is

5988 for http
5989 for https.

You appear to be using 6989

**Comment by allen0817** [comment]
> Lets try something simple. What does
> 
> openssl s_client connect https://192.168.1.10:6989
> 
> give you?
> 
> It should return info on the protocol, cipher, the server cert, etc.
> 
> NEXT Question: Are you sure about the port address. The standard port address for WBEM servers is
> 
> 5988 for http
> 5989 for https.
> 
> You appear to be using 6989
> 
> NOTE: In the use of pywbem listener I set the server ports since the indication listener is has not predefined default ports (I set 5000 and 5001 but could be whatever you want.

1.
[root@zsacp7 ~]# openssl s_client -connect 192.168.1.10:6989 -tls1
CONNECTED(00000005)
depth=0 C = US, ST = NY, L = Armonk, O = IBM, OU = CIM Agent, CN = owner, emailAddress = owner@us.ibm.com
verify error:num=18:self signed certificate
verify return:1
depth=0 C = US, ST = NY, L = Armonk, O = IBM, OU = CIM Agent, CN = owner, emailAddress = owner@us.ibm.com
verify return:1
---
Certificate chain
 0 s:C = US, ST = NY, L = Armonk, O = IBM, OU = CIM Agent, CN = owner, emailAddress = owner@us.ibm.com
   i:C = US, ST = NY, L = Armonk, O = IBM, OU = CIM Agent, CN = owner, emailAddress = owner@us.ibm.com
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDeDCCAmACCQDrCE9VIifvzjANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
UzELMAkGA1UECAwCTlkxDzANBgNVBAcMBkFybW9uazEMMAoGA1UECgwDSUJNMRIw
EAYDVQQLDAlDSU0gQWdlbnQxDjAMBgNVBAMMBW93bmVyMR8wHQYJKoZIhvcNAQkB
FhBvd25lckB1cy5pYm0uY29tMB4XDTE5MDcxMTIzMTEyNloXDTI5MDcwODIzMTEy
NlowfjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk5ZMQ8wDQYDVQQHDAZBcm1vbmsx
DDAKBgNVBAoMA0lCTTESMBAGA1UECwwJQ0lNIEFnZW50MQ4wDAYDVQQDDAVvd25l
cjEfMB0GCSqGSIb3DQEJARYQb3duZXJAdXMuaWJtLmNvbTCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAKh5HsBZKq/tzSkvH6G1EUkJc2e264P2TPHzuDJ4
AEWjifWkSwV5tn7aPw84zMdXprzFQt3N/MCYEpZegZWMdpaJ8edzERm5LWtJUunn
q3iU0hFXrG/GqukcXHPUaSlAOFziXk1RF+0pNU+ErodH8/3LLM/2aPORaDkXgJSX
ZKWDASBUowcKH0Nmk6tqYPlhgYvJodK0MXrv2qmUHVscb9fQTXJVTZWk8fxWaTSm
LN2RXi3t7uqiHbn7HRYj5f6mW+TdWgHIow9QQlOhdLvfVS/iKoCVER0aFhU69RZa
xqF/P+T/s/0YElIYfFi2ecXa02JvoIVBUG5pkTrCg5tr0hMCAwEAATANBgkqhkiG
9w0BAQsFAAOCAQEAiG9gc7YlbmTN928n7uBfJwkYP8TmuHgiU6C1yREm51dVGZXF
ceU/ZVNE0RgtVSOBz8Pv+T88yL9sKyY2SAQgCplC8tvK5xRDihSHI0ccx/X/hKEv
Gl1uGjHUyjDYn+qJOwZX7Cr1aOIA+3Y4TCragb9YE5yXDBCPBrF29drTdODwJ3HY
GB2zycpH+g31chxeAEyscWPlV8SgUA1M23iaQ9+BOSZAFN/Lz8Y2pEzw+5W25Ooy
f+dgFlr6MTI17t88xayj8uQV8qa39f/FPiA8aRwVR9aP7oYzgg68fVeUx8G3d9T9
sTqAN4vpNE11uTpNLsggWXpsC7NhrLs4e3nY1Q==
-----END CERTIFICATE-----
subject=C = US, ST = NY, L = Armonk, O = IBM, OU = CIM Agent, CN = owner, emailAddress = owner@us.ibm.com

issuer=C = US, ST = NY, L = Armonk, O = IBM, OU = CIM Agent, CN = owner, emailAddress = owner@us.ibm.com

---
No client certificate CA names sent
Peer signing digest: MD5-SHA1
Peer signature type: RSA
Server Temp Key: ECDH, P-521, 521 bits
---
SSL handshake has read 1636 bytes and written 328 bytes
Verification error: self signed certificate
---
New, TLSv1.0, Cipher is ECDHE-RSA-AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : ECDHE-RSA-AES128-SHA
    Session-ID: 49C16674E6680A34BB3A1075597811E28D9BA38B0A42A8B55E771DDAF7BE3A36
    Session-ID-ctx: 
    Master-Key: 8F24CBC2D23E43929D21779A82F72720AE2DF7AABC4ECCB0E6C33333AFBE34D502E1DC6F25EAE0B24FCD7E46AB68E577
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - c5 3f f2 35 65 9d 1d ca-e5 7c 67 92 e2 eb 90 62   .?.5e....|g....b
    0010 - fd a3 97 e7 a6 fd f7 b1-51 13 c0 75 c1 94 f6 d4   ........Q..u....
    0020 - b3 28 cb da cf c4 de 5f-a5 20 f7 5c ee 38 26 f7   .(....._. .\.8&.
    0030 - 2d 79 65 b3 3a 21 08 c8-6c c1 58 a3 ec 26 f1 17   -ye.:!..l.X..&..
    0040 - e1 68 ab 5c b0 ba 64 59-54 3e 52 e2 ea 46 2c bc   .h.\..dYT>R..F,.
    0050 - 6e 47 9d 83 52 c0 57 cf-7e 97 6b 9c 59 2b 2f 04   nG..R.W.~.k.Y+/.
    0060 - 01 c7 55 5c 8c 85 a0 e5-0f a0 e8 0f 32 59 61 3f   ..U\........2Ya?
    0070 - 87 22 29 1a 34 f9 5f d6-fc a0 5e ec 7f 33 4b 3e   .").4._...^..3K>
    0080 - 1a 7f be eb ae 40 f3 73-4d a6 00 f3 c1 8d df 1a   .....@.sM.......
    0090 - c1 d8 ff c7 cc bc 47 16-bf 63 26 a9 4d 78 e9 f4   ......G..c&.Mx..
    00a0 - a5 65 85 7a 26 c0 c8 e7-85 47 6a 0e f8 2d f4 c0   .e.z&....Gj..-..

    Start Time: 1575595129
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
    Extended master secret: no

2. port is 6989,I have confirmed with the manufacturer and can Telnet.
3.device  is ibm ds8000

**Comment by andy-maier** [comment]
I got hold of a DS8K myself and was able to communicate with its CIM server using pywbem master on Python 3.6 and 3.7 and 2.7 on macOS with OpenSSL 1.1.1d 10 Sep 2019 (I did not test other python versions), using no_verification=True.

**Comment by andy-maier** [comment]
The self-signed certificate should not be an issue when pywbem's no_verification=True.

All I can ask for is:
1. Could you please use the version of pywbem from its master branch?
2. Could you please post the complete exception traceback so we can see where the AuthError is raised?

**Comment by allen0817** [comment]
Python 3.5.7 (default, Nov 14 2019, 10:38:20) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywbem 
>>> conn = pywbem.WBEMConnection('https://192.168.1.10:6989', ('customer', 'cust0mer'), 'root/ibm',None,None,False,True)
>>> res = conn.ExecQuery('WQL', 'select * from IBMTSSVC_StorageVolume')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_operations.py", line 4196, in ExecQuery
    **extra)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 858, in wbem_request
    raise AuthError(response.reason, conn_id=conn_id)
pywbem.exceptions.AuthError: Unauthorized
>>>

**Comment by andy-maier** [comment]
Ok. This occurrence of the AuthError is raised when the server returned HTTP status 401. The SSL/TLS handshake went fine.

When I try it on my DS8K, that is exactly what I get if the userid does not exist or the password is incorrect. But that does not mean it is the only reason this can happen.

You can use this userid and password to log on to the GUI of the HMC of the DS8000, by directing your web browser to `https://192.168.1.10`. The GUI provides a terminal (click on the terminal symbol in the left hand set of icons).

In the DS8K terminal, please verify that the CIM service is enabled:
```
dscli> lsaccess
Date/Time: December 10, 2019 6:37:52 AM GMT IBM DSCLI Version: 7.8.33.131 DS: -
hmc  cmdline wui     modem    cim
=====================================
hmc1 enabled enabled disabled enabled
hmc2 enabled enabled disabled enabled
```
Or, to get some more details:
```
dscli> showaccess hmc1
Date/Time: December 10, 2019 6:24:42 AM GMT IBM DSCLI Version: 7.8.33.131 DS: -
hmc           hmc1
cmdline       enabled
wui           enabled
modem         disabled
cim           enabled
aos           enabled
rsc           disabled
vpn           disabled
port1750      disabled
cim(security) 800131a
gui(security) 800131a
ni(security)  800131a
wui(security) 800131a
```
The line with `cim` is the CIM service, and it must be enabled. A disabled CIM service would result in port 6989 not being responsive, resulting in a connection error or the like. So this is not really your symptom.

Also, you may want to verify the group of the userid you use:
```
dscli> showuser maiera
Date/Time: December 10, 2019 6:26:05 AM GMT IBM DSCLI Version: 7.8.33.131 DS: -
Name         maiera
Group        admin
State        active
FailedLogin  0
DaysToExpire 87
Scope        *
```
I did not yet dig into the permission system of the DS8K, but if your userid is not in the admin group, that would be something to follow up on.

Also, the following shows the policy that is used for your userid:
```
dscli> who
Date/Time: December 10, 2019 6:52:34 AM GMT IBM DSCLI Version: 7.8.33.131 DS: -
Name   Group Policy        Scope Type  Version    Address
============================================================
maiera admin initialPolicy *     DSCIM 5.8.1.19   10.23.1.10
maiera admin initialPolicy *     DSCLI 7.8.33.131 10.23.1.10
maiera admin initialPolicy *     DSGUI 88.33.41.0 10.23.1.10
```
Again, I'm not an expert in DS8K permissions and policies, but let us know if it looks different for your user.

I have tested this with pywbem 0.14.0 on Python 3.6 on MacOS, with a VPN connection to the DS8K, and the following script:
```
$ cat try/ds8k.py 
#!/usr/bin/env python

import pywbem

url = 'https://10.23.1.10:6989'
userid = 'maiera'
pw = 'somepassword'

conn = pywbem.WBEMConnection(url, (userid, pw), 'root/ibm', None, None, None, True)

res = conn.EnumerateInstanceNames('CIM_StorageVolume')
print("EnumerateInstanceNames returned %s instances of CIM_StorageVolume" % len(res))
print("Creation class name: %s" % res[0].classname)

res = conn.ExecQuery('WQL', 'select * from CIM_StorageVolume')
print("ExecQuery returned %s instances of CIM_StorageVolume" % len(res))
```

If I change the password to be invalid, I get the AuthError:
```
(pywbem36) dyn-9-152-220-201:pywbem maiera$ python try/ds8k.py 
Traceback (most recent call last):
  File "try/ds8k.py", line 11, in <module>
    res = conn.EnumerateInstanceNames('CIM_StorageVolume')
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem/cim_operations.py", line 2566, in EnumerateInstanceNames
    **extra)
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem/cim_http.py", line 858, in wbem_request
    raise AuthError(response.reason, conn_id=conn_id)
pywbem.exceptions.AuthError: Unauthorized
```

If userid and password are correct, it displays:
```
$ python try/ds8k.py 
EnumerateInstanceNames returned 142 instances of CIM_StorageVolume
Creation class name: IBMTSDS_Volume
ExecQuery returned 142 instances of CIM_StorageVolume
```
Note that I had to change the class name compared to what you were using, but that is unrelated to the AuthError. If you want to write code that works against multiple implementations, it is always a good idea to work against the CIM classes (e.g. "CIM_StorageVolume") and not against the implementation classes (e.g. "IBMTSDS_Volume" or "IBMTSSVC_StorageVolume").

**Comment by allen0817** [comment]
Thank you very much for your help. I can't get into the command line now. I'll let you know when I get there

**Comment by allen0817** [comment]
hello andy-maier:
    I have installed dscli on my win computer, but I can't use it, and I don't know the port I'm connected to. Can you give me a tutorial.
   thanks!

**Comment by andy-maier** [comment]
I did not use a locally installed dscli. As described above, I used the web browser to log on to the GUI (on the standard port for https, 443). Van you log on to the GUI?

**Comment by allen0817** [comment]
@andy-maier 
Do you have dscimcli  installed？connect ds8000 need install?

**Comment by allen0817** [comment]
I'm connected to the storage ds8k, account number problem.
thank you very much @andy-maier

**Comment by andy-maier** [comment]
OK, glad to hear that. On your previous question: I do not have dscimcli installed, and it is not needed in order to use pywbem for connecting to the DS8K.
