### ISSUE TITLE
Listener uses deprecated SSL construct

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2002]
Listener.py uses the deprecated ssl socket methd

server.socket = ssl.wrap_socket(server.socket,
                                                certfile=self._certfile,
                                                keyfile=self._keyfile,
                                                server_side=True)

This has been deprecated in favor of a similar function that uses SSLcontext.

The current python documentation for ssl.wrap_socket(...) includes the following:

Deprecated since version 3.7: Since Python 3.2 and 2.7.9, it is recommended to use the SSLContext.wrap_socket() instead of wrap_socket(). The top-level function is limited and creates an insecure client socket without server name indication or hostname matching.

SSLContext was added in python 2.7.9

See https://bugs.python.org/issue28022

https://bugs.python.org/issue24372

Note that this may cause problems in support of Python 2.7.9 and earlier.

**Comment by KSchopmeyer** [comment]
We can make this dependent on python version.  So that if SSLContext not allowed wrap from the gobal function.

**Comment by andy-maier** [comment]
Fixed in PR #2103 for master and PR TBD for 0.17.0.
