### ISSUE TITLE
unittest2? Just say NO!

### ISSUE THREAD

**Issue by mcepl** [pywbem/pywbem#2003]
I would think that compatibility with Python 2.6 is overrated these days.

(Sorry for not forking, but I am an openSUSE maintainer and I have too many packages to maintain to spend too much time on any of them).

[Suggested patch](https://github.com/pywbem/pywbem/files/3932910/unittest2-just-say-no.patch.txt)

**Comment by andy-maier** [comment]
I agree that we should avoid the dependency on unittest2, but I'd like to fix that not by abandoning py26 right away, but by using the built-in unittest by default and unittest2 only on py26.

**Comment by mcepl** [comment]
>  not by abandoning py26

Really? I mean, I work for SUSE, so we HAVE some products with python 2.6 still around, but they are all in that state “don’t fix a bug in the product, unless the aircraft career sinks because of it”. Does anybody really install package from the GitHub master on these?

**Comment by andy-maier** [comment]
We don't know whether pywbem is still used on py26. We have at least one user that still uses RHEL 6 but this one uses pywbem on py35. We have already removed py26 support from the upcoming pywbem 1.0.0, but as long as it does not cause unsurmountable difficulties, we don't want to remove it from the 0.x.x versions. The 0.x.x versions are already in bug fix mode.

**Comment by andy-maier** [comment]
In the pywbem master branch (the upcoming 1.0.0 version), unittest2 was already no longer used.

PR #2005 removes the usage of unittest2 in the upcoming 0.16.0 version except when on py26.

**Comment by mcepl** [comment]
Also, while on the topic of deprecated libraries. You know that ``yamlordereddictloader`` has been deprecated and it should be replaced by https://github.com/Phynix/yamlloader, right?

**Comment by andy-maier** [comment]
No, I did not know that. Thanks for pointing it out! I have created issue #2008 for that.
