### ISSUE TITLE
MOF parsing: Qualifier declaration does not apply flavor defaults

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#203]
In the standard qualifiers.mof (CIM Schema 2.45), the EmbeddedInstance qualifier is one example of a qualifier that is defined without explicit flavors, relying on the defaults:

    Qualifier EmbeddedInstance : string = null, 
        Scope(property, method, parameter);

When the MOF compiler parses this qualifier declaration, the resulting CIMQualifierDeclaration object contains `None` for the flavors that have not been specified. While that is formally correct according to how the interface is defined (`None`means "information not available"), it is not very practical.

**Proposed solution:** Set the flavors to the DSP0004/DSP0201 defined defaults, if not specified in the qualifier declaration MOF (e.g. in `_build_flavors()` in `mof_compiler.py`).

**DIscussion:** Proposed solution needs discussion.

Considerations:

* Should the defaults be applied at this level, vs. the object just shows exactly what was specified, leaving application of defaults to some higher level?

**Comment by andy-maier** [comment]
We tend to think the defaults should be set on object creation (not applied on object use).
Karl volunteers to do this as part of another fix.

**Comment by KSchopmeyer** [comment]
I want to discuss briefly to be sure we agree before I finish this one.

**Comment by andy-maier** [comment]
We first need to address issue #202, and then come back to this one to fix whatever it takes in the MOF compiler.

**Comment by andy-maier** [comment]
We agreed to do this in 0.9.0, and what we do is to move the code that applies to default values to the flavors, from the MOF compiler into the CIMQualifierDeclaration class.

**Comment by KSchopmeyer** [comment]
I tried again and is really messy to try to use the class for defaults.  The default mechanism in the compiler creates defaults for the input keywords, not for the actual flavors. Further, we would have to make this a class level thing to make it usable then since we do not have the instance of the CIMQualifierDeclaration class available at that point.

Once again, I tend to believe that we should not touch this until we actually do a repository.

**Comment by andy-maier** [comment]
I'm ok with leaving it as it is, but then we should document that `CIMQualifierDeclaration` shows the attributes as specified in MOF, not including the application of DSP0004 defined defaults.

**Comment by andy-maier** [comment]
Karl has prepared issue #450 to address this.
