### ISSUE TITLE
requests proxy support

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2040]
The requests package supports proxies: https://2.python-requests.org//en/latest/user/advanced/#proxies

There has been one user request by @andy-ypsilon for that (see PR #2023).

This could be done by adding an optional parameter to WBEMConnection(), which is passed on to requests.

**Comment by andy-maier** [comment]
We agreed to pursue this. If possible, with an additional optional parameter.

**Comment by andy-ypsilon** [comment]
After adding a property called 'proxies' to WBEMConnection an using it within the Requests session I was able to connect to a WBEM Server with https via a SOCKS5 proxy.
This gives me the flexibility to use a proxy as an optional feature for each connection.
Its working for me, but I'm looking forward to have it build into the next release.
If I can support somehow regarding this feature come back to me.

**Comment by andy-maier** [comment]
Thanks for the offer, but in this case, I'd like to do it myself. You are welcome to review it once the PR is up.

**Comment by andy-maier** [comment]
PR #2082 adds proxy support.
@andy-ypsilon Could you please review that PR and test it in your proxy environment? Thx!!

**Comment by andy-maier** [comment]
@andy-ypsilon Hi Andy. Karl tried to test the code, but was not successful. See his update to PR #2082. Could you please review the code and try it against your proxy?
