### ISSUE TITLE
MOF parser: Qualifier flavor toinstance set to true if tosubclass is true

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#205]
In `_build_flavors()`, there is code that sets the `toinstance` attribute to True if `tosubclass` ends up being True. Note that MOF as defined in DSP0004 does not provide a way to set the toinstance flavor - it was only ever a CIM-XML concept, not a metamodel or MOF concept.

Consistent with the deprecation of toinstance in DSP0201, I suggest to set the `toinstance` attribute to `None` when parsing MOF.

Considerations:
* Does this affect implementations that support ad-hoc declaration of qualifier types on use (WMI), or implementations that support instance-level qualifiers (WMI)?

**Comment by andy-maier** [comment]
Karl has a fix. Also, there is another issue open on this problem. Reassiging to Karl.

**Comment by KSchopmeyer** [comment]
Fixed in pr# 317

**Comment by andy-maier** [comment]
PR #317 has been merged. Closing this issue.
