### ISSUE TITLE
CIM-XML: TYPE attribute of KEYVALUE is required in DTD 2.4

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2052]
DSP0203 2.4.0 changed the TYPE attribute of KEYVALUE to be required. This is an incompatible change.

When creating CIM-XML, pywbem needs to ensure that the TYPE attribute is present to satisfy DTD 2.4. When parsing CIM-XML, pywbem should tolerate an absent TYPE attribute for compatibiity to DTD 2.3.

**Comment by andy-maier** [comment]
The goal to always set the TYPE attribute in KEYVALUE elements when creating CIM-XML can be fully achieved only when the CIM type is stored in the keybindings of the CIMInstanceName objects. Ensuring that would create an incompatible change for users of pywbem because today, a keybinding can be created without specifying any type information. The high level type information used for the VALUETYPE attribute of KEYVALUE can be derived from the value, but the specific CIM type cannot be derived from the value for numeric types.

**Discussion point:** Should we change the keybindings in CIMInstanceName to store CIM type information?

**Comment by andy-maier** [comment]
PR #2059 addresses this for string and boolean key types, with the limitation of not addressing it for numeric key types.

**Comment by KSchopmeyer** [comment]
We propose to improve this by providing an optional CIMType parameter for at least numeric key bindings that would specify the CIMType.

**Comment by andy-maier** [comment]
PR #2059 addresses this in addition for keybinding values specified as pywbem.CIMInt/CIMFloat objects. keybinding values specified as Python int/float continue not to set the TYPE attribute.
