### ISSUE TITLE
Refactor pywbem mock to separate components

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2062]
We propose to refactor the mocker to:

a. Separate it into the components that would conceptually represent a WBEM server including:

1. **repository store class.** This component will manage the data store itself including adding, modifying, deleting CIM classes, instance, qualifier declarations and managing the creation/deletion/enumeration of the namespaces represented in the  data store.  The objective of this component is to:
a. Physically store the objects (CIM classes, instances,qualifier declarations and namespace information)
b. Provide APIs so that the server repository class and providers can add items to the store, and retrieve items from the store.  
c. Separate the store implementation itself (ex. current dictionaries or possible databases in the future from the logical repository.
d. Provide validation of the objects stored to assure the data in the store is valid.

This API is effectively what exists in the mof_compiler BaseRepositoryConnection class today with the addition of the namespace management methods.  This replaces the current _mockmofwebemconnection.py module in pywbem_mock.

 2. **server repository class** - The set of APIs that represent  the calls to the what is conceptually a WBEM server repository. This is all of the methods in cim_operations except for InvokeMethod, pull operations, (and possibly query) which we do not implement within  a repository. It also adds the methods for managing namespaces. This class will manipulate objects in the datastore class using the APIs in that class and manage the testing/manipulation of incoming cim operations to commucate between the objects in the data store and the user for repository objects.  This will include most of the methods currently contained in the mock calls in _wbemconnection_mock.py
    
3. **wbem server class**.  This class represents the server which separates requests into providers and the repository.  It include all calls defined in cim_operations.py. Without any providers, it simply passes operations on to the repository class.  TODO sort out issues of the InvokeMethod implementation which should be part of the providers whereas today they are sort of part of the repository.  This is the class that will be surfaced with the definitons that are today as FakedWBEMConnection and is the class used by the user to define the wbem connection and to insert data into the repositoy the repository.
    
4. **MOCKER**. The mocker which mocks the imethod_call and calls the appropriate server methods  This class would include the mock code and the implementation of each of what is now the fake_... methods that simply call their WBEM server class counterparts. For example _fake_enumerateclasses would simply call the WBEMServer.EnumerateClasses with the parameters defined by cim_operations.py API. It will also map the responses into the form required by imethod_call so that the wbem_server class returns values the same as the cim_operations.py methods.

5. **Provider class.** This class that would provide the API for implementing providers.  This will provide the template for any future provider implementations.  This is a base class from which individual providers could be built.

**Comment by andy-maier** [comment]
Partly addressed by PR #2068

**Comment by andy-maier** [comment]
Completely addressed by PRs #2080, #2132, #2136, #2186, #2199, #2202, #2211, #2225, #2221, #2234.
