### ISSUE TITLE
pywbem_mock add code for deprecated iq and ico per DSP0200

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2065]
We have not considered that iq and ico are deprecated in DSP0200 for get_instance, etc. We could  set up a default to ignore these parameters for the operations in which they are deprecated and we should/could ignore them. We need to document our behavior in relation to the spec.

**Comment by KSchopmeyer** [comment]
From DSP0200

The use of the IncludeQualifiers parameter is DEPRECATED and it may
be removed in a future version of this document. The definition of IncludeQualifiers is ambiguous
and when this parameter is set to true, WBEM clients cannot be assured that any qualifiers will be
returned. A WBEM client should always set this parameter to false. To minimize the impact of this
recommendation on WBEM clients, a WBEM server may choose to treat the value of
IncludeQualifiers as false for all requests.

In version 1.4 of this document, the IncludeClassOrigin parameter is
DEPRECATED. A WBEM server may choose to treat the value of IncludeClassOrigin parameter as
false for all requests, otherwise the implementation shall support the original behavior as defined in the rest of this paragraph. If the IncludeClassOrigin input parameter is true, the CLASSORIGIN
attribute shall be present on all appropriate elements in each returned Instance. If it is false, no
CLASSORIGIN attributes are present.

**Comment by andy-maier** [comment]
Ideally, our mock support would be configurable to show either behavior. After all, it is supposed to represent a WBEM server, and if the WBEM server can behave either way, our mock support should too.

**Comment by andy-maier** [comment]
Addressed by PR #2257, which does provide the ability to configure the behavior. This resolves the discussion point above.
