### ISSUE TITLE
Add tocimxmlstr() to all CIM object classes

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#208]
As a result of the discussion in issue #195, I suggest to add a new method to all CIM object classes, that returns a unicode string of the CIM-XML representation of the CIM object. It basically invokes the extsting `tocimxml()` method on the object, followed by `toxml()`, or `toprettyxml()`, depending on the value of its boolean `pretty` parameter.

The existing `tocimxml()` methods would remain part of the external interface, in case someone needs to do more postprocessing on the output (like aggregating multiple results; this is done much better at the DOM level).

**Comment by KSchopmeyer** [comment]
I agree with this idea.

**Comment by andy-maier** [comment]
I submitted PR #212 for this one. I ended up with a slightly different interface: As I learned that the `toprettyxml()` function has an `indent` parameter, I exposed that and also used it to control pretty vs no-pretty.
