### ISSUE TITLE
under https m2crypto, the client timeout code is disabled in cim_http

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#215]
With pr#376 for issue #363 we are now capable of demonstrating the exact behavior of timeout over a wide range of server delayed responses and timeouts.  It appears that the modifications to exceptions have fixed the issues we found here earlier.  The new openpegasus tests seem to demonstrate that time timeout works now for http and https over a wide range of timeouts and server delays so I propose closing this as fixed

Note that even the issue of very uncertain timeout time no longer exists since the new test against open pegasus demos that the timeout now appear to occur at about the correct time.

The one remaining test might be to confirm this with wbemcli which is where the original issues were found.

**Comment by KSchopmeyer** [comment]
After enabling this we tested the timeout against a version of Pegasus that does not return so causes a client timeout.

1. With cimcli

cimcli Pegasus Exception: connection timed out. Cmd = ec Object = 

At about the correct timeout. Works for both http and https

2. Pywbem 2.7

2a. with HTTP

`
>>> gc = gc('CIM_ManagedElement')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "./wbemcli", line 603, in GetClass
    PropertyList=pl)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 4368, in GetClass
    **extra)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 748, in _imethodcall
    debug=self.debug)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 778, in wbem_request
    break
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 153, in __exit__
    "socket after %.0fs." % duration_sec)
TimeoutError: The client timed out and closed the socket after 4s.
`

2b with https:

**Comment by andy-maier** [comment]
Reopening this issue, because PR #360 only addressed a first part of it.

**Comment by andy-maier** [comment]
The remaining part is to document that with HTTPS, the actual timeout may be significantly larger than the specified timeout.

**Comment by KSchopmeyer** [comment]
Create second PR with doc change to identify problem withm2crypto

**Comment by andy-maier** [comment]
I think in the doc update, we should not mention M2Crypto, but instead Python 2.x.

**Comment by KSchopmeyer** [comment]
Question: Where do we document this and other limitations?

**Comment by andy-maier** [comment]
In the method that has the timeout parameter.

**Comment by andy-maier** [comment]
Partly fixed; the remaining work is to double check the documentation about the possibly longer time it takes to time out.

**Comment by KSchopmeyer** [comment]
Agreed. We will close as complete
