### ISSUE TITLE
wbemcli add the function for prettyprint of xml

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#217]
We have the wrong function definition for the prettyprint of xml in the h() definitions.

if we are to use the prettyprint the function is toprettyxml() whereas the single line is toxml()

However, it will probably all be resolved by the the new tocimxmlstr so maybe the alternative is to
just supply that that as the definition in the help.

**Comment by andy-maier** [comment]
Fixed that in an update to PR #208.
