### ISSUE TITLE
Compile  DMTF schema, ordering of classes being compiled

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2223]
In the DMTFSchemaClass build_schema_mof method, the order class pragma statements are placed into the output string is based on the order of the leaf class list. The DMTF  orders this file of include pragmas to avoid conflicts and dependency issues. The fact that we change the order  has not proven to be an issue to date but there could be cases where the user is inputting more than the leaf classes
and could cause a conflict.  The output pragma list (i.e. the list of classes to be compiled should be in the same order as the list in the original cim_schema file.

Note that if the user only puts leaf classes into the list there should never be an issue since the pywbem MOF compiler handles the dependencies but if the user were to include none-leaf classes in the list it could cause compile issues.

The fix is to output the new pragma list with the classes in the same order as the original list.

I propose that this change NOT be pushed back to earlier releases.

**Comment by andy-maier** [comment]
Fixed in PR #2224
