### ISSUE TITLE
Mocker, eliminate multiple convience methods that are the same thing.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2229]
If the atttribute is not public and not documented that we are reaching for with the convience method, we should probably make it public.

**Comment by KSchopmeyer** [comment]
Here is my first list of the convience methods that can be called directly from conn but are implemented in other classes

|  Name in FakedWBEMConnection |  implementation class and method name |  Used in |
|-----------------------------------------------|--------------------------------------------------------|-------------|
| register_provider                             | ProviderRegistry.register_provider           |  
| namespaces                                    | mainprovider.namespaces                       |
| _get_qualifier_store                         | baseprovider.get_qualifier_store              |
| _get_class_store                              | baseprovider.get_class_store                  |
| _get_instance_store                         | baseprovider.get_instance_store             | self, test_wbemconnection_mock.py |
|  add_namespace                             | baseprovider.add_namespace
|  remove_namespace | baseprovider.remove_namespace 
| interop_namespace_names  | baseprovider.interop_namespace_names
| is_interop_namespace | baseprovider.is_interop_namespace
| find_interop_namespace | baseprovider.find_interop_namespace | self, namespace provider |

**Comment by KSchopmeyer** [comment]
Faked wbemconnection

1. Remove the underscored functions.

2. Change interop_namespace_names() to a property

3. Make the public instance attributes provate.

**Comment by andy-maier** [comment]
Addressed by PR #2245.
