### ISSUE TITLE
User provider implementation of all methods

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2237]
Today a user-provider must implement all of the methods defined in its default provider.  Thus, the user_provider for instancewrite must implement CreateInstance, ModifyInstance, DeleteInstance or an exception is issued upon calling the methods.

An alternate would be to allow the provider to only implement a subset and put a try block around the call to the provider, falling back to the default.

Since calling the default if the user does not want to do anything special in the user-defined provider for some of the methods (just call the superclass with the same parameters) I did not worry about it but in documentation I began to think of what is simplest and most logical and concluded that I am not sure.

DISCUSSION

**Comment by andy-maier** [comment]
We agreed that implementing a subset of the methods and falling back to the default implementation should be legal.

Addressed in PR #2238.
