### ISSUE TITLE
Mocker: Review ProviderDispatcher

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2244]
Karl wants to take a look at the structure of the ProviderDispatcher, for two reasons:
- Simplification potential.
- Find out why it has no instance attribute for the MethodProvider to use as a default, but the FakedWBEMConnection does have one.

**Comment by KSchopmeyer** [comment]
The reason it has no connection to MockProvider is that the only thing MockProvider does is to create an exception and we did that in the provider dispatcher.

**Comment by andy-maier** [comment]
Addressed by PR #2251
