### ISSUE TITLE
MOF Compiler changes default namespace of conn

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2247]
Here is one that has been hanging around a long time and only surfaced when we started compiling into multiple namespaces now.

The compiler itself sets the namespace being compiled into as the conn.default_namepace.

See _mof_compiler line  MOFWBEMConnection Class, 2675,

        self.parser.mof = mof
        self.parser.handle.default_namespace = ns

where ns is an argument of compile_string(...) and set into the parser.handle,

NOTE: The handle is actually the MOFWBEMConnection or WBEMConnection or FakedWBEMConnection  which means that this is changing the
default_namespace in the WBEMConnection.

This new default namespace is used heavily through the compiler.

**Comment by KSchopmeyer** [comment]
The compiler uses this namespace (parser.handle.default_namespace) in a number of places within the compiler methods including:
1.  p_mp_createClass - Get current namespace
2. p_mp_setQualifier - Get current namespace
3. p_compilerDirective "include" Get current namespace
4. p_compilerDirective "namespace" - Sets this value to the namespace pragma value
4. p_qualifier -  to locate the qualcache
5. p_instanceDeclaration - namespace append classname to p.parser.classnames[ns]

6. MOFWBEMConnection. compile string - set here from ns input

This also ties to class MOFWBEMConnection 
1. _getns if self.conn is None to return the current namespace
2. _setns to set self.conn.default_namespace based on a value

NOTE: It also sets in in  p_compilerDirective 'namespace'

**Comment by andy-maier** [comment]
Addressed in PR #2254.
