### ISSUE TITLE
MOF_Compiler and pragma namespace 

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2256]
While MOF and the pywbem MOF compiler support the existence of a pragma namspace statement, the implement is incomplete.

1. the compile_file and compile string REQUIRE a namespace to compile mof.

2. If the namespace pragma is used, must it be predefined?  I don't think that the wbem server behavior is clearly defined in the case what the first indication of a new namespace is a SetQualifier or CreateClass.  To behonest I need to review the mocker also for its behavior.

Actually I am not really sure what the rules on use of this pragma should be.

**Comment by andy-maier** [comment]
DSP0004 says: "This pragma is used to specify a Namespace path.".

First, I think we should ignore any host on the pragma namespace value. The current code assumes the pragma namespace value is directly the namespace name, which according to this definition is not necessarily the case.

Second, regarding the namespace on the pragma namespace value, we need to decide how it relates to the namespace argument of compile_file() and compile_string(), i.e. which of the two definitions has precedence. The current code uses the namespace argument of these methods as the initial target namespace, which is changed for each pragma namespace encountered, from that point on. I think that is a reasonable approach. The only thing we might want to think if is to add a flag to these methods that causes pragma namespace to be ignored, but I'm not even sure we need that.

**Comment by KSchopmeyer** [comment]
There is one question here.  Must the namespace already exist in the target environment for the namespace pragma to be valid.

Andy feels it must exist.  Karl is not sure of current behavior.

What is current behavior at least in mock but I have no problem with the proposal that it already exist.

**Comment by KSchopmeyer** [comment]
I agree that we do not need a flag in the compile_mof_... methods to override the use of  namespace pragma.

**Comment by KSchopmeyer** [comment]
Actions: Correct the issues we agreed to above.  For the host name in the namespace pragma, If it exists, we error out. 

Fintally we agree that there are ambiguities in the compiler specification with respect to the namespace pragma and we will document how it really behaves in pywbem.  We will not make any code changes.
