### ISSUE TITLE
Remove deprecated functionality

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2263]
Good opportunity to remove these with major version change

**Comment by andy-maier** [comment]
Agreed.

**Comment by KSchopmeyer** [comment]
Question? Should we make a pass and remove most of the deprecated capabilities before 1.0.0 release rather than just these two?

**Comment by KSchopmeyer** [comment]
Karl will make a more general list of deprecated items by Friday.

**Comment by KSchopmeyer** [comment]
Here is the list of deprecations I found in the code

  Most of them are the warnings.warning( DeprecationWarning ..) method call.

1. nocasedict. The code for __lt__ etc. creates type error but module
docstring says deprecated.  Change the docstring to not supported. This is just a documentation issue.

2. cim_operations - Instances of warning.warnings DeprecrationWarning method calls

   a. url property setter.
   b. WBEMConnection creds property setter
   c. x509 property setter
   d. ca-certs property setter
   e. no_verification property setter
   f. method_call
   h: imethod_call
   f. timeout setter.
   g. operation_recorder property

3. _cim_pbj.py - Instances of warning.warnings DecrationWarning
   a. class CIMInstance - PropertyList setter
   b. class CIMInstance - pywbem.tocimxml() None value
   c. class CIMInstance - tomof() - indent parameter deprecated.
   c. byname - Function deprecated.

**Comment by andy-maier** [comment]
My vote is for all of these deprecations (items 2 and 3) to remove them.

DISCUSSION

**Comment by KSchopmeyer** [comment]
Agreed

**Comment by andy-maier** [comment]
Addressed as proposed, in PR #2274.
