### ISSUE TITLE
Move pywbem_mock as a sub-package under pywbem?

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2268]
Issue #2260 brought up the question should we change the current `pywbem_mock` package to become a sub-package of `pywbem`, i.e. `pywbem.mock`.

Advantages:
- 1 Pypi package creates 1 Python package (and not 2 as currently).
- If we end up installing the tests as an extra, we could leave the `tests` subtree in one place and just move it under `pywbem`.

Disadvantages:
- We could not split out `pywbem_mock` into its own Pypi package if we wanted.
- We would require each user of pywbem to always have the mock support in their Python namespaces even when not used. Reason is the principle of least surprise, i.e. we want to allow `from pywbem.mock import ...` without having a prior `import pywbem.mock`.

If I think about it, my vote is slightly on the side of not doing this.

DISCUSSION

**Comment by KSchopmeyer** [comment]
I am leaning to not doing this one.  Biggest issue is that this becomes part of the single package and only a small percentage of pywbem users use the mock also

**Comment by andy-maier** [comment]
Ok, then we lean both on the same side :-). CLosing it as wont do.

**Comment by KSchopmeyer** [comment]
My vote is also on the side of not doing this.  Talked it through with Mike Walker and he agrees. The big negative is having to have the mock support in their python namespaces even when not using it.
