### ISSUE TITLE
Changes.rst. dropped the changes frompywbem versions 0.15 - 0.17

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2272]
Pywbem 0.17.0 dropped the changes for 0.15.0, 0.16.0 and n 0.17 in the development of changes for 1.0.0 in changes.rst

**Comment by KSchopmeyer** [comment]
Went through once and found what may be a few missing items.  Want to recheck before telecon.

It would probably be  good to add note that 17,16,15 change defs are integrated into 14 because that is when 1.0.0 was started.

**Comment by andy-maier** [comment]
All the time since we started 1.0.0 from 0.14.x, we rolled changes back, not forward. So I suspect that what you found are things that were only needed on the old version (e.g. because of Python 2.6). But let's double check.

**Comment by andy-maier** [comment]
PR #2281 adds a statement that 1.0.0b1 includes all fixes since 0.14.0 up to 0.17.2.

**Comment by KSchopmeyer** [comment]
I am going through a second time now.

**Comment by KSchopmeyer** [comment]
These are the one I found that are in the 17,16,15 changes.rst but not the 1.0.0.
0.17
Cleanup:
    Renamed all sub-modules within the pywbem namespace so they are now private 

0.16.0
Bug Fixes
"Fixed handling of Unicode string"
Enhancements
"Removed the dependency on unittest2"

0.15.0
Deprecations

The wbemcli command has been deprecated.

**Comment by andy-maier** [comment]
Needs to be worked into PR #2281 .

**Comment by andy-maier** [comment]
As proposed in PR #2281 , change log entries for 0.15, 0.16 amd 0.17 were added.

**Comment by andy-maier** [comment]
Addressed in PR #2281.
