### ISSUE TITLE
Remove instead of deprecate in experimental mock support

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2284]
As of the current master (particularly with PR #2281 and #2283 merged), we are deprecating:
* the `FakedWBEMConnection.compile_dmtf_schema()` method in favor of a new method `compile_dmtf_classes()`, and
* the `DMTFCIMSchema.schema_mof_file` property in favor of a new property `schema_pragma_file`.

Since the mock support is still experimental, it does not seem right to start the new major version 1.0.0 with deprecated functionality within an experimental feature. Instead, the functionality should be removed.

On the other hand, this method and this property were introduced in pywbem 0.13.0, and they likely have current users.

DISCUSSION

**Comment by andy-maier** [comment]
PR #2286 removes the deprecated functionality.

Should we decide to leave the functionality in as deprecated, the following changes should be done instead:
* Fix use of incorrect method name in change log: `compile_dmtf_classes()` -> `compile_dmtf_schema()`.
* Change implementation of the deprecated `compile_dmtf_classes()` to use the recommended replacement of `DMTFSchema()` and `compile_dmtf_classes()`.

**Comment by KSchopmeyer** [comment]
I was going to propose that we keep for the beta and remove between beta and final release. At least compile_dmtf_schema is used in pywbemcli so we have one more change before beta release. Also I know they are used in some of the mock profiles being developed. By leaving the deprecated in for the beta we make the transition easier for users.

**Comment by andy-maier** [comment]
Then we should do the changes I suggested above for the beta.

**Comment by andy-maier** [comment]
PR #2286 targeting 1.0.0 final removes the method and property that was deprecated in 1.0.0b1.
