### ISSUE TITLE
UDSConnection support

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2287]
The current master version of pywbem has three classes for UNIX Domain Socket support:
* `pywbem.PegasusUDSConnection`
* `pywbem.SFCBUDSConnection`
* `pywbem.OpenWBEMUDSConnection`

They are referenced in the documentation and but they are not defined there.
They are are public in the pywbem namespace.
Their implementation passes a UDS file path for the WBEMConnection url parameter, but the WBEMConnection class does not describe this possibility.

Do we believe these classes are still working now that the 'requests' package is used?
Can we test them?

DISCUSSION

**Comment by KSchopmeyer** [comment]
I can test with OpenPegasus.

**Comment by andy-maier** [comment]
We discussed this and decided to drop this functionality without further investigation.

**Comment by andy-maier** [comment]
Addressed in PR #2347
