### ISSUE TITLE
Duplication of incompatible changes between summary and detail sections

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2294]
Some of the items in these sextions are pretty much the same between the summary and detail sections.

DISCUSSION

**Comment by KSchopmeyer** [comment]
I agree.

Generally I think we should make the summary very short with no explanation just the key words so the reader can determine if something might apply.

1. One sentence.
2. Create one item with subitems for the deprecated functionality/methods/etc.

Then maybe even add to the details about what they should do if they  do find they are using the deprecated functionality.  Remember that this may be user level and the actual error is in a package they are just using.

NOTE: I had this all written here and mishit a key and the whole thing disappeared so starting over.

**Comment by KSchopmeyer** [comment]
Proposed changes to summary section:

*Summary of incompatible changes:*

* Removed Python 2.6 support.

* Migrated pywbem to use the 'requests' Python package for HTTP/HTTPS pywbem
  client to WBEM server communication. This removed support for UNIX sockets
  based connections to local WBEM servers as well as the non-standard 'OWLocal'
  and 'Local' authentication schemes, and changed some of the behavior of
  HTTPS-related init parameters of `WBEMConnection`.

* Removed the deprecated `verify_callback` init parameter of `WBEMConnection`.

* Removed the `**extra` keyword arguments from `WBEMConnection` operation
  methods.

* Removed the deprecated ordering for `NocaseDict`, `CIMInstanceName`,
  `CIMInstance` and `CIMClass` objects.

* Removed the deprecated ability to set the following properties of class
  `WBEMConnection`: `url`, `creds`, `x509`, `ca-certs`, `no_verification`,
  and `timeout`.

* Removed the deprecated methods `method_call()` and imethod_call()` and the
  deprecated property `operation_recorder` from class `WBEMConnection`.

* Removed the deprecated property `property_list` and the same-named init
  parameter from class `CIMInstance`.

* Removed the deprecated ability to support a value of `None` for
  `pywbem.tocimxml()`.

* Removed the deprecated `indent` parameter of `CIMInstance.tomof()`.

* Removed the deprecated internal function `pywbem.byname()`.

* Removed the deprecated function `pywbem.tocimobj()`.

* Removed the deprecated `wbemcli` command.

* Made the `MOFWBEMConnection` class (support for the MOF compiler) internal.

* Exception changes:

  * Changed the exception behavior of the MOF compilation methods of the
    `MOFCompiler` and `FakedWBEMConnection` classes to no longer raise
    `pywbem.CIMError`, but to raise exceptions derived from a new base
    class `pywbem.MOFCompileError`.

  * Changed the type of exceptions that are raised by methods of
    `pywbem.ValueMapping` for cases where the value-mapped CIM element has
    issues.

  * Changed the `pywbem.CIMError` exceptions that were raised by pywbem code in
    several `WBEMServer` methods to now raise the new exception
    `pywbem.ModelError`.

  * Added a new exception `pywbem.HeaderParseError` derived from
    `pywbem.ParseError` that is used to report HTTP header issues in the CIM-XML
    response.

* Made all sub-namespaces within the pywbem namespace private, except for
  pywbem.config. Using these sub-namespaces was already deprecated.

* Mock WBEM Server (experimental):

  * Replaced the `add_method_callback()` method  and the `methods` property in
    `FakedWBEMConnection` with user-defined providers.

  * Removed the `conn_lite` init parameter of `FakedWBEMConnection`.

  * Changed the logging behavior of the MOF compilation methods of
    `FakedWBEMConnection` so that the default is for the caller to display
    exceptions rather than the MOF compiler logger.

  * Changed the behavior for the IncludeQualifiers and IncludeClassOrigin
    parameters on the GetInstance and EnumerateInstances operations of the
    mock WBEM server.

**Comment by KSchopmeyer** [comment]
After working through the whole section, I found it was less error prone and easier to create a new pr. Uploading that pr now.

**Comment by andy-maier** [comment]
ok

**Comment by andy-maier** [comment]
Addressed in PR #2295 .
