### ISSUE TITLE
Jupyter notebook mockwbemserver.ipnb incorrect

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2310]
This notebook reflects the api to load a schema before pywbem 1.0.0.  It needs to be updated to show both apis.  The code in the wbemserver_mock.py should suffice.

Since the old methods are not yet removed in 1.0.0b, this need not be incorporated immediatly.

**Comment by andy-maier** [comment]
There is no mockwbemserver.ipnb notebook, but I think the comment applies to the pywbemmock.ipnb notebook.

In that notebook, I could identify the following elements that need to be updated:
* Use of `compile_dmtf_schema()` -> Change to `DMTFCIMSchema()` plus `compile_schema_classes()`.
* Definition and registration of method provider via `add_method_callback()` -> Change to new method provider class and registration.

**Comment by andy-maier** [comment]
PR #2325 addresses this issue.
