### ISSUE TITLE
pywbem_mock OpenExecQuery tests params before valid namespace

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2313]
Minor issue but generally we test namespace first and this causes fail of one of our tests in pywbemtools.

**Comment by andy-maier** [comment]
There is no `OpenExecQuery()`. I assume you talk about `OpenQueryInstances()`?

Its implementation in the main provider first calls `_validate_open_params()` and then invokes the non-pulled operation which checks the namespace. I assume that is the issue you describe.

BTW, that is done for all other pull operations in the main provider, too.

Proposal for any operation we implement in the main or default providers:
* namespace should be checked for existence first
* then the class (for operations that operate on a class) or instance (for operations that operate on an instance) should be checked for existence
* then the other parameters

DISCUSSION

**Comment by andy-maier** [comment]
Also, I think the `_test_pull_operations_disabled()` method should be renamed to something like `_validate_pull_operations_enabled()` to better call out what it does.

**Comment by andy-maier** [comment]
We agreed to go for the first proposed solution, i.e. to add namespace validation after the call to `_test_pull_operations_disabled()`.

**Comment by andy-maier** [comment]
On the proposal further up: It turns out that the precedence for status codes defined in DSP0200 defines invalid namespace to come before invalid parameters, so the agreed upon change is in sync with DSP0200 (and my earlier proposal was not).

PR #2321 addresses this issue.
