### ISSUE TITLE
pywbem_mock enumerate classes --di Very slow

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2314]
This method is hundreds of times slower with pywbem 1.0.0b1 than with pywbem 0.17.

Confirmed that the issue is that in method get_subclassnames we are using the cim repository iter_value() with the copy parameter set to its default which is True.  This means we are creating many worthless copies.  In particular since the only thing we are using from the value is the classname string.

**Comment by andy-maier** [comment]
Fixed in PR #2315
