### ISSUE TITLE
Mock: Add option to disable class and qualifier operations

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2317]
Since there are WBEM servers that do not support class or qualifier operations (notbably SFCB), it might be useful to have an option on the mock support to disable class and qualifier operations, in order to behave like that and to verify that user code (or pywbem code) does not use them by accident. If disabled, these operations would return CIM_ERR_NOT_SUPPORTED.

The mock repository would still have the classes and qualifiers.

DISCUSSION: Should we do that.

**Comment by andy-maier** [comment]
We agreed this should be done.

**Comment by andy-maier** [comment]
We agreed we should do it, but move it out of this release.

**Comment by KSchopmeyer** [comment]
Note that we have an issue here in that the environment must allow building the classes, etc. but then not allow the user to createclass, etc.  Maybe best is we use the scripting itself to allow creating a repo and then disabling update.

**Comment by andy-maier** [comment]
I have second thoughts on this proposal and would like us to revisit this. Nobody has asked for this so far, and I think we should not implement features just to be perfect. **DISCUSSION**

**Comment by andy-maier** [comment]
We discussed and agreed to drop this.
