### ISSUE TITLE
unittestextensions.py.  Two functions do exactly the same thing

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#232]
The functions assertRegexpContains and assertRegexpMatches do the same thing. They both call re.search.  This means that they are looking for the pattern in a multiline string.

Note that unittest uses assertRegexpMatches but could not find assertRegexpContains.

We actually use the re.matches in some of the unittests where it is looking for a specific pattern on the first line, not just anywhere in the file. The mof output tests.  Actually there are probably much better ways of doing these tests but they exist for the moment.

**Comment by andy-maier** [comment]
Looking at the two functions, it seems to me that the intention was that `assertRegexpMatches()` should invoke `re.match()` and that it was simply never changed to that, after having been copied from `assertRegexpContains()`...

Both methods are invoked in `test_cim_obj.py`, in the current master branch. The invocations of `assertRegexpMatches()` all have a `^` at the begin of the regexp, which is what you would normally do with match.

A `make test` on the master branch with `assertRegexpMatches()` changed to invoke `re.match()` runs fine.

So I'll create a PR with that change and propose to accept it as the solution to this issue.

**Comment by andy-maier** [comment]
Created PR #235 to fix this as described above.

**Comment by KSchopmeyer** [comment]
It was not a big deal and I agree with your proposal
