### ISSUE TITLE
User providers still too complicated

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2326]
If i look at the default implementations of user-defined instance write providers in `_instancewriteprovider.py` and at our examples for user-defined method providers (e.g. in the jupytr notebook in PR #2325 ), I think the code there is still to complicated. A lot of that is tied to the fact that the provider does a lot of checking.

I suggest that we move any checking that can be done generically, into the provider dispatcher. The default implementations of user-defined instance write providers in `_instancewriteprovider.py` can be simplified accordingly. Also, i think the default method provider in `_methodprovider.py` can get more code to show what a provider would typically do, and then still raise the same error as before, just more in the place where the actual code would be. I have some ideas on how that could be done.

**Comment by KSchopmeyer** [comment]
1. Remember that there really is no default methodprovider.

2. However, for the method provides we can move the validity tests for the class/instance into the providerdispatcher so that the user is assured both exist before they get called.

3. Finally, we could actually test that the method exists in the defined class before passing the call to the provider.

**Comment by KSchopmeyer** [comment]
I checked the documentation in MethodProvider.py and it states:

   The input parameters for the user defined invoke_method InvokeMethod will
   have been already validated in
   :class:`~pywbem_mock.ProviderDispatcher.ProviderDispatcher` including:

   a. The namespace defined in the namespace parameter exists.
   b. The classname defined in the ObjectName parameter exists in the
      namespace.
   c. The method defined in the MethodName parameter exists.
   d. The method provider is registered for this classname in this namespace.

   The correspondence between parameters in the ``Params`` argument and in
   the class have not been verified.

**Comment by KSchopmeyer** [comment]
The corrections I see to this are:

1. b. The ObjectName defined in the ObjectName parameter exists in the namespace.

2. c The method defined in the MethodName parameter exists in the class of the ObjectName

3. d The method provider is registered as a methodprovider for this classname in this namespace.

Add note that the prechecks to not validate whether the 'static' defintion is on the class indicating whether this is a class or instance provider.

**Comment by andy-maier** [comment]
I have implemented what I had in mind for CreateInstance, in PR https://github.com/pywbem/pywbem/pull/2329. Up for discussion.

**Comment by andy-maier** [comment]
PR #2329 now completely addresses this issue.
Discussion has moved into the PR, so i removed the "discussion needed" label here.
