### ISSUE TITLE
MOF compiler does not support EmbeddedObject qualifier with class definition

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2340]
The DMTF specification allows the specification of either class or instance as the instance declaration value of a CIM Property with the embeddedobject qualifier.

Pywbems mof compiler supports only the instance declaraction as a value.  A class definition will be rejected with a MOFParse Error.

Since there are no instances of this the class being used as an embeddedinstance value, it is not clear if pywbem will ever support this functionality.

The algorithm used to handle compiling instances cannot be used directly because it makes the assumption that compiling an instance only compiles that instance so that catching the p_createinstance and routing the created instance to a local location works.  In the case of compiling classes, any class compile can create recurssive class compiles of dependent classes all of which must be routed to the repository (we assume)  or the assumption is made that this class is compiled to the repository or the rule is that this class cannot have any dependencies. Since all of this is open and there is no known use of this capability it would seem that this is not really a useful capability today.

**DISCUSSION**

**Comment by andy-maier** [comment]
Let's put it on the agenda of some future release.

**Comment by KSchopmeyer** [comment]
Agreed. My only question is how do we define something that is a future, undetermined, questionable capability.

**Comment by andy-maier** [comment]
It is defined in the DMTF specs, so it is neither future nor undetermined. It is just not used in the DMTF CIM schema, and probably not by vendor schemas either. So we can discuss the priority we give it, but how it would work is well-defined (I think).

**Comment by andy-maier** [comment]
We discussed this and decided that at this point, we will not support that and will update section "Standards conformance" to describe the limitation.
