### ISSUE TITLE
mof_compiler EnumerateClasses function missing.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#240]
Not sure why but the function EnumerateClasses is completely missing from MOFWBEMConnection. It may be that GetClass sufficies.

**Comment by andy-maier** [comment]
MOFWBEMConnection does not need it, I verified that. 

It is not a general purpose repository, but it is scoped to use by the MOF compiler, which invokes only those operations that are in the new abstract base class `BaseRepositoryConnection`.

Let me know whether you agree.

**Comment by andy-maier** [comment]
Agreed to close it.
