### ISSUE TITLE
Create container packaging to define mock functionality installation

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2409]
This issue is based on one that started in pywbemtools (https://github.com/pywbem/pywbemtools/issues/674).  However we concluded that we should put the packaging into pywbem_mock so that any user of pywbem_mock is able to package definitions of what is to be installed in a mock server.

The mock server definition is becoming more and more complex. We need to define a container so that the various components of a mock server can be contained in a single file. This would include data like:

* The mof files that make up the mock and any install pywbem files required to build the repository.
*  The schema used if one is required. This would include the schema source, version, and the leaf classes required.
*  The namespaces required
* Basic serve information like server name, objectmanager name, etc.
*The user-defined providers required.
* Registered Profiles required
* Packaged profile definitions to install. This may be part of 2 above also, at least to install the classes.

The first goal is to be able to define the package for a single profile that would be installed in the mock_server so that the package definition defines what is to be installed, and methods are added to FakedWBEMConnection to execute the installation.

A profile definition should define at least the following to enable the environment to build the classes and instances for a profile.

1 The user namespace.
2. The DMTF Schema or other basic MOF qualifier declarations and and class definitions that must be installed in the namespace designated for the profile.
2b. User defined classes and qualifier declaractions that must be installed as part of this profile.
3. Prerequisites that must be installed before this profile can be installed.
4. The definition of the profile, ex. the RegisteredProfile instance and associations that must be installed to include this profile in the registered profiles and connect the profile registration to the central or scoping instances.
5. The instances of the profile.

**Comment by KSchopmeyer** [comment]
We agreed to move this out to the next version.

**Comment by andy-maier** [comment]
**DISCUSSION:** Move to next release?

**Comment by KSchopmeyer** [comment]
We agree to move this to the next release

**Comment by KSchopmeyer** [comment]
We concluded that we will not do this in pywbem.  Closed
