### ISSUE TITLE
Document strategy for pywbem command line tools in contributors guide

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#241]
Karl pointed out in PR #236 that we need to come up with a strategy for where to have the sript-ish code when we create more pywbem command line tools.

Here is a stab at that, for discussion:

- Anything that could be useful as a module goes into a module (not in the script).
- Command line argument processing, plus all of the rest related to the script (i.e. that is not useful as a module) goes into an extension-less script file, whose hash-bang states it is Python (using `/usr/bin/env python`, to pick up any virtual python).
- There is a .bat file for Windows that invokes python with the suffix-less script of the same name.

That strategy provides for:

- commands with a clear command name without being tied to a suffix revealing the implementation language
- same command name whether on Linux or Windows
- as a result, the same single documentation applies to both
- nicely supported by Python setup scripts (both the suffix-less file and the Windows .bat file get installed into the script directory and thus are available in the PATH).

I do realize that these benefits can also be achieved by what we had before this PR, but it allowed running the module as a script to have a command, and now users are forced to use the suffix-less command. Maybe that is the real reason.

**Comment by KSchopmeyer** [comment]
my only suggestion is that this can be captured in our contributors guide.

**Comment by andy-maier** [comment]
Karl volunteered to start a contributors guide somewhere.

Maybe simply add to DEVELOP.md, for now?

**Comment by andy-maier** [comment]
One item would be common command line options and config file settings and environment variables for connecting to a WBEM server. See the `wbemcli` command as of PR #279 for our current master definition of command line options / args.

**Comment by andy-maier** [comment]
This issue was fixed in PR #372.
