### ISSUE TITLE
Pywbem_mock Invoke method response will not accept NocaseDict. 

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2415]
It accepts a list/tuple of CIMParameter and apparently a dict but not NocaseDict.  Since one of the logical use cases is to return the input parameters this means that the NocaseDict that is the params on input will fail if the user trys to return it without mapping to something else.

**Comment by andy-maier** [comment]
I definitely agree that NocaseDict should be a valid type for the output parameters in a method provider. I have added support for that in PRs #2416 for master and #2417 for 1.0.1.
