### ISSUE TITLE
HTTP Exception on response content-type text/xml

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2420]
pywbem received the following exception from a new server being tested.  Note that we do not have direct access to this server to test.

Error: HeaderParseError: pywbem detected invalid content-type in HTTP response: text/xml;charset=UTF-8
CIM-XML response: <?xml version="1.0" ?><CIM CIMVERSION="2.8" DTDVERSION="2.4"><MESSAGE ID="1001" PROTOCOLVERSION="1.4">...

The overall XML was valid.  The request was enumerate instances

The DMTF  HTTP spec (DSP200)spec states that application/xml or text/xml should be acceptable.

**NOTE:** The error only produces the specific component in error and the xml, no further information on the http header. Since we display the whole XML contect, should we also display the http header content?

See section 7.2.11

**Comment by andy-maier** [comment]
The code in _cim_http.py raises HeaderParseError and it erroneously accepts only "appication/xml".
