### ISSUE TITLE
pywbem_mock ModifyInstance. Issue with validity test

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2449]
The validity test in the code for pywbem_mock/_provideridspatcher.py/ModifyInstance (the default ModifyInstance implementation has an issue in that it tries to load the original instance from the repository before it executes the test for modified key properties.

Thus, the test for modified properties is never executed since if a key property is changed, the instance get fails.

The validity test should probably be done before the instance get.

Note that there is an inherent issue in this problem.  For the client, it is an error in changing a key property value which should be a parameter error.  However, for the server, it is really  an error that the original property cannot be found since changing the value of a key property changes the instance name.

**Comment by andy-maier** [comment]
I understand the general issue of modifying key properties, but I don't understand what you think is incorrect with the ModifyInstance implementation in the provider dispatcher:

The modified key properties are in the instance portion of the ModifiedInstance input argument, and the instance path portion of the ModifiedInstance input argument has the original keys. So in case of an attempt to change the key properties, the original instance can still successfully be fetched from the repository, and the check for changed key properties will then detect that.

An alternative implementation could detect the key property change by comparing the keys in the instance path with the key properties in the instance portion of the ModifiedInstance input argument without fetching the instance from the repository, but the current implementation is also correct, IMO.

**Comment by KSchopmeyer** [comment]
Karl agrees that this is not an issue with the validity testing.  However, we need a test where we keep the original path and change a key property to catch that code.

**Comment by KSchopmeyer** [comment]
Here may be a new issue for discussion.  If a key property in the modified instance is modified, the setitem also modifies the path. That is why we are seeing the

**Comment by andy-maier** [comment]
The behavior of a `pywbem.CIMInstance` object does not need to include all the restrictions of CIM instances in a WBEM server. Remember, that object is just a local data construct, and it is a valid use case to use the same `CIMInstance` object to represent different CIM instances over time, e.g. by changing its path.

**Comment by KSchopmeyer** [comment]
Note that this is an asymmetric characteristic, if you change the property the path changes but if you change the path, the instance does not change.

**Comment by andy-maier** [comment]
Created issue #2475 to deprecate the propagation in CIMinstance. This PR here is ready to go.
