### ISSUE TITLE
Test coverage for 1.2.0

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2490]
As of 1.1.0, the coverage is 90.7%
The goal for 1.2.0 is 94%

**Comment by KSchopmeyer** [comment]
We agreed that each of us will update the issue and define which things they are working on.

Overview to find where the largest gains can be made with least effort.

**Comment by KSchopmeyer** [comment]
**DISCUSSION:** Can we consider this one closed at 92% for version 1.2.0

**Comment by andy-maier** [comment]
I vote for YES
