### ISSUE TITLE
Warnings and exceptions for instance paths without keys

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2514]
**Update:** This issue was originally created as "Tolerate class paths in association references returned by servers" and after discussion was repurposed to add warnings and exceptions for instance paths without keys. See the discussion points, below.

The issue reported in https://github.com/pywbem/pywbemtools/issues/806 is that a WBEM server returns a reference in an association that is a class path. Here is a fragment of the response CIM-XML:
```
              <INSTANCENAME CLASSNAME="IFA_McsRedundancySetIdentity">
                <KEYBINDING NAME="SameElement">
                  <VALUE.REFERENCE>
                    <LOCALCLASSPATH>
                      <LOCALNAMESPACEPATH>
                        <NAMESPACE NAME="Intelliflash" />
                      </LOCALNAMESPACEPATH>
                      <CLASSNAME NAME="IFA_McsControllerRedundancySet" />
                    </LOCALCLASSPATH>
                  </VALUE.REFERENCE>
                </KEYBINDING>
                <KEYBINDING NAME="SystemElement">
                  <VALUE.REFERENCE>
                    <LOCALINSTANCEPATH>
                      <LOCALNAMESPACEPATH>
                        <NAMESPACE NAME="Intelliflash" />
                      </LOCALNAMESPACEPATH>
                      <INSTANCENAME CLASSNAME="IFA_Array">
                        <KEYBINDING NAME="CreationClassName">
                          <KEYVALUE VALUETYPE="string">IFA_Array</KEYVALUE>
                        </KEYBINDING>
                        <KEYBINDING NAME="Name">
                          <KEYVALUE VALUETYPE="string">172.18.76.227</KEYVALUE>
                        </KEYBINDING>
                      </INSTANCENAME>
                    </LOCALINSTANCEPATH>
                  </VALUE.REFERENCE>
                </KEYBINDING>
              </INSTANCENAME>
```

This is allowed as per DSP0201, but disallowed as per DSP0004 section 7.7.5.

Nevertheless, pywbem should tolerate this and return a CIMClassName object in such cases. All variations of class paths need to be supported as child elements of VALUE.REFERENCE: CLASSPATH, LOCALCLASSPATH, CLASSNAME

**Comment by andy-maier** [comment]
While working through this issue, a number of discussion points came up:

* Standards perspective on instances without keys: The DMTF standards seem to be contradictory about this:
 
  * DSP0201 allows INSTANCENAME without any child elements and states in 5.3.4.10 "INSTANCENAME": "If no key-bindings are specified, the instance is assumed to be a singleton instance of a keyless class."
  * DSP0004 states in the naming chapter: "Classes that do not expose any keys cannot have instances that are addressable with an object path for instances." and in 7.6.4 "Key Properties": "Any non-abstract class shall expose key properties."
  * DSP0207 requires at least one key-value pair in an instance path WBEM URI.
  * Current pywbem support (before resolving this issue):
    * Allows creation of CIMInstanceName objects with no keybindings
    * Generates and parses CIM-XML from/to such objects
    * Generates WBEM URI from such objects
    * Does not parse the generated WBEM URI back into such an object but recognizes a string typed key because the required key-value pair is missing.
  **DISCUSSION**: What is our interpretation of the standards? What should pywbem implement?
  
* Standards perspective on instance keys that reference classes: 
  * DSP0201 allows it by means of VALUE.REFERENCE allowing all forms of class references.
  * DSP0004 disallows it in section 7.7.5 "Object References": "Object references in associations shall reference instances only and shall not have the special Null value."
  * Current pywbem support (before resolving this issue):
    * Rejects creation of CIMInstanceName objects with keybindings that reference classes (CIMClassName).
    * Cannot generate corresponding CIM-XML because the input object cannot be created.
    * Rejects parsing CIM-XML (see issue https://github.com/pywbem/pywbemtools/issues/806)
    * Cannot generate corresponding WBEM URI because the input object cannot be created.
    * WBEM URI `/n1:C1.k1="/n2:C2"` is parsed as a string typed key k1 because the required key-value pair is missing.
  **DISCUSSION**: What is our interpretation of the standards? What should pywbem implement?

* Clarify the meaning of some WBEM URIs:
   * `/n1:C1.k1="/n2:C2"` - currently pywbem parses this with k1 being a string typed value `"/n2:C2"`, but generates it from instance with no keys. Should k1 be interpreted as referencing a class (that would be consistent with class paths in DSP0207)?
   * `/n1:C1.k1="/n2:C2."` - currently pywbem parses this with k1 being a string typed value `"/n2:C2."`, and does not generate it. According to DSP0207, at least one key value pair is needed, so DSP0207 does not support the case of an instance without keys.

**Comment by KSchopmeyer** [comment]
OpenPegasus XmlWriter implementation of creationg of <INSTANCENAME element.

Because of the confusion over singleton instance names, OpenPegasus  recognized an implementation with holes in it for instance names with no keybindings.  That shows in the code below

In the creationg of appending Reference Elementsfor Reference properties, OpenPegasus uses this algorithm. If the objectPath has no key bindings, it Appends LocalClassPath, Otherwise it appends LocalInstancePath.  Note that ithe code also recognizes that this as an issue in that the alternate appendValueReferenceElement allows the caller to disallow the ClassPath.

So OpenPegasus probably has an issue depending on the discussions above.  In any case it appears to do something different for ClassPath and LocalClassPath


```

      appendInstanceNameElement method
      . . .

        // Append KEYBINDING ELEMENT
        // <!ELEMENT KEYBINDING (KEYVALUE|VALUE.REFERENCE)>
        //   <!ATTLIST KEYBINDING
        out << STRLIT("<KEYBINDING NAME=\"");
        out << keyBindings[i].getName() << STRLIT("\">\n");

        if (keyBindings[i].getType() == CIMKeyBinding::REFERENCE)
        {
            CIMObjectPath ref = keyBindings[i].getValue();
            // isClassPath = false
            appendValueReferenceElement(out, ref, false);
        }

    //------------------------------------------------------------------------------
    //
    // appendLocalObjectPathElement()
    //
    //     If the reference refers to an instance, write a LOCALINSTANCEPATH;
    //     otherwise write a LOCALCLASSPATH.
    //
    //------------------------------------------------------------------------------

    // appendValueReferenceElement does this correctly with isClassPath flag
    // Called only but formatSimple
    void XmlWriter::appendLocalObjectPathElement(
        Buffer& out,
        const CIMObjectPath& objectPath)
    {
        //
        //  ATTN-CAKG-P2-20020726:  The following condition does not correctly
        //  distinguish instanceNames from classNames in every case
        //  The instanceName of a singleton instance of a keyless class has no
        //  key bindings
        //  See bBUG_3302.
        //
        if (objectPath.getKeyBindings ().size () != 0)
        {
            appendLocalInstancePathElement(out, objectPath);
        }
        else
        {
            appendLocalClassPathElement(out, objectPath);
        }
    }

    //------------------------------------------------------------------------------
    //
    // appendValueReferenceElement()
    //
    //    <!ELEMENT VALUE.REFERENCE
    //        (CLASSPATH|LOCALCLASSPATH|CLASSNAME|INSTANCEPATH|LOCALINSTANCEPATH|
    //         INSTANCENAME)>
    //
    //------------------------------------------------------------------------------
    // Builds either a classPath or InstancePath based on isClassPath
    // parameter which was carried forward from, for example, the
    // request. The caller must define if this is a class or instance path
   void XmlWriter::appendValueReferenceElement(
        Buffer& out,
        const CIMObjectPath& reference,
        Boolean isClassPath)
    {
        out << STRLIT("<VALUE.REFERENCE>\n");

        appendClassOrInstancePathElement(out, reference, isClassPath);

        out << STRLIT("</VALUE.REFERENCE>\n");
    }


    // Append either the classPathElement or InstancePathElement depending on
    // the isClassPath input argument.
    //  INSTANCENAME | CLASSNAME

    void XmlWriter::appendClassOrInstancePathElement(
        Buffer& out,
        const CIMObjectPath& reference,
        Boolean isClassPath)
    {
        if (isClassPath)
        {
            appendClassPath(out,reference);
        }
        else
        {
            appendInstancePath(out,reference);
        }
    }

**Comment by andy-maier** [comment]
Renamed the issue title to reflect the new purpose, after the agreement on the discussion points.
