### ISSUE TITLE
pywbem_mock fails with msgs about profiles if mof compiled with invalid namespace pragma

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2575]
pywbem_mock fails with either a ModelError or CIMError naming a profile class if the MOF includes a pragma statment that refers to a namespace that does not exit and no fleshed out interop namespace exists

This is because the compiler qualifier declaration directly calls the server.create_namespace which is expecting some means of communicating with the server to create a namespace but when there is no interop namespace, or there is just an empty namespace the compiler fails with exceptions like ModelError or CIMError 

I think we need to refine this to return an exception that is more understandable, i.e. the named namespace does not exist.

**Comment by KSchopmeyer** [comment]
There are two examples of this behavior in tests/unitest/ TODO.

**Comment by andy-maier** [comment]
I believe this has been fixed with PR #2581 . Please verify.
