### ISSUE TITLE
Safety issue with tornado & removal of Jupyter support on py27

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2593]
The Jupyter Notebook set of packages have removed Python 2.7 support for quite some time now. This has caused pywbem to pin these versions on Python 2.7. As new security vulnerabilities are discovered, they are being addressed only on package versions that require Python 3.

The most recent example of that is the "tornado" package which is used by a number of the Jupyter packages, where a vulnerability is currently reported by the safety command, but it is fixed starting with tornado 6.2. That version no longer supports Python 2.7. See for example this test run on py39: https://github.com/pywbem/pywbem/runs/1857748020?check_suite_focus=true

Options for **DISCUSSION**:
1. Ignore the vulnerability with the argument that it only affects the development environment.
2. Remove the installation of Jupyter Notebook on py27.

**Comment by KSchopmeyer** [comment]
We propose to remove notebook support for python 2.7
