### ISSUE TITLE
Speedup with Cython

### ISSUE THREAD

**Issue by rchateauneu** [pywbem/pywbem#2606]
Cython is a Python converter to C, and provides a speedup with any code change (And refinements are possible).

It is used by numpy.

Maybe this is worth considering for pywbem ?

**Comment by andy-maier** [comment]
Hi Remi. Do you have specific scenarios where you need a speedup? (e.g. MOF compile? CIM-XML processing? pywbem mock? pywbemtools?) How about memory usage?

**Comment by rchateauneu** [comment]
Hi Andreas,
Thanks for the answer.
Execution and queries. Memory is OK.

Here is an example of an adapted setup.py file to compile modules at installation or during development. It works on Linux and Windows, and is optional if Cython is not installed:
https://github.com/rchateauneu/survol/blob/master/setup.py

**Comment by andy-maier** [comment]
I tried it, but Cython cannot deal with the deferred imports pywbem is doing occasionally, e.g. here:
```
Error compiling Cython file:
------------------------------------------------------------
...
        return dct

    def __setstate__(self, dct):

        try:
            class_type = CIMClass
                        ^
------------------------------------------------------------

pywbem/_cim_types.py:219:25: undeclared name not builtin: CIMClass
```

So if we go there, it requires some reorganization of the pywbem source to eliminate the deferred imports. Which would be a good thing to do anyway.

**Comment by andy-maier** [comment]
I was able to work around the issue with deferred imports by removing the performance optimization, so the source code shown in the previous comment becomes:

```
        from pywbem._cim_obj import CIMClass as class_type
```

It now creates a wheel file. However, the generated wheel file is 10 times larger than before:

```
-rw-r--r--   1 maiera  staff  3893996 Mar 10 08:07 pywbem-1.2.0.dev1-cp38-cp38-macosx_10_15_x86_64.whl   # cythonized
-rw-r--r--   1 maiera  staff   381044 Mar 10 07:45 pywbem-1.2.0.dev1-py2.py3-none-any.whl    # uncythonized
```

**Comment by andy-maier** [comment]
Some discussion about cython output size, for reference:
* https://towardsdatascience.com/how-to-shrink-numpy-scipy-pandas-and-matplotlib-for-your-data-product-4ec8d7e86ee4
https://github.com/cython/cython/issues/2102

On speedup: The `make resourcetest` requires some work before it properly uses the cythonized version.

**Comment by andy-maier** [comment]
I managed to get the symbols stripped by specifying `CFLAGS=-g0 -Wl,-s` with the `steup.py` command that builds the wheel archive.

The result is:
```
5055417 B    dist/cython_with_symbols/pywbem-1.2.0.dev1-cp38-cp38-macosx_10_15_x86_64.whl
4371703 B    dist/cython_symbols_stripped/pywbem-1.2.0.dev1-cp38-cp38-macosx_10_15_x86_64.whl
 381044 B    dist/no_cython/pywbem-1.2.0.dev1-py2.py3-none-any.whl 
```

**Comment by andy-maier** [comment]
I posted my first attempt as PR #2608.

**Comment by rchateauneu** [comment]
Apparently this error message while compiling the Cython-generated C code is a well-known problem and related to Python 3.9:
```
/tmp/pip-install-811dr0hz/Cython/Cython/Plex/Scanners.c:7913:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
```
[Deprecation warnings about _PyUnicode_get_wstr_length and PyUnicode_AsUnicode](https://github.com/cython/cython/issues/3924)

For Python 2.7 failures, maybe os.walk() would help instead of glob ? [How to use glob() to find files recursively?](https://stackoverflow.com/questions/2186525/how-to-use-glob-to-find-files-recursively)
```
TypeError: glob() got an unexpected keyword argument 'recursive'
```

**Comment by andy-maier** [comment]
I have fixed these issues.

The next hurdle is to find out how a cythonized version would be uploaded to Pypi. With the latest update to the PR, twine would upload the source archive and normal wheel archive as it did before, plus the cythonized wheel archive for only the Python version and platform I happened to use when I run `make upload`. What would be needed on Pypi I think are the cythonized versions for all supported Python versions times all supported OS platforms. Note that even the OS version is part of the cythonized wheel archive's file name. Example: `pywbem-1.2.0.dev1-cp38-cp38-macosx_10_15_x86_64.whl`. That seems like a horrible approach to me.

**Comment by rchateauneu** [comment]
Indeed, this would be a lot of versions. Therefore a first solution could be to only upload the pure Python version by default, as of now, and let users cythonize their package on-demand. This would not change anything by default - this is less risky at the beginning --, but give a speed-up for users wishing to experiment.

Something like:
``
pip install pywbem --install-option="--cython-compile"
``

Of course, it does not prevent, in the future, to provide cythonized versions of wheel archives depending on the demand. Also, it might not be necessary to cythonize all files, but only the CPU-intensive ones.

Just an idea.

**Comment by andy-maier** [comment]
The idea to cythonize on demand during pip install is good.

I just need to find out how that can be done if there is a wheel archive (which does not execute the setup.py upon install). Basically pip needs to use the source archive in that case, which does install via setup.py.

**Comment by andy-maier** [comment]
I have updated the PR #2608 to now provide support for users to build a cythonized wheel. See the PR for details.
The cythonized version of the wheel file can then be installed with a normal `pip install {filename}`.

It is not exactly the idea of doing that during pip install but if we do not upload the cythonized archive to Pypi, any way of building it locally by the user requires a development environment to be set up and the repo to be checked out, so this way of providing cythonized support is not the reason for that requirement, and so I think this way should be OK. But please let me know in case this causes troubles for users.

Please try it out and let me know how it works (I did not test it yet, nor did I measure CPU or memory).

**Comment by andy-maier** [comment]
I have updated the PR to add documentation and to run the unit and function tests on the cythoinized archive.
It turns out that the MOF compiler fails during tests because the ply package cannot build its YACC parser.

**Comment by andy-maier** [comment]
Another update of the PR. I think we are ready for review and merge now.
