### ISSUE TITLE
Cases where the unclosed ResourceWarning appears

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2610]
1. mof_compiler when compiling against a server

The test i was running was to compile against the openpegasus container we are using and in dryrun

mof_compiler -s http://localhost:9988 -d -v -I . CIM_Core.mof 

where CIM_Core is the files that are in the Core schema directory.  Pegasus sot of does this.

Exception ignored in: <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 41836), raddr=('127.0.0.1', 9988)>
ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 41836), raddr=('127.0.0.1', 9988)>

**Comment by andy-maier** [comment]
Searching for this reveals that the likely culprit is not to close the `requests.Session()` object in the pywbem code.
See also:
* https://stackoverflow.com/q/24717027/1424462
* https://github.com/psf/requests/issues/3912
* https://github.com/psf/requests/issues/4367
