### ISSUE TITLE
CIMMethods and return type

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#264]
There is a TODO question in cim_obj.py CIMMethod.tomof() "Is None allowed for return type.

Per DSP0004, No. 
7.9 Method Declarations 4145
A method is defined as an operation with a signature that consists of a possibly empty list of parameters 4146 and a return type.

However, the CIMMethod __init__ specifies return_type-None as defualt and as far as I can tell does not treat this as an error.
Also the tomof only ouputs the return type if self.return_type is not None

**Comment by andy-maier** [comment]
I agree, and I think the solution should be to make sure in `CIMMethod.__init__()` that the `return_type` instance variable cannot be `None`. Basically a similar kind of checking that happens in `CIMProperty.__init__()`.

**Comment by KSchopmeyer** [comment]
I will take that one.

**Comment by andy-maier** [comment]
Adressed by PR #345.

**Comment by KSchopmeyer** [comment]
pr committed. close
