### ISSUE TITLE
ConnectionError with bad status line 'POST / HTTP/1.1\r\n'

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2659]
We get occasional connection errors in test code when sending indications to the pywbem listener, that result in the following exception for the sender. The error always shows up in test function `test_WBEMListener_send_indications()` as follows:

```
AssertionError: Testcase sending indication #29 raised ConnectionError: ('Connection aborted.', BadStatusLine('POST / HTTP/1.1\r\n'))
```

The indication number where this happens, varies.

Note there was an earlier issue #2383 that could not be resolved, had a different symptom but may be related.

List of recent GitHub Actions runs that failed that way (incomplete):

* [2021-02-17 macos-latest, 3.9, latest](https://github.com/pywbem/pywbem/runs/1916166016?check_suite_focus=true#step:12:201): on indication # 29
* [2021-03-20 macos-latest, 2.7, latest](https://github.com/pywbem/pywbem/runs/2154863512?check_suite_focus=true#step:13:201):  on indication # 2
* [2021-03-20 macos-latest, 3.9, latest](https://github.com/pywbem/pywbem/runs/2154863515?check_suite_focus=true#step:13:201):  on indication # 13

TODO: Add new occurrences here.

**Comment by andy-maier** [comment]
I was able to reproduce it on macOS with Python 3.8:

I changed the "send_count" parameter in test_WBEMListener_send_indications() to just 500, and issued:
```
$ i=0; while true; do i=$[$i+1]; echo make test $i; pytest -s tests/unittest/pywbem/test_indicationlistener.py -k test_WBEMListener_send_indications >make.log 2>&1; rc=$?; if [[ $rc != 0 ]]; then echo rc=$rc; grep "^ERROR" make.log; fi; done
```
Running that for slightly above 500 make test runs resulted in the ConnectionError as initially described to occur as follows:
```
make test 9: Indication #318
make test 26: Indication #150
make test 75: Indication #443
make test 92: Indication #149
make test 109: Indication #154 
make test 126: Indication #154
make test 159: Indication #300
make test 208: Indication #456
make test 257: Indication #460
make test 274: Indication #154
make test 291: Indication #155
make test 340: Indication #466
make test 389: Indication #465
make test 406: Indication #155
make test 455: Indication #456
make test 505: Indication #362
```
This means in 500 x 500 sends, the problem occurred 15 times.

**Comment by andy-maier** [comment]
The BadStatusLine exception is raised in `http/client.py` in the standard Python library, while called when the testcase code sends the indication. I added some more information to the expection by changing the source file from:

```
$ grep "BadStatusLine(" /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py
            raise BadStatusLine(line)
                raise BadStatusLine(line)
            raise BadStatusLine(line)
class BadStatusLine(HTTPException):
```

To:

```
$ grep "BadStatusLine(" /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py
            raise BadStatusLine("Line does not start with 'HTTP/': {}".format(line))
                raise BadStatusLine("Status is not between 100 and 999: {}".format(line))
            raise BadStatusLine("Status is not an integer: {}".format(line))
class BadStatusLine(HTTPException):
```
That confirmed that it raises the exception when it checks for the status line to start with `HTTP/`:
```
Testcase sending indication #487 raised ConnectionError: ('Connection aborted.', BadStatusLine("Line does not start with 'HTTP/': POST / HTTP/1.1\r\n"))
```

Other debug code added to that module shows the actual HTTP status line in a successful case:
```
HTTP/1.0 200 OK
```
So what the sender gets back is actually the first line of the request, and not the first line of the response.

**Comment by andy-maier** [comment]
Call stack at the point the exception is raised:
```
  /Users/maiera/PycharmProjects/pywbem/pywbem/tests/unittest/pywbem/test_indicationlistener.py(713)test_WBEMListener_send_indications()
-> response = requests.post(url, headers=headers, data=payload,
  /Users/maiera/virtualenvs/pywbem38/lib/python3.8/site-packages/requests/api.py(119)post()
-> return request('post', url, data=data, json=json, **kwargs)
  /Users/maiera/virtualenvs/pywbem38/lib/python3.8/site-packages/requests/api.py(61)request()
-> return session.request(method=method, url=url, **kwargs)
  /Users/maiera/virtualenvs/pywbem38/lib/python3.8/site-packages/requests/sessions.py(542)request()
-> resp = self.send(prep, **send_kwargs)
  /Users/maiera/virtualenvs/pywbem38/lib/python3.8/site-packages/requests/sessions.py(655)send()
-> r = adapter.send(request, **kwargs)
  /Users/maiera/virtualenvs/pywbem38/lib/python3.8/site-packages/requests/adapters.py(439)send()
-> resp = conn.urlopen(
  /Users/maiera/virtualenvs/pywbem38/lib/python3.8/site-packages/urllib3/connectionpool.py(699)urlopen()
-> httplib_response = self._make_request(
  /Users/maiera/virtualenvs/pywbem38/lib/python3.8/site-packages/urllib3/connectionpool.py(440)_make_request()
-> httplib_response = conn.getresponse()
  /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py(1348)getresponse()
-> response.begin()
  /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py(308)begin()
-> version, status, reason = self._read_status()
> /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py(290)_read_status()
-> raise BadStatusLine("Line does not start with 'HTTP/': {}".format(line))
```

**Comment by andy-maier** [comment]
I have created a standalone script that reproduces the error, and that uses only Python 3 standard libraries. (it can be configured to use the request package instead). With the script, I have opened Python issue https://bugs.python.org/issue43912.

**Comment by andy-maier** [comment]
I discovered that a retry of the `requests.post()` in case of the BadStatusLine works. So that may be a good workaround for our testcases.

**Comment by andy-maier** [comment]
I have put up PR #2666 with a workaround that lets the test code retry the POST in case of BadStatusLine.

I have run the failing test function with this workaround configures with 1000 indications per test run, and in 1000 test runs, there were 71 occurrences of BadStatusLine, all of which were successfully recovered by a retry.

**Comment by KSchopmeyer** [comment]
I have run the script against Linux Ubuntu, version 18.04 (patches current) twice now. Once for about 10,000 iterations  of the script and a second time for 35,000 iterations of the script without any failures.  I don't know if this means that there is a real difference between linux and mac or just some environmental difference.

This was with pywhon 3.9.4 and ubuntu linux 18.04

I will redo this test in a completely new vittual environment to be sure it is not some artifact of the virtual environment.
