### ISSUE TITLE
CIMClass tomof with method sometimes includes extra space before closing line

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#266]
There is a blank line between the last line of a method and the closing line of the class

```
Delete();

};
```

However, when I took out the \n that generates this, it caused failures in the tox testing on some systems showing   `Delete)_;};`.  Not that this did not happen on all python versions.

I consider this low priority

**Comment by andy-maier** [comment]
We agreed to not change this because it is consistent with the CIM Schema MOF.
