### ISSUE TITLE
Subscription manager, issues

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2701]
1.  Issue with definition of Name property.

When the SubscriptionManager Name property creates a new destination it defines the name property as:

```

SubscriptionManager, Line 1179
        dest_inst['Name'] = _format(
            'pywbemdestination:{0}:{1}:{2}',
            ownership, self._subscription_manager_id, uuid.uuid4())

```

However, when the add_server looks for owned indications: ist uses syntax for the Name property defined by the regex

```

        this_host = getfqdn()
        dest_name_pattern = re.compile(
            _format(r'^pywbemdestination:owned:{0}:{1}:[^:]*$',
                    this_host, self._subscription_manager_id))

```

Which contains the "this_host" value.   Thus, it never finds the owned destinations.

The same issue applies to the add_filter()

We will fix this to include the fqdn as the value of this component of each Name property and add code to includ it in the pattern.

```

2. Issue with comparison of paths of new subscription instance and instance from owned list.  In this case, the instance created for the new subscription instance to be created does not include the keybindings even though they are in the instance.  See the code below from SubscriptionManager, line 1336:

```
        sub_path = CIMInstanceName(SUBSCRIPTION_CLASSNAME,
                                   namespace=server.interop_ns)

        sub_inst = CIMInstance(SUBSCRIPTION_CLASSNAME)
        sub_inst.path = sub_path
        sub_inst['Filter'] = filter_path
        sub_inst['Handler'] = dest_path

        if owned:
            for inst in self._owned_subscriptions[server_id]:
                if inst.path == sub_path:
                    # It does not have any properties besides its keys,
                    # so checking the path is sufficient.
                    return sub_inst

```

The sub_inst.path is not completed with the keybindings

```
The _createfilter method  does not create a complete path for the new filter because it does not add the keybindings to the path but only sets the classname and namespace.  
3. Issue with same test in create_filter.  Created path is incomplete with no keybindings. While this is correct for the CreateInstance that follows, the test of inst.path == ..._path fails because the keybindings are not defined.
4. Same issue with dest_path
5. The hostname in this_host variable that becomes the SystemName property value for destinations and filters was being set with the client host name, not the server name in _createfilter and _createdestination.  It needs to have the name returned by the server.  This can be fixed by capturing the SystemName used by the Server upon initialization of the SubscriptionManager where it is already contained in the serber.WbemServer.cimom_inst['SystemName'] property since this is a required property because it is a key we can depend on its existence. The only issue is if  particular providers use a different value that the common system name returned with the CIM_ObjectNamager instance.

**Comment by KSchopmeyer** [comment]
A more precise example:

At SubscriptionManager line 358 in add server trying to find owned destinations

```

'instance of CIM_ListenerDestinationCIMXML {\n
   InstanceID = NULL;\n
   Caption = NULL;\n
   Description = NULL;\n
   ElementName = NULL;\n
   OtherPersistenceType = NULL;\n
   OtherProtocol = NULL;\n
   Protocol = 2;\n
   CreationClassName = "CIM_ListenerDestinationCIMXML";\n
   SystemCreationClassName = "CIM_ComputerSystem";\n
   SystemName = "2af83bd6e403";\n
   Name = "pywbemdestination:owned:pywbemcliSubMgr:962de433-bea1-4fb7-8a6c-11549f22"\n
          "d0f9";\n
   Destination = "http://192.168.3.149:25988";\n
   PersistenceType = 2;\n};\n'
   
(Pdb++) p inst.path.keybindings['SystemName']
'2af83bd6e403'

# however the dest_name_pattern in add_server includes the fqdn (i.e. leonard) 
(Pdb++) p dest_name_pattern
re.compile('^pywbemdestination:owned:leonard:pywbemcliSubMgr:[^:]*$')

(Pdb++) p this_host
'leonard'

```

The same applies to the Destination

```

1179             dest_inst['Name'] = _format(                                   
1180                 'pywbemdestination:{0}:{1}:{2}',                           
1181                 ownership, self._subscription_manager_id, uuid.uuid4())    
1182             dest_inst['Destination'] = listener_url

(Pdb++) p dest_inst['Name']
'pywbemdestination:owned:pywbemcliSubMgr:73f5d552-9b9e-4b12-bb66-35b4075d4c42'


1168             this_host = getfqdn()    
Fully qualified name of host

**Comment by andy-maier** [comment]
On 1. I think the host should not be part of the destination Name property value. All we want to do is to identify instances owned by a subscription manager, so the id should be sufficient.

In fact, having the host there has two disadvantages:
* it would be required to be consistent w.r.t. using hostname vs IP address
* one would need to operate from the same client host for all operations across the entire lifecycle of the destination.

**Comment by andy-maier** [comment]
On 2. Good catch.

**Comment by andy-maier** [comment]
One more note on lifecycles: The module docstring of the sub.mgr. module states that the lifecycle of owned instances in the server is bound to the lifecycle of the registration of the server with the sub.mgr python object. It is not explicit about how the lifecycle of the registration of the server relates with the lifecycle of the sub.mgr python object. The paragraph starting on line 74 gives some hint on that by describing the case where the sub.mgr object goes away before all owned objects could be removed, and that they are rediscovered by a future sub.mgr object. That basically allows the owned instances to live longer than the sub.mgr python object. Which is why we need to discuss the case where the client changes its IP address.

**Comment by KSchopmeyer** [comment]
Will mark that one for discussion.

**Comment by KSchopmeyer** [comment]
Another issue.  I was hoping to be able to tie uniqueness of the filter_id down at least in pywbemcli so that the combination of owned and filter_id could uniquely identify a filter.  That does not work because when the filter is built in _create_filter() even if all of the instance parameters are the same and a filter with exactly those parameters exists, a new filter is created with a new guid.  Thus add_filter ALWAYS adds a new filter even if owned is set and the filter has exactly the same properties.  I can insure in pywbemcli that the add_filter always has a unique ID but someone can build one in pywbem with the same id bud a different guid.  If that is the rules we want, I can simply add the code to cover the multiple owned filters with the same filter_id but for the moment I am disallowing add_filter with an existing filter_id and owned.
