### ISSUE TITLE
pywbem does not account for WBEMServer profile

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2709]
pywbem does not account for the WBEMServer profile.  The functionality in components like SubscriptionManager are based on the CIM_ObjectManager

**Comment by andy-maier** [comment]
Some more details: In the WBEM Server profile (https://www.dmtf.org/sites/default/files/standards/documents/DSP1092_1.0.0.pdf), the CIM class used to represent the server is CIM_WBEMServer, and the CIM_ObjectManager class is not used.

This requires changes mainly in the `pywbem.WBEMServer` class, particularly (but not only) its public `cimom_inst` property.

The `pywbem.WBEMSubscriptionManager` class does not rely on the CIM_ObjectManager class directly, but uses it through the `cimom_inst` property of the `pywbem.WBEMServer` class.

**Comment by andy-maier** [comment]
**DISCUSSION**
* Should we simply expose the CIM_WBEMServer instance in the `cimom_inst` property of the `pywbem.WBEMServer` class, if a CIM_ObjectManager instance does not exist?

**Comment by KSchopmeyer** [comment]
After discussion it is the pywbem team's group not to implement the WBEMServer profile unless we get a client request.
