### ISSUE TITLE
Subscriptions, filters, handlers, open questions for properties

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2712]
1. The CIM_Indication Class and profile have defined source_namespaces and deprecated source_namespace.  Should we modify the add_filter method to allow SourceNamespaces, or default to SourceNamespaces, etc. since it has been the preferred solution for many years. now.

   **Suggestion.**  Add option for SourceNamespaces in addition to sourcenamespace with test that they cannot both be provided on a add_filter method call.

2. The PersistenceType property: Should the client set the persistence type property. Note that this property is included in the CIM_ListenerDestination mof file and documented in the Indications Profile sect 7.3.23.4

3. Should we support the IndividualSubscriptionSupported property in the CIM_IndicationFilter and should the client be setting it?
   The model property documentation is:

```
If IndividualSubscriptionSupported is true, the implementation "
          "shall support direct subscription to this IndicationFilter. If "
          "IndividualSubscriptionSupported is false, the implementation shall "
          "not support direct subscription to this IndicationFilter."
```
See section 7.2.7 for more information on the IndividualSubscriptionSupported feature.

4. Should we be using CIMListenerDestinationCIMXML for the listener class or CIM_ListenerDestination since CIM_ListenerDestinationCIMXML is now deprecated and actually contributes nothing new to the values, etc. NOTE: This change (agreed to bel0w) has been moved to its own issue to be sure it is clearly noted and because it represents a possibly incompatible change to the CIM_IndicationFilter  objects created as well as a clear extension of the SubscriptionManager api.

**Comment by KSchopmeyer** [comment]
Based on the the fact that the DMTF indication profile uses SourceNamesapaces we propose to move the filter creation to use SourceNamespaces.

**Comment by KSchopmeyer** [comment]
OpenPegasus supports them both.  If both are provided, they are merged together.

**Comment by andy-maier** [comment]
On PersistenceType: According to DSP1054 2.2.2, this ListenerDestination property basically controls whether the server cleans up failing indication deliveries - upon delivery failure the server removes the subscription and destination instances.
We agreed that this should become an option to select in the add_destination(9 etc methods of the SubscriptionManager.

**Comment by andy-maier** [comment]
On the IndividualSubscriptionSupported property:
We read through DSP1054 1.2.2, and basically this property controls whether a subscription to the indication filter instance is permitted or rejected. The subscription is created via CreateInstance on the Subscription instance, so its provider is the one that needs to do this check.

**Comment by andy-maier** [comment]
On CIMListenerDestinationCIMXML: We agreed to switch the pywbem code to use CIMListenerDestination instead.

**Comment by andy-maier** [comment]
All items have been addressed, as follows:
* item 1: PR #2730 
* item 2: PR #2723
* item 3: PR #2724
* item 4: PR #2721
