### ISSUE TITLE
Windows run of pywbem install trys to call bash

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2713]
pip_upgrade_$(pymn).done: Makefile
	-$(call RM_FUNC,$@)
	bash -c 'pv=$$($(PIP_CMD) --version); if [[ $$pv =~ (^pip [1-8]\..*) ]]; then $(PIP_INSTALL_CMD) pip==9.0.1; fi'
	$(PIP_INSTALL_CMD) $(pip_level_opts) pip
	echo "done" >$@

**Comment by andy-maier** [comment]
This did not show up in the GitHub Actions test because there the Windows environment does have a bash command.

**Comment by andy-maier** [comment]
I have fixed it in PR #2717 by not upgrading Pip to a minimum of 9.x before doing further upgrades. This means there is now a dependency on having at least Pip 9.x on Windows that the user needs to ensure themselves.

You were setting it to priority and milestone to 1.2.1. Does that mean you are suggesting a quick release of 1.2.1 with that fix?
