### ISSUE TITLE
wbemcli clarify help

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#273]
the port help is as follows
usage: wbemcli [options] server

Provide an interactive shell for issuing operations against a WBEM server.

Positional arguments:
  server                Host name or IP address of the WBEM server.

Server related options:
  Specify the WBEM server and namespace

  --port port           Port where the WBEM server listens

However, it does not clarify if this is overridded by the choice of --no-ssl or non-existence of that parameter

**Comment by andy-maier** [comment]
Fixed in PR #279.
