### ISSUE TITLE
SSL connection issue with python 2.7

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#274]
Now that I have a server consistently working with other clients (cimcli) I am getting errors on connection with pywbem 8.2 and 8.3 and the 8.3 with my working patches.

It is generating the response:

    raise ConnectionError("Socket error: %s" % exc)
ConnectionError: Socket error: certificate verify failed

when connection is made either with test code or with wbemcli using the same credentials that work for cimcli.

**Comment by KSchopmeyer** [comment]
We are getting cert files from the os so that cim_http ends up with /etc/ssl/certs as a proposed cert file and that is an indication that the certs must be checked.  We need to discuss why this code is getting the file from the system.  Not sure of the reason for the logic there yet. (get
When I force the certs file and ca_certs to none internal to the function, it works. on pyython27

The good news is that python3 also works.  Now, I have to clean up the code mess since it is full of diagnostics.

**Comment by KSchopmeyer** [comment]
I retake the previous statement about python3.  There is still a problem in that it reports previously connected.

**Comment by KSchopmeyer** [comment]
I think this means that you cannot use wbemcli with ssh hosts unless the cert is in ssl/certs.

I added no_verification to the connect as a test and that worked.  Question is what parameters should we really have on wbemcli for security

**Comment by KSchopmeyer** [comment]
The code makes the assumption that the certs in ssl/certs are valid options. Thus, the user not supplying a cert does not mean that verification is bypassed because the default certs are included so any certs = None is bypassed. Only the use of no_verification disables this and at least wbemcli does not provide either a cmd line option or default for this.  In open pegasus, if the user did not provide infor on a cert file that meant there were no certs.  

**Discussion:** What should the behavior be in cim_http.py. Should any certs from the system be included by default? If that is the case, then no_verification becomes more important in that it is the way a user defines ssl usage but does not care about verifying the server cert.

**Comment by KSchopmeyer** [comment]
This is a problem across both python 2 and 3

**Comment by KSchopmeyer** [comment]
The issue is that cim_http.py searches the system for default certificates in a number of files in /etc.
See the function def get_default_ca_certs().   This means that if there are any certificates in these directories, the user MUST set no_verification=True  to avoid having these certificates tested against the cert from the server.

**Comment by andy-maier** [comment]
Karl,
I found the commit that introduced the search in the default locations:

https://github.com/pywbem/pywbem/commit/f7599379b26a685d772b2620a16316130f46c474#diff-b9405e82967722562550d56a33267141

**Comment by KSchopmeyer** [comment]
At the very least, we should add no_verification to wbemcli or create an option to be able to force either certificates on input or no_verification since generally when users are testing with wbemcli they do not have server certs in the standard list of certs and there  is no way to make either of those available today.  Thus, the only way to run a test with wbemcli would be to have the server certs in the system ssl certs files.

**Comment by KSchopmeyer** [comment]
This was a confusing conversation but I now know what some of the issues are.  First, wbemcli is incomplete when uses with ssl in that unless you have valid certificates and ca certs for the server you connections fail.  Since most test servers have self generated local certs, that makes testing a bit difficult right now.  In any case I am starting another issue specifically to propose changes to wbemcli to make it more useful with ssl testing.

**Comment by andy-maier** [comment]
PR #179 fixes this issue.

**Comment by andy-maier** [comment]
Need to discuss what is still left of this, and to what extent it is addressed by PR #179.

**Comment by andy-maier** [comment]
PR #179 (merged) addresses that for 0.9, and PR #298 (not yet merged) addresses that for 0.8.
Once PR #298 has been verified and merged, this issue can be closed.

**Comment by andy-maier** [comment]
PR #298 has been merged. Closing this issue.
