### ISSUE TITLE
mocker/compiler create instances from abstract classes

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2742]
All parts of pywbem environment that create instances ignore the rule that instances cannot be created from Abstract classes. The code to test and reject these attempts to do CreateInstance need to be included in a) parts of the compiler path, b) the mocker.

**Comment by andy-maier** [comment]
This requires that the client side CreateInstance() method inspects the class before issuing the CreateInstance operation. 

This has several disadvantages:

* Extra operation
* Does not work with SFCB (it does not support class operations)
* Should not be a client responsibility anyway to check this, instead the server ought to reject this.

I suggest not doing this.

**Comment by andy-maier** [comment]
I understand the mocker, but why in the compiler path? The compiler acts as a client against a server. If the server is a real server or a pywbem mocked server, it should reject creation of instances of abstract classes, but as a client, the compiler does not need to check this upfront.

**Comment by KSchopmeyer** [comment]
The problem here is that the compiler path is actually to a local file that acts as a local server.  Should we allow the  instances to be created here to then be rejected by a server.  If this was really part of just the compiler path, the issue makes sense but this local repo acts both at a shortcut to speed things up and as a repository.  That is why I put the test in the compiler path

**Comment by andy-maier** [comment]
OK, I see.

**Comment by KSchopmeyer** [comment]
Actually could have argued either way since it is both a client support tool and a local server.  Arggggghhhhh
