### ISSUE TITLE
Proposed changes to WBEMConnection properties

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2752]
1. The timeout property.  This property is set for each operation so it would be logical that the user could modify it before a particular request was executed and not just at the creation of the connection.

So far, that is the only change I can see in the state change of the properties.

That would require adding a setter to the timeout property. Since the property is already being picked up by each request, not other change would be necessary

**Comment by andy-maier** [comment]
Bottom line: Make the timeout property on WBEMConnection settable
