### ISSUE TITLE
Overlapping parameters on SubscriptionManager add_filter

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2757]
The add_filter method includes the following parameters:

    owned=True,  filter_id=None, name=None,

However it also states that:

1. filter_id and name are mutually exclusive:
2. name can only be used with filters that have the owned=False attribute.

Thus we have 3 parameters and two possibilities:

1. owned: we create the Name from filter_id with other fields
2. not_owned, the name property is inserted directly into the name.

In trying to make this work in pywbemcli, I became aware of the complexity of this, at least in creating parameters that make sense on the command line.

My questions are:

1. Is this too complex for the add_filter method.  Would not al alternative like id and owned where:
   a. ID (replacing both filter_id and name) became the name directly if owned = False.
   b. id became the name by integrating it into a pywbem defined string that i) defined the ownership, identified pywbemcli as the source, etc. if owned = True

or

2. We keep the existing nameing for pywbem but simplify it for pywbemcli where we have just id and owned parameters.

**Comment by KSchopmeyer** [comment]
RE: the issue of filter_id and owned filters:

COMMENT: KS: The documentation for add_filter() reads as shown below. That was the proposal I though we had agreed to but it is clear that line 888 shows that the documentation and code differ:
        * indirectly by specifying the `filter_id` parameter.

          In this case, the value of the `Name` property will be:

          ``"pywbemfilter:" {ownership} ":" {client_host_name} ":"
          {subscription_manager_id} ":" {filter_id} ":" {guid}``

          where
          ``{ownership}`` is ``"owned"`` or ``"permanent"`` dependent on
          whether the filter is owned or permmanent;
          ``{client_host_name}`` is the fqdn of the client hos;
          ``{subscription_manager_id}`` is the subscription manager ID;
          ``{filter_id}`` is the filter ID; and
          ``{guid}`` is a globally unique identifier.

        Only owned  filters can use the filter_id to create the     <<<<<<<<<<<<<< Here
        `Name` property.

**Comment by KSchopmeyer** [comment]
I propose the following change:

    Both owned  and permanent filters can use the filter_id parameter to create the  `Name` property.  Only permanent filters can be created using the name parameter

**Comment by andy-maier** [comment]
I read the current code incorrectly: The code excludes name for owned, while the docs exclude filter_id for permanent. In the discussion today, we agreed that we want to support only these two cases:
- owned with filter_id
- permanent with name

The code and docs of add_filter() needs to be adjusted accordingly.
