### ISSUE TITLE
Add config file mechanism that can be used with wbemcli and also with other cmd line tools

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#278]
See issue 273. This pulls that part of the other issue off as separate issue.

**Comment by KSchopmeyer** [comment]
This will add the capability of providing alternative cli parameter choices (config file, env variables) for cli tools such as wbemcli.

There are several packages that do this including configparse and configargparse.

What we have to evaulate the the completness of each and the extra work that they apply to the argparse option definition.  Thus, for example, 

configargparse states that it seamlessly integrates so that it uses argparse as the basis for the config file and env parsing

configparser is part of python as of python3 and at least some python 2.  But it separates the config file parsing from the cmd line parsing so requires more code to support.

**Comment by andy-maier** [comment]
We agreed to abandon this one.
