### ISSUE TITLE
Warnings that pop up with at least some pylints

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#28]
I am using pylint 1.5.1.  The following warnings pop up about deprecation of items in the config
file

Warning: option profile is obsolete and it is slated for removal in Pylint 1.6.
Warning: option comment is obsolete and it is slated for removal in Pylint 1.6.
Warning: option zope is obsolete and it is slated for removal in Pylint 1.6.
Warning: option ignore-iface-methods is obsolete and it is slated for removal in Pylint 1.6.
Warning: option required-attributes is obsolete and it is slated for removal in Pylint 1.6.

**Comment by andy-maier** [comment]
I removed these deprecated options from the pylint.rc file and verified that the generated pylint output is still the same (using pylint 1.3.1 and pylint 1.5.4).
PR #32 contains the changed pylint.rc.

**Comment by andy-maier** [comment]
Addressed in PR #32.
