### ISSUE TITLE
Separate utilities --help output from longer description for man and RTD

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#281]
If done right, the `--help` output gets quite lengthy. We are currently just pasting its output into the RTD docs.

It would be good to have a reasonably short text in `--help`, and the full description in the RTD output. Ideally, this full output would also go into man-compatible format (just for the utility commands).

**Comment by KSchopmeyer** [comment]
Note that we established in pegasus that this can become real manual drugery if there is not tool support and also causes significant errors if both definitions are not throughly reviewed for every change in the code.  We made the mistake of putting them in different places even so somebody was always forgetting to update one or the other.  The ideal would be some extension to argparse where we build the extra doc right into a single definition of the cli parsing mechanism.

**Comment by andy-maier** [comment]
Not sure where we should go with this. Withdrawing the issue.
