### ISSUE TITLE
MOF compile of abstract class: Change error to warning

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2825]
pywbemtools issue https://github.com/pywbem/pywbemtools/issues/1054 should be addressed by changing the error raised in the MOF compiler when creating an instance of an abstract class, to issuing a Python warning of type `ToleratedSchemaIssueWarning`.

**Comment by KSchopmeyer** [comment]
See issue pywbemtools issue https://github.com/pywbem/pywbemtools/issues/1054 that was the origin of this issue.  Please be sure that issue is closed also.
