### ISSUE TITLE
Operation IterEnumerateInstances Returns host name in path

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2841]
The EnumerateInstances, . etc. does not set the host into the path elements in the returned instances.  However, the IterEnumerateInstances does set the host name into each path.

This is a difference between the operations (probably applies to Associators and References also) that we do document but in just one sentence.

**DISCUSSION:** Is this operationally correct and should we document it better?  Or should we consider modifying the code to make this completely compatible with the Pull and Original operations?  Remember that the iter... is our own pywbem operation and we could therefore justify this difference if properly documented but it does represent a difference from  what is returned in the request operations that we use

**Proposal:** ~~We are tending to think that this would be more logical if we added the host to the enumerateinstances, etc. but we should go back and see if there is any documentation in the commits as to why we added it to the iterenumerateinstances.~~  Update. Based on the information in other comments in this issue, it is proposed to make only  one change, Modify the documentation to note that we are always returning host name in the InterEnumerateInstances and IterEnumerateInstancePaths response even if the original non-pull requests were made which do not include this information in the response.  It is also noted that we actually fill in empty namespace value in the response path but probably should not have done that to more clearly reflect what the server returned, even if the server did not return this value.  However, I propose that we leave this alone (KS)

Therefore, the only change proposed is a minor one to documentation

**Comment by KSchopmeyer** [comment]
I did not find anything in the commit documentation.

**Comment by andy-maier** [comment]
The cases where instance paths are returned, are:
- instance path returned by enumerate instances (traditional / pull / iter)
- instance path returned by enumerate instance paths (traditional / pull / iter)

**Comment by KSchopmeyer** [comment]
From the DMTF specifications:

* EnumerateInstanceNames - Per dsp0200, a list  the entity <InstanceName> is to be returned from this request.  DSP0201 defines this as class and keybindings only.  That section is shown below:
    5.3.4.10 INSTANCENAME
    946 The INSTANCENAME element defines the location of a CIM instance within a namespace (it is referred
    to in DSP0004 as a model path). It comprises a class name and key-binding information.
    947
    948
    949 If the class has a single key property, a single KEYVALUE or VALUE.REFERENCE subelement may be
    used to describe the (necessarily) unique key value without a key name. Alternatively, a single
    KEYBINDING subelement may be used instead.
    950 If the class has more than one key property, a KEYBINDING subelement shall appear for each key.
    951 If no key-bindings are specified, the instance is assumed to be a singleton instance of a keyless class.
    <!ELEMENT INSTANCENAME (KEYBINDING* | KEYVALUE? | VALUE.REFERENCE?)>
    <!ATTLIST INSTANCENAME
    %ClassName;>
* OpenEnumerateInstancePaths Per DSP0200 the return element is InstancePath is to be returned.  DSP0200 defines this as "The INSTANCEPATH element defines the absolute path to a CIM instance.". It consists of <!ELEMENT INSTANCEPATH (NAMESPACEPATH, INSTANCENAME)>. See section 5.3.4.8

The same difference applies to associatornames, and referencenames.

Thus there is a basic incoherence between what the Open...  requests return and what the traditional requests return.  One returns <InstanceName>, the other returns <InstancePath><InstanceName> At that time we never conceived that they would be merged into a single return and, in fact, the traditional  operations had been deprecated. So much for history.

Thus  when we integrated them into the iter... operations, we tried to return the maximum information possible and keep the user from knowing which operation had been used.

**Comment by KSchopmeyer** [comment]
From The DMTF specifications:

* EnumerateInstances returns a list of the element <NamedInstance>
* OpenEnumerateInstances returns a list of the element <instanceWithPath>

Where:

* <NamedInstance> is defined as : <!ELEMENT VALUE.NAMEDINSTANCE (INSTANCENAME, INSTANCE)>
* <InstanceWithPath> is defined as : <!ELEMENT VALUE.INSTANCEWITHPATH (INSTANCEPATH, INSTANCE)>

and:

*<NAMEDINSTANCE> is: 
*

**Comment by KSchopmeyer** [comment]
The same applies to the corresponding Names operations (ex. EnumerateInstanceNames)

**Comment by KSchopmeyer** [comment]
The associators and references requests differ from EnumerateInstances in the definition of object returned:

* Associators/References returns OBJECTWITHPATH which is already an object that includes host name.
* OpenAssociatorInstances/OpenReferenceInstances returns INSTANCEWITHPATH which is similar to OBJECTWITHPATH except that it allows only instances.
* IterAssociatorInstances/IterReferenceInstances does not attempt to test for existence of host or namespace or to modify the request responses.

Thus these operations are always expected to return host name.  The code in pywbem _cimoperations.py does NOT test for the existence of namespace or host value in either of these responses but passes the returned value to the method response.  This differs, therefore, from the return for Enumerate where we attempt to fill in both namespace and host if they are None in the resulting path response component.
