### ISSUE TITLE
Clarify the timeout usage.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2853]
The timeout in CIMOperations can be confusing becuase the actual timeout of a command may differ significanly from this value because the time to actual failure is much more complex that a single timeout.  It may include scenarios like:

1. Single timeouts corrected on retry in different parts of the response which accumulate to a total that triggers the retry exception.
2. Multiple retries (today 2 retries) before the timeout exception occurs so that the actual timeout is 3 times the value of the timeout parameter.

However, we return only the fact that it was a timeout or retry error and the timeout value for the single operation that was defined with the timeout parameter.

I propose that we should clarify this.

1. Document the actual behavior as best as we can.
2. Consider how we can provide more information with the timeout and retry exceptions.  Note that today the information in these exceptions comes from httplib3 as part of the exception.   For the timeout exception the added message simply states read timeout=<timeout value provided to WBEMConnection> (Example in the pywbemtools issue).  I don't yet know what message is provided with the retry exception.

**Comment by andy-maier** [comment]
After reading the current description for the timeout parameter, I think we also need to clarify that it is only the timeout for sending a request, and not for performing the requested operation.
