### ISSUE TITLE
Add optional arguments to WBEMConnection to set more ssl/tls parameters

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#286]
1. Should be able to set the minimum TLS/SSL on the command line.  Right now it is fixes at SSL23 which is well below norms.  Note that the server is the ultimate check but no reason we cannot bring this out to public view.  We would need to discuss the default since the most logical/secure but the easiest would be to set it low and let the server decide.  This would be in the form of a set of keywords that WBEMConnection would translate to SSL constants (ex. SSL2 SSl3 SSL23 TLS1.0 TLS1.1 TLS 1.2, etc.
2. Possibly set preferred ciphers.  This one is more problamatic and it is the server who is the ultimate arbitrator but we can make choices in the client.  The default would to be let the implementation decide.  This one can be problematic since the list of ciphers is implementation dependent and there are so many of them now.   However, the normal preferred list is actually very small, especially in SNIA and changing all the time.

While we decided before that the server is the ultimate arbitrator, there is no reason the client cannot make minimum level security demands.  In particular as we add config mechanisms to tools, it will be logical for the client to set minimums.

No milestone set since I believe this is after 0.9.0

**Comment by andy-maier** [comment]
I did set the milestone by mistake - I agree this should be after 0.9.0.

**Comment by KSchopmeyer** [comment]
Karl will discuss with some client writers.

**Comment by andy-maier** [comment]
**Discussion points**:

* Do we know what client writers think about this?

**Comment by KSchopmeyer** [comment]
We concluded that there is probably no reason.

One possible case is where the server is returning a weak cipher but the client wants to get the server to force a stronger cipher.

We do not have a clean customer requirement today.  Lets wait for customer input here.

**Comment by KSchopmeyer** [comment]
Karl will ask the question of the SNIA security group and if there is no real interest, we will simply close the issue

**Comment by KSchopmeyer** [comment]
close as nobody interested.
