### ISSUE TITLE
Support logging to the system log

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#294]
Add infrastructure to log to the system log.

Also, change the debug prints added in PR #290 / #293 into system log calls.

**Comment by KSchopmeyer** [comment]
Move to 0.10.0

**Comment by andy-maier** [comment]
Log these specific situations:
- Unknown IPARAMVALUE elements for output parameters of operations (e.g. pull)
- Namespace not set in instance path, when returning instances with path (e.g. ei)

**Comment by andy-maier** [comment]
We agreed not to implement creating logs for such cases, but to issue Python warnings (e.g. see UserWarning in tupleparse)

TODO: Verify what we should do in the cases listed above.

**Comment by andy-maier** [comment]
The situations mentioned above are handled as follows:

* Unknown IPARAMVALUE elements for output parameters of operations (e.g. pull):
  Actually this is about PARAMVALUE. PR #1322 introduces checks for that and raises a ParseError in all cases of unexpected elements.

* Namespace not set in instance path, when returning instances with path (e.g. ei):
  In all cases where returned objects do not have a namespace by design of the CIM-XML protocol, pywbem adds the effective target namespace. In all cases where returned objects must have a namespace by design of the CIM-XML protocol, a missing namespace causes a ParseError to be raised. In all cases where returned objects have an optional namespace, the namespace will be present if returned by the server (ExecQuery is the only such case).

As a result, no further changes are needed. Closing this issue.
