### ISSUE TITLE
Drop the tunnel variable on httpsConnection

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#296]

**Comment by KSchopmeyer** [comment]
The code in question is in cim_http.py:
    self.sock = socket.create_connection(...)
    if self._tunnel_host:
        self._tunnel()

The tunnel attribute is part of httplib. There are properties for
        self._tunnel_host = None
        self._tunnel_port = None
The _tunnel... attributes are used with https and proxy servers. 


the httplib HTTPConnection _tunnel() function executes a connect to what is defined as the proxy using information from
self._tunnel_host and self._tunnel_port.  It excepts with an HTTP error if the connect fails.
Thus, in theory, if self._tunnel_host is not None, httplib tries to connect to the defined proxy host on the defined socket.

 Our first issue is that we really do not have a proxy environment so cannot test this

There are two separate tunnel functions in httplib  HTTPConnection.
1. Set with a required host parameter that sets the tunneling parameters from host, port, headers parameters in the call.
    def set_tunnel(self, host, port=None, headers=None):
        """ Sets up the host and the port for the HTTP CONNECT Tunnelling.

        The headers argument should be a mapping of extra HTTP headers
        to send with the CONNECT request.
       """

2. httplib HTTPConnection._tunnel(self) executes a connect to the host and port defined in set_tunnel()

In the httplib HTTPConnection class, the connect() function executes
    connect()
        ....
        if self._tunnel_host:
            self._tunnel()
        ...

in the httplib HTTPSConnection class is a subclass of HTTPConnection and its connect() method effectively does the same thing.

        def connect(self):
            "Connect to a host on a given (SSL) port."

            sock = socket.create_connection((self.host, self.port),
                                            self.timeout, self.source_address)
            if self._tunnel_host:
                self.sock = sock
                self._tunnel()
            self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)

So apparently when we did our own HTTPS connect we did sort of the same thing by simply adding the two lines to set call the tunnel() function if a _tunnel_host exists.

Second issue that it is really unclear where in  the pywbem environment, the proxy host, etc. arguments would ever be set. They are not part of the pywbem HTTP connection mechanism. in WBEMConnection,  we execute the connect at the time of the send (however, that is not clearly documented). If a user had proxy requirements I am assuming that they could do

CONN = WBEMConnection(...)
CONN= CONN.set_tunnel(host, ...)
after the WBEMConnection and before the first send execution (i.e. the first wbem operation)
(remember that I have not tried any of this)

By the way, it is not at all certain that this really works with HTTPS since there is a lot more two-way communication and it is clear that as of about a year ago HTTPS proxing on the requests package was apparently broken.

1. For HTTPConnection, pywbem just uses the httplib functions so any tunneling works as well with pywbem as with other httplib users of HTTP.
2. For HTTPSConnection, it is not clear

**Comment by andy-maier** [comment]
It seems to me we should drop the tunnel support.

**Comment by KSchopmeyer** [comment]
Either that or make it work right.  Note that if we were to move to requests it all changes again.
DISCUSSION: Drop tunnel support

**Comment by KSchopmeyer** [comment]
We propose to get rid of this and wait for customer requirements. We agreed to do this for 0.8.4

**Comment by KSchopmeyer** [comment]
Modified name

**Comment by andy-maier** [comment]
PR #310 removes the tunneling support for 0.8.

**TODO:** Roll that change forward into master branch.

**Comment by andy-maier** [comment]
PR #311 removes the tunneling support for the master branch.
