### ISSUE TITLE
Change Makefile so safety issues failure is not test failure

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2970]
We are getting a significant number of new security issues now so that our build is down the first of about every month for possibly multiple days while we sort out issues.  I propose that we discuss that we consider making the security checks non-critical so that they do not stop the build at least for the nightly build.

Since the safety issue list is updated once a month we could set up a first of month test that does fail to be sure we get a flag on safety issues.

**Comment by andy-maier** [comment]
I suggest that we this in two stages:
* Stage 1: Simply tolerate non-zero return codes in the Makefile
* Stage 2: Set up a separate GitHub Actions workflow to run the safety check separately, and then that separate workflow can fail while the test workflow succeeds.

**Comment by andy-maier** [comment]
We agreed to implement stage 1 for 1.6.0.

**Comment by andy-maier** [comment]
I have created issue #2977 for stage 2, so this issue can be closed as resolved by PR #2975.
