### ISSUE TITLE
Is there any workaround for bugs in a vendor CIM imlementation?

### ISSUE THREAD

**Issue by M-Startc** [pywbem/pywbem#2991]
I have very simple code  
```
--------------------
url = 'https://<some ip>:5989'
user = 'admin_user'         
password = 'some_password'   
namespace = 'root/ibm'  

creds = (user, password)

conn  = pywbem.WBEMConnection(url, creds, no_verification=True)
cim_enum = pywbem.ValueMapping.for_property(conn, 'root/ibm', 'IBMTSSVC_Cluster', 'Dedicated')
--------------
```

and now I have the error
```
----------------
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\user\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\user\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\user\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\user\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\user\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\user\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\_work-materials\_currWork\CIM\Get_CIM_Info\cim_enum_issue.py", line 15, in <module>
    cim_enum = pywbem.ValueMapping.for_property(conn, 'root/ibm', 'IBMTSSVC_Cluster', 'Dedicated')       
  File "c:\_work-materials\_currWork\CIM\Get_CIM_Info\venv\lib\site-packages\pywbem\_valuemapping.py", line 270, in for_property
    new_vm = cls._create_for_element(property_obj, conn, namespace,
  File "c:\_work-materials\_currWork\CIM\Get_CIM_Info\venv\lib\site-packages\pywbem\_valuemapping.py", line 590, in _create_for_element
    values_str = values_list[i]
IndexError: list index out of range
----------
```

the piece of library code that generates the error is 
```
----------
            valuemap_list = valuemap_qual.value
            for i, valuemap_str in enumerate(valuemap_list):
                values_str = values_list[i]
----------
```
As I understand  the issue reason is that the lengths of `valuemap_list` and `value_list` are not the same.
The `valuemap_list` content is 
```
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '28..32567', '32568..65535']
```
And it's lengtht is 32

The `value_list` is 
```
['Not Dedicated', 'Unknown', 'Other', 'Storage', 'Router', 'Switch', 'Layer 3 Switch', 'Central Office Switch', 'Hub', 'Access Server', 'Firewall', 'Print', 'I/O', 'Web Caching', 'Management', 'Block Server', 'File Server', 'Mobile User Device', 'Repeater', 'Bridge/Extender', 'Gateway', 'Storage Virtualizer', 'Media Library', 'ExtenderNode', 'NAS Head', 'Self-contained NAS', 'UPS', 'IP Phone', 'Management Controller', 'Chassis Manager', 'DMTF Reserved']
```
And it's lengtht is 31

The source of the error is the mistake in `class_obj` that is returned in 259 line of `pywbem\_valuemapping.py` file
```
--------
        class_obj = get_class(ClassName=classname,
                              namespace=namespace,
                              LocalOnly=False,
                              IncludeQualifiers=True)
--------
```
As i understand the error comes from this enum implementatoin in CIM server, i.e. the last `value_list` value looks lost in IBM firmware.

In other devices i.e. DS8000 the `Dedicated` enumeration has additional element `Vendor Reserved` for `value_list` that is  corresponding  to the `32568..65535` element of the `valuemap_list`

Is there any workaround possible to skip last value `32568..65535` in `valuemap_list` or substitute `Vendor Reserved` to `value_list`?
And another question 
Is there any general hint to protect my code from mistakes in a CIM implementation?

**Comment by andy-maier** [comment]
Sorry for the delay. I try to do something about that in pywbem. Stay tuned.

**Comment by andy-maier** [comment]
First of all, I looked up DSP0004 to see if it has any provisions for the case of non-matching sizes of the Values and ValueMap arrays, but it does not (other than requiring that the sizes must match).

From the qualifiers you showed, one can guess that the difference is in the last array items:
ValueMap: `'28..32567', '32568..65535'`
Values: `'DMTF Reserved'`

Besides the fact that they probably meant to write 32767/8 and not 32567/8, it is not clear what the intention was to which of these two ValueMap items the one Values item should map.

So in pywbem, we cannot solve this problem (and other such problems) semantically correct, but we can lower the impact and have a reasonable default rule. For example, we can use an empty string for missing Values items, which would always be applied at the end of the array.

**Comment by andy-maier** [comment]
@M-Startc  I have created PR #3000 that has the following solution:

If the sizes of the Values and ValueMap arrays differ, the default behavior is that a pywbem.ModelError exception will be raised. Alternatively, the behavior can be changed to have the Values array adjusted to the size of the ValueMap array, by filling in any missing items at the end with a default value, or by truncating any extra items.

Please let us know whether this solution works for you.

**Comment by andy-maier** [comment]
@M-Startc On your question:
> Is there any general hint to protect my code from mistakes in a CIM implementation?

pywbem tries to be tolerant against mistakes in a CIM implementation where possible. Where not possible, it raises pywbem.ModelError to make a clear statement to the user about that. These cases are documented on each method that can possibly raise that exception. If you get that exception, there is very likely an error in the CIM implementation, and in such cases pywbem was not able to figure out what to do, and has to leave it to the user to handle.

**Comment by M-Startc** [comment]
@andy-maier Hello
I tested the new paramater and it vorks in my case. I think it will be enough for now. Thank you.

I just want to note that in my specific case the element at the border of the Values was lost. But it may be the other case when an element be lost in the middle of Values/ValueMap sequence. So ... as an idea ...  may be add an ability to overwrite the both Values and ValueMap with sending a tuple like (( <values> ), ( <value_map> )) ?

But in any case  current solution is ok for my case
Thank you one again  :-)
Regards
