### ISSUE TITLE
Use lxml or cElementTree for xml parsing/serializing.

### ISSUE THREAD

**Issue by skolsuper** [pywbem/pywbem#300]
The stdlib xml module, especially minidom, can be [extremely slow](http://effbot.org/zone/celementtree.htm#benchmarks) in some cases.  There are drop in replacements that could be used.  In the process of overriding the `imethodcall` method of `WBEMConnection`, I noticed that the function is divided into 3 parts by comments, basically:
1. serialize request
2. make request
3. parse response

It would be good if the imethodcall and methodcall functions would delegate serialize and parse to other methods then it would be easier to override this behaviour in subclasses.  Otherwise, maybe look into using `cElementTree` or `lxml.etree` inside `cim_xml`.

**Comment by andy-maier** [comment]
I suggest to go to lxml.etree.

**Comment by KSchopmeyer** [comment]
questions:

1. determine what the difference in performance is between the two.

**Comment by KSchopmeyer** [comment]
We see no reason today to go from the sax parser we started using in 2016 to lxml.

Andy did note that we do intend to remove the use of the minidom for pretty printing. See issue # 579.

We are therefore closing this issue.
