### ISSUE TITLE
Release v0.8.4

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#306]
TODOs:

* Open issues:
  - DONE: Issue #294: Moved out to 0.9.
  - DONE: Issue #296: Moved in to 0.8.4, for general code sanity (tunnel support had been removed for the py3 path already). Has been merged.
  - DONE: Issue #309: Has been reviewed and tested, and merged.

* Testing:
  - DONE: SSL tests - Karl's tests run fine with stable_0.8 as of commit d6bf75e.
  - DEFERRED: MOF roundtrip tests not possible with 0.8. Deferred to 0.9.

* Release to PyPI:
 - DONE: Made decision to release (Karl&Andy)
 - TODO(Andy): Release according to the procedure in [DEVELOP.md](https://github.com/pywbem/pywbem/blob/stable_0.8/DEVELOP.md), verifying the steps again.

**Comment by KSchopmeyer** [comment]
+1 Karl agrees that this is what we want for this release.

**Comment by andy-maier** [comment]
[pywbem v0.8.4](https://github.com/pywbem/pywbem/releases/tag/v0.8.4) has just been released!
