### ISSUE TITLE
python 3.12 setup fails withResolutionT00Deep

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#3102]
Collecting jupyter-lsp>=2.0.0 (from jupyterlab<5,>=4.0.2->-r dev-requirements.txt (line 283))
  Downloading jupyter_lsp-2.2.1-py3-none-any.whl.metadata (1.8 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Collecting pip-check-reqs!=2.5.0,>=2.4.3 (from -r dev-requirements.txt (line 348))
  Downloading pip_check_reqs-2.5.1-py3-none-any.whl.metadata (8.6 kB)
  Downloading pip_check_reqs-2.4.4-py3-none-any.whl (12 kB)
  Downloading pip_check_reqs-2.4.3-py3-none-any.whl (12 kB)
Collecting jupyterlab<5,>=4.0.2 (from -r dev-requirements.txt (line 283))
  Downloading jupyterlab-4.0.10-py3-none-any.whl.metadata (15 kB)
  Downloading jupyterlab-4.0.9-py3-none-any.whl.metadata (15 kB)
  Downloading jupyterlab-4.0.8-py3-none-any.whl.metadata (15 kB)
  Downloading jupyterlab-4.0.7-py3-none-any.whl.metadata (15 kB)
  Downloading jupyterlab-4.0.6-py3-none-any.whl.metadata (15 kB)
  Downloading jupyterlab-4.0.5-py3-none-any.whl.metadata (15 kB)
  Downloading jupyterlab-4.0.4-py3-none-any.whl.metadata (15 kB)
  Downloading jupyterlab-4.0.3-py3-none-any.whl.metadata (15 kB)
  Downloading jupyterlab-4.0.2-py3-none-any.whl.metadata (15 kB)
Collecting jupyterlab-server<3,>=2.22.1 (from -r dev-requirements.txt (line 279))
  Downloading jupyterlab_server-2.25.1-py3-none-any.whl.metadata (5.9 kB)
  Downloading jupyterlab_server-2.25.0-py3-none-any.whl.metadata (5.9 kB)
  Downloading jupyterlab_server-2.24.0-py3-none-any.whl.metadata (5.8 kB)
  Downloading jupyterlab_server-2.23.0-py3-none-any.whl.metadata (5.8 kB)
  Downloading jupyterlab_server-2.22.1-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 12.7 MB/s eta 0:00:00
Collecting notebook>=7.0.2 (from -r dev-requirements.txt (line 271))
  Downloading notebook-7.0.6-py3-none-any.whl.metadata (10 kB)
Collecting nbconvert>=7.7.3 (from -r dev-requirements.txt (line 253))
  Downloading nbconvert-7.14.1-py3-none-any.whl.metadata (7.7 kB)
  Downloading nbconvert-7.14.0-py3-none-any.whl.metadata (7.7 kB)
  Downloading nbconvert-7.13.1-py3-none-any.whl.metadata (7.7 kB)
  Downloading nbconvert-7.13.0-py3-none-any.whl.metadata (7.7 kB)
  Downloading nbconvert-7.12.0-py3-none-any.whl.metadata (7.7 kB)
  Downloading nbconvert-7.11.0-py3-none-any.whl.metadata (7.7 kB)
  Downloading nbconvert-7.10.0-py3-none-any.whl.metadata (7.8 kB)
  Downloading nbconvert-7.9.2-py3-none-any.whl.metadata (7.9 kB)
  Downloading nbconvert-7.9.1-py3-none-any.whl.metadata (7.9 kB)
  Downloading nbconvert-7.9.0-py3-none-any.whl.metadata (7.9 kB)
  Downloading nbconvert-7.8.0-py3-none-any.whl.metadata (8.0 kB)
  Downloading nbconvert-7.7.4-py3-none-any.whl.metadata (8.0 kB)
  Downloading nbconvert-7.7.3-py3-none-any.whl.metadata (8.0 kB)
Collecting jupyter-server>=2.4.0 (from -r dev-requirements.txt (line 229))
  Downloading jupyter_server-2.12.4-py3-none-any.whl.metadata (8.4 kB)
  Downloading jupyter_server-2.12.3-py3-none-any.whl.metadata (8.4 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
make: *** [Makefile:525: done/develop_py3.12_latest.done] Error 2
Error: Process completed with exit code 2.
0s
0s
0s

**Comment by andy-maier** [comment]
When using PR #3107 I could not reproduce this issue.

**Comment by KSchopmeyer** [comment]
This issue apparently caused by issue #3107 -

**Comment by KSchopmeyer** [comment]
Close as resolved by issue #3107
