### ISSUE TITLE
Warning produced by pylint

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#3113]
Pylint issues following warnings with python 3.6 and python 3.7 running CI tests in the python 3.12 branch but only with PACKAGE_LEVEL=minimum. All other tests pass.

NOTE: This is issue on working branch ks/#3098-python312-#3097-fix](https://github.com/pywbem/pywbem/tree/ks/%233098-python312-%233097-fix)  PR #3110

1. Python 3.6 - Generates 

    tests/functiontest/conftest.py:1:0: W0612: Unused variable 'exp_result' (unused-variable)

There is no exp_result in the first line of this file .

2. Pytnon 3.7 - Generates warning:
 
     warnings.warn("Setuptools is replacing distutils.")

**Comment by KSchopmeyer** [comment]
The complete output is:

Run make pylint
Makefile: Running Pylint
rm -f done/pylint_py3.7_minimum.done
pylint --version
/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
pylint 2.13.0
astroid 2.11.0
Python 3.7.17 (default, Jun 23 2023, 13:13:52) 
[GCC 11.3.0]
  warnings.warn("Setuptools is replacing distutils.")
pylint --enable=fixme --rcfile=pylintrc setup.py pywbem/__init__.py pywbem/_cim_constants.py pywbem/_cim_http.py pywbem/_cim_obj.py pywbem/_cim_operations.py pywbem/_cim_types.py pywbem/_cim_xml.py pywbem/_cliutils.py pywbem/_exceptions.py pywbem/_features.py pywbem/_listener.py pywbem/_logging.py pywbem/_mof_compiler.py pywbem/_nocasedict.py pywbem/_recorder.py pywbem/_server.py pywbem/_statistics.py pywbem/_subscription_manager.py pywbem/_tupleparse.py pywbem/_tupletree.py pywbem/_units.py pywbem/_utils.py pywbem/_valuemapping.py pywbem/_version.py pywbem/_warnings.py pywbem/config.py pywbem_mock/__init__.py pywbem_mock/_baseprovider.py pywbem_mock/_baserepository.py pywbem_mock/_dmtf_cim_schema.py pywbem_mock/_inmemoryrepository.py pywbem_mock/_instancewriteprovider.py pywbem_mock/_mainprovider.py pywbem_mock/_methodprovider.py pywbem_mock/_mockmofwbemconnection.py pywbem_mock/_namespaceprovider.py pywbem_mock/_providerdependentregistry.py pywbem_mock/_providerdispatcher.py pywbem_mock/_providerregistry.py pywbem_mock/_resolvermixin.py pywbem_mock/_subscriptionproviders.py pywbem_mock/_utils.py pywbem_mock/_wbemconnection_mock.py pywbem_mock/config.py mof_compiler 
/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

------------------------------------
Your code has been rated at 10.00/10

pylint --disable=fixme --rcfile=pylintrc tests/__init__.py tests/elapsed_timer.py tests/utils.py tests/end2endtest/__init__.py tests/end2endtest/test_indications.py tests/end2endtest/test_operation_timeouts.py tests/end2endtest/test_profile_generic.py tests/end2endtest/test_profile_snia_server.py tests/end2endtest/test_profile_snia_smis.py tests/end2endtest/test_server.py tests/functiontest/__init__.py tests/functiontest/conftest.py tests/leaktest/__init__.py tests/leaktest/test_leaks_cim_obj.py tests/leaktest/test_leaks_cim_xml.py tests/leaktest/test_leaks_dict.py tests/leaktest/test_leaks_elementtree.py tests/leaktest/test_leaks_minidom.py tests/leaktest/test_leaks_statistics.py tests/manualtest/__init__.py tests/manualtest/run_cim_operations.py tests/manualtest/run_enum_performance.py tests/manualtest/run_enum_performancesimple.py tests/manualtest/run_operationtimeouts.py tests/manualtest/run_response_performance.py tests/manualtest/run_uprint.py tests/perftest/__init__.py tests/perftest/test_indications.py tests/resourcetest/__init__.py tests/resourcetest/memory_utils.py tests/resourcetest/random_objects.py tests/resourcetest/resource_measurement.py tests/resourcetest/test_enuminst.py tests/resourcetest/timers.py tests/unittest/__init__.py tests/end2endtest/utils/__init__.py tests/end2endtest/utils/assertions.py tests/end2endtest/utils/pytest_extensions.py tests/end2endtest/utils/utils.py tests/unittest/end2endtest_utils/__init__.py tests/unittest/functiontest/__init__.py tests/unittest/functiontest/test_conftest.py tests/unittest/pywbem/__init__.py tests/unittest/pywbem/test_cim_http.py tests/unittest/pywbem/test_cim_obj.py tests/unittest/pywbem/test_cim_operations.py tests/unittest/pywbem/test_cim_types.py tests/unittest/pywbem/test_cim_xml.py tests/unittest/pywbem/test_exceptions.py tests/unittest/pywbem/test_indicationlistener.py tests/unittest/pywbem/test_itermethods.py tests/unittest/pywbem/test_logging.py tests/unittest/pywbem/test_mof_compiler.py tests/unittest/pywbem/test_nocasedict.py tests/unittest/pywbem/test_perf_equality.py tests/unittest/pywbem/test_recorder.py tests/unittest/pywbem/test_statistics.py tests/unittest/pywbem/test_subscriptionmanager.py tests/unittest/pywbem/test_tupleparse.py tests/unittest/pywbem/test_tupletree.py tests/unittest/pywbem/test_units.py tests/unittest/pywbem/test_utils.py tests/unittest/pywbem/test_valuemapping.py tests/unittest/pywbem/test_warnings.py tests/unittest/pywbem/test_wbemserverclass.py tests/unittest/pywbem_mock/__init__.py tests/unittest/pywbem_mock/conftest.py tests/unittest/pywbem_mock/test_complexassoc.py tests/unittest/pywbem_mock/test_inmemory_repository.py tests/unittest/pywbem_mock/test_multi_ns_assoc.py tests/unittest/pywbem_mock/test_providerdependentregistry.py tests/unittest/pywbem_mock/test_providerregistry.py tests/unittest/pywbem_mock/test_system_providers.py tests/unittest/pywbem_mock/test_wbemconnection_mock.py tests/unittest/resourcetest/__init__.py tests/unittest/resourcetest/test_memory_utils.py tests/unittest/unittest_utils/__init__.py tests/unittest/utils/__init__.py tests/unittest/utils/dmtf_mof_schema_def.py tests/unittest/utils/pytest_extensions.py tests/unittest/utils/unichr2.py tests/unittest/utils/unittest_extensions.py tests/unittest/utils/validate.py tests/unittest/utils/wbemserver_mock.py  
/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
************* Module tests.functiontest.conftest
tests/functiontest/conftest.py:1:0: W0612: Unused variable 'exp_result' (unused-variable)

------------------------------------
Your code has been rated at 10.00/10

make: *** [Makefile:766: done/pylint_py3.7_minimum.done] Error 4
Error: Process completed with exit code 2.

**Comment by KSchopmeyer** [comment]
Python 3.7, 

```
Run make pylint
Makefile: Running Pylint
rm -f done/pylint_py3.7_minimum.done
pylint --version
/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
pylint 2.13.0
astroid 2.11.0
Python 3.7.17 (default, Jun 23 2023, 13:13:52) 
[GCC 11.3.0]
  warnings.warn("Setuptools is replacing distutils.")
pylint --enable=fixme --rcfile=pylintrc setup.py pywbem/__init__.py pywbem/_cim_constants.py pywbem/_cim_http.py pywbem/_cim_obj.py pywbem/_cim_operations.py pywbem/_cim_types.py pywbem/_cim_xml.py pywbem/_cliutils.py pywbem/_exceptions.py pywbem/_features.py pywbem/_listener.py pywbem/_logging.py pywbem/_mof_compiler.py pywbem/_nocasedict.py pywbem/_recorder.py pywbem/_server.py pywbem/_statistics.py pywbem/_subscription_manager.py pywbem/_tupleparse.py pywbem/_tupletree.py pywbem/_units.py pywbem/_utils.py pywbem/_valuemapping.py pywbem/_version.py pywbem/_warnings.py pywbem/config.py pywbem_mock/__init__.py pywbem_mock/_baseprovider.py pywbem_mock/_baserepository.py pywbem_mock/_dmtf_cim_schema.py pywbem_mock/_inmemoryrepository.py pywbem_mock/_instancewriteprovider.py pywbem_mock/_mainprovider.py pywbem_mock/_methodprovider.py pywbem_mock/_mockmofwbemconnection.py pywbem_mock/_namespaceprovider.py pywbem_mock/_providerdependentregistry.py pywbem_mock/_providerdispatcher.py pywbem_mock/_providerregistry.py pywbem_mock/_resolvermixin.py pywbem_mock/_subscriptionproviders.py pywbem_mock/_utils.py pywbem_mock/_wbemconnection_mock.py pywbem_mock/config.py mof_compiler 
/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

==================================
Your code has been rated at 10.00/10

pylint --disable=fixme --rcfile=pylintrc tests/__init__.py tests/elapsed_timer.py tests/utils.py tests/end2endtest/__init__.py tests/end2endtest/test_indications.py tests/end2endtest/test_operation_timeouts.py tests/end2endtest/test_profile_generic.py tests/end2endtest/test_profile_snia_server.py tests/end2endtest/test_profile_snia_smis.py tests/end2endtest/test_server.py tests/functiontest/__init__.py tests/functiontest/conftest.py tests/leaktest/__init__.py tests/leaktest/test_leaks_cim_obj.py tests/leaktest/test_leaks_cim_xml.py tests/leaktest/test_leaks_dict.py tests/leaktest/test_leaks_elementtree.py tests/leaktest/test_leaks_minidom.py tests/leaktest/test_leaks_statistics.py tests/manualtest/__init__.py tests/manualtest/run_cim_operations.py tests/manualtest/run_enum_performance.py tests/manualtest/run_enum_performancesimple.py tests/manualtest/run_operationtimeouts.py tests/manualtest/run_response_performance.py tests/manualtest/run_uprint.py tests/perftest/__init__.py tests/perftest/test_indications.py tests/resourcetest/__init__.py tests/resourcetest/memory_utils.py tests/resourcetest/random_objects.py tests/resourcetest/resource_measurement.py tests/resourcetest/test_enuminst.py tests/resourcetest/timers.py tests/unittest/__init__.py tests/end2endtest/utils/__init__.py tests/end2endtest/utils/assertions.py tests/end2endtest/utils/pytest_extensions.py tests/end2endtest/utils/utils.py tests/unittest/end2endtest_utils/__init__.py tests/unittest/functiontest/__init__.py tests/unittest/functiontest/test_conftest.py tests/unittest/pywbem/__init__.py tests/unittest/pywbem/test_cim_http.py tests/unittest/pywbem/test_cim_obj.py tests/unittest/pywbem/test_cim_operations.py tests/unittest/pywbem/test_cim_types.py tests/unittest/pywbem/test_cim_xml.py tests/unittest/pywbem/test_exceptions.py tests/unittest/pywbem/test_indicationlistener.py tests/unittest/pywbem/test_itermethods.py tests/unittest/pywbem/test_logging.py tests/unittest/pywbem/test_mof_compiler.py tests/unittest/pywbem/test_nocasedict.py tests/unittest/pywbem/test_perf_equality.py tests/unittest/pywbem/test_recorder.py tests/unittest/pywbem/test_statistics.py tests/unittest/pywbem/test_subscriptionmanager.py tests/unittest/pywbem/test_tupleparse.py tests/unittest/pywbem/test_tupletree.py tests/unittest/pywbem/test_units.py tests/unittest/pywbem/test_utils.py tests/unittest/pywbem/test_valuemapping.py tests/unittest/pywbem/test_warnings.py tests/unittest/pywbem/test_wbemserverclass.py tests/unittest/pywbem_mock/__init__.py tests/unittest/pywbem_mock/conftest.py tests/unittest/pywbem_mock/test_complexassoc.py tests/unittest/pywbem_mock/test_inmemory_repository.py tests/unittest/pywbem_mock/test_multi_ns_assoc.py tests/unittest/pywbem_mock/test_providerdependentregistry.py tests/unittest/pywbem_mock/test_providerregistry.py tests/unittest/pywbem_mock/test_system_providers.py tests/unittest/pywbem_mock/test_wbemconnection_mock.py tests/unittest/resourcetest/__init__.py tests/unittest/resourcetest/test_memory_utils.py tests/unittest/unittest_utils/__init__.py tests/unittest/utils/__init__.py tests/unittest/utils/dmtf_mof_schema_def.py tests/unittest/utils/pytest_extensions.py tests/unittest/utils/unichr2.py tests/unittest/utils/unittest_extensions.py tests/unittest/utils/validate.py tests/unittest/utils/wbemserver_mock.py  
/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
************* Module tests.functiontest.conftest
tests/functiontest/conftest.py:1:0: W0612: Unused variable 'exp_result' (unused-variable)

------------------------------------
Your code has been rated at 10.00/10

make: *** [Makefile:766: done/pylint_py3.7_minimum.done] Error 4
Error: Process completed with exit code 2.

**Comment by andy-maier** [comment]
The pylint failures on py36/37-min are not caused by the userwarning, but by:
```
tests/functiontest/conftest.py:1:0: W0612: Unused variable 'exp_result' (unused-variable)
```
This only occurs with pylint==2.13.0, and no longer with 2.13.1.

Nevertheless, the solution should be to change in conftest.py (occurs 2 times):
```
result = namedtuple("exp_result",  ...
```
to:
```
result = namedtuple("result",  ...
```
