### ISSUE TITLE
RFE: drop python<=3.7 support and use of `six`

### ISSUE THREAD

**Issue by kloczek** [pywbem/pywbem#3138]
As it is now added urllib3 2.x support is it not would be good to start cleaning code and:
-  remove python 2.x and python<=3.7 support dropping
-  drop use of ``six`

IMO it could be done after next version (1.6.4?) would be good to start working on `pywbem` 2.x announcing that 1.6.x will be backported only critical changes.

PS. Just checked and `pyupgrade --py38-plus` generates almost 1MB patch and ruff probably would be able to generate even more cleanups .. so it is a lot of things which could be dropped making whole code much cleaner.

**Comment by andy-maier** [comment]
Hi Tomasz @kloczek
We'll discuss that today.

**Comment by andy-maier** [comment]
@tasleson Tony, do you have an opinion on this proposal from  RHEL perspective?

**Comment by tasleson** [comment]
> @tasleson Tony, do you have an opinion on this proposal from RHEL perspective?

I think this should be fine.  However, please remember that Fedora is packaging `0.17.6` and carrying it's own internal patches for things we run into as that was the last version before code functionality was broken out into separate libraries.  RHEL is at `0.15.0`  Until that is solved we won't be picking up any new versions of pywbem.

**Comment by andy-maier** [comment]
@tasleson Tony, we want to vendor in nocasedict and nocaselist to pywbem. That would allow you to go to newer versions. 

If you considered going to such a new version of pywbem, would you then still be ok with us dropping support for Python 2.7, 3.6 and 3.7?

**Comment by andy-maier** [comment]
Our thought is to release pywbem 1.7.0 with nocasedict/nocaselist vendored in and no drop in support of Python versions. In pywbem 1.8.0, we would then drop Python 2.7, 3.6, 3.7.

**Comment by tasleson** [comment]
> If you considered going to such a new version of pywbem, would you then still be ok with us dropping support for Python 2.7, 3.6 and 3.7?

RHEL9 uses python 3.9 which is the oldest shipping version of RHEL that we could possibly pickup a newer pywbem release.  Given that I see no reason against dropping  the versions you list.

**Comment by andy-maier** [comment]
@kloczek Hi Tomasz, I have run "ruff pywbem" and it did not report any issues.

**Comment by kloczek** [comment]
I started working on this RFE and on top of what generated `pyupgrade` I made have another 30KB other cleanups after which ruffs was able to generate another 6KB patch removing many imports. on top of which ruff with --unsafe-fixes generated another ~3kb patch
```coneole
[tkloczko@pers-jacek SOURCES]$ ls -l python-pywbem-*.patch
-rw-r--r-- 1 tkloczko tkloczko    117 Apr  5 22:50 python-pywbem-add_pytest_testpaths.patch
-rw-r--r-- 1 tkloczko tkloczko  37720 Apr  5 22:59 python-pywbem-post_pyupgrade_py38.patch
-rw-r--r-- 1 tkloczko tkloczko    686 Apr  5 22:50 python-pywbem-post_pyupgrade_py39.patch
-rw-r--r-- 1 tkloczko tkloczko 996892 Apr  5 22:51 python-pywbem-pyupgrade_py38.patch
-rw-r--r-- 1 tkloczko tkloczko  24438 Apr  5 22:50 python-pywbem-pyupgrade_py39.patch
-rw-r--r-- 1 tkloczko tkloczko   6135 Apr  8 20:46 python-pywbem-ruff.patch
-rw-r--r-- 1 tkloczko tkloczko   3251 Apr  8 20:47 python-pywbem-ruff_unsafe_fixes.patch
```
BTW small improvement for pytest
```patch
--- a/pytest.ini
+++ b/pytest.ini
@@ -0,0 +1,4 @@
+[pytest]
+testpaths =
+    tests/unittest
+    tests/functiontest
```
Without that pytest tries to scan attic/
As currently `pywbem` did not move to pyproject.toml alternatively those settings can be added alternatively to tox.ini (pytest can use tox.ini as well)

All above still is not finished because it does not pass test suite after I've started accumulating some manual changes in python-pywbem-post_pyupgrade_py38.patch.
Nevertheless it would be good to know is it any decision plan which I've sketched in this ticket 😋

**Comment by andy-maier** [comment]
@kloczek Hi Tomasz.

On pytest and attic: The way we invoke pytest already excludes the attic directory.

On using ruff: On the master branch, it generates 4 errors for the tests directory:
```
$ ruff --unsafe-fixes pywbem pywbem_mock tests
tests/end2endtest/test_indications.py:45:22: F811 Redefinition of unused `wbem_connection` from line 28
tests/end2endtest/test_operation_timeouts.py:155:19: F811 Redefinition of unused `wbem_connection` from line 18
tests/end2endtest/utils/pytest_extensions.py:226:30: F811 Redefinition of unused `es_server` from line 25
tests/unittest/pywbem/test_recorder.py:1597:12: E714 [*] Test for object identity should be `is not`
Found 4 errors.
```
The first 3 being related to the fact that ruff does not understand pytest fixtures so we need yet another way to have it ignore those. The 4th error can indeed be "fixed my moving the "not" after the "is". However what ruff does not get apparently is that this is an unidiomatic type check, for which - once ruff has learned about that - we again have to add a ruff ignore. I guess ruff has some way to go until it reaches the quality of pylint, and before it gets there we wpould not give u running pylint. So ruff does not speed up the testing, it adds to the test time. I'll see if it is there in the Ubuntu provided in GitHub Actions, and if so we can run it. If not, then not.

On dropping py<3.8: That is in plan for pywbem 1.8.0. We want to give people that still need py27/36/37 a chance to get the nocasedict/list vendoring support in pywbem 1.7.0. I did not try pyupgrade yet, but I certainly will for 1.8.0.

**Comment by kloczek** [comment]
> @kloczek Hi Tomasz.
> 
> On pytest and attic: The way we invoke pytest already excludes the attic directory.

👍 
Nevertheless that should be present in source tree pytest settings to be able use pytest without any params.

> On using ruff: I have created issue #3144 for investigating the use of ruff.

Try to use `find . -name \*.py | xargs pyupgrade --py38-plus" and than ruff. That pair of course is not able to produce OOTB prod useful changes but it shows some potential how much more code cleanups can be pushed.

> On dropping py<3.8: That is in plan for pywbem 1.8.0. We want to give people that still need py27/36/37 a chance to get the nocasedict/list vendoring support in pywbem 1.7.0. I did not try pyupgrade yet, but I certainly will for 1.8.0.

So not 20.x but more likely 1.8.x 😋 
OK 👍 😄 
IMO move to pyproject.toml could be added as another 1.8.x goal as well 😋  (pylint, flask, black, coverage, pytest, tox, ruff settings can be kept in that single place/file as well).
Just please give me a shout when 1.7.x branch will be created to be able start preparing some PRs against master.

As I'm working on whole distro python packages (I have now +1.25k such packages under my hood) my goal is to drop in that whole population use of such packages like `six`.
If you want/if you will allow me .. I can try to prepare as DRAFT PR when such changes will be ready and at least not producing pytest fails (not to merge that ASP but to have more eyeballs is someone here may be interested).

**Comment by andy-maier** [comment]
On the use of pyupgrade to 3.8: I ran it and was pleased with the result. See the recent issue. So I think that will be an easy one.

**Comment by andy-maier** [comment]
PR #3154 removes support for Python <3.8 and used pyupgrade + postprocessing to adjust the sources. See the commit messages for details.

**Comment by kloczek** [comment]
Just checked and looks like https://github.com/pywbem/nocasedict/ doe is no longer using `six`. Version vendored here still used that module 🤔

**Comment by andy-maier** [comment]
Correct, PR #3155 will address that.
