### ISSUE TITLE
Upgrade the vendorized nocasedict & nocaselist to version 2 to get rid of six

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#3155]
The drop of support for Python 2 allows to get rid of the six package in the pywbem source code. However, it is still a dependency of the pywbem package because pywbem now has vendorized nocasedict and nocaselist, and thus inherits its package dependencies.

This issue is to increase the vendorized nocasedict and nocaselist to their versions 2.x which require Python 3 and no longer depend on the six package.

**Comment by kloczek** [comment]
Why not merge those two modules code with `pywbem` without vendorisation? 🤔 

So far I was not able to find any other module which is using those two.
Do you know such modules? 🤔

**Comment by tasleson** [comment]
> We have separated out nocasedict so it becomes useable by other projects. We have some internal projects that use it, for example.
> 
> With nocaselist, merging would mean that it would then be under the LGPL license of pywbem. It was intentionally released under the Apache 2.0 license. We are also using it internally.

I'm not 100% sure as IMNAL, but according to:

https://opensource.stackexchange.com/questions/5664/linking-from-lgpl-2-1-software-to-apache-2-0-library

using `nocaselist` would be prohibited.  However, the code was written originally for pywbem right?  However, thinking about this more has raised more questions like:

* How many people contributed to the `nocaselist` source code? (or maybe this wasn't included before?)
* The pybem project doesn't have a CLA right?  Thus did everyone who contributed to this file OK to the license change?

It's ok to dual license code too, if you own the copyright, but things are muddled with the questions above.

Also, using something internally and never distributing the changes implies you can do whatever the heck you want with it.

As I've mentioned, I'm not a lawyer, but I have access to some good ones internally if needed for clarification on this.

**Comment by andy-maier** [comment]
@tasleson

The nocaselist package was written by myself (https://github.com/pywbem/nocaselist/graphs/contributors) and is not a spin-off from pywbem but a new development. That's why we were not bound by the pywbem LGPL license and we used Apache 2.0.

The nocasedict package is a spin-off from pywbem and therefore kept its LGPL license.

**Comment by kloczek** [comment]
Is it anything more on outstanding list before 1.8.0 release? 🤔

**Comment by kloczek** [comment]
gentle ping .. is it anything more on outstanding list before 1.8.0 release? 🤔
