### ISSUE TITLE
Resolve remaining TODO-PYTHON still in _cim_types.py

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#3186]
There is one TODO-PYTHON still in `pywbem/_cim_types.py`: The use of the `x` key in dictionary in the CIMInt code and used in functiontests to supply Uint32 data to the InvokeMethod function tests.

This issue is to resolve that.

**Comment by KSchopmeyer** [comment]
This originated when x was a valid input parameter for the value of the Python int function whose signature defines a parameter x defining the int value and a keyword optional value defining the number base as a way to get around the issue of assigning value to a Uint32 in the invokemethod functiontest using x as a positional parameter.  However, in Python 3.7 the the use of the x parameter was dropped except in the documentation.  The user can no longer enter int(x=3, ... but must enter int(3, ...)

in effect, the same signature was kept in the documentation but not in the code.  The x parameter is no longer a keyword parameter but a positional parameter.  

The question for pywbem is what to do with this hidden use of a

**Comment by KSchopmeyer** [comment]
Alternatives:

1. Keep the as a keyword argument and document it.  In this case, the only change would be to documentation. This would be compatible with Python < 3.7 interface for int() but deviate from Python 3..8+. At the same time it would allow be a logical and consistent interface.
2. Remove the x parameter completely and modify the function tests to resolve the x = YAML parameter to pass the the tests.  This would be consistent with the Python int().
