### ISSUE TITLE
RFE: use `zoneinfo` instead of `pytz`

### ISSUE THREAD

**Issue by kloczek** [pywbem/pywbem#3191]
Switch to standard `zoneinfo` module.
Below may help  https://github.com/pydantic/pydantic-core/commit/fd262933

**Comment by andy-maier** [comment]
Zoneinfo was added in Python 3.9. Is there a backport to 3.8?

**Comment by kloczek** [comment]
> It is not yet fully clear to me in which cases the `tzdata` package needs to be added to the dependencies. Apparently definitely on Windows...

On U*nix platforms `tzdata` is part of the system resources.
Have no idea how it is on Win.

**Comment by andy-maier** [comment]
Ok
