### ISSUE TITLE
Issues with Spec DSP0201 and VALUE.INSTANCEWITHPATH

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#321]
This is a spec issue with this spec and the issues is only a reminder for karl to file bug with DMTF.

DSP0200 and DSP0201 disagree on the qualtity component of this definition (1 vs 0-many

**Comment by KSchopmeyer** [comment]
Karl set this one to 0.9.0 as remainder to write mantis report

**Comment by KSchopmeyer** [comment]
This issue has been documented in DMTF Mantis bug 2629 on 20 June 2016

**Comment by andy-maier** [comment]
Ok, great! Closing this issue here.
