### ISSUE TITLE
Issue with associator and associatornames operations

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#322]
Testing with run_cimoperations.py. Problem is that the functions inside AssociatorNames, Associators, References, ... Are not correctly sorting out classname, namespace, etc. per the documentation for the class version of this function. From the doc:

For class level usage: The class path of the source class, as a `string` or `CIMClassName` object.
If specified as a string, the string is interpreted as a class name in the default namespace of the connection, and can have any lexical case.
If specified as a `CIMClassName` object that does not specify a namespace, the default namespace of the connection is used.

It is getting the classname as the namespacename.

I have not yet explored any futher.

Call:

        classes = self.cimcall(self.conn.Associators, TEST_CLASS)

Error:

    ERROR: test_all (__main__.AssociatorNames)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "./run_cim_operations.py", line 687, in test_all
        names = self.cimcall(self.conn.AssociatorNames, TEST_CLASS)
      File "./run_cim_operations.py", line 78, in cimcall
        result = fn(*pargs, **kwargs)
      File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 2092, in AssociatorNames
        **extra)
      File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 795, in _imethodcall
        raise CIMError(code, err[1]['DESCRIPTION'])
    CIMError: 3: CIM_ERR_INVALID_NAMESPACE: CIM_ComputerSystem

print inside AssociatorNames:

        namespace = self._iparam_namespace_from(ObjectName)
        objectname = self._iparam_objectname(ObjectName)
        
        print('namespace=%s, objectname=%s, ObjectName=%s' % (namespace, objectname, ObjectName))

    namespace=CIM_ComputerSystem, objectname=CIM_ComputerSystem, ObjectName=CIM_ComputerSystem

**Edit:** Andy updated for better readability.

**Comment by andy-maier** [comment]
Fixed by PR #328.
