### ISSUE TITLE
I think we lost the simple list of all operations in the move to new doc

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#323]
In the old doc there was a list of the operations which represented a sort of toc to get to the operations easily.  In the new doc, they are all detailed in a long html page but not easy to get to each one.

I don't have a solutions but with 20+ operations, we need to do something like have an extra layer in the
left side menu, etc.

**Comment by andy-maier** [comment]
Karl, 
we have a table of the operations in chapter 2.2 WBEM Operations: https://pywbem.readthedocs.io/en/latest/client.html#wbem-operations
If we move the package version chapter up, it even appears at tge begin of chapter 2 Client API.

In addition, there is a manually maintained cluent quick links page: http://pywbem.github.io/pywbem/apidoc.html

Does that address this issue?

**Comment by KSchopmeyer** [comment]
On 05/25/2016 01:17 PM, Andreas Maier wrote:
>
> Karl,
> we have a table of the operations in chapter 2.2 WBEM Operations: 
> https://pywbem.readthedocs.io/en/latest/client.html#wbem-operations
> If we move the package version chapter up, it even appears at tge 
> begin of chapter 2 Client API.
>
> In addition, there is a manually maintained cluent quick links page: 
> http://pywbem.github.io/pywbem/apidoc.html
>
> Does that address this issue?
>

I think so. What I was seeing was that on the web page we build and did 
not see anything in the way of the table that is on the web
page and want to be sure that there is a table view to make it simple to 
get to the operations.  When I went to the build docs directory
there is nothing there.

Karl
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/323#issuecomment-221678109>
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
The table of the operations in chapter 2.2 "WBEM Operations" is in the html pages generated by Sphinx, so it is in the build_docs directory.

**Comment by andy-maier** [comment]
Please close this issue if you think it is addressed.
Let me know if you think something could be done better.

**Comment by andy-maier** [comment]
We agreed in the call that the table is easy to miss if one is directed towards the `WBEMConnection` class.
- The description of the `WBEMConnection` class could get a link to the table (right above it).
- Each operation could get a link to the table.

**Comment by KSchopmeyer** [comment]
We agree with andys comments about the links to the table

**Comment by andy-maier** [comment]
I'll wait with this one until PR #320 is merged, because they will overlap.

**Comment by andy-maier** [comment]
Completely addressed now with PR #357.
