### ISSUE TITLE
Restructure examples and tutorial

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#324]
Suggest that as a way to build up a set of working examples, we add more to the examples directory.  There is a problem with this in that (I assume) they are not distributed with pip package but at least they are a) in the open if you use github, b) executable so we can test and confirm that they work.

These can act as both code examples and good practice examples for use of PyWBEM

**Comment by andy-maier** [comment]
Agreed. 
By the way, we could add the examples directory to the package.

**Comment by KSchopmeyer** [comment]
Put that one on the discussion list only because nobody really looks at 
the imports so nobody would see it.  Just wonder if there is a better 
way to make it visible.

Maybe both in the distribution and also as a web page.   By the way, the 
key will be that we actually test these examples.

I will have the first one up for review as a pr today.  We can then 
discuss issues of exceptions since in writing this simple test for my 
presentation wednesday I
learned some things about exeptions and the complexity of getting them 
right.

Welcome back this weekend.

I am now back in Dallas, Drove back yesterday.

We gave almost 4 hours of presentations on PyWBEM and will put them up 
for us to review today or tomorrow.

Karl
On 05/25/2016 01:30 PM, Andreas Maier wrote:
>
> Agreed.
> By the way, we could add the examples directory to the package.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/324#issuecomment-221681493>
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
I think a better way would be to have the examples on the web site, as downloads or using ipython notebook.

**Comment by KSchopmeyer** [comment]
On 05/27/2016 08:09 AM, Andreas Maier wrote:
>
> I think a better way would be to have the examples on the web site, as 
> downloads or using ipython notebook.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/324#issuecomment-222156131>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ACO30VVAUgV0sy68lp1ZbLuc79u79StVks5qFvstgaJpZM4Imryy>.
>
I think that having examples as a working directory that gives us the 
capability to test these examples is worthwhile

These examples can then be mapped into the website.   Not sure yet about 
ipython notebook other than that we
should support it as a learning tool.  However, the examples we put into 
that may be different or subsets of what
we do on the web and examples pages.

Lets try a few examples on the examples page and use that to get GOOD 
examples that really represent good
coding practice for parts of the logic. Then we use those as the basis 
for other things.

Thus, for example, exactly what should the code look like for a complete 
enumerate including all exceptions?

For example, I accidentally put the ConnectionError exception around the 
WBEMConnect when, in fact it only occurs
on the operation call.

What should the code be to get particular properties out of returned 
instances and use them including issues of
the properties only conditionally being available?

The explore.py is a good working example of using the server code so 
that can start as part of the examples page.

Note that we probably also need to be able to automate the execution of 
the examples page to assure ourselves that
they are really correct.

Karl



-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
ipython notebook is now called jupyter notebook.

they have a notebook viewer that allows linking to the notebooks and using them on a web site. for example, the following link to one of their example notebooks:

https://raw.githubusercontent.com/ipython/ipython/master/examples/IPython%20Kernel/Trapezoid%20Rule.ipynb

can ve viewed and operated as an interactive notebook by using this link:

http://nbviewer.jupyter.org/github/ipython/ipython/blob/master/examples/IPython%20Kernel/Trapezoid%20Rule.ipynb

**Comment by andy-maier** [comment]
it seems their nb viever can only view but not edit.

**Comment by andy-maier** [comment]
[PR 11 on pywbem.github.io](https://github.com/pywbem/pywbem.github.io/pull/11) improves the examples by adding exception handling, and correcting some errors. Please review.

**Comment by andy-maier** [comment]
We discussed in the call that one approach would be to merge the current tutorial page and the example files into a new tutorial page with links to python notebooks. The new page would exist in parallel to the old page until satisfactory.

**Comment by andy-maier** [comment]
We discussed today that the new tutorial page would be in the pywbem project, no longer on pywben.github.io:

* Top level tutorial section in docs/tutorial.rst, that has links to the actual tutorial chapters.
* The actual tutorial chapters are Jupyter notebooks, and the links render them via the jupyter nbviewer page.

Content-wise, that would cover:

* The current tutorial page on pywbem.github.io.
* The examples on the pywbem.github.io project.
* The examples on the pywbem project.

**Comment by andy-maier** [comment]
The master branch now contains the first few tutorials. See the new Tutorials section in the API documentation.

Unfortunately, RTD seems to have a problem right now, but you can also see the tutorials when building locally with `make builddoc`.

Remaining work is to cover the rest of the examples from the old pywbem.github.io tutorials page, and to cover the remaining files in the pywbem `examples` directory.

**Comment by andy-maier** [comment]
We agreed in the call today that the current path taken should be continued.

**Comment by andy-maier** [comment]
PR #353 now addresses this issue completely.
