### ISSUE TITLE
Can't install on CentOS-6.7 due to M2Crypto issues.

### ISSUE THREAD

**Issue by tcengineer** [pywbem/pywbem#325]
Failure appears to be in the swig installation

$ sudo pip install pywbem
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pywbem
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached pywbem-0.8.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.6/site-packages (from pywbem)
Requirement already satisfied (use --upgrade to upgrade): ply in /usr/lib/python2.6/site-packages (from pywbem)
Collecting M2Crypto>=0.24 (from pywbem)
  Using cached M2Crypto-0.24.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): unittest2 in /usr/lib/python2.6/site-packages (from M2Crypto>=0.24->pywbem)
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.6/site-packages (from unittest2->M2Crypto>=0.24->pywbem)
Requirement already satisfied (use --upgrade to upgrade): traceback2 in /usr/lib/python2.6/site-packages (from unittest2->M2Crypto>=0.24->pywbem)
Requirement already satisfied (use --upgrade to upgrade): linecache2 in /usr/lib/python2.6/site-packages (from traceback2->unittest2->M2Crypto>=0.24->pywbem)
Installing collected packages: M2Crypto, pywbem
  Running setup.py install for M2Crypto
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-aHZeIL/M2Crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Erd7dS-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    copying M2Crypto/httpslib.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/m2urllib.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/m2urllib2.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/X509.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/BIO.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/EVP.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/ASN1.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/DSA.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/RC4.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/m2xmlrpclib.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/BN.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/AuthCookie.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/Err.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/EC.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/DH.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/Engine.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/threading.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/Rand.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/SMIME.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/m2.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/__init__.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/ftpslib.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/callback.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/util.py -> build/lib.linux-x86_64-2.6/M2Crypto
    copying M2Crypto/RSA.py -> build/lib.linux-x86_64-2.6/M2Crypto
    creating build/lib.linux-x86_64-2.6/M2Crypto/PGP
    copying M2Crypto/PGP/PublicKey.py -> build/lib.linux-x86_64-2.6/M2Crypto/PGP
    copying M2Crypto/PGP/constants.py -> build/lib.linux-x86_64-2.6/M2Crypto/PGP
    copying M2Crypto/PGP/packet.py -> build/lib.linux-x86_64-2.6/M2Crypto/PGP
    copying M2Crypto/PGP/PublicKeyRing.py -> build/lib.linux-x86_64-2.6/M2Crypto/PGP
    copying M2Crypto/PGP/__init__.py -> build/lib.linux-x86_64-2.6/M2Crypto/PGP
    copying M2Crypto/PGP/RSA.py -> build/lib.linux-x86_64-2.6/M2Crypto/PGP
    creating build/lib.linux-x86_64-2.6/M2Crypto/SSL
    copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-x86_64-2.6/M2Crypto/SSL
    copying M2Crypto/SSL/Checker.py -> build/lib.linux-x86_64-2.6/M2Crypto/SSL
    copying M2Crypto/SSL/cb.py -> build/lib.linux-x86_64-2.6/M2Crypto/SSL
    copying M2Crypto/SSL/Session.py -> build/lib.linux-x86_64-2.6/M2Crypto/SSL
    copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.linux-x86_64-2.6/M2Crypto/SSL
    copying M2Crypto/SSL/Connection.py -> build/lib.linux-x86_64-2.6/M2Crypto/SSL
    copying M2Crypto/SSL/SSLServer.py -> build/lib.linux-x86_64-2.6/M2Crypto/SSL
    copying M2Crypto/SSL/timeout.py -> build/lib.linux-x86_64-2.6/M2Crypto/SSL
    copying M2Crypto/SSL/__init__.py -> build/lib.linux-x86_64-2.6/M2Crypto/SSL
    copying M2Crypto/SSL/Context.py -> build/lib.linux-x86_64-2.6/M2Crypto/SSL
    copying M2Crypto/SSL/Cipher.py -> build/lib.linux-x86_64-2.6/M2Crypto/SSL
    running build_ext
    building 'M2Crypto.__m2crypto' extension
    swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c
    swig -python -D__x86_64__ -I/usr/include/python2.6 -I/usr/include -I/usr/include/openssl -includeall -modern -builtin -outdir build/lib.linux-x86_64-2.6/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
    swig error : Unrecognized option -builtin
    Use 'swig -help' for available options.
    error: command 'swig' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-aHZeIL/M2Crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Erd7dS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-aHZeIL/M2Crypto

**Comment by andy-maier** [comment]
Hello!
The reason for this is that the Swig version is too old. Install Swig v2.0 or higher. I forgot where I got it from on CentOS 6.7, but I believe it was either the IUS or EPEL repo. I'm limited to my mobile phone until sunday, so I cannot verify that, I'm afraid.

Alternatively, you can use the OS-level dependency install capability of pywbem:

     pip download --install pywbem
     sudo python setup.py install_os
     sudo python setup.py install

Again, this is from the back of my mind, unverified.

Let me know whether one of these hints worked.

**Comment by tcengineer** [comment]
Andreas,

Thanks for such a quick response. I had IUS and EPEL repositories configured yet couldn’t update swig from 1.3. I ended up finding a 2.0.10 version rpm package and was able to update it manually (yum localupdate …)

Not sure if it matters but I got the rpm from:

ftp://ftp.pbone.net/mirror/ftp5.gwdg.de/pub/opensuse/repositories/home:/dipe/CentOS_CentOS-6/x86_64/swig-2.0.10-2.1.x86_64.rpm

Once I updated swig:

$ sudo pip install pywbem
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pywbem
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached pywbem-0.8.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.6/site-packages (from pywbem)
Requirement already satisfied (use --upgrade to upgrade): ply in /usr/lib/python2.6/site-packages (from pywbem)
Collecting M2Crypto>=0.24 (from pywbem)
  Using cached M2Crypto-0.24.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): unittest2 in /usr/lib/python2.6/site-packages (from M2Crypto>=0.24->pywbem)
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.6/site-packages (from unittest2->M2Crypto>=0.24->pywbem)
Requirement already satisfied (use --upgrade to upgrade): traceback2 in /usr/lib/python2.6/site-packages (from unittest2->M2Crypto>=0.24->pywbem)
Requirement already satisfied (use --upgrade to upgrade): linecache2 in /usr/lib/python2.6/site-packages (from traceback2->unittest2->M2Crypto>=0.24->pywbem)
Installing collected packages: M2Crypto, pywbem
  Running setup.py install for M2Crypto
  Running setup.py install for pywbem
Successfully installed M2Crypto-0.24.0 pywbem-0.8.4

Thanks again for your help!

John  88{Q

_______________________________________
Technology & Systems Support Engineer
Storage Networking Industry Association
Mobile: 719-963-0889 (Primary)
Office: 719-694-1383
Fax: 719-694-1389
john.malia@snia.org<mailto:john.malia@snia.org>

**Comment by andy-maier** [comment]
Hi John.
Glad to see it worked!

Thanks for the pointer to the RPM.

I have opened issue #327 to create a trouble shooting section for such cases.

Closing this issue.
