### ISSUE TITLE
wbemcli has unused input arg for EnumerateInstances

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#33]
on the EnumerateInstances function the optional input argument LocalOnly is in the _init_ but never used.  Need to sort out if this is an issue with the function in wbmcli or the called function. Note that, in general, this argument is deprecated.

**Comment by andy-maier** [comment]
Good catch, Karl.
It is missing. (I know LocalOnly is deprecated in the CIM-XML standard, but that does not mean it went away, and we are supporting it in PyWBEM).

Also, please note the different way the arguments of most other functions in `wbemcli.py` are defined: Generically with `*args, **kwargs`. It seems to me that we could change `EnumerateInstances()`, `EnumerateInstanceNames()`, and `GetInstance()` to also be generically defined, and that that would be a backwards compatible change.

**Comment by andy-maier** [comment]
PR #48 was merged. Closing this issue
