### ISSUE TITLE
Remove support for Python 2.6

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#330]
More and more things are falling apart for PyWBEM on Python 2.6:
- `virtualenvwrapper` still works but issues a failure about `stevedore` package using `logging.NullHandler` (see [this commit](http://git.openstack.org/cgit/openstack/stevedore/commit/?id=72e3e1177dc23b4f3d358294d68b58c01d7c5931) which removed the `NullHandler` workaround as part of a general removal of Python 2.6 support).
- Our long standing issue #26 on the `pbr` package is specific to Python 2.6.
- The Sphinx build problem discussed in PR #328 is caused by Sphinx using the latest (2.0.3) version of the GitPython Pypi package that imports `OrderedDict` from `collections` without a fallback to the `ordereddict` package. The GitPython team has added a workaround for this in their master branch, but that fix is not yet released. So this one should be resolved with the next release of GitPython.

In addition, there are some "soft factors" that may cause problems at some point down the road:
- PyWBEM is using some packages that seem to work on Python 2.6 but do not specifically claim support for Python 2.6 (However, I was also surprised how many of the packages we use, still specifically claim Python 2.6 support):
  - The `stevedore` package states a minimum of 2.7 (it is the only one of those we use that does that).
  - There are several packages we use that claim Python 2 support without being more specific and that possibly did not intend to imply Python 2.6 support with that claim. One of those is Pylint (and its dependents) - I seem to recall that they have dropped Python 2.6 support (but did not double check that).
- The Python core team has stopped updating Python 2.6 with Python 2.6.9 in 10/2013.
- In addition, all Python 2.6.x releases after 2.6.6 were source-only releases, which probably is the reason that RHEL 6.x (and possibly other Linux distros) stayed on the last binary release 2.6.6.
- The OpenStack team has decided in 11/2015 to drop support for Python 2.6 (the stevedore issue mentioned above is a direct result of that decision since the `stevedore` package is maintained by an OpenStack sub-team).

**Discussion point:**

The discussion to have is whether we still need support for Python 2.6 in PyWBEM.

It would be very helpful is PyWBEM users would state their requirements for Python 2.6 support as comments to this issue.

**Comment by willspearman** [comment]
I am a believer in supporting older version if it is easy, but it sounds like a major inconvenience to support Python 2.6. I am fine with dropping support for Python 2.6.

**Comment by KSchopmeyer** [comment]
On the down side, apparently centos6 currently is distributed with a python 2.6 installation as the basis for its own mgt tools.  During a recent installation in the SNIA tech center, they tried to just get PyWBEM running as a test with a new Centos6.x installation and found python 2.6.? as the preinstalled python.   Note that apparently Centos 6 versions are still heavily used.  

Also, people are still even installing CentOS6 because they seem to have significant problems with CentOS 7 new installations.

Note that personally I would prefer to drop 2.6 since it is the source of much of our installation pain and special tests but we need to look at all sides.

**Comment by andy-maier** [comment]
We decided today in the call to keep Python 2.6 support for 0.9.0, and reconsider it afterwards.

**Comment by KSchopmeyer** [comment]
We propose that we will seriously consider dropping python 2.6 support for every release going forward from 0.9.0.  The decision will be based on use cases from pyWBEM uses and the new issues we run into trying to continue to support it as other support for 2.6 weakens.

**Comment by KSchopmeyer** [comment]
Lets keep it for this version and relook at the question for the next version.

**Comment by andy-maier** [comment]
We discussed this again today and made the following decision:

Version 0.12.0 of pywbem will be the last version with Python 2.6 support. We need to work through the set of items to put into 0.12.0 (see issue #771).

The next version after that will likely be pywbem 1.0.0, without Python 2.6 support.

**Comment by andy-maier** [comment]
I created PR #1760 which finally removes support for Python 2.6 from pywbem. It targets the upcoming 1.0.0 version of pywbem. Versions of pywbem below 1.0.0 will continue to have Python 2.6 support, for now.
