### ISSUE TITLE
Travis CI fails make builddoc on Python 2.6

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#331]
The following Travis run originally failed due to this:
https://travis-ci.org/pywbem/pywbem/builds/133595156

The root cause is that Sphinx uses GitPython v2.0.3 which imports `collections.OrderedDict`, which was introduced only in Python 2.7.

GitPython has fixed that in its master branch, by importing `ordereddict.OrderedDict` in case the import of imports `collections.OrderedDict` fails with `ImportError`. See [GitPython PR 443](https://github.com/gitpython-developers/GitPython/pull/443). This has been included in GitPython v2.0.5.

Unfortunately, GitPython 2.0.5 has introduced a new issue with Python 2.6, that causes a "TypeError: decode() takes no keyword arguments" to be raised. See [GitPython issue 457](https://github.com/gitpython-developers/GitPython/issues/457). This PR has been merged and is targeted for GitPython 2.0.6.

**Status:** Waiting for availability of GitPython 2.0.6.

**Comment by andy-maier** [comment]
PR #332 fixes this as mentioned above, as a temporary workaround, until GitPython 2.0.4 is released.

**Comment by andy-maier** [comment]
PR #333 fixes this partly, by using GitPython 2.0.5 and improving the Python installer.

**Comment by andy-maier** [comment]
[GitPython issue 457](https://github.com/gitpython-developers/GitPython/issues/457) has been merged and is targeted for GitPython 2.0.6.

**Comment by andy-maier** [comment]
PR #333 has been merged.

This issue is now waiting for the release of GitPython 2.0.6 (see [GitPython on Pypi](https://pypi.python.org/pypi/GitPython/)), at which point the `make builddoc` can be re-enabled for Python 2.6 in `.travis.yml`.

**Comment by KSchopmeyer** [comment]
Changed to release optional since we are already building the doc under 3 other versions of python in the travis tests and we have no control over the next GitPython release.

**Comment by andy-maier** [comment]
GitPython 2.0.6 has been released.

**Comment by andy-maier** [comment]
PR #383 fixes this issue.
