### ISSUE TITLE
Pretty ugly structure for exceptions

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#334]
I was creating an example of enum instances and ended up with the following:

try:
    CONN = WBEMConnection(HOST_URL, CREDS, default_namespace=TEST_NAMESPACE)

    instances = CONN.EnumerateInstances(TEST_CLASS)

    print('insts type=%s  insts=%s len=%s' % (type(instances),
                                                   repr(instances),
                                                   len(instances)))

    for inst in instances:
        print('path=%s\n' % inst.path)
        print(inst.tomof())

except CIMError as ce:
    print('CIMError: Response code=%s, msg=%s' % (ce[0], ce[1]))
    exit(1)
except ConnectionError as ce:
    print('ConnectionError exception %s' % ce)
    exit(1)
except AuthError as ae:
    print('AuthenticationError exception %s' % ae)
    exit(1)
except TimeoutError as te:
    print('TimeoutError exception %s' % te)

Unless I am missing something, the user either has to except at the level of Error or supply the above 4 exceptions.  Note that in reality, the WBEMConnection does not even have to be in the try block since this is lazy connection so that they cannot separate out even AuthError as a connection artifact.

Looking for comments, etc.

**Comment by andy-maier** [comment]
The base class `pywbem.Error` can be used to generate a reasonable message text:

    except pywbem.Error as exc:
        print ("XYZ operation failed: %s" % exc)

**Comment by KSchopmeyer** [comment]
For now, OK but in the long run I am uncomfortable with that in that it is the base for all pywbem exceptions including MofParseError.

Also, we are picking up error outside of the list we have, in particular M2CRYPTO.SSL.SSLError (certificate failed).  I would have assumed that this showed up as Connection or Auth error.  Note that the python 3 error does fall back through Connectionerror
ConnectionError exception SSL error <class 'ssl.SSLError'>: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

**Comment by KSchopmeyer** [comment]
Lets move the M2Crypto thing to a new issue. Karl will do this.  Also, in python 3 this shows up as Connection error and not Auth error. Karl will file both of these.

**Comment by KSchopmeyer** [comment]
Closed as resolved in discussion.
