### ISSUE TITLE
Is the concept of lazy connection really logical or does it confuse the user?

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#335]
We do lazy connection with PyWBEM. Thus we do not actually connect until the first operation.  The connection is just a setup.

**Comment by andy-maier** [comment]
It is logical given how HTTP is defined.

What we should actually find out, is how we can reuse the SSl connections across HTTP methods.

**Comment by KSchopmeyer** [comment]
Agreed.

**Comment by andy-maier** [comment]
We agreed to close this one.
