### ISSUE TITLE
Issue with travis after last rebase to pr # 317

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#336]
Travis now fails on python 3 tests with the error:

HTTP error 503 while getting https://pypi.python.org/pypi

error: 503 Server Error: No healthy backends for url: https://pypi.python.org/pypi

make: *** [develop] Error 1

Not sure whose issue this is.  I retried it a couple of times but same result.

**Comment by andy-maier** [comment]
As I understand it, these are instabilities of the pypi site. to be solved by retrying.

that's why i look at the new pypi warehouse site.

**Comment by KSchopmeyer** [comment]
Close as invalid. After about 4 retries it finally worked.  Guess this is the price of the unstable site. :-)

**Comment by KSchopmeyer** [comment]
Just wanted to be sure since the first couple of retries also bombed in the same place. Closing as invalid now.
