### ISSUE TITLE
Associator of class does not return CIMClass element

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#339]
Apparently the call Associator(class) returns a list of  tuples and not of CIMClass

test_class_associator (__main__.Associators) ... class assoc for CIM_ComputerSystem
type <type 'tuple'>

for the following test I am adding to run_cimoperations.py:

        assoc_classes = self.cimcall(self.conn.Associators, TEST_CLASS)
        
        print('class assoc for %s' % TEST_CLASS)
        for cls in assoc_classes:
            #validate is class return
            print('type %s' % type(cls))
            self.assertTrue(isinstance(cls, CIMClass))

each tuple is as follows:
(CIMClassName(classname=u'CIM_SettingData', namespace=u'root/cimv2', host=u'sheldon'), CIMClass(classname=u'CIM_SettingData', superclass=u'CIM_ManagedElement', properties=NocaseDict({u'Caption': CIMProperty(name=u'Caption', value=None, type=u'string', reference_class=None, embedded_object=None, is_array=False, array_size=None, class_origin=None, propagated=True, qualifiers=NocaseDict({})), u'ChangeableType': CIMProperty(name=u'ChangeableType', value=None, type=u'uint16', reference_class=None, embedded_object=None, is_array=False, array_size=None, class_origin=None, propagated=None, qualifiers=NocaseDict({})), u'ConfigurationName': CIMProperty(name=u'ConfigurationName', value=None, type=u'string', reference_class=None, embedded_object=None, is_array=False, array_size=None, class_origin=None, propagated=None, qualifiers=NocaseDict({})), u'Description': CIMProperty(name=u'Description', value=None, type=u'string', reference_class=None, embedded_object=None, is_array=False, array_size=None, class_origin=None, propagated=True, qualifiers=NocaseDict({})), u'ElementName': CIMProperty(name=u'ElementName', value=None, type=u'string', reference_class=None, embedded_object=None, is_array=False, array_size=None, class_origin=None, propagated=None, qualifiers=NocaseDict({})), u'InstanceID': CIMProperty(name=u'InstanceID', value=None, type=u'string', reference_class=None, embedded_object=None, is_array=False, array_size=None, class_origin=None, propagated=None, qualifiers=NocaseDict({}))}), methods=NocaseDict({}), qualifiers=NocaseDict({})))

**Comment by KSchopmeyer** [comment]
DISCUSSION: Change the api or the documentation?

**Comment by KSchopmeyer** [comment]
Same issue applies to getting responses for class level references.

        assoc_classes = self.cimcall(self.conn.Associators, TEST_CLASS)
        
        print('class assoc for %s' % TEST_CLASS)
        for cls in assoc_classes:
            #validate is class return
            print('type %s' % type(cls))
            self.assertTrue(isinstance(cls[1], CIMClass))
            self.assertTrue(isinstance(cls[0], CIMClassName))
            print('CIMClassName=%s' % cls[0])
            print(cls[1].tomof())

The above snippit works.  Note that the path is not a complete path, it is only host, namespace, class

**Comment by andy-maier** [comment]
Probably, the reason for that is that CIMClass does not include the class path. That difference to CIMInstance creates complexity.
 We could add it to CIMClass

**Comment by KSchopmeyer** [comment]
Maybe since this function is not widely used (primarily by browsers trying to sort out the association relationships) we could just document it as:
Returns tuple:
     * classname
     * class

Putting classpath into class sounds logical but
   a. Not sure how often it will be used
   b. Not sure of secondary effects.

Actually no reason for not making classpath part of class but still have the issue of changing an existing api.

Also, I have not tracked down the history of this but if it is 0.7.0, we can expect people to be using the tuple already and will break them.  I am assuming that, for example science logic, who did a walker used the associators/references class calls to build their walker and changing from returning a tuple to a class could break their walker.

Finally, what we should always have done was to create separate client apis  for class and instance associators, associatornames, references, referencenames. Then if in the future the monololic operations are deprecated, these operations would continue to exist for the client

I actually knew this from before since the test itself with the tuple response was in run_cimoperations.py  However it doing new tests I refound it and then noted the documentation discrepency

**Comment by KSchopmeyer** [comment]
As a simple approach I propose that we change the documentation for associators and references, 
From:
        Returns:

            For instance level usage, a list of
            :class:`~pywbem.CIMInstanceName` objects that are the instance
            paths of the associated instances.

            For class level usage, a list of :class:`~pywbem.CIMClass` objects
            that are representations the associated classes.
To:
        Returns:

            For instance level usage, a list of :class:`~pywbem.CIMInstance`
            objects that are representations of the associated instances.


            For class level usage, a list of tuples where the tuple entries are:

               *  [0] - class:`~pywbem.CIMClassName` object including host and
                  namespace entities that is the representation of the name of one
                  associated class.
               *  [1] - :class:`~pywbem.CIMInstance` object that is the representation
                  of one associated class

            objects that are the class paths of the associated classes.

This leaves the code alone completely.  It would not bother me to add the classpath to CIMClass but we should probably keep the existing api.

DISCUSSION: alternatives are:
   1. change api to match documentation
   2. change documentation to match api
   3. Change CIMClass to include CIMClassname component and also change api.
   4. Change documentation to match current api and also add class level separate operations that
       correctly return class (whtether we add classname to class or not.

**Comment by andy-maier** [comment]
FIxed in PR #350.
