### ISSUE TITLE
wbemcli is really very undecipherable

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#34]
Trying to use this utility to really do something is difficult. Some of the issues include:
1. There is no list of the client functions available. You need the python source for that.
2. There is no clear documentation on the set of parameters for any given function.  Note that some of 
   the client functions defined in wbemcli do include specific arguments but many of them just use
   _args and *_kwargs. Since the functions they call do not really include argument documentation it is a long trail for the user to find out what arguments apply to any function.
3. The display possibilities are not really documented.  Thus, how could you display mof or xml for a result, how do you display the various types of results (class, instance path qualifierType, list of classes, list of classes, instances, paths, qualifiertypes; and finally how would you input and get a response for an invoke method.

While the general direction should be to move to a real set of client browsers (both cli and gui) there should be some way to make this more usable now.

Thus, for example, you can display a class in mof format:
     cl = gc('CIM_ManagedElement')
    print cl.tomof()

or display the xml with:
    print(cl.tocimxml().toprettyxml(indent = '  '))

Just as simple examples.

**Comment by andy-maier** [comment]
Started working on this one. Intend to:
- Add help function.
- Fix docstrings
- Change interfaces of wbemcli functions to use specific args
- Display facility for result objects exists, and is their `repr()`, `tocimxml()`, and `tomof()` functions, or the global `tocimxml()` function. Will document that in help.
