### ISSUE TITLE
Extend wbemcli to support the pull operations

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#341]
We need to extend wbemcli to support the pull operatons.  However, that support is really problematic in that these operations cannot guarantee completion in a single call and feature a timeout between calls making line by line input somewhat messy. 

It is easy to add these calls.  It will be more difficult for people to use them effectively.

The easiest suggestion is to simply add the opens as separate calls with shortcuts that parallel the existing shortcuts but with a pull in front of them.

The next alternative would be to actually create a wrapper that did the open and pulls together and so that we supplied extra parameters for max objects for opens and pulls.

**Comment by KSchopmeyer** [comment]
We concluded that the correct solution for now is simply to document and implement a shortcut for each of the new operations. Each new operation will have the shortcut of the original prepended with 'p'

**Comment by andy-maier** [comment]
PR #372 addresses this issue.
