### ISSUE TITLE
Get Class with property list issues incorrect xml

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#347]
Pegasus returns:

ConnectionError: CIMError: request-not-valid, PGErrorDetail: Validation error: on line 2: Expected close of IPARAMVALUE element, got VALUE instead

Apparently VALUE.ARRAY component missing.

Note that the markdown formatting is off.  Click on edit to see actual result.

``
**pyWBEM**:
<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0">
    <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
        <SIMPLEREQ>
            <IMETHODCALL NAME="GetClass">
                <LOCALNAMESPACEPATH><NAMESPACE NAME="root"/>
                    <NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH>
                <IPARAMVALUE NAME="ClassName"><CLASSNAME
                    NAME="CIM_ComputerSystem"/></IPARAMVALUE>
                <IPARAMVALUE NAME="PropertyList">
                    <VALUE>PowerManagementCapibilities</VALUE>
                </IPARAMVALUE>
            </IMETHODCALL>
        </SIMPLEREQ>
    </MESSAGE>
</CIM>
``
**OpenPegasus Client**
``
<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0">
    <MESSAGE ID="1000" PROTOCOLVERSION="1.0">
        <SIMPLEREQ>
            <IMETHODCALL NAME="GetClass">
                <LOCALNAMESPACEPATH>
                    <NAMESPACE NAME="root"/>
                    <NAMESPACE NAME="cimv2"/>
                </LOCALNAMESPACEPATH>
                <IPARAMVALUE NAME="ClassName">
                    <CLASSNAME NAME="CIM_ComputerSystem"/>
                </IPARAMVALUE>
                <IPARAMVALUE NAME="PropertyList">
                    <VALUE.ARRAY>
                        <VALUE>PowerManagementCapabilities</VALUE>
                    </VALUE.ARRAY>
                </IPARAMVALUE>
            </IMETHODCALL>
        </SIMPLEREQ>
    </MESSAGE>
</CIM>
``

**Comment by KSchopmeyer** [comment]
We concluded in discussion of the pr that we a) ignore testing and let the server find the problem.

b) allow the tuple or, in fact any iterable
c) extend the test to allow any iterable

**Comment by andy-maier** [comment]
Addressed by PR #348.
