### ISSUE TITLE
Mof compiler output overruns line length

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#35]
The mof compiler consistently overruns the 80 col limit with description outputs because it does not
account for the qualifier name on the first line. For example:

Where the first line characters each " are beyond the 80 char limit. 
      [Description ("A user-friendly name for the object. This property allows each "
       "instance to define a user-friendly name in addition to its key "
       "properties, identity data, and description information. \nNote that "

This is a problem of the fold processor since it folds the string without knowing about the prepended Description, etc.

**Comment by andy-maier** [comment]
Fixed by PR #260.
