### ISSUE TITLE
Generates CIMError inside ConnectionError

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#352]
The following simple test which is actually an http error from the server generates
a CIMError within a ConnectionError.

This was created by simply creating a connection and making a request with a string (i.e. no list) as PropertyList for a GetClass.  This causes invalid XML (value instead of value.array)

        <IPARAMVALUE NAME="PropertyList">
          <VALUE>Name</VALUE>
        </IPARAMVALUE>

That is a strange return.  At the least it leads us to recommend that people always use Error as the
exception and then sort out what they get.

pywbem.exceptions.ConnectionError: CIMError: request-not-valid, PGErrorDetail: Validation error: on line 2: Expected close of IPARAMVALUE element, got VALUE instead

The actual response from the server was:

<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0"><SIMPLEREQ><IMETHODCALL NAME="GetInstance"><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH><IPARAMVALUE NAME="PropertyList"><VALUE>Name</VALUE></IPARAMVALUE><IPARAMVALUE NAME="InstanceName"><INSTANCENAME CLASSNAME="PG_ComputerSystem"><KEYBINDING NAME="CreationClassName"><KEYVALUE VALUETYPE="string">PG_ComputerSystem</KEYVALUE></KEYBINDING><KEYBINDING NAME="Name"><KEYVALUE VALUETYPE="string">sheldon.inovadevelopment.com</KEYVALUE></KEYBINDING></INSTANCENAME></IPARAMVALUE><IPARAMVALUE NAME="LocalOnly"><VALUE>False</VALUE></IPARAMVALUE></IMETHODCALL></SIMPLEREQ></MESSAGE></CIM>
1465327789s-20838us: XmlIO [24022:140536489084800:HTTPConnection.cpp:924]: 
HTTP/1.1 400 Bad Request
CIMError: request-not-valid
PGErrorDetail: Validation%20error%3A%20on%20line%202%3A%20Expected%20close%20of%20IPARAMVALUE%20element%2C%20got%20VALUE%20instead

**Comment by andy-maier** [comment]
Aahh - That is the HTTP header "CIMError", not the `pywbem.CIMError` exception. The `pywbem.CIMError` exception is raised when an "ERROR" element comes back. The current code that handles bad HTTP status codes raises `pywbem.ConnectionError` for any bad HTTP status (and it special-cases a "CIMError" header by checking for a possibly present "PGErrorDetail" header (lines 752 and 754 of cim_http.py).

This is another case where some new exception would be appropriate, for any bad HTTP status codes returned by the server. Maybe `pywbem.HTTPError`? We would then restrict the use of `pywbem.ConnectionError` to connectivity errors below HTTP.

**Comment by KSchopmeyer** [comment]
Listener,  need header field Andy invented a CIM_Error_Detail for the listener.  We need to consider expanding that.

We also need to consider some form of HTTP error. so that we can more cleanly separate these out when the exception is received.

ACTION: Karl fix and close

**Comment by KSchopmeyer** [comment]
We want to have an http errorspecifically.

**Comment by andy-maier** [comment]
Created issue #371 for HTTPError, and issue #370 for raising AuthError in all cases of auth errors.
