### ISSUE TITLE
Need tests for the indication listener.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#362]
Right now we have zero tests for indication listener, only 1 demo in examples and another demo that Karl is doing in examples.  We need at least some regularly run tests either in

run_cim_operations.py See issue #379 which specifically defines need  for run_cimoperations.py tests

In future this but will cover adding mock tests
mock

**Comment by andy-maier** [comment]
The example that sends indications could be used as a basis for an indication emitter for test purposes.

**Comment by andy-maier** [comment]
Current coverage of the `_listener.py` module is 75%.

**Comment by andy-maier** [comment]
We agreed that 75% is good enough to close this issue and to improve the coverage as part of the general coverage improvement work.
