### ISSUE TITLE
Possible issue with make all

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#37]
I hit a real error in the process (had a TODO with no # to set it as a comment) and the make all finished
successfully.  It did mark the error in the output text but continued on with the whole process.

Easy to recreate.  Just put a statement like

   TODO blah blah

into one of the *.py files.  I am assuming that an error like this should stop the whole process

**Comment by andy-maier** [comment]
That's hard to believe. Make all includes make test. Are you sure that's in a file that is used?

**Comment by KSchopmeyer** [comment]
On 02/11/2016 06:00 PM, Andreas Maier wrote:
>
> That's hard to believe. Make all includes make test. Are you sure 
> that's in a file that is used?
>

Yup.  When you save the all output, you see the flag in the output. But 
the test continues on

That one was easy to produce.

I just create a TODO line and forgot to make it a comment in one of the 
files in pywbem module

I had another one sort of the same but this was my error in the tests.  
It showed the error in the
test.log output but went on and continued the testing.

My only issue is that the makefile continues on and you have to do a 
detailed inspection to see
that there was a real error.

Will retest.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/37#issuecomment-183118094>.
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
This issue was solved as part of the Python3 changes (see PR #46).

**Comment by andy-maier** [comment]
I have separated the fix for this from the Python 3 PR #46: PR #43 solved this issue now.
