### ISSUE TITLE
pegasusindicationtest.py script misses indications

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#375]
PR #367 introduced `examples/pegasusindicationtest.py`. This script invokes a method of OpenPegasis that causes a specified number of indications to be sent.

However, the script only receives a subset of them.

Investigate where the problem is.

**Comment by KSchopmeyer** [comment]
1467114975s-880478us: XmlIO [14812:140223637411584:HTTPConnection.cpp:924]: 
POST / HTTP/1.1

HOST: sheldon.inovadevelopment.com:2003

Content-Type: application/xml; charset=utf-8

content-length: 0000000958

TE: chunked, trailers

CIMExport: MethodRequest

CIMExportMethod: ExportIndication



<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0">
<MESSAGE ID="1033" PROTOCOLVERSION="1.0">
<SIMPLEEXPREQ>
<EXPMETHODCALL NAME="ExportIndication">
<EXPPARAMVALUE NAME="NewIndication">
<INSTANCE CLASSNAME="Test_IndicationProviderClass" >
<PROPERTY NAME="IndicationIdentifier"  TYPE="string">
<VALUE>9</VALUE>
</PROPERTY>
<PROPERTY NAME="IndicationTime"  TYPE="datetime">
<VALUE>20160628065615.878877-300</VALUE>
</PROPERTY>
<PROPERTY.ARRAY NAME="CorrelatedIndications"  TYPE="string">
<VALUE.ARRAY>
</VALUE.ARRAY>
</PROPERTY.ARRAY>
<PROPERTY NAME="MethodName"  TYPE="string">
<VALUE>SendTestIndicationsCount</VALUE>
</PROPERTY>
<PROPERTY NAME="SequenceContext"  TYPE="string">
<VALUE>PG:IndicationService-PG:127-0-1-1-1467114966809473-1467114975809491</VALUE>
</PROPERTY>
<PROPERTY NAME="SequenceNumber"  TYPE="sint64">
<VALUE>8</VALUE>
</PROPERTY>
</INSTANCE>
</EXPPARAMVALUE>
</EXPMETHODCALL>
</SIMPLEEXPREQ>
</MESSAGE>
</CIM>

1467114975s-880997us: XmlIO [14812:140223637411584:HTTPExportResponseDecoder.cpp:115]: HTTP/1.1 200 OK

Content-Type: application/xml; charset=utf-8

transfer-encoding: chunked

CIMExport: MethodResponse

Trailer: CIMStatusCode, CIMStatusCodeDescription, Content-Language



<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0">
<MESSAGE ID="1033" PROTOCOLVERSION="1.0">
<SIMPLEEXPRSP>
<EXPMETHODRESPONSE NAME="ExportIndication">
</EXPMETHODRESPONSE>
</SIMPLEEXPRSP>
</MESSAGE>
</CIM>

**Comment by KSchopmeyer** [comment]
Good news is that it is not an issue with listener threading, etc. Appears to be issues in headers, etc. that is causing failures
