### ISSUE TITLE
case issue in PyWBEM server namespace access

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#377]
The functions that  return the interop namespaces seem to have an issue with casing and the interop namespace:

Note below that the explore.py example displays the interop namespace with an lowercase o and the same namespace in the namespace list with an uppercase O.

Interop namespace:
  root/PG_Interop
All namespaces:
  root/PG_InterOp
  root/SampleProvider
  root/benchmark
  test/CimsubTestNS2
  test/CimsubTestNS3
  test/CimsubTestNS0
  test/CimsubTestNS1
  root/PG_Internal
  test/WsmTest
  test/TestIndSrcNS1
  test/EmbeddedInstance/Static
  test/TestINdSrcNS2
  test/TestProvider
  test/EmbeddedInstance/Dynamic
  root/cimv2
  root
  test/cimv2
  test/static

**Comment by andy-maier** [comment]
Fixed by PR #382.
