### ISSUE TITLE
Pylint warnings for map, filter, lambda code

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#38]
(deprecated-lambda) (9 uses),  which includes warnings like:
map/filter on lambda could be replaced by comprehension (deprecated-lambda)

```
    return map(lambda x: x[2], result[2])
```

and
        plist = map(lambda x:
                    cim_xml.IPARAMVALUE(x[0], cim_obj.tocimxml(x[1])),
                    params.items())

and (bad-builtin) (10 uses) often on the same function as deprecated-lambda
Used builtin function 'map'. Using a list comprehension can be clearer. (bad-builtin)

unnessary-lambda(2)

Both appear to be questions of style rather than really bad code.  In fact, a number of
responders to questions about these styles indicate that the  the map/filter syntax is
faster.

I propose that for the time being we disable these warnings in pylint.rc and we can
sort this out later (there may be a reason to change when we fully incorporate python 3)

**Comment by andy-maier** [comment]
I have removed some of them as part of the work on Python 3 support.

**Comment by andy-maier** [comment]
This issue is addressed by PR #46.

**Comment by KSchopmeyer** [comment]
I agree with andy that PR #46 completely negates the need for this issue.  I am closing this one
