### ISSUE TITLE
Issue with error when _listener gets a WBEMServer cannot be found error.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#387]
In creating tests for run_cim_operations.py listener I was getting an error stating that the listener cannot find the server as below.   That is not the issue. the problem is that ValueError includes a display of the WBEMServer object which in this case is about 60,000 characters long, all on one line.
It includes all the elements in the wbemserver including profiles, etc. so is way more info than is necessary.

Traceback (most recent call last):
  File "./run_cim_operations.py", line 2854, in test_create_delete_indication
    subscription_path = listener.add_subscription(server, filter_path)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_listener.py", line 1108, in add_subscription
    server_url)
ValueError: WBEM server not known by listener: WBEMServer(url='http://sheldon',
 conn=WBEMConnection(url='http://sheldon',

**Comment by andy-maier** [comment]
I agree that that is not helpful...
We are using the WBEMServer object as an identification of the server for some listener functions. It seems to me that the server URL should be sufficient in the exception message.

Maybe we should even change the identification in the listener function to also use the URL.
Let's discuss.

**Comment by andy-maier** [comment]
We already use the server URL as an identification in the listener methods.

What we could do as an improvement, is to change the documentation to talk about server ID instead of server URL.

Plus, of course to fix the 60000 char issue ...

**Comment by andy-maier** [comment]
Fixed by PR #394.
