### ISSUE TITLE
parser functions for classpath, etc. missing

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#39]
There are several parser functions in cimxml-parse that were simply not implmented.  They are flagged as missing by pylint but otherwise would not show up until someone tried to run some of the class
operations.  the missing functions are:

parse_classpath, parse_localclasspath, parse_classname

I marked this as bug because we should at least implement the functions even if they were to just
exception out.

**Comment by andy-maier** [comment]
I don't think these functions will ever be called.

The only place they are invoked is in `parse_value_reference()` which parses the CIM-XML element `VALUE.REFERENCE`. While [DSP0201](http://www.dmtf.org/sites/default/files/standards/documents/DSP0201_2.4.0.pdf) suggests a use of that element that includes class paths and instance paths, [DSP0200](http://www.dmtf.org/sites/default/files/standards/documents/DSP0200_1.4.0.pdf) shows in Table 2 (Mapping of Intrinsic Method Pseudo-Types to XML Elements) that this element is used to represent the values of reference properties. DSP0200 is unfortunately silent about the specifics of parameter values in extrinsic method invocations, but DSP0201 makes it clear that `VALUE.REFERENCE` can also occur in `PARAMVALUE`, presumably for representing reference values. The point now is that [DSP0004](http://www.dmtf.org/sites/default/files/standards/documents/DSP0004_2.8.0.pdf) restricts reference properties and reference parameters to be only instance paths, but not class paths.

There is one additional use of the `VALUE.REFERENCE` element, as a child of `IPARAMVALUE` and `IRETURNVALUE`, i.e. parameters or return values of intrinsic operations. However, there is no such intrinsic operation today that uses that element.

So the functions that are not implemented intend to cover the cases of references to class objects that DSP0201 provides for, but that cannot happen if the rules of DSP0200 and DSP0004 are taken into account in addition.

Therefore, I suggest to raise a suitable exception if these elements are encountered, e.g. by implementing these three missing functions accordingly. Different to what you suggested, this would be the permanent fix, and not a quick workaround.

Let's discuss which exception would be suitable.

**Comment by KSchopmeyer** [comment]
Close this one since we no longer use cim-xml. It was moved to attic
