### ISSUE TITLE
MofRound trip tests for cim_object to cim_object equivalence, Not exact mof output

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#391]
The MOF round trip tests.  builds objects from mof, rewrites the mof from the objects and compiles a second time and then compares the objects created the first and second compile for equality.

However, it does not compare the mof created with the original mof.  There are probably at least two differences in the mof:
1. The mofcompiler sets all flavors on qualifiers and qualifier declarations whereas the original mof assumed that there is a default setting for flavors and only flavors that differ from that default need to be set.
2. The output mof applies the value in all case to binary qualifiers (i.e. association=true) whereas the original input mof allows the keyword association to represent a qualifier with the same value as the declaration.

To be completely correct we should correct these limitations and actually test the created mof against the input mof for equality.

**Comment by andy-maier** [comment]
We discussed to what extent we think this is still worth while, and concluded to drop it completely. Our MOF test does a roundtrip and compares the object representations. Being also able to compare the pywbem generated MOF with the DMTF generated MOF is not worth the effort.
