### ISSUE TITLE
pywbem compiler issue with pragma include

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#4]
Does not correctly process pragma include directive in p_compilerDirective function in that it does not
consider issue of whether there is a path component.  Note that there is a commented  statement, it appears that at one time at least part of this was corrected.

Old code:

def p_compilerDirective(p):
    """compilerDirective : '#' PRAGMA pragmaName '(' pragmaParameter ')'"""
    directive = p[3].lower()
    param = p[5]
    if directive == 'include':
        fname = param
        #if p.parser.file:
        fname = os.path.dirname(p.parser.file) + '/' + fname
        p.parser.mofcomp.compile_file(fname, p.parser.handle.default_namespace)

Proposed change:
def p_compilerDirective(p):
    """compilerDirective : '#' PRAGMA pragmaName '(' pragmaParameter ')'"""
    directive = p[3].lower()
    param = p[5]

    if directive == 'include':
        fname = param
        if len(os.path.dirname(p.parser.file)) != 0:
            fname = os.path.dirname(p.parser.file) + '/' + fname
        p.parser.mofcomp.compile_file(fname, p.parser.handle.default_namespace)

**Comment by andy-maier** [comment]
Karl, I have applied the proposed change to the master branch (commit 96ccdbc).

**Comment by KSchopmeyer** [comment]
Andy committed this change so we should close this issue. I am marking it closed.
