### ISSUE TITLE
Use of [] and {} as default values in function argument definitions.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#40]
Dangerous default value [] as argument (dangerous-default-value) ex variable=[]. This occurs typically in the arguments for functions, especially _init_.  It has the possibility of being a real problem in some cases in that the point in the lifecycle where defaults for arugments is set differes from where values are put.  The proposed solution is to change these to None.

**Comment by andy-maier** [comment]
I agree we should fix this. However, I'd like to defer this to after 0.8.0.

**Comment by KSchopmeyer** [comment]
Note that this is really resolved in the python3 changes since as far as I can tell at least most of the map and filter functions were changed to list comprehensions.

**Comment by andy-maier** [comment]
Did you mean this comment to be on issue #38, instead?

**Comment by KSchopmeyer** [comment]
On 02/14/2016 02:03 PM, Andreas Maier wrote:
>
> Did you mean this comment to be on issue #38 
> <https://github.com/pywbem/pywbem/issues/38>, instead?
>
yes. Updating.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/40#issuecomment-183965564>.
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by KSchopmeyer** [comment]
The comment above about resolved in python3 changes was incorrect and was meant for issue 38. per Andy's comment.  This one remains open and since it appears not to be causing problems now we probably can put off (note however, that problems could be subtle since the issue is that defaults are evaluated only when the function is defined and not when it is evaluated) so that we might have dictionaries and lists in the environment that are not really starting cleared on each call.

The problem is that we may have cases that work correctly because of this behaviour and other that have problems so that we probably have to evaluate each usage individually to be sure.
