### ISSUE TITLE
Should we set up separate file for run_cim_operatons for each test

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#401]
When Andy committed the recorder changes part 2 a simple extension was added to run_cim_operations.py

Couple of questions:

1. Thought we were going to do a file per test??? since if anybody really uses this on the full test, The file will be enormous.
2. Should we be deleting existing file before running tests.
3. Should we find some naming combo that allows us to assure files are ignored by git and we do not accidentally get one in the repository (i.e. a defined prefix)???

**Comment by andy-maier** [comment]
On 1: From a WBEMConnection perspective, the recorder file is controlled by its user (e.g. its name, when it is closed and a new one opened). The user is run_cim_operations.py in this case. Can we do this there?

On 2. Yes.

On 3. Yes. `tmp.*` is already excluded, but of course we can add a new pattern.

**Comment by KSchopmeyer** [comment]
I have no problem with using something template already excluded as part of the file name.  I also put this at a very low priority.  What we have now works to get through the 0.9 release.  Will set for 10 if you agree

**Comment by andy-maier** [comment]
Target 0.10: Agreed.

**Comment by KSchopmeyer** [comment]
See Issue #493 that should resolve issue #1. The user could set the characteristics of a record session and turn on/off the output at will.

This leaves only issue # 2 which is really an issue for the user, not the recorder since an open file is passed to the recorder.  In particular, cim_run_operations is not doing this.
