### ISSUE TITLE
Creating instance in compiler sets values into class

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#402]
Example: testmofs/TestTypes.mof.  Currently instances disabled but in file. If you try to compile with
the instances enabled it sets the instance values into the class.

Probably line 1379 of mof compiler which uses the class properties as the instance properties
    inst = CIMInstance(cname, properties=cc.properties,
                       qualifiers=quals, path=path)

**Comment by andy-maier** [comment]
Fixed by PR #404.
