### ISSUE TITLE
Automatic cleanup of owned destinations, filters, subscriptions

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#407]
Pywbem takes no part in any cleanup of subscriptions and filters that might be left in the server when the listener is stopped without removing these subscriptions/filters.

We do not have a way to identify them as created by our client, etc. so they could be eliminated subsequent at a later time.

At this point I just want to start the conversation since after a bunch of testing where we were terminating the test programs early we ended up with a bunch of outdated filters in the server all with the name cimfilter<uid>

**Comment by andy-maier** [comment]
We can keep track of everything we created, so it is generally possible to clean up. The interesting question is when...

**Comment by andy-maier** [comment]
Discussion points:

* Making sure the WBEMListener object cleans up, even if the program using it dies.
* Can the WBEMListener check for pre-existing instances when it is about to create them?

**Comment by andy-maier** [comment]
The remaining issue is to make sure owned destination, filter and subscription instances are cleaned up when the subscription manager goes away.

This can generally only be done by the user of pywbem, but pywbem can make this easier by providing a context manager for the subscription manager, whose exit function calls `remove_all_servers()`.

A context manager solves this problem only for Python exceptions, it does not solve the problem for killing -9 of the Python process. Therefore, such a cleanup solution is complementary to e.g. a recovery of owned instances by the subscription manager, as discussed in issue #461 .

**Comment by andy-maier** [comment]
**Discussion point:** It seems the only improvement for automatic cleanup would be a context manager as discussed above. Given that we now have automatic recognition of owned instances as such, do we still want to have a context manager that cleans up?

**Comment by KSchopmeyer** [comment]
The context manager concept is logical but not complete.  Would it be logical to have a context manager as an option in the code or just use examples to demonstrate how and why they should always use a context manager.

Lets look seriously at a context manager. Andy feels that is logical.  this would mean we put context manager in our code and show its use in examples.

**Comment by andy-maier** [comment]
**TODO:** Add context manager for the subscription manager, whose exit function calls `remove_all_servers()`.

**Comment by andy-maier** [comment]
PR #583 addresses the remaining issue.
