### ISSUE TITLE
Test failure in make all does not stop tests

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#41]
We need to sort out what the rules are but right now, a failure in testing (I had one that was failing in the cimxml test with an exception that was my problem) did not stop the make.  You needed to sort through the result in detail to determine if there was an error.

This may be the way we want to run in some conditions but in general, for local testing I think it would be better to stop the test at the first failure.

This is open for comment.

**Comment by KSchopmeyer** [comment]
The test.log sort of works but it is easy for a tester to ignore errors when the tests go to completion.

**Comment by andy-maier** [comment]
Given that the intentional exceptions in the test cases that ahppen to be reported, do not count, my take is that PR #43 solves this issue.
