### ISSUE TITLE
Question.  the ValueMapping class. Why part of _server.py

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#410]
The ValueMapping class is so large and might be useful outside of the server context.  Would it be logical to make a separate pywbem file for it???

I did note that buried within the server it can easily be bypassed by prospective users.

Question only.

**Comment by andy-maier** [comment]
In the documentation, it shows up as section 4.3 "ValueMapping" under section 4 "WBEM Server API", and as a sibling section to 4.2 "WBEMServer". 

If we move it into another sub-module, it would still show up there, unless we change the documentation structure as well.

So the real question is where do we want it to show up in the documentation.

Note that at the top level, the documentation is organized along a notion of different APIs. Which API would you like ValueMapping to be part of?

**Comment by KSchopmeyer** [comment]
We concluded that it does works now as it is.  Close
