### ISSUE TITLE
Listener does not remove handler instance.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#411]
In example pegasusIndicationtest.py we do cleanup of:

```
    listener.remove_subscription(server_id, subscription_path)
    listener.remove_dynamic_filter(server_id, filter_path)

    # Stop the listener and remove the server.
    listener.stop()
    listener.remove_server(server_id)
```
However, the handler instances remain in the pegasus server after this is completed
```
kschopmeyer@sheldon:~/pgogtest/pegasus/src/Clients$ cimsub -lh
HANDLER                                                              DESTINATION
root/PG_InterOp:CIM_ListenerDestinationCIMXML.cimlistener1467562861  http://127.0.0.1:5000
root/PG_InterOp:CIM_ListenerDestinationCIMXML.cimlistener1467562963  http://127.0.0.1:5000
```

There is no specific cleanup or even handling of the hander instances available to the user.  I assumed that these were removed when we removed the subscription.

The subscriptions and filters are removed.

We need to sort out what the rules are for this.  These are orphan instances (no subscription) but the pegasus indication service does not specifically remove them when they become orphan.

**Comment by andy-maier** [comment]
`remove_server()` deletes subscriptions, filters and destinations that were created through this listener object. If it doesn't, there is a bug, but the cleanup support is basically there.

**Comment by KSchopmeyer** [comment]
This could have been testing issues although I thought I had run the test clean.  I did a simple test and confirmed that it does remove the handler instance.

**Comment by andy-maier** [comment]
Ok. Probably we should look at making sure we clean up any created instances. We can discuss this in issue #412.
Closing this one.
