### ISSUE TITLE
Listener not reporting back on subscriptions, listeners

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#412]
Either the listener is not reporting back correctly on indications or I do not understand what it is supposed to be doing. Not yet sure of reason for the discrepencey.

I show indications in the server via pegasus utiliities:
```
kschopmeyer@sheldon:~/pgogtest/pegasus/src/Clients$ cimsub -lh
HANDLER                                                              DESTINATION
root/PG_InterOp:CIM_ListenerDestinationCIMXML.cimlistener1467562861  http://127.0.0.1:5000
root/PG_InterOp:CIM_ListenerDestinationCIMXML.cimlistener1467562963  http://127.0.0.1:5000
root/PG_InterOp:CIM_ListenerDestinationCIMXML.cimlistener1467567036  http://127.0.0.1:5000
root/PG_InterOp:CIM_ListenerDestinationCIMXML.cimlistener1467568595  http://127.0.0.1:5000
kschopmeyer@sheldon:~/pgogtest/pegasus/src/Clients$ cimsub -lf
FILTER                               QUERY
root/PG_InterOp:cimfilter1467568600  "SELECT * from Test_IndicationProviderClass"
```
When a call to view these in the code:
```
    server_id = LISTENER.add_server(server)

    dfilters = LISTENER.get_dynamic_filters(server_id)
    print('%s dynamic filters' % len(dfilters))
    for i in dfilters:
        print('dynamic filter %s', i.tomof())

    old_filters = LISTENER.get_dynamic_filters(server_id)
    print('%s filters' % len(old_filters))
    for i in old_filters:
        print('all filter %s', i.tomof())

    subscriptions = LISTENER.get_subscriptions(server_id)
    print('%s subscriptions' % len(subscriptions))
    for i in subscriptions:
        print('old subscrptions %s', i.tomof())
```

says that there are none:

```
0 dynamic filters
0 filters
0 subscriptions
```

**Comment by andy-maier** [comment]
The `WBEMListener` object knows only the instances of dynamic filters, subscriptions and listener destinations it has previously created, and it stores that information in instance variables. The `get_*()` methods you have shown return that knowledge from the instance variables; these methods do not enumerate them globally on the WBEM server. The exception is `get_filters()` which returns all filters by enumerating them in the WBEM server.

That explains why it is possible that the WBEM server has instances that are not shown by the `get_*()` methods.

It does not explain why they have not been cleaned up; I suspect that premature termination of a listener script may have been the reason.

**Comment by KSchopmeyer** [comment]
ckosing
