### ISSUE TITLE
The listener process indication callback is limited

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#413]
Should we consider a more general interface to the indication processor that allowed
access back to the listener or other components of the environment without using
globals?

**Comment by KSchopmeyer** [comment]
Karl sort out what might be better, ex. wbem server object, etc.

**Comment by KSchopmeyer** [comment]
CONCLUSION: 

1.We want to separate the subscription process from the listener itself but somehow the indication consumer has to have a way to get back to the server object that was used to define the indication subscription.

2. Consider that the consumer gets the wbem server object as an argument instead of the host. We have use cases for this

3. We do not see the need now that it get the wbem listener object.  No use case for this now.

**Comment by andy-maier** [comment]
With the separation of `WBEMListener` and `WBEMSubscriptionManager`, the `WBEMListener` does not even know a `WBEMServer` object anymore. It simply passes on every indication it receives, regardless of the origin.

Given that, I don't see how we can address this issue.

**Comment by KSchopmeyer** [comment]
Agree.  Close not fixed
