### ISSUE TITLE
Separate _listener so we have separate components for listener and subscription management

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#414]
There are real cases where a listener and the subscription creation tool are separate.  The subscription mechanism creates subscriptions but does NOT remain alive.  The listener is a separate entity with a separate life cycle.

Currently the pywbem listener strategy is that subscription lifecycle is within the lifecycle of the listener, created when the listener starts and removed when the listener terminates. 

While a user can always fall back to using the subscription create instance, etc. directly the question is whether our listener strategy should allow for async lifecycle of subscriptions independent of the lifecycle of the listener that creates/deletes the indications.  We have demonstrated that you can create an independent listener with the examples/listen.py code so that it is clear that we can actually make such a listener.

**Comment by KSchopmeyer** [comment]
1. We do want to separate the subscription manager and listener. Further we will do it before the 0.9.0 release

**Comment by KSchopmeyer** [comment]
Andreas. My initial thinking is 

a. server
b. subscriptionManager wo which you attach wbemserver as now.
c. Listener.

However, I have not layed out the details.  The major issue is to cleanly separate the listener so that the destination object used for the listener is known to the subscriptionManager

**Comment by andy-maier** [comment]
I agree with this split. Let's start that way, we can learn about the details as we go.
