### ISSUE TITLE
Indications lost under heavy load conditions

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#417]
The test examples/pegasusindicationtest.py can cause indications to disappear between the indication sender and receiver when we try to send large numbers of indications (ex. 5000, 10,000) as rapidly as possible.   We do not really know what the issue is but since indications are experimental in 0.9.0 we propose to put this off to 0.10.0.

The problem does not appear to be random indications missing but that at some point the listener gets overloaded and seems to quite or slow down to accept almost nothing.

We will need to expand the tests in both pegasus and pywbem to sort out this problem.

Note that up to about 3000 indications in a batch we can cleanly send indications from pegasus to pywbem listener with no problems.

**Comment by KSchopmeyer** [comment]
**Test Notes:** With the 0.9.0 release we tested bbetween examples/listen.py and sendications.py.  Using multiple instances of sendIndications.py we can send 90,000 indications with not loss locally, (30,000 per sendindication instance) with no loss. In a single machine using localhost, the throughput is about 97 indications per second per sender while logging to the console every indication or about 100 indications per second per sender with logging set to a level where there is no output.

This means that our theory about a simple threading issue in listener being the cause of indication losses appears to be flawed.  It is apparently something more complex between OpenPegasus and the listener.

**Comment by KSchopmeyer** [comment]
We did find one issue with OpenPegasus in that it has an output queue for indications and simply discards indications when the size of that queue reaches a defined limit.  That limit is also small so that a test we run with 100,000 indications exceeds that limit. In testing I set the limit very high however, and we still have a problem so there may be concerns on the pywbem side.

**Comment by andy-maier** [comment]
Please provide details about a potential problem on the pywbem side.

**Comment by KSchopmeyer** [comment]
See above which is will be a documented Pegasus issue.

CONCLUSION: Close this as pywbem issue and open Pegasus issue

**Comment by andy-maier** [comment]
I agree with the conclusion.

**Comment by andy-maier** [comment]
**Discussion point:** Has the Pegasus issue been created?

**Comment by KSchopmeyer** [comment]
Note that we opened pegasus issue  10113 specifically to cover the limit in max indication queue size.

**Comment by andy-maier** [comment]
Ok, so that Pefasus issue also covers this issue here. Closing it.
