### ISSUE TITLE
We always create new instances of subscription handler, etc

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#419]
We always create new instances in the server of indication subscription objects such as the handler, etc.  It might be more efficient to use existing instances.  We need to investigate the alternatives.

**Comment by andy-maier** [comment]
**Discussion point:**

With the current design n 0.9.0, the user has full control over reuse vs. creation. Also, in issue #461, we will take care of picking up owned instances when the subscription manager restarts. 

We should discuss whether this issue can be closed.

**Comment by KSchopmeyer** [comment]
What we do here depends on #461. Lets see if we can tie that and this together.

**Comment by andy-maier** [comment]
**Discussion point**: PR #541 addresses issue #461 by automatically recognizing owned instances. Is anything in addition needed in context of this issue here?

**Comment by KSchopmeyer** [comment]
This issue may have been obsoleted by later work.  Review and possibly close as done.

**Comment by andy-maier** [comment]
I suggest to close this one. Let's discuss to make sure we agree.

**Comment by KSchopmeyer** [comment]
Close as nothing else needs to be done
