### ISSUE TITLE
compiler requires a destination, even for complete compile and dryrun

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#424]
There is no way to actually run just a dry run compile with pywbem mof_compile even if your mof-input is complete.

**Comment by andy-maier** [comment]
Clarified that the need to be able to run without a destination applies only to the combination of complete compile and dry-run.

**Comment by andy-maier** [comment]
Discussion: Target release?

**Comment by andy-maier** [comment]
We agreed to move this one out of 0.12.

**Comment by andy-maier** [comment]
We agreed to close this one as won't implement. Not important enough.
