### ISSUE TITLE
The  test_client is an all or nothing test and cannot be broken out by component

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#426]
Right now the test_client is all or nothing.  It does not allow testing against individual yaml tests or files.

It would be good if a user could execute single tests.  This could be done by making this a dynamic unit test so that the testcases were dynamically created from the yaml file list or maybe other techniques.

Also, Andy noted that someone else in IBM noted that there are other solutions than yaml for achieving mock unit tests as we have done in test_client.  (KS) In retrospect this is actually logical I think.   The real question is whether using yaml for the test definition gains us anything that using a python destdefintion class or dictionaies would not against the fact that we would not have to  map from yaml to python.  I think this is more an issue of convience and simplicity than a major direction change.

I unilaterally set it to v 0.10.0

**Comment by KSchopmeyer** [comment]
Note that I partly solved this by allowing a single test to be run.  However that still means that the whole test suite is run as a single test.   Actually this is easily modified by using dynamic test creation to create separate testcases for each yaml testcase.

**Comment by andy-maier** [comment]
Basically this means to remove the concept of defining the test_client testcases in YAML, and to go back to unittest testcases for them.

**Comment by andy-maier** [comment]
We should investigate to what extent pytest functionality can be used here. Basically, testclient.py would need to be migrated to pytest, and in the test case loop, pytest would need to be told what test case it is currently on (if such an interface exists).

**Comment by andy-maier** [comment]
I asked about this on SO, with some answers provided: https://stackoverflow.com/q/48340658/1424462

**Comment by andy-maier** [comment]
Fixed in PR #1219.
