### ISSUE TITLE
Need test of mof_compiler script

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#428]
We need a test of mof-compile script but cannot do that one until we modify mof_compile so that it does not depend on existence of server for a dry-run.  Then we can test against the test_mof files for errors, actually confirming that the messages output correctly.

Then we can do something like mof_compiler --dry-run <error_file>.mof

This is probably unique in that it is a regression test that tests against a previous good output saved in a file.

**Comment by andy-maier** [comment]
This issue should test only the mof_compiler script, and not the MOFCompiler class used by it.

**Comment by andy-maier** [comment]
We have no known issues with that script, and it is not likely to change much. Decided to close this issue.
