### ISSUE TITLE
Issue with getinterop_ns in _server on some servers

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#433]
On some servers in test environment, the call to server.interop_ns returns:

WBEM server URL:  https://10.1.134.98
KeyError=%s "Key 'interop' not found"

No Further info at this point.

This only happens with certain servers in the smi lab and apparently only with python2. However, I am still gathering information.

Turns out it is difficult to actually get a detailed trace from the operations in the client.  See next issue

**Comment by KSchopmeyer** [comment]
Andy noted that line 590 has index error where it should be keyerror.  We will start from there.

**Comment by KSchopmeyer** [comment]
Tested with change above and we get different issue, primarily because apparently this server uses a
non-standard interop namespace.   However, the function returns interop as the namespace.  I am still checking this however.

**Comment by KSchopmeyer** [comment]
Getting really wierd results from this one implementation.

WBEM server:  https://10.1.134.91, principal=smilab, credential=F00sb4ll
test ns=interop
OK rtn at 541
inst_paths=[CIMInstanceName(classname='FUJITSU_Namespace', keybindings=NocaseDict({'CreationClassName': 'FUJITSU_Namespace', 'Name': '/root/eternus', 'ObjectManagerCreationClassName': 'FUJITSU_ObjectManager', 'ObjectManagerName': 'FUJITSU:ETERNUS SMI-S Agent', 'SystemCreationClassName': 'FUJITSU_System', 'SystemName': 'FUJITSU:ETERNUS SMI-S Agent'}), namespace='interop', host=None)]
KeyError: ns=interop
ns_dict NocaseDict({'/root/eternus': '/root/eternus'})
Return interop_ns interop
Brand:CIM, Version:None, Interop namespace:interop
All namespaces: ['/root/eternus']

Where I set displays as follows:

    def _determine_interop_ns(self):
        """
        Determine the name of the Interop namespace of the WBEM server, by
        trying to communicate with it on a number of possible Interop
        namespace names, that are defined in the :attr:`INTEROP_NAMESPACES`
        class variable.

        If the Interop namespace could be determined, this method sets the
        :attr:`interop_ns` property of this object to that namespace and
        returns.
        Otherwise, it raises an exception.

        Raises:

            Exceptions raised by :class:`~pywbem.WBEMConnection`.
            CIMError: CIM_ERR_NOT_FOUND, Interop namespace could not be
            determined.
        """
        test_classname = 'CIM_Namespace'
        interop_ns = None
        for ns in self.INTEROP_NAMESPACES:
            print('test ns=%s' % ns)
            try:
                inst_paths = self._conn.EnumerateInstanceNames(test_classname,
                                                               namespace=ns)
                print('OK rtn at 541')
            except CIMError as exc:
                print('CIMError 543 %s' % exc)
                if exc.status_code == CIM_ERR_INVALID_NAMESPACE:
                    # Current namespace does not exist.
                    continue
                elif exc.status_code in (CIM_ERR_INVALID_CLASS,
                                         CIM_ERR_NOT_FOUND):
                    # Class is not implemented, but current namespace exists.
                    interop_ns = ns
                    print('No class but ns exists %s code=%s' (ns, exc.status_code))
                    break
                else:
                    print('raise 533, other error')
                    # Some other error happened.
                    raise
            else:
                # Namespace class is implemented in the current namespace.
                # Use the returned namespace name, if possible.
                print('inst_paths=%s' %inst_paths)
                ns_names = [p.keybindings['name'] for p in inst_paths]
                ns_dict = NocaseDict(list(zip(ns_names, ns_names)))
                try:
                    interop_ns = ns_dict[ns]
                except KeyError:
                    print('KeyError: ns=%s\nns_dict %s' % (ns, ns_dict))
                    interop_ns = ns
                break
        if interop_ns is None:
            print('interop_ns None')
            # Exhausted the possible namespaces
            raise CIMError(CIM_ERR_NOT_FOUND,
                           "Interop namespace could not be determined " \
                           "(tried %s)" % self.INTEROP_NAMESPACES)
        print('Return interop_ns %s' % interop_ns)
        self._interop_ns = interop_ns

**Comment by KSchopmeyer** [comment]
Note: the function _validate_interop_ns is never called from within server.

**Comment by KSchopmeyer** [comment]
Here is a table of results we are getting back from a number of servers in smilab now:

Url                  Brand       Company         Version  Interop_ns   Status
==================================================================
http://10.1.132.227  OpenPegasus NetApp          2.13.0     interop      OK    
https://10.1.132.33  EMC         EMC             None       interop      OK    
https://10.1.134.186 EMC         EMC             None       interop      OK    
https://10.1.134.117 sfcb        Dot Hill        None       root/interop OK    
https://10.1.134.252             Hitachi Data Sy                         ConnEr
https://10.1.134.137             Hewlett Packard                         ConnEr
https://10.1.134.146 sfcb        Hewlett Packard None       root/interop OK    
http://10.1.134.184              EMC                                     ConnEr
https://10.1.134.116 sfcb        Dot Hill        None       root/interop OK    
https://10.1.134.145             Hewlett Packard                         Err   
https://10.1.132.24  EMC         EMC             None       interop      OK    
https://10.1.132.227 OpenPegasus NetApp          2.13.0     interop      OK    
https://10.1.134.75  EMC         EMC             None       interop      OK    
https://10.1.134.163 WBEM        Brocade         None       interop      OK    
https://10.1.134.91  CIM         Fujitsu         None       interop      OK    
https://10.1.134.165             Hitachi Data Sy                         Err   
https://10.1.134.98  CIM         Fujitsu         None       interop      OK    
https://10.1.134.136 CIM         Fujitsu         None       interop      OK    
https://10.1.132.185 PURESTORAGE Pure Storage    None       interop      OK    
https://10.1.134.96  WS          Dell/Compellent None       interop      OK    
http://10.1.137.211              Cisco                                   ConnEr
https://10.1.132.246 OpenPegasus NetApp/LSI      2.9.1      interop      OK    
https://10.1.134.227 Device      Hitachi Data Sy None       interop      OK    
https://10.1.134.185 EMC         EMC             None       interop      OK    
https://10.1.134.147 sfcb        Hewlett Packard None       root/interop OK    
https://10.1.134.148 sfcb        Hewlett Packard None       root/interop OK    
http://10.1.134.160  HP          HP/3PARData     None       root/PG_Inte OK

**Comment by andy-maier** [comment]
We agreed to move the inconsistencies of the various servers into a new issue, and to scope this issue here to only fixing the incorrect exception that is checked, which is already done by PR #439.
