### ISSUE TITLE
add new test to run_cimoperations.py in accord with issue #126 fixes.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#443]
Need to add test to confirm that there are no issues with pegasus and embedded instances.

**Comment by andy-maier** [comment]
Please perform the test and either report any issues or close this issue.

**Comment by KSchopmeyer** [comment]
We added a class of tests class PegasusTestEmbeddedInstance some time ago and I beleive that satisfies this issue. I am closing this issue
