### ISSUE TITLE
getting Importwarning defined below

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#444]
Noticed on testing that I am getting the following warnign message during tests at least with python 27

============================= test session starts ==============================
platform linux2 -- Python 2.7.6, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/kschopmeyer/pywbem/githubpywbem/pywbem, inifile: 
plugins: cov-2.2.1
/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:73: ImportWarning: Not importing directory '/home/kschopmeyer/pywbem/githubpywbem/pywbem/testsuite/test_client': missing __init__.py
  fd, fn, desc = imp.find_module(lastname, path)

**Comment by andy-maier** [comment]
As part of its test case collection algorithm, `py.test` finds the `testsuite/test_client.py` file and then attempts to import it. In doing so, it considers the first directory upwards from the file in question that does not have a `__init__.py` file, to be the base directory, which it adds to the module search path, and relative to which it attempts to import the module it found was a file. So for `testsuite/test_client.py`, it considers `testsuite` to be the base directory, and imports module `test_client`. Now there is a `test_client` directory (the one with the yaml files) and a `test_client.py` file. Apparently, the directory has precedence and is being imported as a package. As a package however, it would need to have a `__init__.py` file inside of it. Which it rightfully doesn't, and which causes the `ImportError` we see.

I verified that the following solution works:
- rename directory `testsuite/test_client` to `testsuite/testclient`
- adjust `test_client.py` to search the yaml files in that changed directory.
- added `testsuite/testclient` to the ignore list of `py.test`. That is not really needed, but it makes sense anyway.

**Comment by andy-maier** [comment]
Fixed by PR #447
