### ISSUE TITLE
Create python class from cimclass so that instances can be created from python class

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#446]
Moving closer to a client generator we should be able to create python classes directly from cimclass objects as received from some entity.  If that entity was a server, these would be fully resolved cim classes so that the corresponding cimclass could be created directly.

If the user wanted to start from mof, we would have to first generate a repository so we have the class hierarchy (mostly resolving the  things that pass down through the class hiearchy and the result of that could be used to generate the corresponding python classes.

The question is whether we consider this to be part of PyWBEM or a separate repository?

**Comment by andy-maier** [comment]
First, it is absolutely possible in Python to create Python classes on the fly, based upon e.g. the information from a `CIMClass` object.

However, if we apply this thought to WBEM operations against a CIM server, then those operations, at least as perceived by the user, deal mostly with instances. Creating a Python class that represents the CIM class of one of those CIM instances is not possible from the instance alone. So if we were to do that, we would need to perform an extra operation against the server that retrieves the class and its chain of superclasses, and maintain them in a cache, like a cached repository. I think this is what you were saying.

On your question whether we would consider this to be part of pywbem: It layers on top of today's wbem client library api, so I guess technically we have both options. I think I would tend to make it part of the pywbem package, though.

I seem to recall that there was another python project that did that. We should look at that.

**Comment by KSchopmeyer** [comment]
Andy comments that you realy want to represent to represent returned instances as python instance instead of cim instance.
Note FSCB does not support class operations.

**Comment by KSchopmeyer** [comment]
We propose to simply look at the possible advantages. We are not sure if in Python this is even an advantage.
Also, lets remove from 0.11 to enable us to get this next version out in minumum time

**Comment by andy-maier** [comment]
**Discussion point:** Do we want to address this as part of pywbem.

**Comment by andy-maier** [comment]
We think this one should not be pursued with a very high priority at the moment.
We leave it open, so we can reflect further input on it.

**Comment by andy-maier** [comment]
We agreed to abandon this one.
