### ISSUE TITLE
Issue between pegasus and pywbem delivering indications

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#455]
We do have a problem betweenpegasus and python delivering indications.  

We established with a new test of a script sending indications to the listener that sending even large numbers of indications appars not to cause lost of indications.

However, against open pegasus, the results are different.  In some cases there are no loses in other large numbers of indications are not delivered.  I have no clear explanation for this today.

Note that when this test is run against the pegasus  listener there is NO loss of instances.

**Comment by KSchopmeyer** [comment]
Not sure in general but the += in the example is NOT thread safe so need to lock around that operation in both run_cimoperations and the pegindicationtest.py in examples

**Comment by andy-maier** [comment]
Please provide details about exactly what fails.

**Comment by KSchopmeyer** [comment]
CONCLUSION: We have a potential issue in OpenPegasus when we have multiple subscriptions with the same filter.  It appears to deliver too many indications. In a test in run_cimoperations with a test provider that delivers a single indication, IndicationService received 2 indications but by the time it got to the pegasus IndicationHandler (which is responsible for output) it appears that this was multiplied to 4, 8, etc. indications.

This does NOT happen when there is a single subscription with the filter.

PROPOSAL. Create Pegasus issue and close this one for us

**Comment by andy-maier** [comment]
I agree with the proposal.

**Comment by andy-maier** [comment]
**Discussion point:** Has the Pegasus issue been created?

**Comment by KSchopmeyer** [comment]
Created pegasus issue # 10113 at

http://bugzilla.openpegasus.org/show_bug.cgi?id=10113

**Comment by andy-maier** [comment]
Closing this issue.
