### ISSUE TITLE
cim_http validtes https but not http.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#457]
parse_url function in cim_http validates https but allows as the other alternative allows anything.

**Comment by andy-maier** [comment]
**Discussion point:** Do we want to fix that in 0.9?

The only concern against requiring either "http" or "https" is whether people use the "file" scheme (there is a corresponding connection object in `cim_http.py`) or a relative form of it, without scheme.

**Comment by KSchopmeyer** [comment]
Confirm that this is real issue and clairfy or close

**Comment by andy-maier** [comment]
**Discussion point:** What do we do with the "file" scheme, and with the relative URI (without scheme); both of that seems to be supported in cim_http.py.

**Comment by andy-maier** [comment]
I looked at this again and it seems to me we need to understand the value of such a cleanup, specifically related to making the checking and parsing of http/https URLs on the one hand and file/no-scheme URLs on the other hand.

Currently, the `WBEMConnection` supports UNIX domain sockets (vie URLs with file scheme or no scheme. The `WBEMListener` does not support UNIX domain sockets.

Which CIMOMs support UNIX domain sockets for their server and for their indication emitter?

**Comment by andy-maier** [comment]
We decided today that we would not clean that up. The code seems to work.
Closing this issue.
