### ISSUE TITLE
Add Iter... methods to WBEMConnection to hide open... vs enumerate operations

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#466]
We will want to extend the enumerates so that the user does not have to make decisions about whether to use pull or not.

If we do it at the WBEMConnection level, the first enumerate request could test for existence of pull operations and set a flag that would last for the life of the WBEMConnection.  I think that the it is logical to do this at the WBEM.

This would also require that the user be able to set some configuration information:
1. interoperation timeout
2. Max objects on each pull

These could be added to the WBEM connection optional variables with a default.

new new operations would probably be based on a generator so that the user would call the operation and get a generator returned.

**Comment by KSchopmeyer** [comment]
We agreed on a telecon that we do need this functionality

**Comment by andy-maier** [comment]
This issue will be addressed in PR #499.
