### ISSUE TITLE
Improve usage/documentation of ipython notebook

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#470]
Karl noted that he found use of the ipython notebook difficult. We agreed that we should work to make it clearer how to incorporate notebooks, etc. so that using the notebooks becomes simple. Otherwise only those who already use notebooks will use them.

We noted that we should be able to use notebooks for executable examples, demos, some presentations, etc but we had to be able to easily integrate pieces into notebooks and create both local and remote notebooks to make this work.

**Comment by andy-maier** [comment]
I improved the tutorial page to make their usage more obvious. See PR #491.
