### ISSUE TITLE
Improve Testing indications/subscriptions in run_cimoperations.py

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#471]
We need to modify this code to:
1. Test against multiple listeners.
2. Clean any outstanding indications out of server between tests. The way it works today if any test fails it leaves indications in the server.
3. Consider pattern that forces shutdown of listener even if there are exceptions since if the listener is not stopped, that port is blocked for the next test.

**Comment by andy-maier** [comment]
If possible, add such tests to the end2end testcases instead of growing the manual test scripts.

**Comment by andy-maier** [comment]
We decided to not pursue this one.
