### ISSUE TITLE
Directions and Priorities for 0.10.0

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#478]
This is an overview of the major goals for PyWBEM 0.10.0 release.  It is a work in progress and the following are just proposals at this point
1. Extend windows testing if possible. issue # 494
   DONE - we are now running pywbem in the Appveyor CI.
2. Extend WBEMEnumerate options to combine pull and non-pull into a single simpler operation issue #466
   DONE - with the new Iter* methods (experimental).
3. Remove experimental from subscription management, listener and WBEMServer to make them fixed apis. #495
   DONE
4. Try to return to a single ssl environment. #496
   NOT DONE - move out to next version
5. Set a coverage goal for mock and try to create enough mock tests to reach that goal (ex. this release + 10 %)  First  be sure we have the mandatory flag on all issues tied to coverage.  Second set a goal. Currently we are at 63% for python 27.  The open issues today are: 464, 440, 437, 436, 428, 403, 391, 362, 285, 75, 61, 44, 18, 15, 13. Generally they are tied to specific test requirements.  13 is general, close it.
   NOT DONE - we gained something and lost something - move out to next version
6. Improve efficiency/speed. ACTION:  Karl will generate tests to compare pegasus client with pywbem client for a set of tests.  From that we can determine how big the issue is. One of the improvements is moving away from the minidom issue #498
   PARTLY DONE - SAX used instead of minidom
7. Next extensions to server and indications. 
   NOT DONE
8. Clean up associations returns #349
   NOT DONE

Time frames: The SNIA plugfests have proven to be reasonable presentation venues for a new version so the following dates are possible:
1. Current date for next plugfest 3 Oct - Too soon to accomplish anything
2. SNIA tech conference 11 Oct
3. Proposed date for next plugfest (about last week of october)

For the moment lets set the end of October for release so we set the end of the development phase at 14 October, Friday.  We have 33 open mandatory issues so even those are probably impossible to complete by the 14th of october.

Question: Would we be better doing more releases with fewer changes per release?  Ex. One in Sept with a couple of changes and a second in Oct instead of a bigger one in Oct.

**Thought:** with OpenPegasus we had to try to build at least one "reason for the user to upgrade" change in to push people to upgrade. That could be something that was required by the specs or some new feature a lot of people wanted.  Lots of minor changes and bug fixes just did not drive users to update.  In PyWBEM, they will update.  What we want to do is to encourage new users to come on board.  The question is how.  Certainly quality is an issue we are resolviing. Meeting standards is close to being resolved. I think it is probably higher level functionality that uses the interface (browsers, etc. implmentation of more and more of the  profiles that are being used. etc.)

**Comment by andy-maier** [comment]
Action item: create new issue with the remaining items, and then close this one.

**Comment by andy-maier** [comment]
All open items in this list now have a new place:
* Issue #635 for incompatible changes in v2.
* Issue #636 for changes targeting v1.0.0.
* Issue #633 for changes targeting v0.11.0.

Closing this one.
