### ISSUE TITLE
Clean up run_CimOperations.py

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#479]
Found some issues in this test program.  Would like to clean up but since I am the only one using it, I would think that this is 0.9.0 optional.

The issues include:
1. Poor names on some variables.
2. Incomplete tests for equality of instances between pull nad not-pull operations.  Actually only the
   counts were being compared, not the instances returned..
3. Couple of code errors in the pull tests leading to incomplete pull tests.  Partly this is because the pull tests are not really determininstic since the server can return a variable number of responses to any single request.
   Specifically this fixes the issue where we were getting different counts of responses when pull sequence compared to an enumerateInstances return.

**Comment by andy-maier** [comment]
Addressed in PR #480.
