### ISSUE TITLE
Pull operation response count error

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#485]
In run_cimoperations.py we run tests of the pull operations by running both the pull operation and the corresponding  non-pull and comparing results.   We occasionally hit one error, in the pull of paths with maxobjectcount = 1 where we are tryng to retrieve about 700 paths.  This does not happen all the time but it does happen.

```
IL: test_get_onebyone (__main__.PullEnumerateInstancePaths)
Enumerate instances with MaxObjectCount = 1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_cim_operations.py", line 1124, in test_get_onebyone
    self.assertEqual(len(paths_pulled), len(paths_enum))
AssertionError: 702 != 700
```

We had a couple other of this type of issue and found that they were actually errors in the test code, not PyWBEM.  In addition in all cases I have documented it is a difference of two paths.

As an example, I ran a repeat 100 times of this one test and the problem happened 2 times. In each case,  the pull showed 2 fewer instances than the enumerate response.

It now only happens with this boundary case of asking for instances one at a time so we released 0.9.0 with the issue open

**Comment by andy-maier** [comment]
Addressed in PR #505.
