### ISSUE TITLE
PyWBEM documentation Quicklinksmissing Pull Operations.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#488]
**Please review"**  Pr is pywbem/pywbem.github.io#14

This documentation does not include:

Pull Operations

Note that it also states that it is for the latest development version. Is the correct or is it the release?

**Comment by andy-maier** [comment]
The version of the links goes to latest dev (i.e. RTD/latest), so what it states regarding the version is correct.

The Pulled enums are indeed missing.

**Comment by KSchopmeyer** [comment]
I will update today.

**Comment by KSchopmeyer** [comment]
Created pr in pywbem.github.io

https://github.com/pywbem/pywbem.github.io/pull/14

**Comment by andy-maier** [comment]
Merged the PR, closing this issue.
