### ISSUE TITLE
CIM Schema gets downloaded on every Travis CI run

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#49]
Which translates to twice per push, because for some reason, Travis runs two jobs for each push.

A possible solution would be to have the CIM Schema files in the PyWBEM git repo, probably best one by one (instead of the zip file).

**Comment by KSchopmeyer** [comment]
We propose that we make the change to zip the latest download and expand the tester to use the zip file. We should also automate the process as much as possible to avoid having to change anything in the environment/make when we update.

**Comment by KSchopmeyer** [comment]
Some open questions:

1. can we easily store binary files in our repo?
2. Are we allowed by licensing rules to store dmtf schemas in our repo?

**Comment by andy-maier** [comment]
Git LFS allows storing large files: https://git-lfs.github.com/
I believe this is not needed for storing binary files, though.

A zip file with the MOF files from the experimental CIM Schema is about 2MB in size, which is not tremendous, particularly if we update it only a couple of times per year.

**Comment by andy-maier** [comment]
Addressed by PR #610
