### ISSUE TITLE
Issue with example certificat in tmp.pem

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#503]
We are using requests module to send indications.  When we try to set the server certificate, we get
the following response indicating that there is an issue with the certificate tmp.pem as far as 
the requests module is concerned.

(pywbem3)kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem/examples$ ./send_indications.py https://localhost:5001 -d 3 -c tmp.pem
/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/requests/packages/urllib3/connection.py:303: SubjectAltNameWarning: Certificate for localhost has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
Exception no appropriate commonName or subjectAltName fields were found

**Comment by andy-maier** [comment]
Action is to fix this example certificate.

**Comment by andy-maier** [comment]
No issue, the tmp.pem file is not part of the pywbem repo.
