### ISSUE TITLE
Reduce pylint and flake8 issues to where we can successfully test return code

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#520]
The release is mandatory is for flake8 and any non-zero returns.

In pylint, the return code returned is as follows:

   Output status code:
      Pylint should leave with following status code:
     \* 0 if everything went fine
     \* 1 if some fatal message issued
     \* 2 if some error message issued
     \* 4 if some warning message issued
     \* 8 if some refactor message issued
     \* 16 if some convention message issued
     \* 32 on usage error
     status 1 to 16 will be bit-ORed so you can know which different
     categories has been issued by analysing pylint output status code

So far I have not identified what the return codes are for flake8 other than it appears to return 1 for any issue (informal documentation)

**Comment by andy-maier** [comment]
PRs #532, #539 and #543 address this issue to some extent.

Remaining flake8 issues at this point:

```
3     E131 continuation line unaligned for hanging indent
33    E501 line too long (115 > 80 characters)
1     F401 '._version.__version__' imported but unused
2     F821 undefined name 'ResourceWarning'
1     F841 local variable 'insts_enum' is assigned to but never used
2     W601 .has_key() is deprecated, use 'in'
```

**Comment by andy-maier** [comment]
I'll work on the rest of them.

**Comment by andy-maier** [comment]
PR #544 now fixes all remaining flake8 issues.
