### ISSUE TITLE
We have no unit test for the recorder

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#536]
Since the recorder is a significant piece of code, we need at least a minimal test.  That wil:
1. Increase coverage
2. Reduce code errors like issue #351 since we will at least run the recorder.
3. Maybe even confirm the output format although I would make that a lower level priority.

This is being resolved as part of issue #676

**Comment by andy-maier** [comment]
The unit test should cover two pieces, probably separately:
- the use of recorders in general in cim_operations, down to the point where record() is called.
- the specific TestClientRecorder, mainly its record().

**Comment by andy-maier** [comment]
Addressed by PR #696.
