### ISSUE TITLE
update schema used in tests to a current version of the DMTF schema. 

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#54]
For now we will download at least once but make the version downloaded flexible.

**Comment by andy-maier** [comment]
The CIM Schema version was updated from 2.20 to 2.45 in pywbem v0.8.1.
Discuss how to make the schema download flexible.
This is related to issues #49 and #82.

**Comment by andy-maier** [comment]
Discussion in the call today: The remaining issues are:
- To have a simple to use control point for the CIM Schema version. Right now, it is set in multiple places. 
- Apparently there are tests that are CIM schema version specific. This needs investigation.

**Comment by KSchopmeyer** [comment]
For 0.10.0. We should update to the currently released schema.We need to write the rules for updating so that we and others know what to do if they use some alternate schema as the basis for testing.

**Comment by KSchopmeyer** [comment]
We just need to make it so it is easy for someone to change to another version.  This is at least more documentation and maybe an extension to a script.

**Comment by KSchopmeyer** [comment]
Moved all of the variables for updating schema to a separate file in testsuite and documented the process in development.rst

**Comment by andy-maier** [comment]
PR #692 addresses this issue.
