### ISSUE TITLE
wbemcli does not accept optional attributes when abbreviation used

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#548]
The following works

```
>>> x = oei('CIM_ManagedElement')
```

The following fails

```
>>> y = oei('CIM_ManagedElement', MaxObjectCount=10)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: OpenEnumerateInstances() got an unexpected keyword argument 'MaxObjectCount'
```

But the non-alias cmd works:

```
>>> y = CONN.OpenEnumerateInstances('CIM_ManagedElement', MaxObjectCount=10)
```

**Comment by andy-maier** [comment]
The short functions such as `oei()` also have short argument names. the equivalent argument for `MaxObjectCount` is `moc`. See also the help function: `help(oei)`

**Comment by KSchopmeyer** [comment]
This was user error.  There are short forms for the options also. Consider this closed as no change

**Comment by andy-maier** [comment]
In the call we agreed that one reason that might cause confusion is that there are global functions with the long names, that have the short argument names.

We should drop them and have only the methods on CONN, and the global functions with short function names and short argument names.

**Comment by KSchopmeyer** [comment]
Yup.   That is where the confusion comes in.  Maybe just more examples.

**Comment by andy-maier** [comment]
PR #586 will address the remaining items from this issue.
