### ISSUE TITLE
Rebuilds MOF parser tables when it shouldn't

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#55]
Branch Python 3 causes a rebuild of the mof and lex table files.  When compiling with python 3 it rebuilds the tables into the table python files multiple times at the end of the build and even in 2.7
it rebuilds the tables when the table files are dated later than the files from which they originate.

This may result from the extra makefile dependencies we inserted.

**Comment by KSchopmeyer** [comment]
The table rebuild after a download for 2.7 appears to be issues with the dates on files as they are retrieved from git.

See below where I did a fresh checkout of the python3 branch and note that the date/times are such that it will recompile once.

-rw-rw-r-- 1 kschopmeyer kschopmeyer   4422 Feb 22 17:19 __init__.py
-rw-rw-r-- 1 kschopmeyer kschopmeyer  99783 Feb 22 17:19 cim_obj.py
-rw-rw-r-- 1 kschopmeyer kschopmeyer  30492 Feb 22 17:19 cim_http.py
-rwxrwxr-x 1 kschopmeyer kschopmeyer  13717 Feb 22 17:19 wbemcli.py
-rw-rw-r-- 1 kschopmeyer kschopmeyer  24162 Feb 22 17:19 twisted_client.py
-rw-rw-r-- 1 kschopmeyer kschopmeyer   3295 Feb 22 17:19 tupletree.py
-rw-rw-r-- 1 kschopmeyer kschopmeyer  49591 Feb 22 17:19 tupleparse.py
-rwxrwxr-x 1 kschopmeyer kschopmeyer  63592 Feb 22 17:19 mof_compiler.py
-rw-rw-r-- 1 kschopmeyer kschopmeyer  52610 Feb 22 17:19 cim_xml.py
-rwxrwxr-x 1 kschopmeyer kschopmeyer  31925 Feb 22 17:19 cimxml_parse.py
-rw-rw-r-- 1 kschopmeyer kschopmeyer  21167 Feb 22 17:19 cim_types.py
-rw-rw-r-- 1 kschopmeyer kschopmeyer  80114 Feb 22 17:19 cim_provider.py
-rw-rw-r-- 1 kschopmeyer kschopmeyer  88329 Feb 22 17:19 cim_provider2.py
-rw-rw-r-- 1 kschopmeyer kschopmeyer  87479 Feb 22 17:19 cim_operations.py

However, the problem with python3 is not clear at all.  when I build with python3, the detailed make out file. Thus:

As shown below it goes directly from the test output to redoing the compiles without any makefile processing. Strange.

Exception in thread Thread-94:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/httpretty/core.py", line 637, in fill_filekind
    headers
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/testsuite/test_client.py", line 156, in socket_ssl
    raise SSLError(1, "Arbitrary SSL error.")
ssl.SSLError: Arbitrary SSL error.

Generating LALR tables
WARNING: 4 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 54 resolved using rule (qualifierName -> ASSOCIATION)
WARNING: rejected rule (empty -> <empty>)
WARNING: reduce/reduce conflict in state 54 resolved using rule (qualifierName -> ASSOCIATION)
WARNING: rejected rule (empty -> <empty>)
WARNING: reduce/reduce conflict in state 56 resolved using rule (qualifierName -> INDICATION)
WARNING: rejected rule (empty -> <empty>)
WARNING: reduce/reduce conflict in state 56 resolved using rule (qualifierName -> INDICATION)
WARNING: rejected rule (empty -> <empty>)

**Comment by andy-maier** [comment]
Karl,
the make rules are only one reason to build the table files. Test invocations of the mof compiler may be another one. That should be looked at, too.

**Comment by KSchopmeyer** [comment]
Working way through the compiler code now. This is clearly coming from compiler invocation and the compiler tests in python 3 whereas the python 2 stuff is coming from time differences in the files after a pull or checkout of the python3 branch. Part of the problem with python2 is that we increased the dependencies significantly but I am not yet sure why the time/date differences in a checkout vs what you see in the web version of the files.

**Comment by KSchopmeyer** [comment]
Interesting in that python v3 significantly rebuilds some of the tables, for example this mofllextable.py diff:

-_lextokens    = {'QUALIFIER': 1, 'octalValue': 1, 'SCOPE': 1, 'INDICATION': 1, 
+_lextokens    = {'OF': 1, 'ANY': 1, 'DISABLEOVERRIDE': 1, 'floatValue': 1, 'dec

**Comment by KSchopmeyer** [comment]
We are getting closer.  It turns out that PLY validates the table when 
the parser is started in yacc.yacc.

It is apparently getting an exception when it tries to read that 
signature in yacc.py and so rebuilds the table.

This come from the read_table function in yacc.py module that generates 
an exception in python 3 when it tries to do an exec.

See the code in the bug.  Now just have to figure out exactly what the 
issue in the exec statement is.


Karl
On 02/23/2016 12:09 AM, Andreas Maier wrote:
>
> Karl,
> the make rules are only one reason to build the table files. Test 
> invocations of the mof compiler may be another one. That should be 
> looked at, too.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/55#issuecomment-187595825>.
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by KSchopmeyer** [comment]
Not sure of the reason for the failure yet but it is clearly the 
exec(import ...) on python3

ply moved to:

         if isinstance(module,types.ModuleType):
             parsetab = module
         else:
             exec('import %s' % module)
             parsetab = sys.modules[module]

in later version but that fails also with exception.

More later.  Need to get some presentations cleaned up now.

Karl
On 02/23/2016 12:09 AM, Andreas Maier wrote:
>
> Karl,
> the make rules are only one reason to build the table files. Test 
> invocations of the mof compiler may be another one. That should be 
> looked at, too.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/55#issuecomment-187595825>.
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by KSchopmeyer** [comment]
Changed back to release optional and, I propose that we not even try to fix it but to replace with the 3.8 version of ply (issue #8 ) since that fixes the problem and there are a number of code changes, not this.  Further, it appears that the problem largely occurs during our own test_mof-compiler test and simply takes up more time to rebuild the tables rather than causing an actual error.

**Comment by andy-maier** [comment]
The rebuild problem is now fixed with PR #68, as of commit c55a3b4.
