### ISSUE TITLE
import of WBEMConnection and WBEMServer from pip download of pywbem

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#553]
For some reason, on another project that uses pywbem when we do an import like

from pywbem import WBEMConnection, WBEMServer, ValueMapping, Error, \
                   ConnectionError, TimeoutError

pylint reports:

explore.py:18: [E0611(no-name-in-module), ] No name 'WBEMServer' in module 'pywbem'

explore.py:18: [E0611(no-name-in-module), ] No name 'ValueMapping' in module 'pywbem'

The code actually works so the python run finds these classes so this appears to be an issue between pylint and pywbem.

Note that this does not occur in our development environment (i.e. the examples directory)

**NOTE:** This may be simply an issue with the virtual environment where you cannot easily run sudo ... scripts because it loses the virtual env.

Will check further when I get back to Dallas

**Comment by andy-maier** [comment]
This sounds as if pylint was run with both of these being true:
* was not run in the work directory with PYTHONPATH=. set
* was run with an older version of pywbem available in the Python path

Pylint imports the module under test using normal Python means, so you can try this to see where it came from:

`$ python -c "import pywbem; print(pywbem.__file__); print(pywbem.__version__)"`

**Comment by KSchopmeyer** [comment]
Canceling this one.  It was my error
