### ISSUE TITLE
Installation on raspberry pi, debian os

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#554]
A number of prerequistes have to be manually installed with this OS.  Not sure if this is a debian issue or a debian/raspberry pi issue. I will have to create a new disk and go through the install again to get the complete list since I manually installed them as I found them but did not take notes.

**Comment by andy-maier** [comment]
Please provide details about the issue.

**Comment by andy-maier** [comment]
PR #865 documents a post-install action for Ubuntu 17.04 on Python 2.6 that is probably also needed by Debian (for multi-arch systems). Please use PR #865 when reproducing the issue.

**Comment by andy-maier** [comment]
Reproduction is needed to report the failure symptoms.

**Comment by KSchopmeyer** [comment]
DISCUSSION: This was always low level and the only usage probably does not really exist.  I suggest we close this one.

**Comment by KSchopmeyer** [comment]
Karl proposes to close this one.

**Comment by andy-maier** [comment]
Agreed.
