### ISSUE TITLE
flake8 does not run against scripts without a .py file suffix

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#560]
I only noticed that it appears to do nothing when I call it from within geany so far.  But I noted some issues in wbemcli that flake8 should have caught and it did not catch them in make all.

Note in particular that the \ on help lines is still in the code and flake8 is not complaining.

Confirmed it does not run against wbemcli: Any files without extensions are simply ignored.  Even the command

    flake8 wbemcli 

which produces no results and if the -v option is set says it is checking 0 files.

copying wbemcli to wbemcli.py

produces lots of flake8 errors.

**DISCUSSION:**  To date the only proposed solution is to temporarilyu copy the scripts to a corresponding *.py file before executing flake8 in the makefile and then remove the temp copy.

Should we do this?

**Comment by andy-maier** [comment]
Yes, we should do this. I grabbed this one.

**Comment by andy-maier** [comment]
I found that specifying `--filename="*" causes flake8 to process the files without suffix.

**Comment by andy-maier** [comment]
I will also fix the flake8 errors that were newly reported for wbemcli and mof_compiler.

**Comment by andy-maier** [comment]
Fixed in PR #574.
