### ISSUE TITLE
Expand WBEMCLI to execute a script as part of startup

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#563]
There could be cases where users of wbemcli want to setup an environment beyond what we do as standard as part of the startup of wbemcli or execute specific python code before the interactive console is made available to the user.  As an example today, set up a server object but that is just one simplistic environment.

This could involve executing imports, creating new functions or classes, and possibly executing additional functions/methods before the user gets control in the wbemcli interactive console.

Python has several components that interact with the python environmnent including to include/execute, etc. code dynamically:

**exec statement** - supports dynamic execution of Python code. if the optional parts are omitted, the code is executed in the current scope. If only the first expression after in is specified, it should be a dictionary, which will be used for both the global and the local variables. If two expressions are given, they are used for the global and local variables, respectively.

**execfile statement** - This function is similar to the exec statement, but parses a file instead of a string. It is different from the import statement in that it does not use the module administration — it reads the file unconditionally and does not create a new module.

**import** - The import statement combines two operations; it searches for the named module, then it binds the results of that search to a name in the local scope.

either exec or execfile seem to do what I think I want.

I did the work and created a PR.  Have that pr up for discussion

**Comment by andy-maier** [comment]
Addressed by PR #566.
