### ISSUE TITLE
Add a concept for unit testing the wbemcli and mof_compiler scripts.

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#569]
The problem is that there is significant code in these scripts but it is not tested in unit tests and therefore is negative hit on coverage as well as being open to undiscovered bugs.

Generally some of the possible solutions include:

1. Move much of the wbemcli code back into testable functions within the pywbem library and leave only a thin shell within the wbemcli file itself.  Several web sites propose this.  Thus, for example, the parser creater could become a function or method, the argparse execution another.  Then we could create unit tests that would simply create the argparser and execute various cmdline options against it testing the results.  Further we could isolate a number of the functions within wbemcli and make them testable with unittests.

Then wbemcli itself becomes a much smaller script and a large part of the code is unittested.

Here are a couple of examples:

   http://stackoverflow.com/questions/12809970/python-unittest-test-a-script-with-command-line-args

   http://dustinrcollins.com/testing-python-command-line-apps

2. Write a unittest that executes the wbemcli as a subprocess and tests results. This is probably fairly limited because it would either have to have mock support to really test much.  We could use it as a regression test for the help, for example but pretty much everything else would have to have a mock component.

3. Use the scripts extension to run wbemcli and test various components.  Thus, if we agree to implement the scripts option (and maybe extend it) we might be able to use this by itself to test at least some of the functionality of wbemcli but not sure how we tie it into overall testingat this point.  You could, for example have test scripts that tested the various cmdline options and did a pass/fail but never passed control on to the interactive console (This would mean making the opts available to the test script).

4. Extend our unittest concepts to be able to run scripts as part of the unittests.

**Comment by KSchopmeyer** [comment]
Suggest we move the mof_compiler script test to another issue and add this on the the

**Comment by KSchopmeyer** [comment]
Opened #730 for MOF compiler command line.  Suggest we can close this one with respect to wbemcli by pointing to the Log issue that also adds a wbemcli test.

**Comment by KSchopmeyer** [comment]
we agreed to close this one

**Comment by KSchopmeyer** [comment]
Modified this and reopened it to have an issue covering the addition of test_wbemcli code that was part of pr #691 that has been withdrawn.  It now is just issue that states requirement for a wbemcli test.

**Comment by andy-maier** [comment]
Fixed in PR #736.
