### ISSUE TITLE
Found the following flake8 issues in code after latest rebase from master

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#575]
Here is list from pr 563 a few minutes ago.  However, on my local system these issues do not show up.
Strange.  This list came from the appvuyer output of the failed test of the pr.

setup.py:537:1: E305 expected 2 blank lines after class or function definition, found 1
pywbem/cim_xml.py:90:1: E305 expected 2 blank lines after class or function definition, found 1
pywbem/cim_http.py:121:1: E305 expected 2 blank lines after class or function definition, found 1
pywbem/mof_compiler.py:269:1: E305 expected 2 blank lines after class or function definition, found 1
pywbem/mof_compiler.py:282:1: E305 expected 2 blank lines after class or function definition, found 1
pywbem/mof_compiler.py:289:1: E305 expected 2 blank lines after class or function definition, found 1
pywbem/mof_compiler.py:305:1: E305 expected 2 blank lines after class or function definition, found 1
pywbem/mof_compiler.py:1909:1: E305 expected 2 blank lines after class or function definition, found 1
pywbem/_recorder.py:79:1: E305 expected 2 blank lines after class or function definition, found 1
testsuite/test_cim_http.py:350:1: E305 expected 2 blank lines after class or function definition, found 1
testsuite/run_cim_operations.py:3659:1: E305 expected 2 blank lines after class or function definition, found 1
testsuite/run_cim_operations.py:3886:1: E305 expected 2 blank lines after class or function definition, found 1
testsuite/validate.py:86:1: E305 expected 2 blank lines after class or function definition, found 1
13    E305 expected 2 blank lines after class or function definition, found 1
make: *** [makefile:316: flake8.log] Error 1
ERROR: InvocationError: 'C:\\cygwin\\bin\\make.EXE check'
___________________________________ summary ___________________________________
ERROR:   pywin: commands failed

The only think I do not understand is why this was not caught on the pr where the changes were made.

**COMMENT KS:** Identified the problem.  flake8 just updated from 3.0.4 (at least that is what I had) to 3.2.0 and apparently added test for 2 spaces at end of class definition.  Tested the changes and the old flake8 does not complain so filing pr after doing tests.

The only thing I do not understand is why when I create a new python virtual env and install pywbem it still brings up flake8 version 3.0.4 and have to do the pip install flake8 --upgrade.

**Comment by andy-maier** [comment]
PR #574 fixes that.
