### ISSUE TITLE
cim_operations.py PropertyList parameter can cause bad XML in request

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#577]
The PropertyList parameter on a number of the wbem operations assumes a list as input.  If a single property name (not in a list is provided), the parameter is accepted but the xml produced and set to the server is invalid.  Because the list definition is not there, the xml does not include the VALUE.ARRAY element around the VALUE element.

Proposal. We could just reject this but maybe the better approach is to allow either str or list input and if it is str, make it a list.

POST /cimom HTTP/1.1
Host: localhost:5988
Accept-Encoding: identity
Content-type: application/xml; charset="utf-8"
Content-length: 521
Authorization: Basic XXXXXXXX
CIMOperation: MethodCall
CIMMethod: OpenEnumerateInstances
CIMObject: root/cimv2

<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0">
<SIMPLEREQ><IMETHODCALL NAME="OpenEnumerateInstances">
<LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="cimv2"/></LOCALNAMESPACEPATH>
<IPARAMVALUE NAME="PropertyList"><VALUE>Name</VALUE></IPARAMVALUE>
<IPARAMVALUE NAME="ClassName">
<CLASSNAME NAME="CIM_ManagedElement"/>
</IPARAMVALUE>

<IPARAMVALUE NAME="MaxObjectCount"><VALUE>100</VALUE>
</IPARAMVALUE></IMETHODCALL
></SIMPLEREQ></MESSAGE></CIM>

HTTP/1.1 400 Bad Request
CIMError: request-not-valid
PGErrorDetail: Validation%20error%3A%20on%20line%202%3A%20Expected%20close%20of%20IPARAMVALUE%20element%2C%20got%20VALUE%20instead

POST /cimom HTTP/1.1
HOST: 
Content-Type: application/xml; charset=utf-8
content-length: 0000000570
TE: chunked, trailers
CIMOperation: MethodCall
CIMMethod: EnumerateInstances
CIMObject: root%2Fcimv2
PegasusAuthorization: Local "kschopmeyer"

<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0">
<MESSAGE ID="1000" PROTOCOLVERSION="1.0">
<SIMPLEREQ>
<IMETHODCALL NAME="EnumerateInstances">
<LOCALNAMESPACEPATH>
<NAMESPACE NAME="root"/>
<NAMESPACE NAME="cimv2"/>
</LOCALNAMESPACEPATH>
<IPARAMVALUE NAME="ClassName">
<CLASSNAME NAME="CIM_ComputerSystem"/>
</IPARAMVALUE>
<IPARAMVALUE NAME="DeepInheritance">
<VALUE>FALSE</VALUE>
</IPARAMVALUE>
<IPARAMVALUE NAME="PropertyList">
<VALUE.ARRAY>
<VALUE>Name</VALUE>
</VALUE.ARRAY>
</IPARAMVALUE>
</IMETHODCALL>
</SIMPLEREQ>
</MESSAGE>
</CIM>

**Comment by andy-maier** [comment]
I agree that we should accept single properties in the PropertyList parameter and turn them into a list.

**Comment by andy-maier** [comment]
Fixed by PR #606.
