### ISSUE TITLE
Misnamed parameters in OpenQueryInstances

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#578]
I named the positional parameters in OpenQueryInstances FilterQueryLanguage and FilterQuery. prob

They should have been QueryLanguage and Query since they are not filter properties at all but the spec names them the same way.

The problem is that these are not filter queries but select queries and we confuse people with this naming.  

Hard to change the spec since the data becomes part of the protocol but easy to change our api

**Comment by andy-maier** [comment]
Karl,
so far, the Pywbem operations use the exact same names for any operation parameters as the CIM-XML spec. I don't think it would be a good idea to deviate from that rule.

I have to say though that GenOps uses "QueryLanguage" and "QueryString" for these parameters. But there are probably more differences between CIM-XML and GenOps, and with Pywbem we were consistent with CIM-XML, so far.

**Comment by andy-maier** [comment]
**Discussion point:** Consistency with CIM-XML operation parameters.

**Comment by andy-maier** [comment]
We decided to leave the parameters as they are now, for consistency with the DSP0200 spec.
