### ISSUE TITLE
Minor issue with recorder

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#590]
This is minor but the change would make working with yaml files easier.

Today the xml form from the recorder is:
```
    data: '<?xml version="1.0" encoding="utf-8" ?>
      <CIM CIMVERSION="2.0" DTDVERSION="2.0">
     . . .
      </CIM>'
```

Would be easier to work with if it was of the form produced by recorder was:

data: >
    <?xml version="1.0" encoding="utf-8" ?>
     <CIM CIMVERSION="2.0" DTDVERSION="2.0">
     . . .
    </CIM>

Just makes it easier to grab and edit if necessary.

**Comment by KSchopmeyer** [comment]
Andy notes that we may not be able to do this.

**Comment by andy-maier** [comment]
It requires investigation as to whether pyyaml is able to do that.

**Comment by KSchopmeyer** [comment]
I agree with andy, the python yaml simply does not give that level of control.

I propose closing as WON'T FIX. Cannot FIX
