### ISSUE TITLE
the make pylint finds an enormous number of issues.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#6]
the pylint target against the rc3 pywbem and got 6200 lines of pylint issues.

a lot of them were simple:
 -- trailing blanks (about 150)
 -- line too long (80 char is the limit) about 400)
-- No space ... ( 20)
-- Unused argument (200+)
-- Invalid Funciton name (100)
-- missing docstring(120)
-- Exactly one space required after comma (800)

**Comment by andy-maier** [comment]
I resolved the most obvious ones in commit 19374d8. The list of files to be checked also has been updated, so that the pylint.log file now has nearly the desired files in them (except for comfychair.py, for which pylint's --ignore does not work).

**Comment by andy-maier** [comment]
We are down to ca. 1100 Pylint issues.

**Comment by andy-maier** [comment]
PR #36 addressed another bunch of them.

**Comment by KSchopmeyer** [comment]
We are fixing this bit by bit in branches.  We will close when we get the pylint output down to something reasonable, ex. 200 - 3-- msgs.

**Comment by andy-maier** [comment]
As of today, the master branch has a total of 242 messages, with by far the most being fixme or missing-docstring.

    +--------------------------+------------+
    |missing-docstring         |93          |
    |fixme                     |92          |
    |bad-continuation          |16          |
    |redefined-variable-type   |8           |
    |no-member                 |8           |
    |trailing-whitespace       |6           |
    |protected-access          |6           |
    |no-self-use               |6           |
    |broad-except              |3           |
    |simplifiable-if-statement |1           |
    |invalid-name              |1           |
    |exec-used                 |1           |
    |cyclic-import             |1           |
    +--------------------------+------------+

Should we close this issue?

**Comment by andy-maier** [comment]
I just created PR #161 which brings it further down:

    +--------------------------+------------+
    |missing-docstring         |93          |
    |fixme                     |92          |
    |redefined-variable-type   |8           |
    |no-member                 |8           |
    |trailing-whitespace       |6           |
    |protected-access          |6           |
    |no-self-use               |6           |
    |broad-except              |3           |
    |simplifiable-if-statement |1           |
    |cyclic-import             |1           |
    +--------------------------+------------+

The trailing newlines are in areas that would create merge conflicts with other PRs, and I think they are solved in them anyway, so I stayed away from them.

**Comment by andy-maier** [comment]
We agreed to close this issue, because now all the fixmes are really one by one.
