### ISSUE TITLE
Add mock (test_client) tests of other operations, especially Associators/Names and References/Names

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#61]
Need to add the local end-end l definition for at least enumerate instances requests and responses

DISCUSSION: Can we close this one as complete.\????

**Comment by andy-maier** [comment]
I suggest to remove the "TODO unsupported" statements in the docstrings of the class and qualifdier operations again. I have used them sufficiently often to believe that they are correctly implemented and described. If errors come up, they are bugs and will be fixed.

I agree that testcases should be added, but that can be done separately.

**Comment by KSchopmeyer** [comment]
On 03/01/2016 04:52 PM, Andreas Maier wrote:
>
> I suggest to remove the "TODO unsupported" statements in the 
> docstrings of the class and qualifdier operations again. I have used 
> them sufficiently often to believe that they are correctly implemented 
> and described. If errors come up, they are bugs and will be fixed.
>
> I agree that testcases should be added, but that can be done separately.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/61#issuecomment-190947387>.
>
I agree.  Will do.

-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
The "unsupported" statements have been removed with PR #76.

Adding tests for class and qualifier operations remains to be done and is now subject of this issue.

**Comment by KSchopmeyer** [comment]
This issue partly corrected with addition of enumerateinstances mock test pull request 79

**Comment by KSchopmeyer** [comment]
Consider that we are complete with this for 0.8.0 and move target for next changes to 0.9.0.

Next we need to define the detailed effort for 0.9.0

Moved to 0.9.0

**Comment by KSchopmeyer** [comment]
I believe that this issue is not satisfied.  We have tests for all of the basic operations in testclient.  While they are not exhaustive, they do test both the main path and exception path for all of the operations.

TODO Check that we actually do all operations

**Comment by andy-maier** [comment]
Addressed by PR #695.
