### ISSUE TITLE
End up with a lot of directories untracked after change to schema 

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#615]
I am ending up with the following directories untracked.  Have not looked into the issue.
	testsuite/schema/Application/
	testsuite/schema/Core/
	testsuite/schema/Database/
	testsuite/schema/Device/
	testsuite/schema/Event/
	testsuite/schema/IPsecPolicy/
	testsuite/schema/Interop/
	testsuite/schema/Metrics/
	testsuite/schema/Network/
	testsuite/schema/Physical/
	testsuite/schema/Policy/
	testsuite/schema/Support/
	testsuite/schema/System/
	testsuite/schema/User/
	testsuite/schema/cim_schema_2.45.0.mof
	testsuite/schema/qualifiers.mof
	testsuite/schema/qualifiers_optional.mof

**Comment by andy-maier** [comment]
Please delete them. They are now one level deeper. And intentionally not in the repo.

**Comment by andy-maier** [comment]
They will be deleted for example with `make clobber`.

**Comment by andy-maier** [comment]
If you agree, I'll close this as no issue.

**Comment by andy-maier** [comment]
We agreed to close this one. Users that run into this will need to have to delete these files once.
