### ISSUE TITLE
mof_compiler does not reflect some issues with compiling

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#617]
1. Does not show if the mof compile to the server failed because the mof already existed. When you try to recompile something that is already in the server, I assume it should report an error.
Status: Pursued by issue #991.

2. Does not appear to remove mof with the -- remove option.
```
Error deleting instance root/cimv2:PyWBEM_Person
     6 CIM_ERR_NOT_FOUND: PyWBEM_Person

kschopmeyer@sheldon:~/pgogtest/pegasus$ cimcli ni Pywbem_Person -n root/cimv2
PyWBEM_Person.CreationClassName="PyWBEM_Person",Name="Alice"
PyWBEM_Person.CreationClassName="PyWBEM_Person",Name="Bob"
PyWBEM_Person.CreationClassName="PyWBEM_Person",Name="Charlie"

Karl. Retest this one.  
```
See issue #1158 that documents this better.

3. The script for mofcompilerd oes not return anything but exit 0 apparently so that there is no exit code to indicate error. 

**COMMENTS:**
See new issue #1157, issues with creating mof.
See new issue #1158, issues with removing mof using mof_compiler script

4. What is impact of doing reject/modify through mofcompilerscript, against a server such as OpenPegasus. Karl test.

ACTION: Karl open two new issues for items 2 and 3

The good news is that it does compile test.mof into pegasus

NOTE: I have documented items 2 and 3 with new issues.  Item 4 can be ignored.   Item 1 is already documented.

**RECOMENDATION:** Close this issue.

**Comment by andy-maier** [comment]
Action: Karl to verify the issues with current code level.

**Comment by andy-maier** [comment]
**Discussion point:** What was the conclusion on this issue?

**Comment by andy-maier** [comment]
Closing this issue, since its parts are either pursued by different issues (see above) or are not valid.
