### ISSUE TITLE
Still missing tests in mock to cover all operations

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#620]
At least the following tests need to be added to the yaml files to test all cim requests:

    finish invokemethod with input and output parameters test
    createclass
    modifyclass
    deleteclass
    setQualifier
    execquery
    openqueryinstances
    OpenQueryInstances
    PullInstances (part of the query instances sequence)

NOTE: Added opequeryInstances is part of the Iter pr, see pr for issue#466.  Sort of got there by accident while we were looking for another problem

**Comment by andy-maier** [comment]
Fixed by PR #647.
