### ISSUE TITLE
New/old issue with connection timeouts.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#628]
Do not know what has happened but it looks like our connection timeouts have sort of bombed.  I will take this one and see in the morning what is causing the problem since this was working for the 9.0 release.  If you ctrl-c it , the code is stuck in the connect mechanism.

I set this to mandatory since it is an enormous delay, minutes for a connection timeout now.  I will work on this first thing in the morning.

Whoops. Went back to v9 release (from pip) and it still takes 2 - 3 minutes for connection timeout.

Apparently this has been something we have missed for a long time. 

**NOTE:** I set this to mandatory when I thought it was a regression. However, given that it appears to have been a long time problem, we have not gotten any feedback about it, and the getaround is for the user to set a valid timeout, we should reconsider if we want to do anything for this release.

The following is from earlier documentation I found on the net:
----------------------------------

Since Python 2.6, httplib has offered a timeout parameter for fetches. As the documentation explains, if this parameter is not provided, it uses the global default.

What the document doesn't explain is httplib builds on top of the socket library. The socket library has a default timeout of None (i.e. forever). This may be an appropriate default for general sockets, but it is a poor default for httplib; typical http clients would use a timeout in the 2-10 second range.

This problem is propagated up to urllib2, which sits on httplib, and further obscures that the default might be unsuitable.

From an inspection of the manuals, Python 3.0.1 suffers from the same problem except, the names have changed. urllib.response sits on http.client.

I, for one, made a brutal mistake of assuming that the "global default" would be some reasonable default for fetching web pages; I didn't have any specific timeout in mind, and was happy for the library to take care of it. Several million successful http downloads later, my server application thread froze waiting forever when talking to a recalcitrant web-server. I imagine others have fallen for the same trap.

While an ideal solution would be for httplib and http.client to use a more generally acceptable default, I can see it might be far too late to make such a change without breaking existing applications. Failing that, I would recommend that the documentation for httplib, urllib, urllib2, http.client and urllib.request (+ any other similar libraries sitting on socket? FTP, SMTP?) be changed to highlight that the default global timeout, sans deliberate override, is to wait a surprisingly long time.

----------------------

I implemented a little script for use with wbemcli  that documents the time to execute a defined operation ( a getclass).  The following demonstrates the time to execute with timeouts not set and set.
When timeout is set, the timeout is a bit longer than the defined time.  When not set, about 4 minutes in my test environment.

```
wbemcli http://sheldonxx -t 10 -s wbemcli-test-timeout.py 
Tests timeouts if invalid server name used for connection

timeout set to -t 10
Start 12:14:37
http connection timeout 10                                 < my diagnostic added to pywbem
Exception Socket error: timed out
After Execution 12:14:57
```
Times out in about 20 seconds and should be 10 but that is acceptable.

```
 wbemcli http://sheldonxx -s wbemcli-test-timeout.py 
Tests timeouts if invalid server name used for connection and no timeout
Start 12:15:14
http connection timeout None
Exception Socket error: [Errno 110] Connection timed out
After Execution 12:19:28


 wbemcli http://sheldonxx -s wbemcli-test-timeout.py 
Tests timeouts if invalid server name used for connection
Start 12:22:12
http connection timeout None
Exception Socket error: [Errno 110] Connection timed out
After Execution 12:26:27
```

Tests timeouts if invalid server name used for connection
Start 15:26:12
http connection timeout None
Exception Socket error: [Errno 110] Connection timed out
After Execution 15:30:27

```

And with python 3
```
Tests timeouts if invalid server name used for connection
Start 15:26:12
http connection timeout None
Exception Socket error: [Errno 110] Connection timed out
After Execution 15:30:27

```
With no timeout, it times out in about 4 minutes with python 2.7 at least in this environment and with python 3 about the same.

First proposal.

Define as part of config.py a PYWBEM_DEFAULT_OPERATION_TIMEOUT and set it to some value. If the user wants the original operation they can set it to None. Otherwise that is the default that we would use when making an http or https connection.  However, that means that the user cannot use the None option without changing the config parameter so looking for something where the user could specifically define None.

**Comment by andy-maier** [comment]
We agreed that the case of timeout=None (default) we should just update the documentation to say it is the standard Python timeout behavior (from several minutes to eternal)

**Comment by andy-maier** [comment]
For a timeout value that is not None, there seem to be some deviations from the specified time, and karl wants to re-run tests for that and post the results.

**Comment by andy-maier** [comment]
Proposing the following text:
```
            A value of `None` means there is the standard timeout behavior of
            the Python requests / urllib3 / sockets packages, which can be
            between several minutes and much longer. Because this is somewhat
            unpredictable, it is recommended to specify a value for the
            timeout.
```

**Comment by andy-maier** [comment]
PR #631 addresses the documentation update.

**Comment by KSchopmeyer** [comment]
The test I have in the environment is the test for operation timeouts when the connected server takes too long to respond.  The test shows that those times are about correct.  This test does NOT test connect timeout (is uses a special method in pegasus to delay the response to a method request).

Below is a short sample of the detailed output for http (the https matches this): 

http  Good Rtn      11    10      10.06  
http  Timeout       11    11      11.00  Timeout when timeout matches delay
http  Timeout       11    12      11.00  
http  Good Rtn      12    10      10.05  
http  Good Rtn      12    11      11.05  
http  Timeout       12    12      12.00  Timeout when timeout matches delay
http  Timeout       12    13      12.00  
http  Good Rtn      13    11      11.06  
http  Good Rtn      13    12      12.12  
http  Timeout       13    13      13.00  Timeout when timeout matches delay
http  Timeout       13    14      13.00  
http  Good Rtn      14    12      12.06  
http  Good Rtn      14    13      13.06  
http  Timeout       14    14      14.00  Timeout when timeout matches delay
http  Timeout       14    15      14.00  
http  Good Rtn      15    13      13.06  
http  Good Rtn      15    14      14.05  
http  Timeout       15    15      15.00  Timeout when timeout matches delay
http  Timeout       15    16      15.00  
http  Good Rtn      16    14      14.06  
http  Good Rtn      16    15      15.06  
http  Timeout       16    16      16.00  Timeout when timeout matches delay
http  Timeout       16    17      16.00  
http  Good Rtn      17    15      15.06  
http  Good Rtn      17    16      16.06
http  Timeout       17    17      17.00  Timeout when timeout matches delay
http  Timeout       17    18      17.00 
http  Good Rtn      18    16      16.05  
http  Good Rtn      18    17      17.05  
http  Timeout       18    18      18.00  Timeout when timeout matches delay
http  Timeout       18    19      18.00  
http  Good Rtn      19    17      17.06  
http  Good Rtn      19    18      18.06  
http  Timeout       19    19      19.00  Timeout when timeout matches delay
http  Timeout       19    20      19.00

**Comment by KSchopmeyer** [comment]
I will write an issue to add test for connection timeout but that is a separate test.  The wbemcli scriptlet shows that it generally works and that the timeout is somewhat longer than the timeout value but not impossible.  Note that this explains some of the confusion in the past because we have to consider the response timeout after connect as a completely different test issue or comment issue than connection timeout.  Right now they both work but one works better than the other.  The one thing we do not know with the response timeout is what happens if the timeout attributes is None.  We do know that the connection timeout is many minutes.  I have to do a test for None as connection timeout  also.

I suggest that this is good enough for Version 10 release

**Comment by andy-maier** [comment]
+1. Merging

**Comment by andy-maier** [comment]
PR #631 was merged, so I'm closing this one as fixed.
