### ISSUE TITLE
wbemcli issue with long form commands

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#629]
The following failed:  Should it have???
>>> cl = conn.GetClass('CIM_ManagedElement')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: GetClass() missing 1 required positional argument: 'ClassName'

However 

cl = CONN.GetClass('CIM_ManagedElement')

works.

since per the help:

Connection:
  CONN             Global WBEMConnection object connected to the WBEM server
  conn             Alias for WBEMConnection class

Shouldn't they both work???

**Comment by andy-maier** [comment]
They should not both work. lower case conn is the class.
