### ISSUE TITLE
Provide MOF compiler API in pywbem namespace

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#634]
Currrently, the MOF compiler API is available in the Python namespace `pywbem.mof_compiler`.

For consistency, it should also be provided in the `pywbem` namespace.

For backwards compatibility, the `pywbem.mof_compiler` namespace should not be changed/removed.

Note, issue #635 has an item to remove the `pywbem.mof_compiler` namespace; this is not part of this issue here.

**Comment by KSchopmeyer** [comment]
We should do this in 0.11.0.

**Comment by andy-maier** [comment]
Fixed in PR #669.
