### ISSUE TITLE
Classes returned from GetClass with property names not unicode

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#644]
CIMClass(classname=u'PyWbem_Run_CIM_Operations1', superclass=None, properties=NocaseDict({u'InstanceID':
CIMClass(classname=u'PyWbem_Run_CIM_Operations1', superclass=None, properties=NocaseDict({ 'InstanceID':

**Comment by andy-maier** [comment]
According to the general concept stated in issue #746, it should be considered a bug.

**Comment by andy-maier** [comment]
PR #841 addresses this issue. Closing the issue.
