### ISSUE TITLE
Recorder issues with recording of open/pull requests.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#648]
We created another type for these requests, 'pullresult' rather than 'result' to get the context info into the response.

The recorder does not cover that difference nor does it report the context information correctly. It
reports it at the same level as the instances rather than within an envelop of its own.

See issue #601 for example of the problem outputting named tuples.  Since the recorder toyaml does not handle namedtuple nor does the python yaml outputter we have to add code to identify named tuples in the recorder and map them to something else.  This can probably be made to work by using th existing isinstance(xxx, tuple) and then a subtest to identify that the item is a named  tuple.  This secondary test will be a hack in that there is no thought-out way to id named tuples in python.  The best is probably to identify an attribute of the tuple (ex. (_asdict() or __dict__) and use this function to map the tuple to a dictionary.  This was one of those things that was clearly not though out in the design of nametuple in that an test for named tuple type is a hack and has variations on different versions of python (python 2.6 being the weakest). But, for example _asdict was obsoleted in 3.4 and then later.

**Comment by andy-maier** [comment]
Fixed in PR #660.
