### ISSUE TITLE
Add option to makefile to generate detailed coverage report

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#649]
Add an optional report generation that shows line by line coverage of the files in the pywbem/pywbem
directory.  This will help analysis of coverage issues.

This is a feature of coverage and can be produced by adding the options for report output:
'''
--cov-report=annotate --cov-report=html
'''
to py.test

Make this optional since there is no reason to generate it for every test run, and particular the continuous integration tests under travis, etc. since it is just discarded.

An optional environment variable/command line variable can be used to control generation of the reports:

ex.
```
make test PYWBEM_COVERAGE_REPORT=1
```

**Comment by andy-maier** [comment]
Fixed in PR #650.
