### ISSUE TITLE
Make sure PyWBEM supports the TLS use of SNIA

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#65]
SNIA requires the use of TLS in a certain way for SMI-S.
These requirements are documented [here](http://www.snia.org/sites/default/files/TLSspec-v1%20Technical%20Position.pdf).

Make sure that PyWBEM supports these requirements, and document that.

**Comment by andy-maier** [comment]
Karl to set up a test against OP with TLS 1.2 enabled. If that succeeds, we can close this issue. We do not tackle client-side enforcement of the SMI-S requirements right now.

**Comment by KSchopmeyer** [comment]
Open pegasus normal mode of operation is TLS 1.2 only.  That is what we have been testing against so far.

Note that there is a runtime variable to disable this.

Comments:
1. No way for the user to check this during run. Interesting.
2. There is a test that is run on build to confirm that it is tls 1.2 but that is tied to a particular cipher so bit messy to run.
3. Also no way to confirm ciphers actually use but there is a runtime definition to set certain ciphers.

**Comment by KSchopmeyer** [comment]
We can close as complete.
