### ISSUE TITLE
There is special code for the openwbem server but no way to test or knowledge about why

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#653]
This code is located in cim_http.py, wbem_request where pywbem is processing the response and looks for a response  header ' Server' that contains the 'openwbem' attriibute.  This appears to be part of authorization challange for OpenWBEM that includes  a special nonce but whose use in the response processing is limited to responses with that specific response header.

 Since the response header 'Server' is a special header, I propose that we simply ignore that fact that this code exists but that we cannot test it.

The only thing we might do is to make a comment in the documentation about special code for the openwebem server.

Since this is open source and we are in a minor version, there is no way this could be removed.

However, I assume that if we move to a different http library we will have to seriously consider if we should move this processing forward since it is 1-00+ lines of code and we have no way of testing it.

**Comment by KSchopmeyer** [comment]
We propose a new section in the documentation to document server specific functionality and servers which we test against.

**Comment by andy-maier** [comment]
Addressed by PR #717.
