### ISSUE TITLE
The cim_operations.py Pull... operations do not check for None for MaxObjectCount

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#656]
Since this is a required parameter for the cim/xml pull operations and the default is None, a request
with None will be sent to the server.  This is not a major error since the servers are expected to answer
with an error response. However, we should really stop it locally:

1. Supply a non-None default(This is actually a very logical solution)
    or
2. Reject if None is received by the API or the attribute is not provided at the interface.

**DISCUSSION:** Anybody prefer either of the two proposals above

**Comment by KSchopmeyer** [comment]
The error is in our code in that two of the functions have MaxObjectCount as an optional and one has it as a required parameter.  We agreed to fix the ones that have it as an option.

**Comment by KSchopmeyer** [comment]
We agreed that we must also fix this in 0.10.0 to minimize the damage.

**Comment by andy-maier** [comment]
PR #658 fixes this for 0.11.0.
TODO (Karl): Integrate that fix into 0.10.1.

**Comment by andy-maier** [comment]
PR #666 backports the fix into 0.10.1.
