### ISSUE TITLE
WBEM Server get_selected_profiles. Compare is case sensitive

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#670]
This test is case sensitive.  Trying to compare profile name array to find the Array profile returns no profile.  Not sure whether this is correct or not.  At the least this should be documented in the _server documentation.

DISCUSSION: Should the test be case sensitive?

This appears to be correct in that these are property values and property values are case sensitive.

The one change that might be logical is the documentation to document that the tests are case sensitive.

**Comment by andy-maier** [comment]
Fixed in PR #703.
