### ISSUE TITLE
Add cim_operation timing to pywbem

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#671]
We propose to add a mechanism that will allow the execution time for each operation to be captured and made available to:

1. The user after the call
2. pywbem statistics keeper

This feature will be normally disabled but can be enabled by the user (ex. similar to the debug feature in WBEMConnection) either by a WBEMConnection constructor parameter or by setting an attribute in WBEMConnection.

Note that the execution time must capture the time both for normal completion and for exceptions.

DISCUSSION: What should we do about the iter functions that are actually a higher level and use the CIM_Operation request primitives?

**Comment by andy-maier** [comment]
Addressed with PR #675.
