### ISSUE TITLE
Comparing ciminstancename objects

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#686]
There is an issue in comparing instance name objects.  If the keybindings are not in the same order in the two items being compared they will not match.  However, they are, in fact, equal.

**Comment by andy-maier** [comment]
I don't believe this. Looking at the code, the equals comparison happens in `NoCaseDict.__eq__()`, whose code explicitly takes care of different iteration order of the underlying Python `dict` objects. Iteration order is the only order defined for a dictionary, and it may not even be repeatable).

Can you please provide a test case?

**Comment by andy-maier** [comment]
I have put up PR #688 to better validate this issue.

A situation where this happened to you would still be useful, Karl.

**Comment by andy-maier** [comment]
The test case in PR #688 is able (on Python 2.7 and 3.6) to construct two `CIMInstanceName` objects whose key bindings are in different iteration order, and to prove that these two objects still compare equal. I have set the "invalid" flag on this issue, for now.

**Comment by KSchopmeyer** [comment]
Close as invalid
