### ISSUE TITLE
Add processing of WBEMServerResponseTime

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#687]
The DMTF Specification provides for an optional response header 'WBEMServerResponseTime" that, if provided defines a measure in microseconds of the elapsed time required by the server to process the request and create a response.  We should extend pywbem to handle this and include it as part of the statistical information provided via the statistics processing in the client.

This is defined in section 6.3.15 of DSP0200 v 1.4.0

Issue #276 is a duplicate of this issue and has been closed as a duplicate.

**Comment by KSchopmeyer** [comment]
Closing as duplicate

**Comment by andy-maier** [comment]
I just closed this by mistake. Reopening it.

**Comment by KSchopmeyer** [comment]
We set this one to 0.11.0, mandatory.

**Comment by KSchopmeyer** [comment]
The WBEMServerResponseTime is documented in DSP0200, section 6.3.15. It is an additional Response header that may be sent by the WBEM Server that contains data that defines the total
server response time for the operation as a 64-bit unsigned integer value.  If the actual response time exceeds the maximum representable, then the maximum value shall be returned.

The header name is WBEMServerResponseTime

Since this header is optional, the client must always expect it but not require it.

**Comment by andy-maier** [comment]
Fixed in PR #716.
