### ISSUE TITLE
getting warning from ply about yacc compile

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#694]
.WARNING: yacc table file version is out of date

We are getting a number of reduce conflicts, etc. but the one that bothers me right now is the out of date warning.

**Comment by andy-maier** [comment]
Can you please describe how to produce that warning? In a clean (i.e. `make clobber`) environment with the `master` branch, I get only the usual warnings about reduce/reduce conflicts:
```
testsuite/test_mof_compiler.py 
Generating LALR tables
WARNING: 4 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 61 resolved using rule (qualifierName -> ASSOCIATION)
WARNING: rejected rule (empty -> <empty>) in state 61
WARNING: reduce/reduce conflict in state 63 resolved using rule (qualifierName -> INDICATION)
WARNING: rejected rule (empty -> <empty>) in state 63
.................................................................................elapsed compile: 15.239926  
Start recompile file= /home/maiera/Projects/pywbem/repos/pywbem/testsuite/test_mofRoundTripOutput.mof
elapsed recompile: 31.871252  
.
```

**Comment by KSchopmeyer** [comment]
For some reason, my virtual env was getting ply 3.8, not the current ply 3.10.  However, the files had been created as ply 3.10. Thus the message since the ply version did not match the version of the files it had created. I removed the virual env and completely recreated it and the problem went away. 

The one question in my mind here is the case where a yacc file is created in a local pywbem installation and for some reason later ply is updated.   Do we cover this case???  That is, in effect, what I had but I cannot explain why the ply file for that virt env was earlier version than the yacc output.

**Comment by andy-maier** [comment]
We do cover this case, I think. The code that re-generates the table files should handle this.
I did not test it though.

**Comment by KSchopmeyer** [comment]
Note that the compile actually worked despite the warning message.

We are closing this one as unable to really recreate and no real impact.
Close as wont't fix

**Comment by KSchopmeyer** [comment]
close
