### ISSUE TITLE
Need concept section in pywbem documentation

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#697]
This should probably be the second section in the documentation

1. Intro
2. Concepts
3. Tutorial
4. Client API
.....

This came up specifically because Karl included concepts for pull and iter operations in the notebooks and we agree that it is not really the place for them.  We can create hyperlinks from the notebooks but the concepts description should be elsewhere.

**Comment by andy-maier** [comment]
PR #699 addresses this issue initially, but contains several TODOs.
