### ISSUE TITLE
Pywbem makefile/pylint does not honor files marked to ignore

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#7]
The makefile check target uses pylint to run lint tests on the python code and puts the results in a log file.

The statement to execute this lint defines two files to be ignored with the --ignore option. However,
executing make check causes pylint to lint at least the mofparsetab file to be checked which is an
issue in part because almost not of the file will pass the lint tests so it generates an enormous number
of lines in the log file.  Since this is a file generated by the yacc parser itself, there should be not
reason to run lint against it.  The syntax of the pylint options seems correct but both of the
files defined get processed.  Adding the # pylint: skip-file at the head of the file does cause the
file to be to be ignored in check (A message in the log indicates that pylint looked at the file and ignored it).  Since this also happens when pylint is manually executed (ex. pylint --ignore=mofparsetab.py mof*.py  it would appear that this might be an issue in pylint self.  We tried

pylint --rcfile=../pylint.rc --ignore=moflextab.py mof*.py
pylint --rcfile=../pylint.rc --ignore=mof*.py mof*.py
pylint --rcfile=../pylint.rc --ignore=moflextab mof*.py

None of which appear to cause the file to be ignored in the check.

Note that we do not want to include these files in the pylint check since they are generated files and
we do not want to try fixing lint problems in them.
pylint.log: $(pylint_rc_file) setup.py os_setup.py $(package_name)/*.py testsuite/*.py
	-sh -c "PYTHONPATH=. pylint --rcfile=$(pylint_rc_file) --ignore=moflextab.py,mofparsetab.py --output-format=text setup.py os_setup.py $(package_name) testsuite/*.py |tee pylint.log"

**Comment by KSchopmeyer** [comment]
It turns out that apparently, while the command line option does not honor the file list, the same option in the configuration file does so that the statement:

ignore moflextab.py,mofparsetab.py

in the file pylint.rc does cause those files to be ignored by pylint.

**Comment by andy-maier** [comment]
Karl,
which version of pylint did you use for this?

I have verified this with Pylint 1.3.1, and the command line option works fine.

Unfortunately, it turns out that Pylint 1.4 and higher intentionally broke compatibility with Python 2.6.

Also, Ubuntu 14.04 still has Pylint 1.1.0, and I think that is quite old.

in PyWBEM's setup.py, we can specify the dependency to Pylint either as a Python level dependency, or as an OS level dependency. The problem is that the Python package 1.4 and higher installs without a problem on Python 2.6, and then breaks when invoked, even with just "pylint --version".

**Comment by KSchopmeyer** [comment]
On 01/19/2016 06:13 AM, Andreas Maier wrote:
>
> Karl,
> which version of pylint did you use for this?
>
> I have verified this with Pylint 1.3.1, and the command line option 
> works fine.
>
I tried the 1.1 (ubuntu 14.04) and also pylint 1.5.1 and still get the 
problem with --ignore= on the command line. Actually just executing the 
make check hits the problem for me in that it lints both of the listed 
files.  also a simple lint command line pylint --ingore=mofparsetab.py 
mof*.py lints the mofparsetab.py unless I am missing something i my setup.

However, putting the ignore into the rc file  works fine.  Discuss 
tomorrow morning. Maybe

Also, We need to add yacc.py and lex.py to  the ignore.  These were 
taken from external code and (hopefully) use exactly the code in from 
the external
source. Also they generate an enormous number of pylint errors and I 
really do not thing we need to fix them.  Since we should also look to 
update
lex/yacc to somewhere near the current version (and isolate them) I 
would be a real mess to clean them up, not to mention that the author warns
not to change the code.
>
> Unfortunately, it turns out that Pylint 1.4 and higher intentionally 
> broke compatibility with Python 2.6.
>

I can try version 1.3.1.
>
> Also, Ubuntu 14.04 still has Pylint 1.1.0, and I think that is quite old.
>
About 4 + years old
>
> in PyWBEM's setup.py, we can specify the dependency to Pylint either 
> as a Python level dependency, or as an OS level dependency. The 
> problem is that the Python package 1.4 and higher installs without a 
> problem on Python 2.6, and then breaks when invoked, even with just 
> "pylint --version".
>
So much for easy  :-)  Subject for discussion  tomorrow morning.

Started the pull operations and currently deep into minidom.

Karl
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/7#issuecomment-172834277>.
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
I found that the files in the pywbem package are properly ignored with both the ignore statement in teh pylint.rc file, and the --ignore command line option, while comfychair.py for example is not ignored either way, and it is in a directory that is not a package.

I was using pylint 1.3.1 on Ubuntu 14.04 and pylint 1.5.4 on RHEL 6.7 for this test, same result.

See whether it excludes the mofparsetab etc for you with the latest master.

**Comment by KSchopmeyer** [comment]
This appears to have been fixes in recent checkins.  In particular we were getting 6000 + pylint messages and now down to about 1000 and the exception list works.

Close this issue
