### ISSUE TITLE
coveralls and issue with coverage versioning.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#723]
Issue #691 has an issue with the test_wbemcli.py generating a deprecation warning that comes from

coveralls
    coverage (apparently versions below 4.1)
          config.py (which is specifically defined with version in coverage) filename issue deprecation warning
          future python 3

This only impacts pywbem because we use subprocess to execute wbemcli in test_wbemcli.py and when coveralls/coverage runs it executes this test script and apparently overrides our setup for that test that disables the deprecation warnings.  Since we test to see if stderr is empty upon return from the subprocess call to execute wbemcli and this deprecation warning gets through and shows up in stderr when stderr should be empty, we fail our tests, not in normal execution but in coveralls/coverage execution.

Newer versions of coverage have been created to fix the deprecation warning issue but right now coveralls specifies an old version of coverage and that specifies an old version of config.

HOWEVER., in the coveralls tox.ini, in github there are setup parameters for coveralls3, coveralls4, etc. that appear to specify more up-to-date dependencies.   At this point I do not know how to activate them.

The following is the relevant sections of tox.ini

```
[testenv]
...
deps =
    cov3: coverage<4.0
    cov4: coverage>=4.0,<4.1
   cov41: coverage>=4.1
...
[testenv:coveralls41]
deps =
   coverage>=4.1
...




```

**Comment by andy-maier** [comment]
PR #1893 increases the minimum versions as follows:

From:
* python-coveralls==2.8.0
* coverage==4.0.3

To:
* python-coveralls==2.9.2
* coverage==4.5.3

That brings coverage above 4.1 which apparently solves the issue according to the issue description above.

However, I have not seen wbemcli tests failing in our tests on Travis or Appveyor even before this change. I did not check, but is there anything in the wbemcli tests that suppresses these warnings, or did this issue simply become moot over time?

**Comment by andy-maier** [comment]
We discussed this and decided to close it because it probably got moot over time.
