### ISSUE TITLE
Extend tests in test_wbemcli.py

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#724]
We build a unittest that specifically tests the wbemcli script.  At the same time it has a limited number of tests today.
We propose to add more tests.

**Comment by andy-maier** [comment]
**Discussion point:** What out of that issue is still open given that we merged PR #1399 in 0.13.0?

**Comment by andy-maier** [comment]
Karl says that nothing is left. We can close this issue.
