### ISSUE TITLE
The logging functions have no documentation other than the code and doc strings

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#725]
We should create more complete documentation to make it easier for users and put it into the html doc

This was documented in pr #708

**Comment by andy-maier** [comment]
It is not true that we have just the code and docstrings as documentation of pywbem logging: We do have a [Logging chapter](http://pywbem.readthedocs.io/en/latest/client.html#logging).

Please point out what the issues are with that chapter.

**Comment by andy-maier** [comment]
**Discussion point:** Propose to close this one.

**Comment by KSchopmeyer** [comment]
close and review to see if there issues with the logging chapter
