### ISSUE TITLE
Linking log entries to connections in multi connection cases

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#729]
Today we output a log entry for each new wbemconnection and a a log entry for each
    method call
    method response
    http request
    htp response.

As long at there is only one connection it is simple to determine which method calls are associated with a connection.  

However, in an environment where the user may be defining multiple connections, it might be difficult to determine which operation and http logs correspond to which connection.

A simple solution for this might be to simply keep a monotonically integer that is incremented for each new connection.  That connection id would be put into each log for the methods for that connection.

This was documented in pr #708

**Comment by KSchopmeyer** [comment]
Andy noted that we need to cover the issue of separate processes feeding the same log.

**Comment by andy-maier** [comment]
This issue has been addressed in PR #739.
