### ISSUE TITLE
Add tests for MOF_Compiler Cmd Line

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#730]

**Comment by andy-maier** [comment]
PR #1936 has decreased the test coverage of the `pywbem/_cliutils.py` module to 0%. The `tests/test_wbemutils.py` command that existed before that PR coul dbe used as a basis for creating a test program for the mof_compiler command.

**Comment by KSchopmeyer** [comment]
Moved to 1.1.0.

**Comment by andy-maier** [comment]
Closed as a duplicate of #428.
