### ISSUE TITLE
Documentation on statistics

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#740]
We have a section on statistics in the documentation but do not include the item in the list at the beginning of client.rst defining the existence of this section.

Add
* :ref:`Statistics` - Statistics on timing and size of  WBEM operations.

**QUESTION:** There also appears to be no reference in the documentation to the config.py file and its parameters. ERROR/ks: It is documented in intro.rst, line 386

Finally, I am not sure how one includes documentation that has the comment form #: in the documentation.  That is just a question for discussion. Answer. Include the :members: statement for the automodule.

**Comment by KSchopmeyer** [comment]
Agreed that we need section on config.py and add the ref to statistics

**Comment by andy-maier** [comment]
Fixed with PR #742.
