### ISSUE TITLE
Unicode / binary string inconsistencies between py3 and py2.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#746]
Gathering examples of where we expect utf but dont get it or get inconsistencies especially between python 2 and 3

In adding tests for the log... subclass of the test recorder, I had a lot of problems with the testfixtures package and trying to compare results of logs created in both python 2 and python 3.  We are getting attributes back in the logs in each version that differ as shown below.

**Test_recorder, capture testing log output. Python 3, test.**

 These differences cause the test which is just a comparison of what you expect vs what the log that was created looks like to be inconsitent between python 2 and python 3 tests.

The namespaces and classname are inconsistently u;.. vs not u' in the log string representation so that tests must be different between python 2 and python 3.
actual:
```
LogOperationRecorderTests.test_getinstance_exception2
(('pywbem.ops',
  'DEBUG',
  'Request: '
  "GetInstance:test_id(InstanceName=CIMInstanceName(classname='CIM_Foo', "
  "keybindings=NocaseDict({'Chicken': 'Ham', 'Beans': 42}), "
  "namespace='root/cimv2', host='woot.com'))"),
 ('pywbem.ops',
  'DEBUG',
  "Exception: GetInstance:test_id(CIMError(6, 'This is a fake CIMError')...)"))
```
expected:
```
(('pywbem.ops',
  'DEBUG',
  'Request: '
  "GetInstance:test_id(InstanceName=CIMInstanceName(classname=u'CIM_Foo', "
  "keybindings=NocaseDict({'Chicken': 'Ham', 'Beans': 42}), "
  "namespace=u'root/cimv2', host=u'woot.com'))"),
 ('pywbem.ops',
  'DEBUG',
  "Exception: GetInstance:test_id(CIMError(6, 'This is a fake CIMError')...)"))
```

But the same test in python2 return:
actual:
```
(('pywbem.ops',
  'DEBUG',
  "Request: GetInstance:test_id(InstanceName=CIMInstanceName(classname=u'CIM_Foo', keybindings=NocaseDict({'Chicken': 'Ham', 'Beans': 42}), namespace=u'root/cimv2', host=u'woot.com'))"),
 ('pywbem.ops',
  'DEBUG',
  "Exception: GetInstance:test_id(CIMError(6, 'This is a fake CIMError')...)"))
```

**Comment by andy-maier** [comment]
The general concept should be that we accept unicode strings and binary strings as input, and that we produce unicode strings as output, and that that is the case for both Python 2 and Python 3.

Let's use this issue to list pywbem APIs that do not behave according to this concept.

**Comment by andy-maier** [comment]
PR #841 addresses this issue for the CIM object classes, so the values are now always unicode.
However, the representation (via `repr()`) of the unicode values differs between python2 (with u) and python3 (without u).

If the testcases continue comparing the `repr()` results, they will continue to distinguish between python2 and python3.

Suggest closing this issue.

**Discussion needed.**

**Comment by KSchopmeyer** [comment]
We propose closing this one since the issue is that the logger adds the u' indicator different in python 2 than python 3 and we are doing string compare on the logger outputs.
