### ISSUE TITLE
Possible python 3 iteritem issues

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#749]
A quick search found the following possible python 2 iteritems
pywbem/cim_obj.py:295:        return list(self.iteritems())
pywbem/cim_obj.py:314:    def iteritems(self):
pywbem/cim_obj.py:337:        The order of dictionary items is the iteration order of `iteritems()`.
pywbem/cim_obj.py:340:                           for key, value in self.iteritems()])
pywbem/cim_obj.py:402:        for key, self_value in self.iteritems():
pywbem/cim_obj.py:1049:    def iteritems(self):
pywbem/cim_obj.py:1055:        return self.keybindings.iteritems()
pywbem/cim_obj.py:1495:        for _, val in self.properties.iteritems():
pywbem/cim_obj.py:1498:    def iteritems(self):
pywbem/cim_obj.py:1502:        for key, val in self.properties.iteritems():
testsuite/test_cim_obj.py:211:        # Test iteritems()
testsuite/test_cim_obj.py:213:        self.assertEqual(len(list(obj.iteritems())), 2)
testsuite/test_cim_obj.py:216:            self.assertTrue((key, exp_dict[key]) in obj.iteritems())

These should be reviewed to see if they are python3 issues.

**Comment by andy-maier** [comment]
I reviewed them and none of them is a Python 3 issue; they are all the iteritems() method of our own NocaseDict, which exists in both py2 and py3.

**Comment by andy-maier** [comment]
Karl agrees we can close this issue.
