### ISSUE TITLE
Add mock (test_client) end-end tests for the class and qualifier type operations

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#75]
These operations need end-end tests added. Today their are none.

**Comment by KSchopmeyer** [comment]
Done in earlier Pr and this one got left in place. the following tests exist

getclass
getqualifier
enumerateclasses
enumerateclassnames
enumeratequalifiers

Lets close this one.

**Comment by andy-maier** [comment]
Agreed. Closed.
