### ISSUE TITLE
The ref :class:`py:tuple` does not produce doc link

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#762]
See cim_operations.py, line 668,

creds (:class:`py:tuple` of userid, password):

I assume that this should generate a link in the documentation.  It just produces bolded text.

**Comment by andy-maier** [comment]
It turns out that in Python 2, `tuple` is a function and not a class. In Python 3.6, there is both a function and a class.

PR #767 fixes that.
