### ISSUE TITLE
SLP support

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#78]
slp is the defined discovery mechanism for SNIA smi and DMTF WBEM.  However, any slp requests would have to be processed outside pywbem today and further, the only apparent python slp implementation is very old meaning that there is no easy way to introduce slp info within a python/pywbem environment.  There are a couple of possibilities here:
1. a new, improved, slp interface as a github project etc. 
2. let users try to use the existing repositories (see  http://openslp.svn.sourceforge.net/)
3. introduce an slp interface within pwbem

Looking for ideas about what we should do

**Comment by KSchopmeyer** [comment]
Found a github openslp interface at https://github.com/ncultra/openslp/tree/master/tags/2.0.beta2/openslp.misc/python. I have not tried this no no idea how well it works.

**Comment by andy-maier** [comment]
I think pywbem should use an SLP library instead of crafting one.
We should start with the existing openslp library and determine its shortcomings, if any.

**Comment by rchateauneu** [comment]
I could not find an other library than openslp, which works although it's
poorly documented. It would be worth to fix its problems (Better error
messages for example ) and use it extensively as it is not far to be
completely operational.

Another good thing is that it is widely distributed. So starting from it
would save a lot of time.

**Comment by andy-maier** [comment]
Remi, thanks for the investigation!

**Comment by andy-maier** [comment]
Which versions of the WBEM SLP template (DSP0206) do the relevant versions of SMI-S require or allow?

**Comment by andy-maier** [comment]
Do we need the ability for consumers of the API to specify arbitrary OpenSLP attribute filters when searching services, or is filtering by initiative and/or profile sufficient?

**Comment by KSchopmeyer** [comment]
They defer to the current dmtf specs.


On 03/10/2016 11:25 AM, Andreas Maier wrote:
>
> Which versions of the WBEM SLP template (DSP0206) do the relevant 
> versions of SMI-S require or allow?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/78#issuecomment-194966332>.
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by KSchopmeyer** [comment]
On 03/10/2016 11:36 AM, Andreas Maier wrote:
>
> Do we need the ability for consumers of the API to specify arbitrary 
> OpenSLP attribute filters when searching services, or is filtering by 
> initiative and/or profile sufficient?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/78#issuecomment-194969791>.
>
If we use the openslp api as the basis (which I think the one I found 
uses) we get all of that.  H0wever, the
real question is that this work, while on github, is not part of Pypi 
and therefore special installation today
and we have no idea of the quality.

Karl

-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
The Python wrapper is also in the original repo at SF: https://sourceforge.net/p/openslp/mercurial/ci/default/tree/openslp.misc/python/

We need to figure out what the difference is. 

Neither repo offers a distribution archive for the Python wrapper. Technically, we can create one ourselves and point the pywbem setup to that URL. This could be a temporary solution, until it is officially on Pypi.

**Comment by andy-maier** [comment]
I created a fork of the origin

**Comment by andy-maier** [comment]
I created a fork of the original repo at SF, for any changes we may need:

https://sourceforge.net/u/andymaier/openslp/

This is a Mercurial repo, and SF meanwhile allows creating merge requests.

The changes in the fork of ncultra (Mike Day) are: Support for SLP interface associations, generalizing any python2.2 commands to python, and SLP templates for kvm.

**Comment by KSchopmeyer** [comment]
We are probably going to need to support slp through python so this is 
logical.  It would be good to be able
to fully move it to github as project and create a full package.

Karl
On 03/11/2016 06:38 AM, Andreas Maier wrote:
>
> I created a fork of the original repo at SF, for any changes we may need:
>
> https://sourceforge.net/u/andymaier/openslp/
>
> This is a Mercurial repo, and SF meanwhile allows creating merge requests.
>
> The changes in the fork of ncultra (Mike Day) are: Support for SLP 
> interface associations, generalizing any python2.2 commands to python, 
> and SLP templates for kvm.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/78#issuecomment-195350218>.
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by KSchopmeyer** [comment]
Not sure yet.

Karl
On 03/10/2016 11:36 AM, Andreas Maier wrote:
>
> Do we need the ability for consumers of the API to specify arbitrary 
> OpenSLP attribute filters when searching services, or is filtering by 
> initiative and/or profile sufficient?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/78#issuecomment-194969791>.
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by rchateauneu** [comment]
Hi Andreas

I would say, an important thing is to help against the mysterious error
code -19:

https://sourceforge.net/p/openslp/mailman/message/30427298/

"When tried to use slptool register, it always got error -19 ... "

This sounds like a stupid obstacle to openslp (Having myself lost much time
on it), because it does not give any other information.

Generally speaking, returning much more information (For example with a
full-debug-verbose mode) will be greatly, greatly beneficial.

Thanks

Remi

**Comment by KSchopmeyer** [comment]
On 03/10/2016 11:36 AM, Andreas Maier wrote:
>
> Do we need the ability for consumers of the API to specify arbitrary 
> OpenSLP attribute filters when searching services, or is filtering by 
> initiative and/or profile sufficient?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/78#issuecomment-194969791>.
>
The native API will provide the general filtering.  First goal is to 
just make sure that works and an import
can suffice to use it in pywbem.

Logical second goal is for us to be able to present simple api with 
minimal attributes to get DMTF profiles
    - 1 vs 2 ? or both
    - interop namespace info
    - possibly selected profiles

Karl


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
We agreed in the call today to move SLP support beyond 0.9.0.

**Comment by KSchopmeyer** [comment]
We agreed to try with the M. Day package from github for 0.10.0

**Comment by KSchopmeyer** [comment]
We agreed to move this beyond 0.11.0.

**Comment by andy-maier** [comment]
I did another investigation on Python SLP support. Here is the result:

| Python package | Approach | On Pypi | License | Repo | Docs |
| ----------------| ------- | ---------| ----- | ------ | ------- |
| openslp.misc.python | openslp wrapper | No | BSD | https://sourceforge.net/p/openslp/mercurial/ci/default/tree/ | N/A |
| python-libslp | openslp wrapper | No | LGPL | https://github.com/tsmetana/python-libslp | 
| pyslp | Pure Python | Yes | ? | Copy: http://pydoc.net/pyslp/0.1.7/pyslp/ | https://pythonhosted.org/pyslp/ |
| slppy | Pure Python | No | Apache 2.0 | https://github.com/jjohnson42/slppy | N/A |

**Comment by rchateauneu** [comment]
Great job.
Also, pyslp is Python 3 only and includes a server.
slppy seems to be Python-agnostic but made to run on Linux.

**Comment by andy-maier** [comment]
It turns out that the OpenSLP Python wrapper uses Pyrex, which still exists as a package on Pypi, but whose files seem to have been removed. Last update to the Pyrex source repo was in 2006. I think this approach can safely be given up on.

**Comment by andy-maier** [comment]
Here is the result of my initial attempt to ghet python-libslp going:

The python-libslp wrapper implements the wrapping code in C. In order to build it on OS-X, I needed to do (thanks to https://github.com/tmux/tmux/issues/257#issuecomment-245315362):
```
brew install openslp
brew install autoconf automake m4 libtool perl pkg-config
```
and in the work directory of its git repo clone:
```
autoconf configure.ac >configure
chmod 755 configure
./configure
make
```
This created `src/openslp.so`.
Running `src/test.py` failed with:
```
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```

**Comment by andy-maier** [comment]
Karl and I discussed ths today, and we decided to abandon this issue as won't implement.

Reason:
* There is no useable SLP package
* Neither Karl nor I are up to writing an SLP package or fixing one of the existing ones
* SLP is not set up properly in the SNIA test center anymore.
