### ISSUE TITLE
OpenQueryInstances has incorrectly named query parameters

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#781]
The `OpenQueryInstances()` method has query related parameters named `FilterQueryLanguage` and `FilterQuery` even though its input is not a filter query. The description of `FilterQueryLanguage` even states that "DMTF:FQL" is not permitted.

These two parameter names are misleading and should have been named `QueryLanguage` and `Query`.

Some data points: 
* In the traditional `ExecQuery()` and in the new `IterQueryInstances()` methods, the query related parameters are named `QueryLanguage` and `Query`.
* The `OpenQueryInstances()` method has been introduced in pywbem 0.9.0 (directly as final, without an experimental phase).

**Comment by andy-maier** [comment]
It seems we can change to the correct names in a compatible manner:
- Change the current parm names to the correct ones
- Accept the current parm names as kwargs, and when supplied issue a DeprecationWarning.
This is compatible both when specifying the parms as positional args and as named args.

**Comment by andy-maier** [comment]
Reviewing this issue again, it turns out that the parameters of the `OpenQueryInstances` operation in DSP0200 are in fact named `FilterQueryLanguage` and `FilterQuery`. The parameters of the corresponding generic operation are named `QueryLanguage` and `Query`. So the current parameter names in pywbem are consistent with DSP0200.

**Discussion point and Proposal:** Leave the parameter names unchanged and close this issue.

**Comment by KSchopmeyer** [comment]
I agree.  We goofed in the documents.  If we want to change something it would be documentation to clarify the problem and possibly one test in the call to tell the user that they are using the wrong query language

**Comment by KSchopmeyer** [comment]
Lets close this one as will not do
