### ISSUE TITLE
The version of PLY used in pywbem is about 7 years and 8 versions old

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#8]
pywbem uses version 3.0 of this code and version 3.8 was released in October 2015.
We should at least explore the changes and issues with moving pywbem to the newer version.

**Comment by andy-maier** [comment]
Version 3.8 is on PyPI, and I suggest that we try it out, and if it works, use it as a dependency instead of copying the code.

**Comment by KSchopmeyer** [comment]
This change is, in fact, probably more of a change than just an enhancement in that it fixes the bug defined by issue #55. However there are a number of possibilities introduced by this, primarily around how this update should be incorporated in that the ply code:

1. Creates/updates two python files in the package (mofparsetab.py and moflextab.py).
2. Does this based on a number of criteria, (not just the file dates)
3. Needs access to the package install to do the update.
4. 


Generally:

a. Put the updated ply yacc.py and lex.py into the pywbem release as we did the current versions. This would insure that we know which version of ply is being used against our mof definitions and also that
we could precompile the yacc and lex tables as part of the package build.

b. Use the ply package as an import.  This reduces the size of pywbem and dependence on a particular version of ply but probably imposes another requirement that the build of the yacc and lex tables be built into the setup.py code so that the tables would be built as part of the install of pywbem and installed into the pywbem install directory for a couple of reasons: 1. It is not certain that ply will not change the tables between versions so that if we were to use tables built when the package is built they might differ from those required by the version of ply installed during the package install and we cannot be certain of the version of ply that will be installed in the users environment; 2. Be sure that the tables are build before the package is used because the package can actually build the tables on any ply yacc initiation if it is unhappy with the current tables (non-existent, bad validity check) and the user may not have access to the install directory (i.e. not sufficient permissions) so that the tables build would fail.
