### ISSUE TITLE
Unittest_extensions.py issue with RegexpMixin

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#804]
The optional RegexpMixin methods include an optional msg attribute but it is not displayed when an assertion is raised. Also it is not in the documentation.

**Comment by andy-maier** [comment]
This issue may become moot once the transition to pytest is complete. Waiting for completion of #1414, then re-evaluate.

**Comment by andy-maier** [comment]
At this point, the RegexpMixin class is only used by run_cim_operations.py. This is not run regularly and is also supposed to be converted to pytest (see issue #1414). For this reason, I am closing this issue as will not fix.
