### ISSUE TITLE
Jobs manager extension -> save the code

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#810]
Provide a service similiar in nature to the existing subscription manager to manage CIM Jobs in WBEM servers

**Comment by KSchopmeyer** [comment]
My first action is to propose the requirements.

**Comment by andy-maier** [comment]
Created a PR #1023 from the branch that Karl pushed on this issue.

**Comment by andy-maier** [comment]
I suggest to move this to beyond 1.0.0.

**Comment by andy-maier** [comment]
We agreed to move this one out.

**Comment by andy-maier** [comment]
We discussed this and don't want to drive that to completion, but we also do want to save the code somewhere.
