### ISSUE TITLE
Correct issues with description formatting of embedded mof

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#815]
See TODO in cim_pbj.py, line method _scalar_value2mof

Today we just throw out any strings that are really embedded objects without and formatting. The TODO asks if we should do any formatting of the embedded entity as an EmbeddedObject. 

Note that the logical way we normally create embedded instances with mof is to use the alias mechanism; a)create a new instance with the embedded instance data and b) create an instance alias and include it in the mof.  The alternative is to include the instance mof directly as value and I am not sure that we even support that.

**Comment by andy-maier** [comment]
Fixed in PR #942.
