### ISSUE TITLE
Implement tool to mock pywbem for testing of higher levels

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#838]
Uses of pywbem need some means of testing against pym without requireing that there be a complete server available.  This is very useful for unit testing the higher levels and can be used for things like simple demos, etc.

We propose to mock at the level of WBEMConnection so that the user can create a fake simple repository and use that to mock pywbem operations against a server, creating data for thefake repository so that users of pywbem can execute comands like getclass, etc. and get known data back.

Proposals:

1. Extend the MofRepository in mof_compile so is could be used as the basis for a repository based 
server mock tool.  The MOFrepository class replaces the WBEMConnection methods that communicate with a server with classes that manage data in local lists. Thus, for example it creates a new GetClass method

2. Extend WBEMConnection directly to mock at the level of _imethod call.  This means that the code in WBEMConnection request methods (GetClass, etc.)

The second concept has some advantages:
   - Does not modify the methods in WBEMConnection so that the logic that prepares WBEM Requests is fully retained (parameter checks, etc.)
  - Only requires two mock functions (_imethodcall and _methodcall)

Further, the implementations of the WBEM request methods in the mof_compiler was build only to create a very simplified repository.   It does NOT validate parameters, just uses them.  It actually uses the GetClass to create new classes in the repository (CreateClass calls GetClass) so that it would require signifcant change to code that already accomplishes a real task, the creation of a repository but not the other, the use of that repository by other tools.

We looked at using the MOFRepository classes as the basis for the repository but, this was really designed as a tool to compile and insert data into a repository not as a tool to access that data.

Primary goals:

1. Create a very simple mocker that observes only the most basic rules of a WBEM Server, accepts snippets of CIM object data and responds directly to WBEMConnection WBEM requests with data. This would be a useful tool for unit testing.  Thus, a tester could create a repository with one class in it, and using getclass and enumerateclass know exactly what data was being returned.

2. Create a more complex mocker that tries to emulate as much of a server with a repository as possible and allows loading complete schemas and processing more complex requests.   The primary differences between the simple one and this is:

  - It will require the class and qualifierdeclarations to be built since they are required to completely build instances and respond to requests like enumerateInstances, associators, etc.  In general it shold ack like a WBEMServer.  The simple form will simply respond with canned data from its fake repository. That means unit tests will be easy to build but very limited in generality for the simple mocker.
  - It will make it easy to execute multiple tests from a single pywbem_mock set of data

This will be a separate package within pywbem that can be used by pywbem tests themselves and also by other tools by enabling the FakeWBEMConnection in place of WBEMConnection and feeding data to it either by compiling qualifiers, classes, instances or by adding the CIMClasses, CIMInstances, CIMQualifiers directly to the repository.

**Comment by andy-maier** [comment]
This issue has been addressed with PR #847 and lateron refined with PRs #982, #999, #1007 and #1012.
**Discussion point:** Anything left to do (except TODOs in the code) or can this issue be closed?

**Comment by andy-maier** [comment]
There is one more issue with CreateClass that should still be fixed as part of PR #1012. After that, we treat new problems as separate issues.
