### ISSUE TITLE
why is DEFAULT_NAMESPACE defined in cim_operations.py

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#84]
To me this is a core setting and finding it buried in one of the std components seems strange.  At the same time I have not found out where it would actually be logical yet

**Comment by andy-maier** [comment]
Maybe in cim_constants.py?

**Comment by KSchopmeyer** [comment]
OK for future but lets not mess with mother nature here and do more than criticals in 0.8.0. I.e. set to 0.9.0

**Comment by andy-maier** [comment]
Just for additional consideration: It's an incompatible interface change, if people used the symbols from the submodules instead of following the (new) recommendation to use the symbols folded into the pywbem namespace. Moving it to 0.9.0.

**Comment by andy-maier** [comment]
Decided on the call that we move this constant to cim_constants.py, and keep it public.
