### ISSUE TITLE
Clean up wbemconnection logger interface.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#859]
We agreed that the current interfaces for defining logging for wbemconnections is not clean, to heavyweight and that we want to change it before we remove the experimental from this api.

**Comment by andy-maier** [comment]
We agreed that each of us would come forward with a proposal.

**Comment by KSchopmeyer** [comment]
Client logging at the api level and at the xml level.  Uses two named loggers.

We agreed to drop the logger on the mocker since it duplicates what the cim_operations logger does.

We have the capability to define the loggers from a formatted string which defines each logger by name, the destination, and whether is is full display or summary display (i.e. 3 pieces of data for each logger) name:dest::detail or simething like that.

**Comment by KSchopmeyer** [comment]
We agreed with the release of 0.11.0 that the pywbemlogger class was an experimental means of configuring the pywbem logger. the goal of this was to define a convient means for users of pywbem to configure the specific loggers used by cim_operations to log request APIs and their responses and also the xml generated given that we wanted to add one new piece of functionality not normally in loggers, the ability to define multiple output formats (detail or summary) for each logger.

We have found several issues with this implementation but cannot find anything better given that we are adding data to the logger configuration.

Specifically:

The documentation is oriented towards the implementation, not the user.

The documentation is incomplete and a number of characteristics such as defaults is not clarified.

It is not really a singleton in that it does not require the creation of a single object but uses the class level variables to store the configuration data

We did agree to keep the method that uses a string input to define the loggers as a common tool for clis that use pywbem.

**Comment by KSchopmeyer** [comment]
I did the clean up and hate the result.  Here are some issue I found:

1. We have logging configuration spread out in two places (the basic configuration is in PywbemLoggers) but we set the size parameter when we enable a logger by creating the instanceobject of LogOperationRecorder.

2. There is no simple default that allows a default logger to be setup with just a single statement (ile. add_logger().  If you do that now, nothing is logged since the default for logger destinations is None.
The default ought to be something that creates a log output so that the only thing minimally necessary to set up a loger would be to:

   a. Create the wbemconnection
  b. Add_operation_logger(LogOperationRecorder())

This would create a default logger that actually output something for both xml and the apis.

3. Having to setup the logger in a separate class now means that you have to do three things to enable a logger.
   a. Create the wbemconnection
  b. Define the loggers in PywbemLoggers by using one of the create methods.
     ex. PywbemLogger.createLoggers('all=stdout:detail')
  c. Add_operation_logger(LogOperationRecorder(max_log_entry_size=300))

4. The for PywbemLoggers is not really connected to the add_logger so you have to find the info in two different places.  It would probably be more logical if you were to set the logger parameters to non-default values directly as part of the LogOperationRecorder init so that if init parameters were to be set they could be set as part of adding the logger.

   a. Create the wbemconnection  conn = WBEMConnection(...)
  b. conn. add_operation_logger(LogOperationRecorder(loggerconfig=xxx, log_max_entry_size=300))

5. Logging is univesal and cannot really differ by connection because we set a named logger with parameters in PyWBEMLoggers and then use this definition in multiple connections.

5. There are a couple of issues with this right now. 
   a. using the logger by name means that we fix the characteristics of the logger once and tie it to a logger name and then use that name as the means to control logging in the recorder.

How we can do better.

1. Drop the name loggers for this and use the LogOperationRecorder __init__ as the config setting tool for the logger.

However, this represents a different problem if we want to configure both loggers, we have either many parameters on the init or have to have some means to set multiple loggers.

Using the string approach is simple.

    conn.add_operation_logger(LogOperationRecorder(loggerconfig='all=stderr:detail', 
        log_max_entry_size=300))

Or better yet. lets build the size parameter into the log config definition:
    conn.add_operation_logger(LogOperationRecorder(config='all=stderr:detail:300')

But while that is one option it depends on a string with parameters to define the configuraiton and we really want an alternative  that is more precise. But we want to possibly set up multiple loggers so the __init__ would have to handle multiples of a config structure to do this.

Maybe something like:
    For the string config def:
        conn.add_operation_logger(LogOperationRecorder(configstr='all=stderr:detail:300')

or

        conn.add_operation_logger(LogOperationRecorder([config('ops', dest='stderr', detail='min'), 
            config('xml', dest=file)]
     
      which would set up both loggers.

**Comment by KSchopmeyer** [comment]
> logger

ecorde

**Comment by andy-maier** [comment]
Fixed in PR #1105.
