### ISSUE TITLE
run_cim_operations.py badly broken

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#87]
Trying to test pywbem using this python testsuite code indicates that it is broken in several areas including

1. The startup hangs with some cmdline input
2. The exception code fails
3. Some tests incomplete
4. The log code is commented out because there is no log function.
5. The arg help defines options that are not in code.

I propose to fix enough to run tests before 0.8.0 release. Expanding tests can come later.

**Comment by andy-maier** [comment]
This file is not used at all by the unit test cases. So we can consider this a case of test coverage improvement and resolve it in the next release after 0.8.0. I'm not trying to fence this off, but we keep making the work for 0.8.0 larger every time we get close to releasing it...

**Comment by KSchopmeyer** [comment]
How I know.  We can move this to 0.9.0 or commit what we have to date since it is definitly better than what I started with Saturday.

**Comment by andy-maier** [comment]
My suggestion: In addition to what we have in the branch so far, let's move the UTF test function into a new module for 0.8.0 and let's defer the rest of the fixes/improvements to 0.9.0.

**Comment by KSchopmeyer** [comment]
I have moved the utf test function.  Lets talk about commit of this at telecon in morning
