### ISSUE TITLE
wbemcli pp does not really do much

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#884]
Some simple examples

>>> pp([1,2,3,4, [6,7,8,9]])
[1, 2, 3, 4, [6, 7, 8, 9]]

As defined it does not even really format a list.

**Comment by andy-maier** [comment]
This is pretty printing( `pprint()`). You used an example where the difference does not matter.

Here is an example from the help text of wbemcli:
```
Example:
  >>> cs = ei('CIM_ComputerSystem')[0]
  >>> pp(cs.items())
  [(u'RequestedState', 12L),
   (u'Dedicated', [1L]),
   (u'StatusDescriptions', [u'System is Functional']),
   (u'IdentifyingNumber', u'6F880AA1-F4F5-11D5-8C45-C0116FBAE02A'),
  ...
```

**Comment by andy-maier** [comment]
I suggest to keep `pp()`.

**Comment by KSchopmeyer** [comment]
Close as no issue.  We did discuss creating a pp method for cimclass, ciminstance, etc. that would prettyprint the data but reached no conclusion
