### ISSUE TITLE
the run_cim_operations test is run whenever test target run

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#89]
The run_cim_operations.py is s special test, a live test against a running cimom. It requires that
a cim server be present to run the test.

However, all of the python files in testsuite are run for every make test including this one.  Suggest that we could break this down by type (those starting with test run for make test, those with another prefix (ex. run) are run by special target (ex servertest) and for now servertest would be manual.

**Comment by andy-maier** [comment]
Karl, I have looked again at the test log files created by "make test", and I cannot see that `run_cim_operations.py` is run. Can you please double check?

**Comment by KSchopmeyer** [comment]
Actually I was guessing since the makefile just specifies all in testsuite.  Not sure how it is excluded then.  When it runs, without params it just complains and exits.

**Comment by andy-maier** [comment]
As I understand it, the test program looks into the directory and runs only files that begin with `test`. Same for methods of the testunit subclasses.
Actually, I think the value of these operation tests is really small. If we want to drive operations against a real WBEM server, we should really turn `wbemcli` into a command line driven program. For testing the operations, we have test_client now.
Another useful test against a real WBEM server would be against a standard test implementation. That's what we should evolve run_operations.py to, over time.
If you agree, then let's create according new issues, and let's close this one.
