### ISSUE TITLE
Several documentation issues in associators, references, and possibly GetQualifier

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#91]
I notes some issues

1. Associators and References with class input returns a tuple
2. The qualifier operations doc refers to get or delete or something like that.
3. I have couple more notes but will fill them in tomorrow.

**Comment by andy-maier** [comment]
Is this about the methods of `WBEMConnection`?

* On 1: Don't understand. They are supposed to return a list, and the description says so.
* On 2: Don't understand.
* New: The GetQualifier method says in its general description section that it returns a `CIMQualifier` object, and in its "Returns" section that it returns a `CIMQualifierDeclaration` object. The latter is correct.
* New: The general description of the EnumerateQualifier method has been copied from GetQualifier without adjusting it.

**Comment by KSchopmeyer** [comment]
Yes and sorry that I did short form yesterday but wanted to get something documented before I forgot.
Will make more complete list later today.  Actually might be easier for me to just fix.

**Comment by andy-maier** [comment]
Merged PR #98.
Waiting for Karl's input on additional incorrect descriptions, based on master branch.

**Comment by andy-maier** [comment]
No issues known right now, but more review needs to be done. Closing this issue.
