### ISSUE TITLE
DSP0200 issue: Incorrect CIMObject escaping in examples

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#925]
Some of the examples in the Appendix A of DSP0200 do not correctly escape the value of the CIMObject header fields. Mostly, the value shown is `root/cimv2` when it should be `root%2Fcimv2`.

This issue here tracks the creation of a corresponding DMTF issue against DSP0200.

**Comment by KSchopmeyer** [comment]
Created DMTF Mantis issue 2852 on 8 Oct. 2019
