### ISSUE TITLE
DSP1054 issue: Allow creators of dynamic filters to recognize their filters

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#926]
Issue #540 discussed the possibilities to allow a client to identfy the dynamic filters they created. It turned out that we did not find such a way, given the current CIM Schema and Indications Profile (DSP1054).

This issue tracks the creation of a corresponding DMTF issue against DSP1054.

Possibly this also needs to be brought back to SNIA.

**Comment by KSchopmeyer** [comment]
Created DMTF Mantis bug # 2851 on 8 Oct. 2019
