### ISSUE TITLE
DSP0201 issue: Representation of reference return types in METHOD

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#927]
Issue #902 discussed the missing support in DSP0201 for representing reference return types in method declarations.

Current situation regarding the support of reference return types in CIM methods in the CIM standards:
* The CIM architecture supports it (see section 5.1.2.9 "Method" in DSP0004 2.8.0, which has no constraint precluding that).
* The MOF syntax supports it (see section 7.10 "Method Declarations" in DSP0004 2.8.0).
* The CIM-XML protocol supports it for method invocations, but not for method declarations (see section 5.3.6.13 "RETURNVALUE" in DSP0201 2.4.0 for an explicit description of reference return values in method invocations, and section 5.3.5.7 "METHOD" in DSP0201 2.4.0 for method declarations).

The issue is that CIM-XML does not support the representation of method declarations that have a reference return type. Because CIM-XML is the ubiquotous protocol for accessing WBEM servers, and because the schema is often "loaded" into a WBEM server viw the CIM-XML protocol, this missing support basically prevents the use of reference return types in CIM.

As a result, Pywbem does not support reference return types.

This issue is to track the creation of a corresponding DMTF issue against DSP0201.

**Comment by KSchopmeyer** [comment]
Created DMTF Mantis issue # 2850 on 8 Oct. 2019.
