### ISSUE TITLE
DSP0207 issue: No definition for referenceValue, plus editorial issue

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#929]
In its ABNF, DSP0207 uses the token `referenceValue` without defining it. DSP0207 refers to DSP0004 for some related tokens, but `referenceValue` is (rightfully) not defined in DSP0004. It ought to be defined in DSP0207, IMO.

To cover untyped WBEM URIs, it could be defined like this:
```
referenceValue = WBEM-URI-UntypedInstancePath
```
The question will be whether it can also be a typed instance path, and if so, whether typed and untyped paths can be mixed.

A second editorial issue is that in the definition of the `WBEM-URI-UntypedInstancePath` ABNF token, the underscores in the token `key_value_pairs` on the right hand side of the definition are not shown. They are there, though, when copying the text from the PDF viewer. Maybe a color issue?

This issue is to track the creation of a corresponding DMTF issue.

**Comment by KSchopmeyer** [comment]
Created Mantis issue #2849 on 8 Oct. 2019
