### ISSUE TITLE
DSP0004 issue: Invalid datetime examples

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#930]
DSP0004 2.8.0 has this in 5.2.4 "Datetime Type":

............
Examples:

* Monday, January 25, 1998, at 1:30:15 PM EST (US Eastern Standard Time) is represented as 19980125133015.0000000-300. The same point in time is represented in the UTC time zone as 19980125183015.0000000+000.
* Monday, May 25, 1998, at 1:30:15 PM EDT (US Eastern Daylight Time) is represented as 19980525133015.0000000-240. The same point in time is represented in the German (summertime) time zone as 19980525193015.0000000+120.

An alternative representation of the same timestamp is 19980525183015.0000000+000.
............

There are two issues with this:
* The microseconds part of all example datetime strings has seven zeroes instead of six.
* The last sentence "An alternative ..." should not appear after the list, but should be part of the second list item.

This issue is to track the creation of a corresponding DMTF issue.

**Comment by KSchopmeyer** [comment]
Filed as DMTF Mantis bug # 2839, 8 Oct 2019
