### ISSUE TITLE
DSP0207 issue: stringValue can be multiple string parts

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#931]
For the definition of string key binding values in WBEM URI strings, DSP0207 refers to the `stringValue` definition in Annex A of DSP0004:
```
// Note: The production rules for stringValue, charValue, booleanValue,
// integerValue, and realValue are defined in Appendix A (MOF Syntax
// Grammar Description) of DMTF DSP0004, CIM Infrastructure Specification.
```

DSP0004 in Appendix A defines `stringValue` to allow multiple double quoted parts, because that definition is targeted at MOF:

```
stringValue = 1*( """ *stringChar """ )
; Whitespace and comment is allowed between double
; quoted parts.
; Double quotes shall be escaped.
; For details, see 7.12.1
```
By these definitions, DSP0207 would allow string-typed key bindings that are specified in multiple double quoted parts. I'm sure that is not how it is intended, nor implemented anywhere.

I suggest resolving this by adding an according restriction to DSP0207.

See also issue #932.

By the way, for datetime typed keys, the same issue could theoretically exist, but this has been addressed in DSP0207 by not referencing datetimeValue as defined in DSP0004 Appendix A, but by having its own definition of datetimeValue that ensures there is only a single double quoted part.

**Comment by KSchopmeyer** [comment]
Created DMTF Mantis issue # 2848 on 8 Oct 2019
