### ISSUE TITLE
DSP0207 issue: charValue can be integer

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#932]
For the definition of char16 key binding values in WBEM URI strings, DSP0207 refers to the `charValue` definition in Appendix A of DSP0004:
```
// Note: The production rules for stringValue, charValue, booleanValue,
// integerValue, and realValue are defined in Appendix A (MOF Syntax
// Grammar Description) of DMTF DSP0004, CIM Infrastructure Specification.
```

DSP0004 in Appendix A defines `charValue` to also allow integer numbers besides single quoted strings:

```
charValue = "’" char16Char "’" / integerValue
; Single quotes shall be escaped.
; For details, see 7.12.2
```
By these definitions, DSP0207 would allow char16-typed key bindings that are specified as an integer number. I'm sure that is not how it is intended, nor implemented anywhere.

I suggest resolving this by adding an according restriction to DSP0207.

See also issue #931.

**Comment by KSchopmeyer** [comment]
Filed DMTF Mantis bug # 2847 on 8 Oct. 2019
