### ISSUE TITLE
mof compiler fails with build of assoc with alias

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#936]
The changes made in pr 903 (changes to atomic_to_cim_xml) causes a failure in the mof compiler when building aliases for instances with reference properties.   The code causing the problem is below.

        try:
            # build instance property from class property but without
            # qualifiers, default value,
            pprop = cprop.copy()
            pprop.qualifiers = NocaseDict(None)
            pprop.value = tocimobj(cprop.type, pval)
            inst.properties[pname] = pprop
            # if alias and this is key property, add keybinding
            if alias and 'key' in cprop.qualifiers:
                keybindings[pname] = atomic_to_cim_xml(pprop.value)

        except ValueError as ve:
            ce = CIMError(CIM_ERR_INVALID_PARAMETER,
                          'Invalid value for property %s: %s' %
                          (pname, str(ve)))
            ce.file_line = (p.parser.file, p.lexer.lineno)
            raise ce

Apparently CIMInstance name was considered as a valid input to atomic before but is not after the change in the pr

The offending mof is probably driven by the class mof below where the two references are keys

        [Association, Description(" Family gathers person to family.") ]
        class TST_MemberOfFamilyCollection {
           [key] TST_Person ref family;
           [key] TST_Person ref member;
        };

and the following instance that defines an alias for this:

        instance of TST_MemberOfFamilyCollection as $SofiMember
        {
            family = $Family1;
            member = $Sofi;
        };

**Comment by KSchopmeyer** [comment]
We probably have two choices:

1. Include CIMNamespace within the types covered by atomic... or extend the compiler to specifically cover the reference

**Comment by andy-maier** [comment]
Fixed with PR #939.
