### ISSUE TITLE
InvokeMethod does not support input parameters that pass instances as embedded objects

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#950]
The `WBEMConnection.InvokeMethod()` method does not support parameters that are embedded instances passed as embedded objects (i.e. in CIM-XML terms, setting embedded_object="object" and passing an INSTANCE, or in MOF terms, setting the qualifier EmbeddedObject(True) on the parameter.

Reason is that the parameters are specified as a tuple name, value, where the value is a CIMClass or CIMInstance object, and the embedded_instance attribute is implied from that class type.

The problem only exists for input parameters, but not for output parameters or method return values, because for those, the embedded_obejct attribute in the CIM-XML response determines the way the instances are represented, and in both cases ("object" and "instance"), the returned CIM instance is always handed byck to the caller of InvokeMethod as a CIMInstance object.

This deficiency is not a huge problem, because CIM instances are recommended to be passed as embedded instance (i.e. in CIM-XML terms, setting embedded_object="instance" and passing an INSTANCE, and that is supported. However, it is technically possible that users define a method with a parameter that sets EmbeddedObject(True) for the purpose of passing an instance.

The difference between method parameters and properties in pywbem is that property values can be represented using CIMProperty (and thus, its embedded_object attribute can be set to "object", but for method parameters, a corresponding CIM object type does not exist (CIMParameter is currently documented to only allow representing the parameter declaration).

**Comment by andy-maier** [comment]
Options to address this issue:
1. Extend CIMParameter to also allow representing parameter values, and allow them to be passed to InvokeMethod as an alternative to the tuple(name,value).
2. Introduce a new class CIMParameterValue for the same purpose.

**Comment by KSchopmeyer** [comment]
Karl agrees with option 1

**Comment by andy-maier** [comment]
Another discussion point is the use of CIMParameter for output parameters. Needs discussion.

**Comment by andy-maier** [comment]
On the discussion point: We agreed to implement option iii. and to document the situation with returning embedded objects in output parameters.

**Comment by andy-maier** [comment]
Summarizing the work for this issue, following the decisions outlined in previous comments:
* Extend `CIMParameter` to also allow representing parameter values, by undeprecating its `value` attribute (it was deprecated in pywbem 0.9), adding a new `embedded_object` attribute, and documenting the use for parameter values.
* Extend `InvokeMethod()` to be able to get input parameters also as `CIMParameter` objects, in addition to the existing tuple(name,value).
* Document how the existing output parameters of `InvokeMethod()` are used to return embedded objects / instances.

**Comment by andy-maier** [comment]
Ok, here comes the spec check ...

* Support for embedded objects in parameters (i.e. type "string" with EmbeddedObject or EmbeddedInstance qualifier):

  - The CIM architecture supports that (not precluded in 5.1.2.10 "Parameter", scope "parameter" allowed in 5.6.3.15 "EmbeddedInstance" and 5.6.3.16 "EmbeddedObject", all in DSP0004 2.8.0)
  - The MOF syntax does not preclude that (see section 7.10 "Method Declarations" in DSP0004 2.8.0).
  - The CIM-XML protocol describes that the EmbeddedObject attribute shall be specified on PARAMVALUE element when the corresponding qualifier is specified on the parameter declaration (see sections 5.2.11 "EmbeddedObject" and 5.3.6.13 "PARAMVALUE" in DSP0201 2.4.0).
  - The CIM-XML protocol does not preclude the representation of of parameter declarations with a EmbeddedObjects/Instance qualifier and string type (see section 5.3.5.7 "PARAMETER" and "PARAMETER.ARRAY" in DSP0201 2.4.0).

This is consistent with the work we plan to do.

**Comment by andy-maier** [comment]
PR #988 provides part 1 of a fix.

**Comment by andy-maier** [comment]
PR #1003 provides part 2 of the fix.
