### ISSUE TITLE
Occasionaly Failure of wbemcli in make test

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#954]
Sometimes I get a total failure of wbemcli in make test as follows: Note that it is only occasionally and simply rerunning the test normally does not repeat the problem.

''

________________________ TestsContainer.test_namespace _________________________

self = <test_wbemcli.TestsContainer testMethod=test_namespace>

    def test(self):  # pylint: disable=missing-docstring
        """ The test method that is generated."""
        # create the path for the quit script. Required to
        # exit wbemcli after the test.
        quit_script_file = create_abs_path('wbemcli_quit_script.py')
    
        script_name = 'wbemcli.bat' if os.name == 'nt' else 'wbemcli'
    
        url = 'http://blah' if test_params.url is None \
            else test_params.url
    
        cmd = ('%s %s %s -s %s' % (script_name,
                                   url,
                                   test_params.cmd,
                                   quit_script_file))
    
        # Disable python warnings for wbemcli call
        # because some imports generate deprecated warnings
        # that appear in std_err when nothing expected
        bash_cmd = 'bash -c "PYTHONWARNINGS= %s"' % cmd
    
        proc = Popen(bash_cmd, shell=True, stdout=PIPE, stderr=PIPE)
        std_out, std_err = proc.communicate()
        exitcode = proc.returncode
    
        # print('bash_cmd: %s\nexitcode: %s std_out:\n%s\nstd_err:'
        #      '\n%s' % (bash_cmd, exitcode, std_out, std_err))
    
        if six.PY3:
            std_out = std_out.decode()
            std_err = std_err.decode()
    
        if test_params.expected_exitcode is not None:
            self.assertEqual(exitcode, test_params.expected_exitcode,
                             ("Test %s: Unexpected exit code "
                              "(expected %s, got %s) from command:\n"
                              "%s\n"
                              "stderr:\n"
                              "%s" %
                              (test_name, test_params.expected_exitcode,
>                              exitcode, cmd, std_err)))
E           AssertionError: Test test_namespace: Unexpected exit code (expected 0, got 1) from command:
E           wbemcli http://blah -n rex/fred -s /home/kschopmeyer/pywbem/githubpywbem/pywbem/testsuite/wbemcli_quit_script.py
E           stderr:
E           Traceback (most recent call last):
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/bin/wbemcli", line 4, in <module>
E               __import__('pkg_resources').require('pywbem==0.11.1.dev186')
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3147, in <module>
E               @_call_aside
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
E               f(*args, **kwargs)
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
E               working_set = WorkingSet._build_master()
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
E               ws.require(__requires__)
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 984, in require
E               needed = self.resolve(parse_requirements(requirements))
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
E               raise DistributionNotFound(req, requirers)
E           pkg_resources.DistributionNotFound: The 'pywbem==0.11.1.dev186' distribution was not found and is required by the application

testsuite/test_wbemcli.py:167: AssertionError
_________________________ TestsContainer.test_timeout __________________________

self = <test_wbemcli.TestsContainer testMethod=test_timeout>

    def test(self):  # pylint: disable=missing-docstring
        """ The test method that is generated."""
        # create the path for the quit script. Required to
        # exit wbemcli after the test.
        quit_script_file = create_abs_path('wbemcli_quit_script.py')
    
        script_name = 'wbemcli.bat' if os.name == 'nt' else 'wbemcli'
    
        url = 'http://blah' if test_params.url is None \
            else test_params.url
    
        cmd = ('%s %s %s -s %s' % (script_name,
                                   url,
                                   test_params.cmd,
                                   quit_script_file))
    
        # Disable python warnings for wbemcli call
        # because some imports generate deprecated warnings
        # that appear in std_err when nothing expected
        bash_cmd = 'bash -c "PYTHONWARNINGS= %s"' % cmd
    
        proc = Popen(bash_cmd, shell=True, stdout=PIPE, stderr=PIPE)
        std_out, std_err = proc.communicate()
        exitcode = proc.returncode
    
        # print('bash_cmd: %s\nexitcode: %s std_out:\n%s\nstd_err:'
        #      '\n%s' % (bash_cmd, exitcode, std_out, std_err))
    
        if six.PY3:
            std_out = std_out.decode()
            std_err = std_err.decode()
    
        if test_params.expected_exitcode is not None:
            self.assertEqual(exitcode, test_params.expected_exitcode,
                             ("Test %s: Unexpected exit code "
                              "(expected %s, got %s) from command:\n"
                              "%s\n"
                              "stderr:\n"
                              "%s" %
                              (test_name, test_params.expected_exitcode,
>                              exitcode, cmd, std_err)))
E           AssertionError: Test test_timeout: Unexpected exit code (expected 0, got 1) from command:
E           wbemcli http://blah -t 10 -s /home/kschopmeyer/pywbem/githubpywbem/pywbem/testsuite/wbemcli_quit_script.py
E           stderr:
E           Traceback (most recent call last):
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/bin/wbemcli", line 4, in <module>
E               __import__('pkg_resources').require('pywbem==0.11.1.dev186')
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3147, in <module>
E               @_call_aside
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
E               f(*args, **kwargs)
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
E               working_set = WorkingSet._build_master()
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
E               ws.require(__requires__)
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 984, in require
E               needed = self.resolve(parse_requirements(requirements))
E             File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
E               raise DistributionNotFound(req, requirers)
E           pkg_resources.DistributionNotFound: The 'pywbem==0.11.1.dev186' distribution was not found and is required by the application

testsuite/test_wbemcli.py:167: AssertionError

**Comment by andy-maier** [comment]
The way we install pywbem in the dev env is to use "pip install -e ." which creates an "editable" installation thatdepends on the existence of the egg-info directory, which gets removed with "make clobber". So after a "make clobber", you need to do a "make install" before you can invoke wbemcli.
