### ISSUE TITLE
Documentation issues with EnumerationContext

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#956]
The following issues exists in CIM_Operations.py including the following:

1. The context is documented as a string and not a tuple in at least a couple of places. See, for example
cim_operations.py line 5785

2. We should consider that the CIMError messages that are a reaction to errors in the EnumerationContext returned by the server should at least reflect that they were generated by the Client to avoid confusion. We agreed that we do not have a better exception than CIMError right now.

3. Add comment to CloseEnumeration noting that cim_operations.py sets the whole context to None when finished.

**Comment by andy-maier** [comment]
Fixed in PR #957.
