### ISSUE TITLE
DSP0201 issue: Multiple issues around namespace names

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#978]
There are several issues around namespace names in DSP0201 (2.4.0):

1. Section 5.3.4.1 "NAMESPACEPATH" contains this sentence: "The NAMESPACE elements shall appear in hierarchy order, with the root namespace appearing first." Because DSP0004 defines that namespaces are flat, this sentence should be updated to be consistent with DSP0004. Also, the sentence is in the wrong section; it actually makes a statement about the NAMESPACE elements in LOCALNAMESPACEPATH and should be moved into that section.

2. The sections on NAMESPACEPATH and NAMESPACE are not clear enough in stating that the namespace as defined in DSP0004 is not represented by a NAMESPACE element, but by the sequence of NAMESPACE elements used in NAMESPACEPATH. The following sentence in the NAMESPACE section is even incorrect w.r.t. that: "The NAME attribute (defined by the CIMName entity) defines the name of the namespace." - it defines only the name of a component of the namespace name.

3. The section on NAMESPACE refers to CIMName as defining the name of a namespace (or component thereof, once corrected, see item 2). However, the definition of CIMName does not mention namespace name components as one of the entities it names. The list of what CIMName can name, should be updated to include namespace name components.

A corresponding DMTF issue should be opened.

**Comment by KSchopmeyer** [comment]
Created DMTF Mantis bug #2846 on 8 Oct. 2019
