### ISSUE TITLE
DSP0004 issue: namespaceName ABNF rule not explained

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#979]
Appendix A of DSP0004 (2.8.0) contains the following ABNF rule:
```
namespaceName = IDENTIFIER *( "/" IDENTIFIER )
```
While it is useful to have this rule because it defines the structure of namespace names as well as the character set that can be used for their components, the issue is that DSP004 does not state that this rule specifies the structure of namespace names. Guessing that from the ABNF rule name is not sufficient for a spec.

A good place to make such a statement would be section 8.1 "CIM Namespaces", right after the sentence "A namespace has a name which shall be unique within the CIM server."

A corresponding DMTF issue should be opened.

**Comment by KSchopmeyer** [comment]
Filed as Mantis issue 2837, 8 Oct 2019. Marked resolution fixed
