### ISSUE TITLE
MOF compiler: CreateClass updates existing class

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#991]
This issue resulted from the following TODO in mof_compiler.py:

W:2117, 0: TODO: should we see if it exists first with (fixme)

The conclusion in a discussion about this was that we should check for existence and reject if it exists, because at this level, the functions should behave like WBEM operations.

**Comment by andy-maier** [comment]
We agreed to move this out of 0.12.

**Comment by KSchopmeyer** [comment]
I took my name off as assignee.

**Comment by andy-maier** [comment]
We need to abandon this issue. See the discussion in issue #1996.
